[#20717] CDCSDK: Send RPC to random tablet with active tservers
Summary:
In context of tablet splitting, we can arrive at a situation where the `YBClient` can host a `RemoteTablet` for a parent split tablet, the `RemoteTablet` in such cases does not have any active tservers. So when the method `getFirstTablet` will return us such `RemoteTablet` and `YBClient` will try to make the RPC call to it, the call would fail with a similar error (method and service names can vary depending on context):

```
org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetTabletListToPollForCDC, service=yb.cdc.CDCService, tablet=null, attempt=1800, maxAttempts=1800, maxTimeoutMs=600000, elapsedTimeMs=6964)
```

This diff fixes this issue by adding a new method `getRandomActiveTablet` which iterates over the list of `RemoteTablet` and returns one where we have tservers linked to it.
Jira: DB-9720

Test Plan:
Jenkins: java only

Run existing tests.

Reviewers: skumar, sumukh.phalgaonkar

Reviewed By: skumar

Subscribers: ycdcxcluster, yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D32346