[#16309] YSQL: DROP SEQUENCE is not atomic
Summary:
Currently the sequences table hosted by the TServers is not transactional.
This means that DDL operations on sequences are not atomic - i.e. they
can reflect on the PG catalog but not on the DocDB sequences table.

Specifically for DROP SEQUENCES, the following scenario is possible:
```
CREATE SEQUENCE s;
SELECT * FROM pg_sequence;

 seqrelid | seqtypid | seqstart | seqincrement |       seqmax        | seqmin | seqcache | seqcycle
----------+----------+----------+--------------+---------------------+--------+----------+----------
    16384 |       20 |        1 |            1 | 9223372036854775807 |      1 |        1 | f
(1 row)

SET yb_test_fail_next_ddl =true;
DROP SEQUENCE s;
ERROR:  Failed DDL operation as requested

SELECT nextval(16384);
ERROR:  Unable to find relation for sequence
```

The above error is because of the following sequence of events:
1. YSQL backend starts up a transaction to update the pg_sequence table
    (among other catalog tables)
2. We then send a request to DocDB to delete the row corresponding to the
    sequence being dropped from the sequences table.
3. The error injection forces the transaction to fail causing the PG catalog
    changes to rollback, however we have already committed the removal of
    the row from the DocDB sequences table
4. Subsequent queries trying to access the sequences table will fail. DocDB will
    fail the operation with "Unable to find relation for sequence"

This patch has a partial fix for this issue. We now schedule the deletion
of the tuple pertaining to the sequence being deleted to be executed after
commit. This uses the infrastructure introduced in 50261627a50dcd9e04b21a9007bd01fa321ec565
to postpone deletion post commit.

The complete fix for this issue and other DDLs on sequences is tracked in #19011

Note: We cannot use the DDL atomicity infrastructure introduced in
e297a5b1c7487701ab2f7e67ed4e65cb1eea1076
as the sequences table is hosted on the TServers whereas the DDL
Atomicity infra is entirely in the YB-Master
Jira: DB-5734

Test Plan: ./yb_build.sh  --cxx-test pg_libpq-test --gtest_filter "*DropSequenceTest*"

Reviewers: myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D28324