[#28653] docdb: Vector index: reverse mapping decoding support in sst-dump tool
Summary:
Currently, sst-dump tool does not support vector index reverse mapping:
```
Process /Users/ar/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-000034cb000030008000000000004203/tablet-e1e29ab997b940389fbc107c9a13ded4/000010.sst
Sst file format: block-based
Corruption (yb/dockv/doc_key.cc:53): Error: failed decoding SubDocKey "\x06Vu\xb2\xf0\xd2\xc8\xcb@\xd7\x995FW1\xcf\xb2\xc0#\x80\x01\x14\xd736v%\x80?\xab": Error when decoding range components of a document key: Unexpected end of key when decoding document key -> 474A4F49800000000000000C2121
Corruption (yb/dockv/doc_key.cc:53): Error: failed decoding SubDocKey "\x06V\x9d\x0f8Ot\xbc@1\x9d\xb7:\xf4mU\x0aB#\x80\x01\x14\xd731\x9e]\x80?\xab": Error when decoding range components of a document key: Unexpected end of key when decoding document key -> 479FAC49800000000000000D2121
Corruption (yb/dockv/doc_key.cc:53): Error: failed decoding SubDocKey "\x06V\xbf\x15\xa0\xacpn@\x14\xaf\\Y\x81\xed~\x1a\x87#\x80\x01\x14\xd736\x88\xe6\x80?\xab": Error when decoding range components of a document key: Unexpected end of key when decoding document key -> 47C8E549800000000000000B2121
```

The fix add support of reverse mapping decoding for sst-dump tool.
Example of sst-dump output:
```
Process /Users/ar/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-000034cb000030008000000000004203/tablet-e1e29ab997b940389fbc107c9a13ded4/000010.sst
Sst file format: block-based
MetaKey(VectorId(5675b2f0-d2c8-cb40-d799-35465731cfb2), [HT{ physical: 1758560466979290 w: 1 }]) -> DocKey(0x4a4f, [12], [])
MetaKey(VectorId(569d0f38-4f74-bc40-319d-b73af46d550a), [HT{ physical: 1758560467296674 w: 1 }]) -> DocKey(0x9fac, [13], [])
MetaKey(VectorId(56bf15a0-ac70-6e40-14af-5c5981ed7e1a), [HT{ physical: 1758560466974489 w: 1 }]) -> DEL
```
Jira: DB-18348

Test Plan: ./yb_build.sh --cxx-test='TEST_F(PgVectorIndexUtilTest, SstDump)'

Reviewers: sergei, rthallam

Reviewed By: sergei, rthallam

Subscribers: ybase, yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D46903