[#27673] YSQL: Flush/Drop buffered operations prior to execute command affecting session state
Summary:
There are multiple scenarios where the `PgTxnManager::SetupPerformOptions` method is called:
  - PgTxnManager::ExportSnapshot
  - PgTxnManager::ImportSnapshot
  - PgTxnManager::RollbackToSubTransaction
  - PgTxnManager::AcquireObjectLock

All this methods sends protobuf to `PgClientService` which affects session/txn state in `PgClientSession` class.
Write operation buffering also affects this sate. And it is possible that scenarios from the above list will be called when buffered operations are not yet completelly flushed. This may leads to the
```
ERROR:  Expecting a used read time from the previous RPC but didn't find one
```
error.

Solution is to flush/drop buffered operations prior to execute operations which affects session/txn state in `PgClientSession` object.

**Note:**
To enforce that all current (and future) scenarios which sends `PgPerformOptionsPB` (i.e. prepares it by calling `PgTxnManager::SetupPerformOptions`) the `SetupPerformOptionsAccessorTag` class is introduced. The instance of this class can be constructed by the `FlushBufferedOperations` / `DropBufferedOperations` of the `PgSession` class only.

**Note:**
The diff fixes the `PgIndexBackfillGinStress.GinStress` unit test
Jira: DB-17271

Test Plan:
Jenkins

```
./yb_build.sh release --cxx-test pgwrapper_pg_index_backfill-test --gtest_filter PgIndexBackfillGinStress.GinStress/1
```

Reviewers: pjain, bkolagani, esheng, jason

Reviewed By: pjain, bkolagani, esheng

Subscribers: smishra, rthallam, yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D45047