[BACKPORT 2.20][20893] YSQL: Fix failure to create an execution plan for SELECT DISTINCT queries.
Summary:
Original commit: aa2c9b4da0847306f2af774e1f99c496c2b1b0f6 / D32151
### Issue

This is a memory corruption issue where under certain conditions, the optimal path chosen by the planner for `SELECT DISTINCT` queries is corrupted and the planner fails to create a valid plan to execute. This issue can manifest itself in the following forms.

#### Unrecognized node type error

This typically happens in debug builds where the query fails with the following (or similar) error

```
yugabyte=# SELECT DISTINCT ...

ERROR:  unrecognized node type: 2139062143
```

#### Server connection closed

This typically happens in release builds. The query fails with the following error

```
yugabyte=# SELECT DISTINCT ...

server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: ...
```

A quick fix is to disable distinct pushdown. Turn off `yb_enable_distinct_pushdown`.

### Root Cause

To understand the root cause, first we observe that Postgres recycles suboptimal `Path` objects that will NEVER be used by the planner in the future. However, this property may be violated when distinct pushdown is enabled if we are not careful.

#### Example Scenarios

Consider the following setup

```
CREATE TABLE t (k INT PRIMARY KEY, v INT);
CREATE INDEX i ON t(v ASC);
INSERT INTO t (SELECT i, i%10 FROM GENERATE_SERIES(1, 10000) AS i);
ANALYZE t;
```

Executing the following query will raise an error

```
SELECT DISTINCT a1.v FROM t a1 RIGHT OUTER JOIN t a2 USING (v) WHERE a2.v = 5 GROUP BY a1.v;
```

Let's demystify the issue. First, observe that the following is a valid plan for the query

```
 HashAggregate  (cost=29.33..29.43 rows=10 width=4)
   Group Key: a1.v
   ->  Hash Left Join  (cost=1.65..4.33 rows=10000 width=4)
         Hash Cond: (a2.v = a1.v)
         ->  Unique  (cost=0.00..1.53 rows=10 width=4)
               ->  Distinct Index Only Scan using i on t a2  (cost=0.00..1.53 rows=10 width=4)
                     Index Cond: (v = 5)
                     Distinct Prefix: 1
         ->  Hash  (cost=1.53..1.53 rows=10 width=4)
               ->  Unique  (cost=0.00..1.53 rows=10 width=4)
                     ->  Distinct Index Only Scan using i on t a1  (cost=0.00..1.53 rows=10 width=4)
                           Index Cond: (v = 5)
                           Distinct Prefix: 1
```

This plan produces distinct output because we pushdown distinct on `a1.v` and we make `a2.v` constant (bonus points for figuring out what happens when a2.v is not a constant). We know that the output of an index scan is sorted on its (range) columns but the hash aggregation node on top destroys this sorting. Now, consider a plan with Unique and Sort attached on top of this plan,

```
 Unique
   ->  Sort
         Sort Key: v
         Sort Method: quicksort
         -> HashAggregate (same plan from above ...)
```

The Unique+Sort plan is sorted on `a1.v` but the HashAgg plan underneath is not. Pg generates both of these "plans" (more accurately they are still paths in Pg) for the query and if the costs are nearly the same, Pg deallocates the plain HashAgg path in favor of the Unique+Sort+HashAgg path (because of better sort keys). This behavior causes a memory corruption since the former path is a child of the latter path.

##### Query Variations

Now, let us consider some variations of the above query and discuss their behavior in context of this bug.

//1. Remove Group By Clause//

Let us remove the **GROUP BY** clause from the original query

```
SELECT DISTINCT a1.v FROM t a1 RIGHT OUTER JOIN t a2 USING (v) WHERE a2.v = 5;
```

and we obtain the following execution plan

```
Hash Left Join  (cost=1.65..4.33 rows=10000 width=4)
   Hash Cond: (a2.v = a1.v)
   ->  Unique  (cost=0.00..1.53 rows=10 width=4)
         ->  Distinct Index Only Scan using i on t a2  (cost=0.00..1.53 rows=10 width=4)
               Index Cond: (v = 5)
               Distinct Prefix: 1
   ->  Hash  (cost=1.53..1.53 rows=10 width=4)
         ->  Unique  (cost=0.00..1.53 rows=10 width=4)
               ->  Distinct Index Only Scan using i on t a1  (cost=0.00..1.53 rows=10 width=4)
                     Index Cond: (v = 5)
                     Distinct Prefix: 1
```

This does not trigger memory corruption because the estimated number of output rows is large enough that the uniq+sort path has a noticeably higher cost unlike the original query where the group by clause reduces the output estimate to just 10 rows.

//2. Use full keys on a unique index//

The following query

```
SELECT DISTINCT a1.k FROM t a1 RIGHT OUTER JOIN t a2 USING (k) WHERE a2.k = 5 GROUP BY a1.k;
```

is still safe since we do not push down distinct on the complete key of a unique index.

That said, we can still trigger the issue when querying a **strict prefix** of the unique key. Example:

```
SELECT DISTINCT a1.k1 FROM t2 a1 RIGHT OUTER JOIN t2 a2 USING (k1) WHERE a2.k1 = 5 GROUP BY a1.k1;
```

where the schema of table `t2` is

```
yugabyte=# \d t2
                 Table "public.t2"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k1     | integer |           | not null |
 k2     | integer |           | not null |
 k3     | integer |           | not null |
Indexes:
    "t2_pkey" PRIMARY KEY, lsm (k1 ASC, k2 ASC, k3 ASC)
```

//3. Use Inner Join//

The issue is not triggered when using inner join instead of right outer join (caveat: range partitioning assumed). The query

```
explain select distinct a1.v from t a1 inner join t a2 using (v) where a2.v = 5 group by a1.v;
```

generates the plan

```
                                             QUERY PLAN
-----------------------------------------------------------------------------------------------------
 Group  (cost=0.00..29.33 rows=10 width=4)
   Group Key: a1.v
   ->  Nested Loop  (cost=0.00..4.33 rows=10000 width=4)
         ->  Unique  (cost=0.00..1.53 rows=10 width=4)
               ->  Distinct Index Only Scan using i on t a1  (cost=0.00..1.53 rows=10 width=4)
                     Index Cond: (v = 5)
                     Distinct Prefix: 1
         ->  Materialize  (cost=0.00..1.58 rows=10 width=4)
               ->  Unique  (cost=0.00..1.53 rows=10 width=4)
                     ->  Distinct Index Only Scan using i on t a2  (cost=0.00..1.53 rows=10 width=4)
                           Index Cond: (v = 5)
                           Distinct Prefix: 1
```

Creating a group path (on an already presorted input) is more efficient than hash aggregating the input. This is because we simply skip over duplicate rows in the grouping case as opposed to hash aggregation where we compute hash tables to de-duplicate (non-trivial overhead).

However, a similar plan is not generated for right outer joins or full outer joins since the output of the join does not come out sorted in these cases. Pg clears `pathkeys` and hence a grouping path must sort the output before de-duplicating. We postulate that in the absence of any outer joins in the query, we can pushdown distinct completely only when the output is also sorted on those keys (range columns assumed). Therefore, the issue is not triggered in absence of **outer joins** since we would never sort a pre-sorted input. Note: the planner must generate BOTH Unique and Sort nodes on top to trigger the memory corruption bug.

//4. Infer column not NULL//

Instead of explicitly changing right outer join to inner join, we can also do that implicitly by hinting Pg. Let us now look at the following query

```
SELECT DISTINCT a1.v FROM t a1 RIGHT OUTER JOIN t a2 USING (v) WHERE a1.v = 5 GROUP BY a1.v;
```

This becomes an inner join since Pg recognizes that `a1.v` can never be NULL as it is equal to 5.

//5. Do not run analyze//

It is a tad trickier to trigger the issue when not running ANALYZE. That said, we are still not immune to the issue either. Consider the following query

```
SELECT DISTINCT a1.k1 FROM t a1 RIGHT OUTER JOIN t a2 RIGHT OUTER JOIN t a3
USING (k1) USING (k1) WHERE a2.k1 = 5 AND a3.k1 = 5 GROUP BY a1.k1;
```

fails to generate an execution plan. Observe that we need more than two relations in our outer join because the default estimates are too low to trigger the issue with just two tables. Moreover, we need to make the columns a2.k1 and a3.k1 constant to trigger the issue because they are not actually part of the distinct target list (only a1.k1 is).

#### Overall Impact

The easiest way to check if a query is impacted: run the query. Run explain on the query if physically running the query is undesirable. As a rough guideline, see if the query calls distinct on the same column that it groups by. Notice that this is redundant since both the operations are semantically equivalent.

### Inaccurate propagation of Unique keys

As part of this change, we have also identified (and fixed) scenarios where we do not propagate `Path::YbPathInfo::yb_uniqkeys` accurately. The list `yb_uniqkeys` is crucial in determining whether the distinct pushdown operation obviates the need to de-duplicate the rows in the postgres/query layer. Impact: This is largely a preventative change and shouldn't see much impact.

#### Example Scenarios

Consider the following query

```
SELECT DISTINCT t.k1 FROM t GROUP BY GROUPING SETS ((k1), (k1)) ORDER BY k1;
```

Let's look at the execution plan for the query.

```
 GroupAggregate  (cost=0.00..27.30 rows=400 width=4)
   Group Key: k1
   Group Key: k1
   ->  Unique  (cost=0.00..22.80 rows=200 width=4)
         ->  Distinct Index Scan using t_pkey on t  (cost=0.00..22.80 rows=200 width=4)
               Distinct Prefix: 1
```

This produces incorrect results for the query (duplicates the column `k1` when it shouldn't).

### Costing changes

We adjust the total cost of distinct index scan paths based on the number of distinct rows. However, the startup cost remains the same. This means that the total cost can go below the startup cost (which is absurd). In this change, we only adjust the run cost (total - startup) and not the total cost. There is no impact on correctness from this costing change.

**Backports:** 2.20, 2.21.0

Test Plan:
Jenkins
./yb_build.sh --java-test TestPgRegressDistinctPushdown

Reviewers: tnayak, smishra, mtakahara

Reviewed By: mtakahara

Subscribers: yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D32331