[BACKPORT 2025.2][#30114] YSQL: Support concurrent create index on the different tables
Summary:
Create index on different tables concurrently failing with the below error consistently;

```
com.yugabyte.util.PSQLException: ERROR: timed out waiting for postgres backends to catch up
  Detail: 4 backends on database 16640 are still behind catalog version 49.
  Hint: Run the following query on all tservers to find the lagging backends: SELECT * FROM pg_stat_activity WHERE backend_type != 'walsender' AND backend_type != 'yb-conn-mgr walsender' AND backend_type != 'yb auto analyze backend' AND catalog_version < 49 AND datid = 16640;
  Where: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

In Yugabyte, CREATE INDEX by default means CREATE INDEX CONCURRENTLY, which works in multiple
stages. Each stage is a transaction that will cause catalog version to increment. The 3rd stage is
doing the backfill work. When the table is large, the 3rd stage will take long time. During the
backfill stage, the PG backend cannot update its local catalog version. This makes the PG backend
becomes a lagging backend that causes another concurrent CREATE INDEX to fail with the above error.

When concurrent CREATE INDEX work on different tables, there is no need for them to wait on each
other. This diff adds a new backend type YB_INDEX_BACKFILL_DDL. When a CREATE INDEX backend is
executing the 3rd stage, it temporarily set the backend type to YB_INDEX_BACKFILL_DDL. The new
backend type YB_INDEX_BACKFILL_DDL is ignored by the SQL query that finds the lagging backends.

Two new unit tests are added that would fail with the above error before this diff:
(1) concurrent CREATE INDEX on two different tables
(2) concurrent CRAETE INDEX on two child partition tables
Test (2) verifies an expected real world use case described at https://docs.yugabyte.com/stable/api/ysql/the-sql-language/statements/ddl_create_index/#partitioned-indexes, where concurrent CREATE INDEX can be used
to speed up creating index on a partitioned table.

Original commit: 50afb0e9a4 / D50067

Test Plan:
./yb_build.sh release --cxx-test pg_concurrent_ddls-test  --gtest_filter=PgConcurrentCreateIndexWithSlowBackfillTest.SlowBackfillTest -n 10 --tp 1
./yb_build.sh release --cxx-test pg_concurrent_ddls-test  --gtest_filter=PgConcurrentCreateIndexWithSlowBackfillTest.PartitionedSlowBackfillTest -n 10 --tp 1

Reviewers: sanketh, pjain, jason

Reviewed By: pjain

Subscribers: yql, ybase, jason

Differential Revision: https://phorge.dev.yugabyte.com/D50913