[BACKPORT 2.23.0][PLAT-15169] Upgrade YBC client and server version to 2.2.0.0-b5
Summary:
Upgrade version to 2.2.0.0-b5

Adds to changes:

- ISSUE
Longer running backups fail after hitting:
Exception: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: ClientCall started after CallOptions deadline was exceeded -4.925995153 seconds ago. Name resolution delay 0.000000000 seconds.

The grpc calls fail with DEADLINE_EXCEEDED exactly after 20 minutes which is the default deadline timeout.

- FIX
The fix is to make the deadline per-rpc instead of it being per-client.

- ISSUE
YBDB PR: https://phorge.dev.yugabyte.com/D37010#change-zwzWSOdH4VDT removed non-transaction based snapshot code flows entirely. This led to removal of a proto request param set_transaction_aware which YBC was using.

- FIX
Remove the param from YBC code flow and re-add deprecated version of the param

Test Plan: dev itests

Reviewers: kkg

Reviewed By: kkg

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D37882