[#10881] DocDB: Fix "loop variable is always a copy because the range of type"
Summary:
Reported by Clang 12 on Mac:

```
error: loop variable 'c' is always a copy because the range of type 'internal::Splitter<delimiter::Literal>' does not return a reference
```

Issue appeared when using Clang 12 after https://phabricator.dev.yugabyte.com/D14342

Test Plan: ybd

Reviewers: sergei

Reviewed By: sergei

Subscribers: bogdan, ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D14381