[#13822] ysql: Fix fastdebug compilation due to wrong indentation in task_states.c
Summary:
Over https://jenkins.dev.yugabyte.com/job/yugabyte-db-phabricator/20955/consoleText :
```
[2022-08-31T14:49:27.039Z] /-------------------------------------------------------------------------------
[2022-08-31T14:49:27.039Z] | COMPILATION FAILED
[2022-08-31T14:49:27.039Z] |-------------------------------------------------------------------------------
[2022-08-31T14:49:27.039Z] src/postgres/contrib/pg_cron/src/task_states.c: In function ���UpdateJobRunStatus���:
[2022-08-31T14:49:27.039Z] src/postgres/contrib/pg_cron/src/task_states.c:371:3: error: this ���if��� clause does not guard... [-Werror=misleading-indentation]
[2022-08-31T14:49:27.039Z]   371 |   if(SPI_execute(querybuf.data, true, 0) != SPI_OK_SELECT ||
[2022-08-31T14:49:27.039Z]       |   ^~
[2022-08-31T14:49:27.039Z] src/postgres/contrib/pg_cron/src/task_states.c:375:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ���if���
[2022-08-31T14:49:27.039Z]   375 |     SPITupleTable *tuptable = SPI_tuptable;
[2022-08-31T14:49:27.039Z]       |     ^~~~~~~~~~~~~
[2022-08-31T14:49:27.039Z] cc1: all warnings being treated as errors
[2022-08-31T14:49:27.039Z]
```
The above was introduced via commit 2963a54f90f41562c3884991a00a58926eb05f7d

This revision fixes the build by proper indentation.

Test Plan: fastdebug compilation passes

Reviewers: plee

Reviewed By: plee

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D19259