Clean up command line for itest workload.
Summary:
- Create command list per token. Since the parsing fails if more than one token per string.
- Fix jar path to include S3 info.

Test Plan:
./run_itest

Still hitting this as the foo@bar.com customer is still not seeded for providers.
{code}
2017-02-14 11:25:10,887 test_base.py:45 ERROR Did not find provider with code: aws
{code}

Reviewers: ram

Reviewed By: ram

Subscribers: eng

Differential Revision: https://phabricator.dev.yugabyte.com/D1276