[BACKPORT 2024.2][#31475] YSQL: Skip partition check when row scan is skipped for updates
Summary:
=== Backport Notes (master --> 2024.2) ===
 - Adjacency conflicts in `nodeModifyTable.c` caused due to differences in the Update API. PG 11 (2024.2) has a single function `ExecUpdate()` which handles the update of 1 row end-to-end, while PG 15 (master), splits this functionality across `ExecUpdatePrologue()`, `ExecUpdateAct()` and `ExecUpdateEpilogue()`. Resolve by preserving PG 11 structure in 2024.2.
 - Commit b611c63ff8e6a8eb8e4a5b4080ac899a532a6a04 fixes storage flush request count in specific scenarios related to single shard updates and partition table updates. 2024.2 does not have this fix. Resolved by adjusting flush counts in a few places. Note that this is only an observability problem, and not a correctness problem.

D52579 / a7c0df145723cc64a6ae4c5d0d5194ee03d0238e tightened the partition key check for single shard updates in the planner and skipped the partition constraint check in the executor when the statement is executed as a single shard transaction (`estate->yb_es_is_single_row_modify_txn = true`).
However, there is a class of statements where the planner produces a single row plan (a `Result` node with no storage scan) but the executor does not run it as a single shard transaction. Examples include single row update statements executed inside an explicit transaction block, inside a stored function or procedure, etc. In these cases, the row to be modified is not fetched from storage. Therefore the executor has insufficient information to carry out the partition constraint check and incorrectly errors out.

Consider the following schema and example:

```sql
CREATE TABLE root (cluster_key INT, part_key INT, v INT) PARTITION BY RANGE (part_key);
CREATE TABLE leaf1 PARTITION OF root (cluster_key PRIMARY KEY) FOR VALUES FROM (1) TO (11);
CREATE TABLE leaf2 PARTITION OF root (cluster_key PRIMARY KEY) FOR VALUES FROM (11) TO (21);

INSERT INTO leaf1 VALUES (1, 1, 5);
```

```sql
yugabyte=# BEGIN;
BEGIN

yugabyte=# UPDATE leaf1 SET v = v + 1 WHERE cluster_key = 1;
ERROR:  23514: new row for relation "leaf1" violates partition constraint
DETAIL:  Failing row contains (1, null, 0).

yugabyte=# ROLLBACK;
ROLLBACK
```

This revision fixes the above issue by skipping the partition constraint check for all cases where the tuple to be updated is not fetched via a scan node from storage. The logic introduced by a7c0df145723cc64a6ae4c5d0d5194ee03d0238e into the planner guarantees that when the storage scan is skipped, neither the partition key nor the primary (clustering) key are modified by the update, and therefore the modified row cannot fail the partition constraint check.

Original commit: 35a565d55814fb940b50eac1e29cac15eddfab7b / D52709

Test Plan:
Run the following test:
```
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressDml#schedule'
```

jenkins: urgent

Reviewers: fizaa, aagrawal, jason

Reviewed By: fizaa

Subscribers: smishra, yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D53922