[BACKPORT 2.8] [#2266] YSQL: Fix YSQL PG crypto function crash issue
Summary:
**Problem:
**The crypto extension for YSQL presiouly would crash (<=v2.6.x) or return error message (>=2.8.x)  for the following YSQL functions:
gen_salt(...) (for all encryption algorithms), and crypt(...).

The exact behavior for salt generation will be:

```
yugabyte=# select gen_salt('bf',4);
ERROR:  gen_salt: Incorrect number of rounds
```

Similarly for crypt() function:
```
yugabyte=# SELECT crypt('foox', '$2a$');
ERROR:  crypt(3) returned NULL
```

**Root cause:
**With our analysis, we found that this is due to API conflicts. There are two versions of implementations of the same dependent APIs. One exists in existing PG [[ https://github.com/yugabyte/yugabyte-db/tree/master/src/postgres/contrib/pgcrypto | code base ]], which is supposed to be used. The other is imported by our [[ https://github.com/yugabyte/yugabyte-db-thirdparty | third-party-package ]].

Take blowfish encryption for example. It both exists in PG [[ https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/contrib/pgcrypto/crypt-gensalt.c#L25 | codebase ]] and [[ https://github.com/yugabyte/crypt_blowfish/blob/master/crypt_gensalt.c#L34 | thirdparty ]]. Their implementations are not exactly the same while the signatures are the same.

During linking, one of the APIs will be picked. So during runtime, if the third-party APIs are called, the results are unexpected.

With further investigation, the problem is that the third-party package is used by DocDB, and it has been built into a uber libyb_util.so. That is why the third-party APIs are brought into the linking process.

**Solution:
**Renaming the confusing function names with `yb` prefix to differentiate
the API signatures, which follows our internal PG naming conventions.

Original commit: D14470 / d6368fb4ad6b9f2ed38d4967800de38c13074289

Test Plan:
Jenkins: rebase: 2.8, all java tests

Added missed pgsql tests to ysql pg java test suite.
Run

```
ybd --no-remote --sb --java-test 'org.yb.pgsql.TestPgRegressContribPgCrypto'

```
Run manual tests and compare results with PG.

Run manual cluster upgrading tests. Crypto functions start to work, while they don't on previous releases.

Reviewers: mihnea, smishra

Reviewed By: smishra

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D14548