[#16020] YSQL: Fix yb_get_range_split_clause primary key constraint wrong assumption
Summary:
Before this diff, the implementation of function `yb_get_range_split_clause` wrongly makes one assumption that column ordering in primary key constraint of a CREATE TABLE statement is the same as the column ordering of key columns in the CREATE TABLE statement.
An issue caused by this assumption is shown by the example:
```
yugabyte=# CREATE TABLE tbl (v VARCHAR, k INT, PRIMARY KEY(k ASC, v ASC)) split at values ((1));
yugabyte=# SELECT * from yb_get_range_split_clause('tbl'::regclass);
ERROR:  Internal error: Unexpected type in the QL value
```
This diff fixes this issue by getting the correct primary key column ordering from `pg_index` catalog.

Test Plan:
Jenkins: urgent
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressMisc#testPgRegressMiscSerial'

Reviewers: mihnea, tverona, jason

Reviewed By: jason

Subscribers: hsunder, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D22810