[#22121] YSQL: fix error on bool NULLS LAST index
Summary:
Commit 5ba859353466c42c5f440f66fd282af99f012354 introduced
DecodeBoolColumn which covers true, false, `kNullLow`, but not
`kNullHigh`, throwing an error in that case:

    ERROR:  Wrong key entry type kNullHigh for bool column

In other words, if a secondary index (since PK does not support null)
has a bool column sorted NULLS LAST, any SELECT trying to decode null
values from that column from that index will hit the above error.  (Note
that ASC is NULLS LAST by default.)  Handle that case.

YCQL is not affected since it does not use this decoding code.
Jira: DB-11047

Test Plan:
On Almalinux 8:

    ./yb_build.sh fastdebug --gcc11 \
      --java-test 'TestPgRegressMisc#testPgRegressMiscIndependent'

Backport-through: 2.20
Close: #22121

Reviewers: sergei

Reviewed By: sergei

Subscribers: yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D34430