[pg15] test: adjust "contains null values" messages
Summary:
Upstream PG 05f18c6b6b6e4b44302ee20a042cedc664532aa2 changes message

    "column \"%s\" contains null values"

to

    "column \"%s\" of relation \"%s\" contains null values"

1. Update tests to expect the new message.
1. YB master 74239ec4bd196bba52057a53111999c7486b9057 duplicates that
   error message to YbATCopyTableRowsUnchecked, and merge
   7c61dca08434c118f04309f6999823b7bb6cc91e over that commit didn't
   detect this.  Change the error message now.  Then, fix test
   "org.yb.pgsql.TestPgAlterTableColumnType#testNotNullConstraints" to
   have the new message.  That test is already in the passing_java.tsv
   list.
1. "TestPgAlterTableChangePrimaryKey#nulls" hits a completely different
   error message between master (PG 11) and pg15 (PG 15) for

       ALTER TABLE nopk ADD PRIMARY KEY (id);

   pg15:

       ERROR:  Missing/null value for primary key column
       ../../src/yb/yql/pggate/util/ybc_util.cc:338:                                                           @     0x7f4ae49a7984  YBCGetStackTrace
       ../../../../../../../src/postgres/src/backend/utils/error/elog.c:1228:                                  @           0xafd876  errmsg
       ../../../../../../src/postgres/src/backend/executor/ybcModifyTable.c:307:                               @           0x7da86c  YBCExecuteInsertInternal
       ../../../../../../src/postgres/src/backend/executor/ybcModifyTable.c:368:                               @           0x7dae1b  YBCExecuteInsertForDb
       ../../../../../../src/postgres/src/backend/executor/ybcModifyTable.c:352:                               @           0x7dae63  YBCExecuteInsert
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:21402:                                  @           0x71c94e  YbATCopyTableRowsUnchecked
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:21772:                                  @           0x71c94e  YbATCopyMetadataAndData
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:21954:                                  @           0x725427  YbATCloneRelationSetPrimaryKey
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:9123:                                   @           0x7256d9  ATExecAddIndex
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:5374:                                   @           0x733a2a  ATExecCmd
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:5209:                                   @           0x7366ec  ATRewriteCatalogs
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:4678:                                   @           0x7366ec  ATController
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:4318:                                   @           0x737c55  AlterTable
       ../../../../../../src/postgres/src/backend/tcop/utility.c:1398:                                         @           0x98a200  ProcessUtilitySlow
       ../../../../../../src/postgres/src/backend/tcop/utility.c:1139:                                         @           0x989976  standard_ProcessUtility
       ../../../../../../src/postgres/src/backend/tcop/utility.c:3939:                                         @           0x989ba0  YBProcessUtilityDefaultHook
       ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:2079:                            @           0xb1ebe8  YBTxnDdlProcessUtility
       ../../../../../../src/postgres/src/backend/tcop/utility.c:554:                                          @           0x989bf6  ProcessUtility
       ../../../../../../src/postgres/src/backend/tcop/pquery.c:1188:                                          @           0x9866c5  PortalRunUtility
       ../../../../../../src/postgres/src/backend/tcop/pquery.c:1358:                                          @           0x986a72  PortalRunMulti
       ../../../../../../src/postgres/src/backend/tcop/pquery.c:809:                                           @           0x987167  PortalRun
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:1320:                                        @           0x9810b9  exec_simple_query
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:5057:                                        @           0x9810b9  yb_exec_simple_query_impl
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:5025:                                        @           0x97e21f  yb_exec_query_wrapper_one_attempt
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:5049:                                        @           0x97fad5  yb_exec_query_wrapper
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:5072:                                        @           0x97fb28  yb_exec_simple_query
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:5791:                                        @           0x9829a5  PostgresMain
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4807:                                @           0x8cadf3  BackendRun
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4507:                                @           0x8cadf3  BackendStartup
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1878:                                @           0x8cadf3  ServerLoop
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1533:                                @           0x8cd4f4  PostmasterMain
       ../../../../../../src/postgres/src/backend/main/main.c:208:                                             @           0x8073d7  PostgresServerProcessMain
           @           0x8073f7
           @     0x7f4ae2965d84
           @           0x4b7a3d
           @ 0xffffffffffffffff

   master:

       ERROR:  column "id" contains null values
       ../../src/yb/yql/pggate/util/ybc_util.cc:364:                                                           @     0x7f36e0ec9b6a  YBCGetStackTrace
       ../../../../../../../src/postgres/src/backend/utils/error/elog.c:1112:                                  @           0xa56ea2  errmsg
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:5297:                                   @           0x6de2fa  ATRewriteTable
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:4985:                                   @           0x6e7c7d  ATRewriteTables
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:3943:                                   @           0x6e7c7d  ATController
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:3630:                                   @           0x6e82d6  AlterTableInternal
       ../../../../../../src/postgres/src/backend/catalog/index.c:322:                                         @           0x5abef7  index_check_primary_key
       ../../../../../../src/postgres/src/backend/commands/indexcmds.c:984:                                    @           0x69c71f  DefineIndex
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:7532:                                   @           0x6dd002  ATExecAddIndex
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:4538:                                   @           0x6e4687  ATExecCmd
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:4399:                                   @           0x6e7464  ATRewriteCatalogs
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:3938:                                   @           0x6e7464  ATController
       ../../../../../../src/postgres/src/backend/commands/tablecmds.c:3606:                                   @           0x6e827c  AlterTable
       ../../../../../../src/postgres/src/backend/tcop/utility.c:1181:                                         @           0x9086aa  ProcessUtilitySlow
       ../../../../../../src/postgres/src/backend/tcop/utility.c:977:                                          @           0x90803b  standard_ProcessUtility
       ../../../../../../src/postgres/src/backend/tcop/utility.c:3612:                                         @           0x9080e9  YBProcessUtilityDefaultHook
       ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:1420:                       @     0x7f36cd5fa94c  pgss_ProcessUtility
       ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:772:                                  @     0x7f36cd5d4672  ybpgm_ProcessUtility
       ../../../../../src/postgres/contrib/pgaudit/pgaudit.c:1192:                                             @     0x7f36cd5c9754  pgaudit_NextProcessUtility_hook
       ../../../../../src/postgres/contrib/pgaudit/pgaudit.c:1220:                                             @     0x7f36cd5cae79  pgaudit_ProcessUtility_hook
       ../../../../../src/postgres/third-party-extensions/pg_hint_plan/pg_hint_plan.c:3056:                    @     0x7f36cd5b5b06  pg_hint_plan_ProcessUtility
       ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:2079:                            @           0xa8ce6a  YBTxnDdlProcessUtility
       ../../../../../../src/postgres/src/backend/tcop/utility.c:377:                                          @           0x908128  ProcessUtility
       ../../../../../../src/postgres/src/backend/tcop/pquery.c:1206:                                          @           0x903cfa  PortalRunUtility
       ../../../../../../src/postgres/src/backend/tcop/pquery.c:1366:                                          @           0x90477c  PortalRunMulti
       ../../../../../../src/postgres/src/backend/tcop/pquery.c:815:                                           @           0x9055ec  PortalRun
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:1220:                                        @           0x8ffec8  exec_simple_query
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:4735:                                        @           0x8ffec8  yb_exec_simple_query_impl
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:4703:                                        @           0x8fd2d0  yb_exec_query_wrapper_one_attempt
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:4727:                                        @           0x8fe951  yb_exec_query_wrapper
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:4750:                                        @           0x8fe9a5  yb_exec_simple_query
       ../../../../../../src/postgres/src/backend/tcop/postgres.c:5375:                                        @           0x90138e  PostgresMain
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4731:                                @           0x85e497  BackendRun
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4395:                                @           0x85e497  BackendStartup
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1773:                                @           0x85e497  ServerLoop
       ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1429:                                @           0x8607f0  PostmasterMain
       ../../../../../../src/postgres/src/backend/main/main.c:234:                                             @           0x7a7dde  PostgresServerProcessMain
           @           0x7a7dfe
           @     0x7f36decf2d84
           @           0x4a89bd
           @ 0xffffffffffffffff

   The difference is index_check_primary_key no longer has
   AlterTableInternal in PG 15 due to upstream PG
   f4a3fdfbdcd3763c42111318d004c2e90d072021 which moves the adding of
   NOT NULL CONSTRAINT to a different location.  In master PG 11, the
   adding of NOT NULL CONSTRAINT is what must have hit the constraint
   violation error message.  For now, fix the error message to what is
   actually being output.  I suspect that it is possible in the future
   when table rewriting code is removed in favor of relfilenode swap,
   this error message may go back to what it was (plus the addition of
   relation name information that PG 15 gave).

Except for the regress test, which is hard to manage, add new tests to
pg15_tests.

Test Plan:
On Almalinux 8:

    #!/usr/bin/env bash
    set -e
    ./yb_build.sh fastdebug --gcc11
    pg15_tests/run_shell_tests.sh fastdebug --gcc11
    pg15_tests/run_passing_java_tests.sh fastdebug --gcc11

Jenkins: rebase: pg15

Reviewers: aagrawal, tfoucher

Reviewed By: tfoucher

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D31625