ENG-4636 (#834): Make transaction failure messages more user friendly
Summary: Currently transaction failure error messages have a lot of details like tablet ID, task ID, hybrid time etc. which is not relevant to users. This commit changes the message printed on shell to a more user friendly format. Note that the detailed message which includes information about tablet ID etc. is logged.

Test Plan:
In psql shell 1:
```
CREATE TABLE foo(a int primary key, b int);
BEGIN;
INSERT INTO foo VALUES(1,1);
```
In psql shell 2:
```
INSERT INTO foo VALUES(1,1);
```
Now, go back to psql shell 1:
```
COMMIT;
```

When commit fails, the error message printed on the shell is:
```
ERROR:  Error during commit: Operation expired: Transaction expired
```

Error message seen in the log:
```
I0213 16:48:49.101312 231014400 tablet_rpc.cc:312] Operation expired (yb/tablet/transaction_coordinator.cc:777): Failed UpdateTransaction: tablet_id: "f296dc1b43fb46a9b3517d90b10bfa18" state { transaction_id: "(Yh(#\320N\311\227\0365\227S6o\202" status: PENDING } propagated_hybrid_time: 6349231427987972096, retrier: { task_id: -1 state: kIdle deadline: 207464.390s } to tablet f296dc1b43fb46a9b3517d90b10bfa18 on tablet server { uuid: 32322cfa8ec44a9c97d8ecbd1a564b3e private: [host: "127.0.0.1" port: 9100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 1 attempt(s): Transaction expired
W0213 16:48:49.101586 231014400 transaction.cc:677] 28596828-23d0-4ec9-971e-359753366f82: Send heartbeat failed: Operation expired (yb/tablet/transaction_coordinator.cc:777): Transaction expired
2019-02-13 16:48:57.267 PST [29012] ERROR:  Error during commit: Operation expired: Transaction expired
2019-02-13 16:48:57.267 PST [29012] STATEMENT:  commit;
```

Sometimes, the INSERT statement in shell 2 fails. In that case, message printed on the shell is:
```
ERROR:  Operation failed. Try again.: Conflicts with higher priority transaction: 28596828-23d0-4ec9-971e-359753366f82
```

And message in the log is:
```
I0213 16:47:17.859995 51752960 tablet_rpc.cc:312] Operation failed. Try again. (yb/docdb/conflict_resolution.cc:68): Failed Write(tablet: 35a8f0c3ada747cd871fdeecf6305344, num_ops: 1, num_attempts: 1, txn: 2c58b180-b5cb-41dc-9bcc-9e54c4677b55) to tablet 35a8f0c3ada747cd871fdeecf6305344 on tablet server { uuid: 32322cfa8ec44a9c97d8ecbd1a564b3e private: [host: "127.0.0.1" port: 9100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 1 attempt(s): Conflicts with higher priority transaction: 28596828-23d0-4ec9-971e-359753366f82
2019-02-13 16:47:17.860 PST [29023] ERROR:  Operation failed. Try again.: Conflicts with higher priority transaction: 28596828-23d0-4ec9-971e-359753366f82
2019-02-13 16:47:17.860 PST [29023] STATEMENT:  insert into foo values(1,1);
```

Reviewers: mihnea, mikhail

Reviewed By: mikhail

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D6172