[Backport to 2.12] [#11887] YSQL: Include information about the index table when ybctid DocKey isn't found in main table
Summary:
Sometimes, support people face the following error in server log:
```
ERROR:  Query error: ybctid DocKey([], ["@{..."]) not found in indexed table
```
The query leading to the above error is complex, involving JOINs over multiple tables and indexes.

Currently support people spend a lot of time trying to separate the query into smaller pieces so that the underlying index / table with missing DocKey can be found.
Since we don't have direct access to customer data, this requires some back and forth between customer and support people.

We can boost troubleshooting efficiency by including the index table Id in the error message.

This would save support people a lot of time when dealing with complex queries.

This includes commits 9a00ecc9f79ba47521e2ebfb4b48498d28298f65 and 7793ec81151716d4834ed5d235c64aea9859cd4a

Test Plan: Jenkins: rebase: 2.12

Reviewers: amartsinchyk

Reviewed By: amartsinchyk

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D16287