[#3876] Cleaner error reporting from process main
Summary:
Certain errors encountered during the actual master or tserver main would not instantly
fail the server, leading to confusion as what errors actually lead to startup failure.

As part of this, also fixed an issue with the inline shell code for running `lsof` where it was not
correctly accounting for process names with whitespace in them.

Test Plan:
Tested with a local cluster:
```
nc -l 6379
yb-ctl create
```

With the code change, we get a clear FATAL in `tserver.err`, and gets cleanly picked up by `yb-ctl`:
```
In YugabyteDB, setting LC_COLLATE to C and all other locale settings to en_US.UTF-8 by default. Locale support will be enhanced as part of addressing https://github.com/yugabyte/yugabyte-db/issues/15572020-03-07 00:12:06.023 UTC [24225] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2020-03-07 00:12:06.035 UTC [24225] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2020-03-07 00:12:06.071 UTC [24225] LOG:  redirecting log output to logging collector process
2020-03-07 00:12:06.071 UTC [24225] HINT:  Future log output will appear in directory "/n/users/bogdan/yugabyte-data/node-1/disk-1/yb-data/tserver/logs".
F0307 00:12:06.673113 24153 tablet_server_main.cc:244] Network error (yb/util/net/socket.cc:334): Error binding socket to 127.0.0.1:6379: Address already in use (system error 98)
Fatal failure details written to /n/users/bogdan/yugabyte-data/node-1/disk-1/yb-data/tserver/logs/yb-tserver.FATAL.details.2020-03-07T00_12_06.pid24153.txt
F20200307 00:12:06 ../../src/yb/tserver/tablet_server_main.cc:244] Network error (yb/util/net/socket.cc:334): Error binding socket to 127.0.0.1:6379: Address already in use (system error 98)
    @     0x7f4b0353865c  yb::LogFatalHandlerSink::send()
    @     0x7f4b02746336  google::LogMessage::SendToLog()
    @     0x7f4b0274379a  google::LogMessage::Flush()
    @     0x7f4b02746869  google::LogMessageFatal::~LogMessageFatal()
    @           0x4109f2  yb::tserver::(anonymous namespace)::TabletServerMain()
    @     0x7f4afdc5e825  __libc_start_main
    @           0x40f919  _start
    @              (nil)  (unknown)

*** Check failure stack trace: ***
    @     0x7f4b03536a41  yb::(anonymous namespace)::DumpStackTraceAndExit()
    @     0x7f4b02743c4d  google::LogMessage::Fail()
    @     0x7f4b02745dbd  google::LogMessage::SendToLog()
    @     0x7f4b0274379a  google::LogMessage::Flush()
    @     0x7f4b02746869  google::LogMessageFatal::~LogMessageFatal()
    @           0x4109f2  yb::tserver::(anonymous namespace)::TabletServerMain()
    @     0x7f4afdc5e825  __libc_start_main
    @           0x40f919  _start
    @              (nil)  (unknown)
```

Before, we would get subprocess related errors in `tserver.err`, due to trying to stop the pg backend:
```
In YugabyteDB, setting LC_COLLATE to C and all other locale settings to en_US.UTF-8 by default. Locale support will be enhanced as part of addressing https://github.com/yugabyte/yugabyte-db/issues/15572020-03-06 23:51:14.494 UTC [20198] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2020-03-06 23:51:14.532 UTC [20198] LOG:  listening on IPv4 address "127.0.0.2", port 5433
2020-03-06 23:51:14.578 UTC [20198] LOG:  redirecting log output to logging collector process
2020-03-06 23:51:14.578 UTC [20198] HINT:  Future log output will appear in directory "/n/users/bogdan/yugabyte-data/node-2/disk-1/yb-data/tserver/logs".
bash: line 0: [: S: integer expression expected
*** Aborted at 1583538675 (unix time) try "date -d @1583538675" if you are using GNU date ***
PC: @     0x7fea118eb215 std::_Rb_tree<>::_M_erase()
*** SIGSEGV (@0x0) received by PID 19968 (TID 0x7fea12623b40) from PID 0; stack trace: ***
    @     0x7fea02dfdba0 (unknown)
    @     0x7fea118eb214  std::_Rb_tree<>::_M_erase()
    @     0x7fea0833002d  yb::Subprocess::~Subprocess()
    @           0x40e201  std::default_delete<>::operator()()
```

Reviewers: neha, sanketh, mihnea, mikhail

Reviewed By: mikhail

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D8099