Merged PR 1248408: [OSS] Fix listIndexes and listCollections command
List indexes was broken in OSS:
- when generating the backend query we were using the api.list_indexes SQL UDF which is the former/old way before cursors support to list indexes and it is available in pgmongo, but since that is obsolete and don't support cursors, we didn't added it to OSS.

Fix is to instead generate a query that fetches directly from the `helio_api_catalog.collection_indexes` table which is basically what list_indexes did:

```
SELECT mongo_api_internal.index_spec_as_bson(index_spec, TRUE)
        FROM mongo_catalog.collection_indexes
        WHERE collection_id = v_collection.collection_id AND
              (index_is_valid OR mongo_api_internal.index_build_is_in_progress(index_id))
        ORDER BY index_id
```
List Collections was broken in OSS because we were using the wrong schema to get the `row_get_bson` UDF and the OpExpr for the text equality for the query where clause `database = <dbName>` , we were not specifying a collation and postgres was failing with:

```
ERROR:  could not determine which collation to use for string comparison
HINT:  Use the COLLATE clause to set the collation explicitly.
```