[#29988] YSQL,GV: Allow creating server of federatedYugabyteDB type
Summary:
This diff is the first in a series of diffs for supporting global views.

This diff only allows the creation of servers of type federatedYugabyteDB.
Servers of this type cannot be used as of this diff. Future diffs will
enable the usage.

Test Plan:
./yb_build.sh --java-test TestPgRegressContribYbPostgresFdw#schedule

Manual testing ---
```
yugabyte=# CREATE EXTENSION postgres_fdw;
CREATE EXTENSION

yugabyte=# CREATE SERVER IF NOT EXISTS yb_global_views_server
yugabyte-#     FOREIGN DATA WRAPPER postgres_fdw OPTIONS (server_type 'federatedYugabyteDB');
CREATE SERVER

yugabyte=# CREATE FOREIGN TABLE IF NOT EXISTS "gv$yb_active_session_history" (
yugabyte(#     sample_time TIMESTAMPTZ,
yugabyte(#     root_request_id UUID,
yugabyte(#     rpc_request_id BIGINT,
yugabyte(#     wait_event_component TEXT,
yugabyte(#     wait_event_class TEXT,
yugabyte(#     wait_event TEXT,
yugabyte(#     top_level_node_id UUID,
yugabyte(#     query_id BIGINT,
yugabyte(#     pid INT,
yugabyte(#     client_node_ip TEXT,
yugabyte(#     wait_event_aux TEXT,
yugabyte(#     sample_weight REAL,
yugabyte(#     wait_event_type TEXT,
yugabyte(#     ysql_dbid OID,
yugabyte(#     wait_event_code BIGINT,
yugabyte(#     pss_mem_bytes BIGINT,
yugabyte(#     ysql_userid OID
yugabyte(# )
yugabyte-# SERVER yb_global_views_server
yugabyte-# OPTIONS (schema_name 'pg_catalog', table_name 'yb_active_session_history');
CREATE FOREIGN TABLE

yugabyte=# SELECT * FROM gv$yb_active_session_history;
ERROR:  global views feature is incomplete

```

Reviewers: kramanathan, ishan.chhangani, cagrawal

Reviewed By: kramanathan

Subscribers: jason, aagrawal, hbhanawat, yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D49678