[BACKPORT 2024.2][#17271] YSQL: Enable several ALTER SEQUENCE sub-commands
Summary:
Original commit: D39066 / 9b28c7c4a6b5e967805d95370774e9a00543584e

Implemented the following statements:
```
ALTER SEQUENCE <seq_name> SET LOGGED;
ALTER SEQUENCE <seq_name> SET UNLOGGED;
ALTER SEQUENCE <seq_name> SET SCHEMA <new_schema>;
ALTER SEQUENCE <seq_name> OWNER TO <new_owner>;
ALTER SEQUENCE <seq_name> RENAME TO <new_seq_name>;
```
Updated `CREATE UNLOGGED ...` and `ALTER ... SET UNLOGGED` statements (for any relations - `TABLE`, `INDEX`, `SEQUENCE`).
The statements output the NOTICE message:
```
NOTICE:  unlogged option is currently ignored in YugabyteDB, all non-temp relations will be logged
```
Updated other related failed statements:
```
alter sequence s1 set without cluster;
alter sequence s1 cluster on c1;
alter sequence s1 options (add opt1 'val');
alter sequence s1 options (set opt1 'val');
alter sequence s1 alter column oid options (add opt1 'val');
alter sequence s1 add column c1 int;
alter sequence s1 add column if not exists c1 int;
alter sequence s1 add c1 int;
alter sequence s1 add if not exists c1 int;
alter sequence s1 drop column oid;
alter sequence s1 alter column oid set statistics 10;
alter sequence s1 alter column oid set data type int;
alter sequence s1 alter column oid set compression cmpr;
alter sequence s1 add constraint cnst1 unique(oid);
alter sequence s1 validate constraint chst1;
alter sequence s1 drop constraint cnst1;
alter sequence s1 set without oids;
alter sequence s1 enable trigger t;
alter sequence s1 enable replica trigger t;
alter sequence s1 enable trigger all;
alter sequence s1 enable trigger user;
alter sequence s1 disable trigger user;
alter sequence s1 disable trigger all;
alter sequence s1 set access method ao_row;
alter sequence s1 set tablespace public;
alter sequence s1 set (statistics=10);
alter sequence s1 reset (statistics);
alter sequence s1 replica identity default;
alter sequence s1 enable row level security;
alter sequence s1 disable row level security;
alter sequence s1 force row level security;
alter sequence s1 no force row level security;
```
The result looks like:
```
ERROR:  ALTER action NO FORCE ROW SECURITY cannot be performed on relation "s1"
DETAIL:  This operation is not supported for sequences.
```
Successful examples:
```
create unlogged sequence s1;
alter sequence s1 set logged;
alter sequence s1 set unlogged;
alter sequence s1 set schema schema1;
alter sequence s1 owner to yugabyte;
alter sequence s1 owner to current_user;
alter sequence s1 owner to session_user;
alter sequence s1 rename to s2;
```
Other not changed supported commands:
```
ALTER SEQUENCE <seq_name> AS <SimpleTypename>;
ALTER SEQUENCE <seq_name> CACHE <NumericOnly>;
ALTER SEQUENCE <seq_name> CYCLE;
ALTER SEQUENCE <seq_name> NO CYCLE;
ALTER SEQUENCE <seq_name> INCREMENT BY <NumericOnly>;
ALTER SEQUENCE <seq_name> MAXVALUE <NumericOnly>;
ALTER SEQUENCE <seq_name> MINVALUE <NumericOnly>;
ALTER SEQUENCE <seq_name> NO MAXVALUE;
ALTER SEQUENCE <seq_name> NO MINVALUE;
ALTER SEQUENCE <seq_name> OWNED BY <any_name>;
ALTER SEQUENCE <seq_name> SEQUENCE NAME <any_name>;
ALTER SEQUENCE <seq_name> START WITH <NumericOnly>;
ALTER SEQUENCE <seq_name> RESTART;
ALTER SEQUENCE <seq_name> RESTART WITH <NumericOnly>;
```

Test Plan:
Main tests in the `yb_pg_sequence.sql`:
./yb_build.sh --java-test org.yb.pgsql.TestPgRegressPgMiscIndependent#testPgRegressPgMiscIndependent
Updated `yb_feature_alter_rename.sql`:
./yb_build.sh --java-test org.yb.pgsql.TestPgRegressFeatureDatabase#testPgRegressFeatureDatabase
Updated `yb_schema.sql`:
./yb_build.sh --java-test org.yb.pgsql.TestPgRegressMisc#testPgRegressMiscSerial

./yb_build.sh --java-test org.yb.pgsql.TestPgRegressContribFileFdw#schedule
./yb_build.sh  --java-test org.yb.pgsql.TestPgRegressForeignKey#testPgRegress
./yb_build.sh  --java-test org.yb.pgsql.TestPgRegressPgForeignData#schedule
./yb_build.sh  --java-test org.yb.pgsql.TestPgRegressPgTable#schedule
./yb_build.sh  --java-test org.yb.pgsql.TestPgRegressPgTypesString#schedule

Reviewers: fizaa, mihnea

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D39470