[BACKPORT 2.27.0.3492][PLAT-18492] Enable ansible removal for configure in YBM
Summary:
Original commits:
1. https://phorge.dev.yugabyte.com/D46554 (4bdfc6505b4e9faafcb2dc240acb530f77499005) [PLAT-18492]
2. https://phorge.dev.yugabyte.com/D46494 (6f224b8d97e4166300655787e30e720ef315c549) [PLAT-18450]

[PLAT-18492] Enable ansible removal for configure in YBM

Enable node agent based server configuration instead of ansible (will be backported to YBM branch)

[PLAT-18450] Add systemctl retry in node agent to handle unstable dbus connection

Wrap systemctl commands in a retry method. Master process status check is done as in Ansible before master files are deleted. This is present in Ansible but was missed out in node agent.

Test Plan:
Already enabled in dev-portal.

Manually tested by creating a universe, stopping a node.

```
YW 2025-09-04T04:15:16.850Z [INFO] 6b769e14-f332-4963-9557-50149cab6392 from NodeAgentClient in NodeAgentGrpcPool-6 - Running shell command for loginctl enable-linger
Running systemd command: systemctl --user daemon-reload
Running shell command for SystemdCommand
Systemd command systemctl --user daemon-reload succeeded in 1 attempts
Running systemd command: systemctl --user enable yb-controller
Running shell command for SystemdCommand
Systemd command systemctl --user enable yb-controller succeeded in 1 attempts
Running systemd command: systemctl --user start yb-controller
Running shell command for SystemdCommand
Systemd command systemctl --user start yb-controller succeeded in 1 attempts

YW 2025-09-04T04:15:16.851Z [INFO] 6b769e14-f332-4963-9557-50149cab6392 from NodeAgentClient$BaseResponseObserver in NodeAgentGrpcPool-1 - Completed for 704fcbea-3dc0-42f9-967d-7a441813ae66-89505238-f1cc-4a7a-94c0-eb07e0e4aee0
```

Tested the master running scenario by running the master process after the precheck is done.

```
2025-09-04T22:32:39.881Z  [info] 5ad575c0-9ca3-4656-8e68-8f0f6bc4d21f NodeAgentClient.java:432 [NodeAgentGrpcPool-5] com.yugabyte.yw.common.NodeAgentClient$BaseResponseObserver Completed for a1cf1ad2-7e94-4353-92aa-df929747c13f-756b0494-b9c3-4390-b703-90da369da92a
2025-09-04T22:32:39.882Z  [debug] 5ad575c0-9ca3-4656-8e68-8f0f6bc4d21f TransactionUtil.java:113 [TaskPool-StopNodeInUniverse(dfedd8c8-3d83-46b9-b080-0c52addee59b)-0] com.yugabyte.yw.models.helpers.TransactionUtil Trying(1)...
2025-09-04T22:32:39.886Z  [error] 5ad575c0-9ca3-4656-8e68-8f0f6bc4d21f TaskExecutor.java:1198 [TaskPool-StopNodeInUniverse(dfedd8c8-3d83-46b9-b080-0c52addee59b)-0] com.yugabyte.yw.commissioner.TaskExecutor Failed to execute task type AnsibleConfigureServers UUID 441df258-37a7-4475-8185-9ca20fb07fa5 details {"platformVersion":"2.27.0.0-PRE_RELEASE","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","deviceInfo":{"volumeSize":100,"numVolumes":1,"diskIops":3000,"throughput":125,"storageClass":"standard","storageType":"GP3"},"universeUUID":"dfedd8c8-3d83-46b9-b080-0c52addee59b","enableYbc":true,"installYbc":false,"ybcInstalled":true,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"internalYsqlServerRpcPort":6433,"nodeExporterPort":9300,"otelCollectorMetricsPort":8889},"extraDependencies":{"installNodeExporter":true},"runOnlyPrechecks":false,"clusters":[],"currentClusterType":"PRIMARY","rootCA":"6ba975a3-a868-4b69-b1c3-fa7b2fe45aa4","clientRootCA":"6ba975a3-a868-4b69-b1c3-fa7b2fe45aa4","rootAndClientRootCASame":true,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"updateSucceeded":true,"universePaused":false,"softwareUpgradeState":"Ready","isSoftwareRollbackAllowed":false,"nextClusterIndex":1,"allowInsecure":false,"setTxnTableWaitCountFlag":true,"itestS3PackagePath":"","remotePackagePath":"","nodesResizeAvailable":false,"useNewHelmNamingStyle":false,"mastersInDefaultRegion":true,"isKubernetesOperatorControlled":false,"overridePrebuiltAmiDBVersion":false,"sequenceNumber":-1,"importedState":"NONE","capability":"EDITS_ALLOWED","updateOptions":[],"otelCollectorEnabled":false,"skipMatchWithUserIntent":false,"installNodeAgent":false,"nodeAgentMissing":false,"azUuid":"232df61c-7587-4f66-aa41-c2965c19523b","nodeName":"yb-admin-nsingh-test-universe3-n1","placementUuid":"3dc05350-06b5-4f0b-912c-7b14a274a026","instanceType":"c5.large","useSystemd":true,"isMaster":true,"isTserver":false,"properties":{"processType":"MASTER"},"type":"GFlags","ybSoftwareVersion":"2024.2.3.0-b116","isMasterInShellMode":true,"enableYSQL":true,"enableConnectionPooling":false,"enableYCQL":true,"enableYSQLAuth":false,"enableYCQLAuth":false,"enableYEDIS":false,"gflags":{},"gflagsToRemove":[],"updateMasterAddrsOnly":true,"callhomeLevel":"MEDIUM","enableNodeToNodeEncrypt":true,"enableClientToNodeEncrypt":true,"nodeToNodeChange":0,"rootCARotationType":"None","clientRootCARotationType":"None","certRotateAction":"ROTATE_CERTS","isSystemdUpgrade":false,"vmUpgradeTaskType":"None","ignoreUseCustomImageConfig":false,"installThirdPartyPackages":false,"resetMasterState":true,"masterJoinExistingCluster":true,"ybcGflags":{},"overrideNodePorts":false,"cgroupSize":0,"skipDownloadSoftware":false,"xclusterInfo":{"targetXClusterConfigs":[],"sourceXClusterConfigs":[]},"targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
java.lang.RuntimeException: Code: 1, Error: Master process must be stopped before resetting state
	at com.yugabyte.yw.common.NodeAgentClient$DescribeTaskResponseObserver.onNext(NodeAgentClient.java:607)
	at com.yugabyte.yw.common.NodeAgentClient$DescribeTaskResponseObserver.onNext(NodeAgentClient.java:584)
```

Reviewers: amindrov, nbhatia, anijhawan, dshubin, yshchetinin

Reviewed By: dshubin

Subscribers: nikhil, yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D46591