[#20300] YSQL:  Disallow new-version DDL in an invalid per-db catalog version configuration
Summary:
To reproduce the bug, create a universe with `ysql_enable_db_catalog_version_mode=true`
and `allowed_preview_flags_csv=ysql_enable_db_catalog_version_mode`.

Do NOT execute the following
```
SET yb_non_ddl_txn_for_sys_tables_allowed=true;
SELECT yb_fix_catalog_version_table(true);
```
Run the next test
```
yugabyte=# create table t(id int);
CREATE TABLE

yugabyte=# insert into t values(1);
INSERT 0 1

yugabyte=# CREATE TABLE tempTable AS SELECT * FROM t limit 1000000;
SELECT 1

yugabyte=# CREATE INDEX idx2 ON tempTable(id);
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req
version 2, master version 0
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req
version 2, master version 0
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req
version 2, master version 0
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req
version 2, master version 0
ERROR:  Requested catalog version is too high: req version 2, master version 0
```

This configuration has an mismatch between --ysql_enable_db_catalog_version_mode
and pg_yb_catalog_version: --ysql_enable_db_catalog_version_mode=true but
pg_yb_catalog_version is still in global-catalog version mode (only has one
row for database template1). This is not a supported configuration but it can
legitimately happen during cluster upgrade to a new release that has the
per-database catalog version mode on by default. The new binary executables are
upgraded first which will have --ysql_enable_db_catalog_version_mode=true, but
the YSQL migration script will be executed at a later time.

In this configuration, it isn't right to allow a new-version DDL statement (one
that increments the catalog version) because during upgrade some nodes may
already have their PG backends running in per-database catalog version mode
while others are still in global catalog version mode. If a new-version DDL
statement is allowed, stale read/write RPCs are possible which can lead to wrong
results. A new-version DDL statement can also fail like the example shown above.

This configuration can also happen due to manual turn on/off the per-database
catalog version mode and the proper steps are not followed.

I made a change to disallow a new-version DDL in this configuration.
Same-version DDLs (those that do not increment the catalog version) are still
allowed because they do not pose any problems.

Note that another configuration where
--ysql_enable_db_catalog_version_mode=false and pg_yb_catalog_version is in
per-database catalog version mode (i.e., it has one row per-database) has no
correctness problem because we only make use of the first row (for template1)
and ignore the other rows in pg_yb_catalog_version.

Also made debug logging change from elog(INFO) to elog(LOG) because elog(INFO) is
user-visible.

Test Plan: ./yb_build.sh --cxx-test pg_catalog_version-test

Reviewers: jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D31043