[BACKPORT 2.20][#24012] YSQL: Replace deprecated function shared_ptr::unique to fix macos compiler error
Summary:
Original commit: 9feb6e80715b965493e52ed156edda1e7fe80fa1 / D38164
An unknown change started causing compilation errors on macos. Fix these compiler errors.

Error 1: deprecated function error

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
../../src/yb/util/debug/long_operation_tracker.cc:119:22: error: no member named 'unique' in 'std::shared_ptr<yb::LongOperationTracker::TrackedOperation>'
  119 |       if (!operation.unique()) {
      |            ~~~~~~~~~ ^
../../src/yb/util/debug/long_operation_tracker.cc:124:24: error: no member named 'unique' in 'std::shared_ptr<yb::LongOperationTracker::TrackedOperation>'
  124 |         if (!operation.unique()) {
      |              ~~~~~~~~~ ^
2 errors generated.

Input files:
  src/yb/util/CMakeFiles/yb_util.dir/debug/long_operation_tracker.cc.o
  /Users/tfoucher/code/yugabyte-db3/src/yb/util/debug/long_operation_tracker.cc
Output file (from -o): src/yb/util/CMakeFiles/yb_util.dir/debug/long_operation_tracker.cc.o
\-------------------------------------------------------------------------------
```

Error2: unused variable error

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
../../src/yb/docdb/docdb_util.cc:46:19: error: unused variable 'kEmptyLogPrefix' [-Werror,-Wunused-const-variable]
   46 | const std::string kEmptyLogPrefix;
      |                   ^~~~~~~~~~~~~~~
1 error generated.

Input files:
  src/yb/docdb/CMakeFiles/yb_docdb.dir/docdb_util.cc.o
  /Users/pbalivada/code/xcode/src/yb/docdb/docdb_util.cc
Output file (from -o): src/yb/docdb/CMakeFiles/yb_docdb.dir/docdb_util.cc.o
\-------------------------------------------------------------------------------
```

Error 3: unused variable error

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
../../src/yb/util/metrics-test.cc:64:21: error: unused variable 'kTableId' [-Werror,-Wunused-const-variable]
   64 | static const string kTableId = "table_id";
      |                     ^~~~~~~~
1 error generated.

Input files:
  src/yb/util/CMakeFiles/metrics-test.dir/metrics-test.cc.o
  /Users/pbalivada/code/xcode/src/yb/util/metrics-test.cc
Output file (from -o): src/yb/util/CMakeFiles/metrics-test.dir/metrics-test.cc.o
\-------------------------------------------------------------------------------
```

Fixes #24012
Jira: DB-12899

Test Plan:
Jenkins: compile only

Backport-through: 2.20

Reviewers: hsunder

Reviewed By: hsunder

Subscribers: ybase, hsunder

Differential Revision: https://phorge.dev.yugabyte.com/D38181