[#11487] YSQL: fix PG crash in stored function call from DDL
Summary:
Problem
-------

* The PL/pgSQL implicitly starts new subtransaction for each procedure block body with the exception handler. When it happens in a stored function called from a DDL statement, `PgClientSession::SetActiveSubTransaction` was returning a IllegalState state error because it was not expecting to be called in the DDL mode, in which case, Transaction(PgClientSessionKind::kPlain) is a nullptr.

* Then the PL/pgSQL error handler in exec_stmt_block tries to rollback the subtransaction, which in turn calls `PgClientSession::RollbackSubTransaction` and hit the similar problem, causing infinite error handling cycle and eventually triggers the postgres' panic.

Example:
```
yugabyte=# CREATE OR REPLACE FUNCTION inverse(float8) RETURNS float8 AS
$$
BEGIN
	RETURN 1::float8 / $1;
EXCEPTION WHEN others THEN
	RAISE NOTICE 'caught exception % %', sqlstate, sqlerrm;
        RETURN 'NaN';
END$$ LANGUAGE plpgsql;
yugabyte-# yugabyte$# yugabyte$# yugabyte$# yugabyte$# yugabyte$# yugabyte$# CREATE FUNCTION
yugabyte=# CREATE TABLE ddl_subtrans_test (c1 float8);
CREATE TABLE
yugabyte=# INSERT INTO ddl_subtrans_test VALUES (0);
INSERT 0 1
yugabyte=# ALTER TABLE ddl_subtrans_test ADD CONSTRAINT c1_not_nan CHECK (inverse(c1) <> 'NaN');
WARNING:  AbortSubTransaction while in DEFAULT state
WARNING:  AbortSubTransaction while in ABORT state
WARNING:  AbortSubTransaction while in ABORT state
WARNING:  AbortSubTransaction while in ABORT state
ERROR:  Illegal state: Set active sub transaction 2, when not transaction is running
ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
PANIC:  ERRORDATA_STACK_SIZE exceeded
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
```

Solution
--------
When the procedure block does not have the EXCEPTION clause, PL/pgSQL executor does **not** use a subtransaction, and the YB code just uses the same transaction object used for the DDL. The fix is to let the subtransaction control functions to do the same thing.

i.e.:
* `PgClientSession::SetActiveSubTransaction`: use Transaction(PgClientSessionKind::kDdl) for the DDL mode request.
* `PgClientSession::RollbackSubTransaction`: find and use the transaction with matching subtransaction id in the request.

Note: [[ https://yugabyte.slack.com/archives/CAR5BCH29/p1651523357263809?thread_ts=1647376752.802849&cid=CAR5BCH29 | According to @mbautin, user table modifications within a DDL transaction are not fully supported (at least yet)]], however, this change does not affect fundamental interactions between the DDL statement and the DMLs within it, and rather, it brings the behavior closer to the scenarios not involving subtransactions.

Test Plan:
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressTransactionSavepoints#testPgRegressTransaction'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressTransactionSavepoints#testPgRegressTransactionWithReadCommitted'

jenkins

Manually tested:
- @amartsinchyk 's test case (https://github.com/yugabyte/yugabyte-db/issues/11487#issue-1138981942)
- Bryn's check constraint test case (https://github.com/yugabyte/yugabyte-db/issues/12875)

Reviewers: pjain, rsami, mtakahara, sergei, dmitry

Reviewed By: sergei, dmitry

Subscribers: dsrinivasan, zyu, myang, mbautin, smishra, amartsinchyk, mihnea, yql, bogdan

Differential Revision: https://phabricator.dev.yugabyte.com/D15982