Fix mac build errors
Summary:
Latest mac clang fails pg15 build due to stricter default compile checks.
Disabling nullability-completeness and availability errors:

> In file included from ../../../../../src/postgres/src/common/f2s.c:38:
> In file included from ../../../../../src/postgres/src/include/postgres_fe.h:25:
> In file included from ../../../../../src/postgres/src/include/c.h:59:
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/stdio.h:64:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/_stdio.h:93:16: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
>         unsigned char   *_base;
>                         ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may be null
>         unsigned char   *_base;
>                         ^
>                           _Nullable
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/_stdio.h:93:16: note: insert '_Nonnull' if the pointer should never be null
>         unsigned char   *_base;
>                         ^
>                           _Nonnull
>

and

> In file included from ../../../../../src/postgres/src/common/f2s.c:38:
> In file included from ../../../../../src/postgres/src/include/postgres_fe.h:25:
> In file included from ../../../../../src/postgres/src/include/c.h:60:
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/stdlib.h:128:
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/malloc/_malloc.h:44:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/malloc/_malloc_type.h:57:1: error: unknown platform 'visionos' in availability macro [-Werror,-Wavailability]
> _MALLOC_TYPE_AVAILABILITY void *malloc_type_malloc(size_t size, malloc_type_id_t type_id) __result_use_check __alloc_size(1);
> ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/malloc/_malloc_type.h:51:35: note: expanded from macro '_MALLOC_TYPE_AVAILABILITY'
> #define _MALLOC_TYPE_AVAILABILITY __API_UNAVAILABLE(macos, ios, tvos, watchos, visionos)
>                                   ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/Availability.h:469:152: note: expanded from macro '__API_UNAVAILABLE'
>     #define __API_UNAVAILABLE(...) __API_UNAVAILABLE_GET_MACRO(__VA_ARGS__,__API_UNAVAILABLE8,__API_UNAVAILABLE7,__API_UNAVAILABLE6,__API_UNAVAILABLE5,__API_UNAVAILABLE4,__API_UNAVAILABLE3,__API_UNAVAILABLE2,__API_UNAVAILABLE1,__API_UNAVAILABLE0,0)(__VA_ARGS__)

Test Plan: Jenkins

Reviewers: jason, tfoucher

Reviewed By: tfoucher

Subscribers: ybase, yql

Differential Revision: https://phorge.dev.yugabyte.com/D36456