[#22060] xClusterDDLRepl: Block multi-statment queries
Summary:
Adding a check that will verify if the query string has multiple commands in it and if any of the
commands don't match with the event trigger command tag.

This ensures that we only allow single DDL query strings, blocking any mixes of DDL+DML (this can
cause issues where we have duplicated rows replicated) or multiple DDLs in a single query string
(this can cause issues when we need to do special handling of individual DDLs within this grouping)
Jira: DB-10982

Test Plan:
```
ybd --cxx-test xcluster_ddl_replication-test --gtest_filter "XClusterDDLReplicationTest.BlockMultistatementQuery"
```

Manual test:
```
>>> ./bin/ysqlsh -c "CREATE TABLE tbl2 (a int); insert into tbl2 values (1),(2);"
ERROR:  Database is replicating DDLs for xCluster. In this mode only a single DDL command is allowed in the query string.
Please run the commands one at a time.
 Full query string: CREATE TABLE tbl2 (a int); insert into tbl2 values (1),(2);
```

Reviewers: hsunder, xCluster

Reviewed By: hsunder

Subscribers: yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D34709