[#15196] YSQL: Take row-level (instead of column-level) locks for UPDATE operations
Summary:
In YugabyteDB, unlike PostgreSQL, concurrent UPDATEs to different
columns of the same row are permitted in REPEATABLE READ/READ COMMITTED
isolation levels, meaning they don't conflict.  This behavior leads to
several correctness issues in YSQL, which are not present in PostgreSQL,
as demonstrated in the following three scenarios. All the issues
described below stem from what could be termed a 'write-skew anomaly
within a row', e.g, txn T1 and T2 concurrently read col1 and col2
(respectively) of a row, and then based on some computation of the read
value, update col2 and col1, respectively.  This breaks some intuitive
invariants that users might expect.

In YSQL, concurrent transactions updating different columns of the same
row don't conflict because we implicitly write only the (kStrongWrite,
kStrongRead) intent modes on the individual columns. Owing to our
algorithm, which writes the kWeak versions of these intent modes on all
prefixes, we take the kWeak versions on the row level too. But these are
not sufficient to cause a conflict.

**Scenario 1**

CHECK constraints on more than one column can be violated if the columns are
updated concurrently in different transactions.

```
CREATE TABLE products (
 product_no integer,
 name text,
 price numeric,
 CHECK (price > 0),
 discounted_price numeric,
 CHECK (discounted_price > 0),
 CHECK (price > discounted_price)
);

INSERT INTO products values (1, 'oats', 10, 1);

--txn1
BEGIN;
UPDATE products SET price = 3 WHERE product_no = 1;

--txn2
BEGIN;
UPDATE products SET discounted_price = 4 WHERE product_no = 1;

--txn1
COMMIT;
--txn2
COMMIT;
```

```
yugabyte=# SELECT * FROM products;
 product_no | name | price | discounted_price
------------+------+-------+------------------
          1 | oats |     3 |                4
(1 row)
```

**Scenario 2**

User maintained "check" constraint via a function can be violated

```
CREATE TABLE t(k INT PRIMARY KEY, v1 INT, v2 INT);
INSERT INTO t VALUES(1, 10, 20);

CREATE OR REPLACE FUNCTION add_with_limit(cur_value INT, delta INT, sum_limit INT) RETURNS INT AS $$
BEGIN
    IF cur_value + delta < sum_limit THEN
        RETURN cur_value + delta;
    END IF;
    RETURN cur_value;
END;
$$ LANGUAGE plpgsql;

-- txn1
BEGIN;
UPDATE t SET v1 = add_with_limit(v1, v2, 35) WHERE k = 1;

-- txn2
BEGIN;
UPDATE t SET v2 = add_with_limit(v2, v1, 35) WHERE k = 1;

-- txn1
COMMIT;
-- txn2
COMMIT;
```

```
yugabyte=# SELECT *, v1 + v2 FROM t;
 k | v1 | v2 | ?column?
---+----+----+----------
 1 | 30 | 30 |       60
(1 row)
```

**Scenario 3**

A foreign key relation may be violated.

```
CREATE TABLE ref_t(k1 INT, k2 INT, PRIMARY KEY(k1, k2));
INSERT INTO ref_t VALUES(1, 1), (10, 1), (1, 10);
SELECT * FROM ref_t;
 k1 | k2
----+----
  1 |  1
  1 | 10
 10 |  1
(3 rows)

CREATE TABLE t(k INT PRIMARY KEY, fk1 INT, fk2 INT, FOREIGN KEY(fk1, fk2) REFERENCES ref_t(k1, k2));
INSERT INTO t VALUES(1, 1, 1);
INSERT INTO t VALUES(2, 10, 10); -- This is expected to fail because ref_t doesn't have row (k1: 10, k2: 10)
ERROR:  insert or update on table "t" violates foreign key constraint "t_fk1_fkey"
DETAIL:  Key (fk1, fk2)=(10, 10) is not present in table "ref_t".

-- txn1
BEGIN;
UPDATE t SET fk1 = 10 WHERE k = 1; -- OK because ref_t has row (k1: 10, k2: 1)

-- txn2
BEGIN;
UPDATE t SET fk2 = 10 WHERE k = 1; -- OK because ref_t has row (k1: 1, k2: 10)

-- txn1
COMMIT;
-- txn2
COMMIT;
```

```
SELECT * FROM t;
 k | fk1 | fk2
---+-----+-----
 1 |  10 |  10
(1 row)

SELECT * FROM ref_t;
 k1 | k2
----+----
  1 |  1
  1 | 10
 10 |  1
(3 rows)
```

We can solve this 'write-skew anomaly within a row' problem in YSQL in various
ways:

1. Take kStrongRead locks on the columns that are read by an UPDATE statement.
2. Take a kStrongRead lock on the whole row instead of just the column which are read.
3. Take kStrongRead and kStrongWrite locks on the whole row instead of just the column which is written.

We take approach (2) because: in (1) it can be hard to identify and lock
only columns that were read by Postgres and had an effect on the values
updated in that row. (3) takes an extra kStrongWrite which breaks
compatibility with FOR KEY SHARE.

The fix essentially reverses the optimization from 83a150b0. It builds
on the existing infrastructure that takes read locks in a SERIALIZABLE
transaction (added in 90bc0620). This extends the read locks to the
other isolation levels.

This commit introduces a new gflag `ysql_skip_row_lock_for_update` to
toggle row-level locking behavior during concurrent updates on different
columns of the same row.

Default Behavior (gflag set to false): This is the recommended setting,
ensuring alignment with standard SQL behavior for data consistency. It
addresses the 'write-skew anomaly within a row' problem by enforcing
stricter locking mechanisms during updates, thereby preserving data
integrity as per the scenarios outlined in this commit message.

Alternative Setting (gflag set to true): While not recommended, this
setting reverts to the previous behavior. It may be necessary in certain
workloads where concurrent updates to different columns significantly
impact performance. However, users should exercise caution as this
setting reintroduces the correctness issues detailed in GitHub Issue
#15196. It should only be used after careful consideration of the
trade-offs between performance and data consistency.
Jira: DB-4381

Test Plan:
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressProc'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgWaitQueuesRegress'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgWithoutWaitQueuesIsolationRegress'
./yb_build.sh --cxx-test pg_row_lock-test
./yb_build.sh --cxx-test pg_misc_conflicts-test --gtest_filter 'PgMiscConflictsTest.DifferentColumnsConcurrentUpdate'

Reviewers: pjain, dmitry

Reviewed By: pjain, dmitry

Subscribers: ybase, yql, smishra

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D30618