[#21866] docdb: Emit abort reason on clone failure.
Summary:
This diff adds the abort reason to the PG output of clone if a clone is aborted.

It also removes the `PgClone.Clone` test because we test the same behavior but with a PG interface in `PgClone.CloneYsqlSyntax`.

It also changes Subprocess::Call to return stdout and stderr separately so we can return the stderr of ysql_dump to the user. This is very useful if they forgot to configure auth, for example:
```
yugabyte=# CREATE DATABASE foo TEMPLATE yugabyte;
ERROR:  Clone operation aborted: Runtime error (yb/util/subprocess.cc:632): Subprocess '/Users/asrivastava/code/yugabyte-db/build/latest/bin/../postgres/bin/ysql_dump' terminated with non-zero exit status 256: ysql_dump: [archiver (db)] connection to database "yugabyte" failed: FATAL:  no pg_hba.conf entry for host "[local]", user "yugabyte", database "yugabyte", SSL off
```

Fixes #21866
Jira: DB-10765

Test Plan: `./yb_build.sh --cxx-test integration-tests_minicluster-snapshot-test --gtest_filter PgCloneTest.AbortMessage`

Reviewers: mhaddad, xCluster, hsunder

Reviewed By: mhaddad

Subscribers: ybase

Differential Revision: https://phorge.dev.yugabyte.com/D35212