[BACKPORT 2025.1][#17159] YSQL: Test secondary indexscan inconsistency on a concurrent delete
Summary:
Original commit: c0e5fd7b0a9558ece975cc1ad5e8569e1da7dd05 / D45015
Port the test from 7d4cb5bb6015d26c9920633969abf44656abf4a9 / D44421

### Test Description

**Setup:** Bank Workload.

Writer: Performs a DELETE_INSERT operation to move balance from an old account to a new one.
Reader: Computes the total balance across all accounts to verify consistency.
Inconsistency error observed (in older versions): missing money

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2025-05-31 03:34:33,162 [Thread-3] ERROR ExceptionsTracker - Failed to compare sums: Expected 10000 - actual 9000, IndexScan,  WHERE id >= 0
java.lang.AssertionError: Expected 10000 - actual 9000, IndexScan,  WHERE id >= 0
```

The above error is not observed on master through 2025.1 because the fix in the original commit is already available in these versions.
Jira: DB-6436

Test Plan:
Jenkins

Test attributed to @pjain

Backport-through: 2025.1

Reviewers: sergei, pjain, smishra

Reviewed By: pjain

Subscribers: yql, pjain

Differential Revision: https://phorge.dev.yugabyte.com/D45022