[#4525][YSQL] Tablegroup query layer changes.
Summary:
The motivation behind having multiple groups of co-located tables within a database is similar to that of specifying a database as co-located. Currently, in specifying a database as co-located, we are able to generate a single tablet that all future tables (that do not opt out of co-location) are added to. This allows a user to co-locate closely related tables together and avoid paying the cost of additional round trips when making joins etc. amongst the related data or paying the storage/compute overhead of creating a tablet for every relation, improving performance.

The first step in supporting more flexible colocation is creating the concept of a "tablegroup." Colocating tables together within a tablegroup allows for related tables to be placed on one tablet (without restrictions on their primary keys). This will be supported in YSQL as follows:

- CREATE TABLEGROUP tablegroup_name grpoptions;
This will create a tablegroup within the current database to allow for future tables to be attached to and colocated together. Similar to our implementation of a colocated database, on the docdb side we will create a single tablet to store the data of all tables that belong to the tablegroup. grpoptions will be how we support Copartitioning / Interleaving in the future.
- DROP TABLEGROUP tablegroup_name;
This will remove a tablegroup of the corresponding name (if it exists).
- CREATE TABLE ... TABLEGROUP tablegroup_name;
This will add a table to a tablegroup. We will not support the joint inclusion of SPLIT and TABLEGROUP in any DDL as tablegroups (for now) are single tablets.  CREATE INDEX follows the tablegroup of the indexed table.

This also involves some changes to the postgres system catalog in order to maintain tablegroup relationships on backup and restore as well as catch DDL errors on the PG side. The following changes will be included in this diff:
- The inclusion of the catalog `pg_tablegroup` which will include a tablegroup's oid, name, owner, acl, and colocation options.
- The inclusion of a `tablegroup` option in pg_class `reloptions` that contains the Oid of a relation's tablegroup (if any, otherwise the text option is null and the `tablegroup` field in the rd_options struct is unallocated).

```
            Table "pg_catalog.pg_tablegroup"
   Column   |   Type    | Collation | Nullable | Default
------------+-----------+-----------+----------+---------
 grpname    | name      |           | not null |
 grpowner   | oid       |           | not null |
 grpacl     | aclitem[] |           |          |
 grpoptions | text[]    |           |          |
Indexes:
    "pg_tablegroup_oid_index" PRIMARY KEY, lsm (oid)
```

Additionally, to avoid confusion, we will not mix the previous colocation functionality and tablegroups. That means that within a colocated database, no tablegroups will be able to be created. The prior implementation of colocation will eventually be deprecated and running clusters with colocated databases will be migrated to use tablegroups.

This diff also includes functionality related to privileges and tablegroup ddl. In order to CREATE TABLEGROUP, the user must either have CREATE privs within the database or be a superuser. In order to DROP TABLEGROUP, the user must be the owner of the tablegroup or a superuser.

The default OIDs I have picked are as followed:
  - pg_class OID for pg_tablegroup (TableGroupRelationId): 8000
  - pg_class OID for pg_tablegroup_oid_index (TablegroupOidIndexId): 8001
  - pg_type rowtype OID for pg_tablegroup (TablegroupRelation_Rowtype_Id): 8002

For all future changes to the catalog that introduce a new default OID, please change `YB_MIN_UNUSED_OID` in `include/catalog/catalog.h` which is currently set to 8003.

Test Plan:
Added the following Java test:

```
org/yb/pgsql/TestPgRegressTablegroup.java
```
As well as the following test schedule with corresponding sql test and expected output:

```
regress/yb_tablegroups_schedule
regress/sql/yb_create_tablegroup.sql
regress/expected/yb_create_tablegroup.out
regress/sql/yb_create_tablegroup_permissions.sql
regress/expected/yb_create_tablegroup_permissions.out
```
The test can be run as follows (reinitdb necessary for pg metadata changes):

```
./yb_build.sh reinitdb --clean-postgres --java-test org.yb.pgsql.TestPgRegressTablegroup
```

To test upgrade did not break things I did the following:
```
git checkout master
ybd && ybd reinitdb
./bin/yb-ctl destroy && ./bin/yb-ctl create
git checkout metadata
ybd
./bin/yb-ctl restart && ./bin/ysqlsh
```
Then I tested various DDL/DML operations to ensure that pg_class tuples were correctly inserted / operations did not break.
I also tested that any statements involving tablegroups produced the following:
```
ERROR:  Tablegroup system catalog does not exist.
```

Reviewers: neha, jason, nicolas, mihnea

Reviewed By: jason, nicolas, mihnea

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D8747