[#26859] YSQL: Fix enum type restore failure from old backup
Summary:
Commit 620938b506fedba07e0cb7ac7df8078cd70a86df preserves enum sortorder during
backup. However if a backup was generated by ysql_dump prior to this commit, it
would not have emitted a query such as
```
SELECT pg_catalog.yb_binary_upgrade_set_next_pg_enum_sortorder('2'::real);
```

Currently when restoring enum type, we throw an error if
yb_binary_upgrade_next_pg_enum_sortorder is not set:

```
        if (isnan(yb_binary_upgrade_next_pg_enum_sortorder))
            ereport(ERROR,
                    (errcode(ERRCODE_INVALID_PARAMETER_VALUE),
                     errmsg("pg_enum sortorder value not set when in binary upgrade mode")));
```

This breaks backward compatibility and the new code cannot restore an old backup.
As a result after restore the pg_enum catalog table is empty.

To fix this regression, I changed ERROR to WARNING, and fall back to
auto-generated new OID as we did before, effectively reverted the fix of above
regression commit , but better than having an empty pg_enum table after db restore.

Test Plan:
Manual test:

(1) Make an old build using commit 4b44b76ef95ccc8b3e898f5514aa30b9f314cd9a
(which comes prior to the above regression commit)
(2) Make a new build using the above regression commit
(3) create a local RF-1 using old build
```
./bin/yb-ctl create --rf 1
```
(4) Run the following ysqlsh command to populate the database yugabyte
```
./bin/ysqlsh -d yugabyte -c "CREATE TYPE planets AS ENUM ( 'A', 'B' ); CREATE TABLE enum_table (c planets); INSERT INTO enum_table (c) VALUES('A'); SELECT * FROM pg_catalog.pg_enum; SELECT * from enum_table"
CREATE TYPE
CREATE TABLE
INSERT 0 1
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 16386 |     16385 |             1 | A
 16388 |     16385 |             2 | B
(2 rows)

 c
---
 A
(1 row)

```
(5) Run the following backup command to produce an old backup
```
./managed/devops/bin/yb_backup.py --masters 127.0.0.1:7100 --remote_yb_admin_binary=./build/latest/bin/yb-admin --remote_ysql_dump_binary=./build/latest/postgres/bin/ysql_dump --remote_ysql_shell_binary=./build/latest/postgres/bin/ysqlsh --storage_type nfs --nfs_storage_path /tmp/ --no_ssh --no_auto_name --TEST_never_fsync --ysql_host=127.0.0.1 --backup_location /tmp/backup/ create --ts_web_hosts_ports 127.0.0.1:9000 --keyspace ysql.yugabyte --verbose
```

(6) stop the cluster
```
./bin/yb-ctl stop
```

(7) restart the cluster using the new build
```
./bin/yb-ctl start
```

(8) Run the following restore command to restore from the old backup using
new build
```
./managed/devops/bin/yb_backup.py --masters 127.0.0.1:7100 --remote_yb_admin_binary=./build/latest/bin/yb-admin --remote_ysql_dump_binary=./build/latest/postgres/bin/ysql_dump --remote_ysql_shell_binary=./build/latest/postgres/bin/ysqlsh --storage_type nfs --nfs_storage_path /tmp/ --no_ssh --no_auto_name --TEST_never_fsync --ysql_host=127.0.0.1 --backup_location /tmp/backup/ restore --ts_web_hosts_ports 127.0.0.1:9000 --keyspace ysql.yb2 --verbose

```
(9) Run the following ysqlsh command after restore
```
./bin/ysqlsh -d yb2 -c "SELECT * FROM pg_catalog.pg_enum; SELECT * from enum_table"
 oid | enumtypid | enumsortorder | enumlabel
-----+-----------+---------------+-----------
(0 rows)

ERROR:  invalid internal value for enum: 16386
```

This demonstrates the regression bug symptom: the pg_enum table is empty after restore,
as a result we see `ERROR:  invalid internal value for enum: 16386`.

(7) Repeat the test by making a new build with the diff, the final step shows
```
./bin/ysqlsh -d yb2 -c "SELECT * FROM pg_catalog.pg_enum; SELECT * from enum_table"
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 16386 |     16385 |             1 | A
 16388 |     16385 |             2 | B
(2 rows)

 c
---
 A
(1 row)
```

From PG log:
```
postgresql-2025-04-17_050553.log:2025-04-17 05:06:14.007 UTC [3826664] WARNING:  pg_enum sortorder value not set when in binary upgrade mode
postgresql-2025-04-17_050553.log:2025-04-17 05:06:14.051 UTC [3826664] WARNING:  pg_enum sortorder value not set when in binary upgrade mode
```

Reviewers: sanketh, mihnea

Reviewed By: sanketh

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D43295