[#11383] YSQL: Backup/Restore support for UDT/Enum types
Summary:
Recently it was discovered that YSQL backup/restore had error when user-defined types or enum types
are involved. Following are three examples from the ticket.

Example 1:
In the source database, run the following SQL commands:

```
create type e_t as enum('c', 'b', 'a');
CREATE TYPE
create table t(id e_t);
CREATE TABLE
insert into t values ('a'), ('b'), ('c');
INSERT 0 3
select oid, * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 16386 |     16385 |             1 | c
 16388 |     16385 |             2 | b
 16390 |     16385 |             3 | a
(3 rows)

select * from t order by id;
 id
----
 c
 b
 a
(3 rows)
```

Do database restore on the target database. After restoring, run the following commands in the
target database and observe the error:

```
select oid, * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 16398 |     16396 |             1 | c
 16400 |     16396 |             2 | b
 16402 |     16396 |             3 | a
(3 rows)

select * from t order by id;
ERROR:  invalid internal value for enum: 16386
```

The last command select * from t order by id; failed because when trying to use OID 16386 as the
primary key to lookup pg_enum table, it is not found. We can see that when the enum type e_t is
recreated on the target cluster, its labels and itself are assigned new OIDs that are different from
the old OIDs on the source cluster. The reason for 16386 showing up in the error is because YSQL
backup/restore copies the underlying SST files in order to have better performance and 16386 comes
from the copied SST files.

Example 2:
In the source database, run the following SQL commands:
```
create type udt1 as (f1 int, f2 text);
CREATE TYPE
create table t2(id udt1);
CREATE TABLE
insert into t2 values((1, '1')), ((1, '2')), ((1, '2'));
INSERT 0 3
select * from t2 order by id;
  id
-------
 (1,1)
 (1,2)
 (1,2)
(3 rows)
```

After restoring, run the following command on the target database:
```
select * from t2 order by id;
ERROR:  type with OID 16386 does not exist
```

In this example, there is no enum type used. However, the type udt1 has an old OID 16386, it is
stored in the record values and in the restored database the type udt1 has a new OID 16396:

```
yb2=# select oid from pg_type where typname = 'udt1';
select oid from pg_type where typname = 'udt1';
  oid
-------
 16396
(1 row)
```

Example 3:
In the source database, run the following SQL commands:
```
CREATE DOMAIN postal_code AS TEXT
             CHECK(VALUE ~ '^\d{5}$'OR VALUE ~ '^\d{5}-\d{4}$');
CREATE DOMAIN
CREATE TABLE foo(postal postal_code[]);
CREATE TABLE
INSERT INTO foo values (array['32768', '65536']::postal_code[]);
INSERT 0 1
select * from foo;
    postal
---------------
 {32768,65536}
(1 row)
```

After restoring, we see
```
select * from foo;
ERROR:  cache lookup failed for type 16385
```

In this example, the array element type is a domain type postal_code and its old OID is stored as
part of the array value.

All these examples show the "stale OID" problem: an old OID is referenced but it no longer exists on
the target database because a new OID is generated for the same database object.

In Postgres, backup and restore involves a complete export/import of the source database. This
includes both the system catalog tables and user tables. During the backup (export) phase, SQL
commands are generated in a file (db-sql-script) to not only recreate the schemas of all the
database objects (via DDL stataments), but also all the data in the user tables (via DML statements
like INSERT or COPY).  During restore phase the previous db-sql-script is send to ysqlsh. If a enum
label OID is referenced in the source user table data, very likely in the target database the same
enum label will have a new OID. By executing db-sql-script to repopulate the user table data, the
new enum label OID will be stored in user table data of the target database. Therefore we'll not
have the "stale OID" problem.

YSQL backup and restore is different from Postgres backup and restore. For performance reason, all
the data in the user tables are not regenerated via db-sql-script. Instead the corresponding docdb
SST files are directly copied to the target cluster and reused as is. If an enum label has a new OID
in the target database, the old OID stored in the user table data isn't updated to the new OID. As a
result, we'll see the "stale OID" problem.

In order to reuse the SST files as is, we must ensure that the old OIDs stored in the user table
data remain valid. This can be done by forcing the new OID to be identical to the old OID.

It turns out that Postgres has already solved this problem for us. Postgres has a --binary-upgrade
option that can ensure that the exact old OIDs are used for the same database object created in the
target database. I made code changes to leverage the Postgres mechanism by adding a new
--yb-binary-backup option to ysql_dump/ysql_dumpall. This new option will not do everything that
--binary-upgrade does during export phase but will be exactly like --binary-upgrade for those OIDs
that need to remain identical between the source and target DBs.

Test Plan:
./yb_build.sh release --cxx-test tools_yb-backup-test_ent
./yb_build.sh release --java-test org.yb.cql.TestYbBackup --tp 1
./yb_build.sh release --java-test org.yb.cql.ParameterizedTestYbBackup --tp 1
./yb_build.sh release --java-test org.yb.pgsql.TestYsqlDump
./yb_build.sh release --cxx-test tools_yb-backup-test_ent./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testAlteredTable
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testAlteredTableInColocatedDB
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testMixedColocatedDatabase
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testAlteredTableInOriginalCluster
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testColocatedWithTableOidAlreadySet
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testAlteredTableWithNotNull
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testIndex
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testIndexTypes
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testCollationIndexTypesEn
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testCollationIndexTypesSv
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testCollationIndexTypesTr
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testPartialIndexes
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testRestoreWithRestoreTime
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testSedRegExpForYSQLDump
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioning
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioningNoRegions
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioningOneRegion
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioningRestoringIntoExisting
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioningWithTablespaces
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioningNoRegionsWithTablespaces
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioningOneRegionWithTablespaces
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testGeoPartitioningRestoringIntoExistingWithTablespaces
./yb_build.sh release --java-test org.yb.pgsql.TestYbBackup#testUserDefinedTypes

Reviewers: mihnea, alex, smishra, oleg, achauhan

Reviewed By: alex, smishra, oleg

Subscribers: yql, jenkins-bot

Differential Revision: https://phabricator.dev.yugabyte.com/D15303