[#8763] Fixed asan/tsan build type default clang version
Summary:
```
ybd asan --sj packaged
+ /nfusr/dev-server/timur/code/yugabyte-db/yb_build.sh asan --sj packaged
[2021-06-04T13:02:45 yb_build.sh:1070 main] YugabyteDB build is running on host 'dev-server-timur'
[2021-06-04T13:02:45 yb_build.sh:1071 main] YB_COMPILER_TYPE=clang
2021-06-04 13:02:45,936 [thirdparty_tool.py:349 INFO] Available release archives:
...
ValueError: Could not find a third-party release archive to download for OS type 'centos7' and compiler type 'clang'. Please see the list of available thirdparty archives above.
```

The fix is to change default compiler type to clang7 for asan/tsan build type, since just "clang" is not supported for centos7 anymore.

Test Plan:
- run `ybd asan` and `ybd tsan`
- Jenkins

Reviewers: mbautin

Reviewed By: mbautin

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D11822