[#25047] YSQL: Implement index AM changes for copartitioned vector indexes
Summary:
This diff brings in LRT support for copartitioned vector indexes. Copartitioned vector indexes are colocated with their respective base tablets. As “copartitioned” would suggest, each partition of the index is colocated with all the main table rows it indexes. DocDB replicates main table inserts/deletes/updates into any associated copartitioned vector indexes. Hence, DocDB ignores any insert/delete/update index requests from PG. So as an optimization, this diff ensures that such index requests from PG are not sent out anymore by making them no-ops. Insert/Delete/Update index logic for these indexes have effectively been made no-ops by this change.

This update improves the efficiency of index scan read requests by ensuring they are handled as colocated index scans. Previously, PG would inefficiently send two separate requests to DocDB for such index scans, similar to non-colocated index scans. DocDB had implemented a temporary workaround to process these requests in that format (D39849/499f75968a6409c2603a4c933cd60756d23a2cf8). With this change, the workaround is no longer needed, and PG will now send a single, optimized colocated index scan request for copartitioned index scans. This change removes this workaround.

Vector index AM’s that are expected to be copartitioned have the boolean `yb_amiscopartitioned` set to true in their AM handler struct.

This diff also makes sure to push down any LIMIT through to a vector index read.
NOTE: Since DocDB vector indexes do not support paging for now, this LIMIT pushdown means that vector queries with a filter and limit may work incorrectly if DocDB truly honors the LIMIT pushdown. For this reason, this change disables such honoring from the DocDB side for now.

Until GHI #22826 is resolved, we cannot support multi-tablet vector indexes, which is why this change makes ybhnsw index creation fail with the following error on tables that have multiple tablets:
```
ERROR:  Invalid table definition: Error creating index yugabyte.items_embedding_idx on the master: Copartitioned vector index must have only one tablet for now.
```

Before this change, one could create a ybhnsw index on a multi-tablet table and receive incorrect results from scans on this table due to GHI #22826.
Jira: DB-14179

Test Plan: ./yb_build.sh --java-tests 'org.yb.pgsql.TestPgRegressThirdPartyExtensionsPgvector.java'

Reviewers: kramanathan, jason, sergei

Reviewed By: jason

Subscribers: sergei, ybase, yql

Differential Revision: https://phorge.dev.yugabyte.com/D40112