[pg15-upgrade] fix: compiler error on various builds
Summary:
Commit 8b270c2843fce04c38d2ef6c395cb4e0e090867a removed the use of the resetwal_bin variable in a YB_TODO, but still declares and sets the variable. This works locally in various build flavors, but causes a build error on the Jenkins alma gcc11 and Mac builds:

  ../../../../../../src/postgres/src/bin/pg_upgrade/controldata.c:75:11: error: variable 'resetwal_bin' set but not used [-Werror,-Wunused-but-set-variable]
          char       *resetwal_bin;

This wasn't caught because Jenkins wasn't run on the commit.

Test Plan: Jenkins: compile only

Reviewers: swapnil.shivam

Reviewed By: swapnil.shivam

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D34573