[#4249][YSQL] Ignore NotFound errors while deleting an index.
Summary:
Since our drop index operation is not atomic with respect to DocDB and postgres
metadata, it is possible that DocDB doesn't have a table metadata but postgres
does. In this case we can neither delete the table or create a new one with the
same name.

With this code we should be able to delete the index from the postgres metadata
by ignoring the 'NotFound' error from DocDB.

Test Plan:
Manually tested by faking an error when a deletion is called for the first time
from the DocDB layer, making sure that it is deleted the second time it is
called.

Before Change:
yugabyte=# create index b_idx on users(b);
CREATE INDEX
yugabyte=# drop index b_idx;
ERROR: Internal error: FAKE error
yugabyte=# drop index b_idx;
ERROR: Not found: The object was deleted: Deleted with tablets at 2020-04-18 01:14:49 UTC

After Change:
yugabyte=# create index b_idx on users(b);
CREATE INDEX
yugabyte=# drop index b_idx;
ERROR:  Internal error: FAKE error
yugabyte=# drop index b_idx;
DROP INDEX

Reviewers: neha, jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D8329