[BACKPORT 2025.1][#27588] YSQL: Print reason for storage flush under debug logs
Summary:
This revision backports the following (in order of cherry-pick) commits:
Original commits:
 - cbbb323e6f1a5f632ba82c6c0aff9fc12c67f466 / D44988
 - 70d5d02ca70e109a0b369d7a4aa93ae8ac1c9352 / D46695
 - c937939553f1cadac65a704d04054c14182bb1ba / D47365

===Backport Notes (master --> 2025.1)===
- src/yb/yql/pggate/ybc_pg_typedefs.h
	- Positional conflict with `b8ae33569f021c7c3b92cb6cdb5b2cf237bde5d8`.
	- Resolution: Move definition of `YbcFlushReason` and `YbcFlushDebugContext` above `YbcPgSharedDataPlaceholder` to maintain same order as in master.
- src/postgres/src/backend/utils/time/snapmgr.c
	- Conflict with `9124c053cc8ba7824ec87e8a02a0afe2c354ed35` which moves the flush from `GetTransactionSnapshot()` to `YbResetTransactionReadPoint()` in `pg_yb_utils.c`
	- Resolution: Keep behavior as in `9124c053cc8ba7824ec87e8a02a0afe2c354ed35`.
- src/yb/yql/pggate/pg_operation_buffer.h
	- Positional conflict due to `aa816a4bc00fd2fd77d650e125abde068025ade7` not being backported.
	- Resolution: Remove changes due to `aa816a4bc00fd2fd77d650e125abde068025ade7`.
- src/yb/yql/pggate/pg_operation_buffer.cc
	- Conflict due to `66551891ce7dda1737203a1f005cd08e16bb4392` being backported before this commit.
	- Resolution: Retain changes from both.
- src/yb/yql/pggate/pg_session.h
	- Conflict in function signature of `FlushBufferedOperations()` due to `aa816a4bc00fd2fd77d650e125abde068025ade7` not being backported.
	- Resolution: Remove changes due to `aa816a4bc00fd2fd77d650e125abde068025ade7`. `FlushBufferedOperations()` continues to return Status.
- src/yb/yql/pggate/pg_session.cc
	- Multiple conflicts due to `aa816a4bc00fd2fd77d650e125abde068025ade7` not being backported. Summarized below:
		- Function `AcquireAdvisoryLock` does not perform a flush. Resolution: Retain behavior as in 2025.1
		- Function `AcquireObjectLock` is not present. Resolution: Retain behavior as in 2025.1
		- Function `SetupIsolationAndPerformOptionsForDdl` does not perform a flush. Resolution: Retain behavior as in 2025.1
		- Function `SetActiveSubTransaction` performs a redundant flush (same flow already performs a flush in `pggate.cc`). Resolution: Copy over the same flush reason from the instance of the function in `pggate.cc` to that in `pg_session.cc`.
		- Function `RollbackToSubTransaction` is removed by the above commit. Resolution: Retain behavior as in 2025.1 and add debug context to flush performed in function.
	- Consequently, the following flush reasons have been removed:
		- YB_ACQUIRE_ADVISORY_LOCK
		- YB_ACQUIRE_OBJECT_LOCK
		- YB_EXECUTE_DDL
                - YB_EXPORT_SNAPSHOT (see below)
                - YB_IMPORT_SNAPSHOT (see below)
- src/yb/yql/pggate/pggate.cc
	- Multiple conflicts due to `aa816a4bc00fd2fd77d650e125abde068025ade7` not being backported. Summarized below:
		- Conflict in function `SetActiveSubTransaction`. Resolution: Remove changes due to `aa816a4bc00fd2fd77d650e125abde068025ade7`
		- Functions `ExportSnapshot` and `ImportSnapshot` do not perform a flush. Resolution: Retain behavior as in 2025.1
- src/yb/yql/pggate/pg_tools.cc
	- Remove changes in this file as buffer is not flushed before acquiring AdvisoryLock or ObjectLock (see above).

===D44988: [#27588] YSQL: Print reason for storage flush under debug logs===
The contents of the write buffer (`PgOperationBuffer`) in pggate is flushed for a handful of reasons:
 - Reasons external to the buffer: such as end of statement/subtransaction/transaction, change of snapshot etc.
 - Reasons internal to the buffer: multiple writes to the same row, an enqueued read operations that needs to read the contents of the buffer etc.

In large queries, it is currently quite hard to determine what caused the flush. It is often important to know in order to improve the query's performance.
This revision logs the reason for flushing the write buffer when `yb_debug_log_docdb_requests` is enabled.

This revision has the following goals:
 - Improve the explainability of storage flush requests: achieved by logging the reason for flushing
 - Improve code searchability: introducing an enum of flush reasons allows grepping for values in the enum across the code base.
 - No degradation in performance: when `yb_debug_log_docdb_requests` is turned off, the debug strings are not constructed, and no memory is allocated. This reduces any performance impact.
Jira: DB-17164

===D46695: [#28605] YSQL: refactor YbcFlushDebugContext code===

Commit cbbb323e6f1a5f632ba82c6c0aff9fc12c67f466 passes around new
YbcFlushDebugContext.  Fix multiple issues with it:

- On the upper layers (PG), pass the YbcFlushDebugContext struct by
  pointer rather than by value.  This not only reduces copying but also
  fixes some pgindent errors on the call sites.
- Remove debug_context_ and pass things around using function parameters
  instead.  The lifecycle of debug_context_ is unclear, and there are
  places that set it to nullptr when it will never be read in that
  situation: it is always set to something else before it is read
  (dereferenced, in fact).
- Also remove internal_debug_context_ since there is no point in keeping
  that around for more than a single stack frame: use stack local
  variables instead.
- Rename all "context" variables to "debug_context" for consistency.

Jira: DB-18297

===D47365: [#28913] YSQL: Fix dangling std::string::c_str() setting up YbcFlushDebugContext===

cbbb323e6f1 adds a few places where we do something like the following:
```
debug_context.strarg2 = row_id.ybctid().ToDebugHexString().c_str();
```
where `ToDebugHexString()` returns a new `std::string`. The backing `std::string` is destroyed
at the end of the assignment, so `debug_context.strarg2` now contains a dangling pointer. This
is caught in newer clang versions (clang21) with the following error:
```
../../src/yb/yql/pggate/pg_operation_buffer.cc:382:35: error: object backing the pointer 'debug_context.strarg2' will be destroyed at the end of the full-expression [-Werror,-Wdangling-assignment-gsl]
  382 |           debug_context.strarg2 = row_id.ybctid().ToDebugHexString().c_str();
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fix this by storing the temporary std::string in a separate variable.
Jira: DB-18636

Test Plan: Run Jenkins

Reviewers: jason, esheng

Reviewed By: jason

Subscribers: ybase, yql, smishra, svc_phabricator

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D47678