ysql: improve ALTER TABLE [NOT] OF errmsg
Summary:
The ALTER TABLE OF error message says

    ERROR:  ALTER TABLE OF name not supported yet

The "name" should be a type name, so "type" would be more fitting, but
just get rid of "name" altogether because it's simpler.

Same goes for ALTER TABLE NOT OF, except it doesn't normally take an
argument, so it's correct to get rid of "name".

Port the ALTER TABLE OF and ALTER TABLE NOT OF portions of the
alter_table regress test to a new yb_pg_alter_table.

Test Plan: ./yb_build.sh --java-test org.yb.pgsql.TestPgRegressTable

Reviewers: myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D12077