[BACKPORT 2.20][PLAT-11805] Fix Edit Universe Retry Failure
Summary:
Original commit: 52481157f2fad2fede4eae511b2b8084ef16f3c1 / D30916
We can see that retry for edit universe in k8s universes can fail with following stack trace in retry.

```
YW 2023-12-09T16:19:16.691Z [ERROR] 37467ffa-3c05-4edd-b659-5857568598ff from TaskExecutor in TaskPool-EditKubernetesUniverse(16b09142-5b08-43e0-9d18-52dbfefbb6ff)-0 - Failed to execute task type ChangeMasterConfig UUID 927a5fdb-86b5-4cc1-9f71-683428246537 details {"platformVersion":"2.21.0.0-b307","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"16b09142-5b08-43e0-9d18-52dbfefbb6ff","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"clusters":[],"currentClusterType":"PRIMARY","rootAndClientRootCASame":true,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"updateSucceeded":true,"universePaused":false,"softwareUpgradeState":"Ready","isSoftwareRollbackAllowed":false,"nextClusterIndex":1,"allowInsecure":true,"setTxnTableWaitCountFlag":false,"itestS3PackagePath":"","remotePackagePath":"","nodesResizeAvailable":false,"useNewHelmNamingStyle":false,"mastersInDefaultRegion":true,"isKubernetesOperatorControlled":false,"overridePrebuiltAmiDBVersion":false,"importedState":"NONE","capability":"EDITS_ALLOWED","updateOptions":[],"otelCollectorEnabled":false,"azUuid":"0a97eefc-3acb-4986-92cc-6f0de7202e62","nodeName":"yb-master-2_us-west1-a","useSystemd":false,"properties":{},"opType":"RemoveMaster","xclusterInfo":{"targetXClusterConfigs":[],"sourceXClusterConfigs":[]},"targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
java.lang.RuntimeException: Cannot find node yb-master-2_us-west1-a
	at com.yugabyte.yw.commissioner.tasks.subtasks.ChangeMasterConfig.run(ChangeMasterConfig.java:99)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:849)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1261)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
```

This is caused because there is a time of check vs time of use issue when we check nodeDetails for the node vs when we use it in task run.
Before task is executed in run method we remove the node from the universe by executing POD_INFO, this causes the node to be removed from universe details.

This change relaxes the assertion in ChangeMasterConfig.run to account for this condition.

If we get ChangeMasterConfig for a node thats already removed from universe, we assume that node is already removed and continue execution.

Test Plan: retry-itest, manual

Reviewers: sanketh, cwang, nsingh

Reviewed By: sanketh

Subscribers: yugaware

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D30961