[Backport 2.19.1.1109][PLAT-9763] Fix Alma 9 ARM AMI upgrade "TypeError: in method 'lgetfilecon_raw'" issue
Summary:
At some point we started getting below errors during VM image upgrade on Alma 9 ARM universes:

TASK [provision-cluster-server : Provision | Ensure proper permissions for mount paths.] ***
Wednesday 19 July 2023  03:56:20 +0000 (0:00:00.213)       0:00:08.672 ********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: in method 'lgetfilecon_raw', argument 1 of type 'char const *'
failed: [10.8.1.133] (item=/mnt/d0) => changed=false
  ansible_loop_var: item
  item: /mnt/d0
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_file_payload_qihpn81r/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
      File "/tmp/ansible_file_payload_qihpn81r/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
      File "/tmp/ansible_file_payload_qihpn81r/ansible_file_payload.zip/ansible/modules/files/file.py", line 665, in ensure_directory
      File "/tmp/ansible_file_payload_qihpn81r/ansible_file_payload.zip/ansible/modules/files/file.py", line 340, in recursive_set_attributes
      File "/tmp/ansible_file_payload_qihpn81r/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1432, in set_fs_attributes_if_different
      File "/tmp/ansible_file_payload_qihpn81r/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1035, in set_context_if_different
      File "/tmp/ansible_file_payload_qihpn81r/ansible_file_payload.zip/ansible/module_utils/basic.py", line 961, in selinux_context
      File "/usr/lib64/python3.9/site-packages/selinux/__init__.py", line 618, in lgetfilecon_raw
        return _selinux.lgetfilecon_raw(path)
    TypeError: in method 'lgetfilecon_raw', argument 1 of type 'char const *'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

Up-versioning ansible helps to fix that, but we need to make other ansible scenarios compatible with newer version.
Short term fix is to replace file mocule call with plain chown call.
Was not able to find though why the issue started - we observe successful upgrades and failures with the same combination of YBA/YB DB and AMI versions.

Original diff: https://phorge.dev.yugabyte.com/D27196

Test Plan:
Create universe with Alma 9 ARM AMI.
Perform VM image upgrade via API. Upgrade is successful.

Reviewers: svarshney, muthu

Reviewed By: svarshney

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D27197