[BACKPORT 2.17.2] Remove nanoid
Summary:
nanoid v4 is an ESM only package so we run into issues when our code is transpiled.
This causes errors in `npm test`
```
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { randomFillSync } from 'crypto'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
For now we'll remove the nanoid dependency and use build-in functions to generate a random alphanumeric string.

Original commit: dbd16ee4cf616d5e850e406b66156e11c9223d64 / D23668

Test Plan:
Pass `npm test`
Verify that existing usages of nanoid's random id generation still work fine with the new random string generator:
Region deletion-
{F35520}
Random GCE Network name generation (feature disabled by default- enabled for testing only):
{F35521}

Reviewers: rmadhavan, svarshney

Reviewed By: svarshney

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D23669