[Backport 2.6] [#4014] YSQL: Indexes on Enum based columns
Summary:
Currently in YSQL enum type only has limited support. The following examples
illustrate the restrictions:

```
yugabyte=# create type e_t as enum('a', 'b');
create type e_t as enum('a', 'b');
CREATE TYPE
yugabyte=# create table foo(id e_t primary key);
create table foo(id e_t primary key);
ERROR:  PRIMARY KEY containing column of type 'user_defined_type' not yet supported
yugabyte=# create table bar(id e_t);
create table bar(id e_t);
CREATE TABLE
yugabyte=# create index bar_id_idx on bar(id);
create index bar_id_idx on bar(id);
ERROR:  INDEX on column of type 'user_defined_type' not yet supported
yugabyte=# alter type e_t add value 'c';
alter type e_t add value 'c';
ERROR:  ALTER TYPE not supported yet
LINE 1: alter type e_t add value 'c';
        ^
HINT:  See https://github.com/YugaByte/yugabyte-db/issues/1893. Click '+' on the description to raise its priority
```

Multiple customers have requested better enum support to allow enum primary
key and index on enum columns.

This diff aims to get the same level of enum support as in postgres with one
exception of the so called "label renumbering". Postgres internally assign
each enum element a unique oid, plus a 4-byte binary float number that is used
to represent the sort order of the label. Postgres also allows adding new labels
before or after an existing label. If one keeps adding new labels before existing
labels, then at some point postgres will not be able to find a float number that
can maintain the sort order of all labels. At that time postgres goes through
a "label renumbering" process to throw away the old set of sorted floats, assign
a new set of sorted floats (initialized to be a new set of consecutive integers
starting from 1). YSQL does not support "label renumbering" because of docdb
implemention restriction.

The changes are:
(1) Remove enum related restrictions from gram.y
(2) Each enum element is stored as an 8-byte int64, which is composed of a 4-byte sort float plus a 4-byte oid of the enum element. Having the 4-byte oid of the enum element makes it possible in the future to use a custom comparator function which can ignore the 4-byte sort order and only do proper sort on the enum element.
(3) In pggate, when we compose PgConstant (which is where we are about to send the enum value to docdb), we build the above int64 combo.
(4) The int64 combo is built in a way that is byte-sortable, so docdb can support index and primary key of enum type.
(5) The existing YB enum test is expanded to include more from the orignal enum regression test. Compared with regular postgres test output, the only differences are
(5.1) "label renumbering"
(5.2) cannot add new values to existing enums in a transaction
(6) A new enum index backfill test is added to ensure pre-existing enum column data that did not have sort order can work properly after database upgrade. Pre-existing enum data are written under a test only gflag --TEST_do_not_add_enum_sort_order.
(7) Known issue:  creating an enum index during upgrade (when some nodes are new and others are old) will not work because old postgres will not add sort order when creating the index. This needs to be added to the release notes.

Original commit: D11379 / 131ea34ec5333c007b2ecab9162abadeeece0b10

Test Plan: Jenkins: rebase: 2.6

Reviewers: mbautin, jason, mihnea, neil

Reviewed By: neil

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D12186