[BACKPORT 2024.2][#30319] YSQL: Improve error hint when a database is dropped and recreated
Summary:
We have a situation where the database is dropped and recreated with the same name. The newly
created database will have a new OID. However even after a universe restart, the client app contains
some stale connection metadata that contains the old OID and it continues to use that old OID to
contact the Yugabyte universe and gets an error like:

```
ERROR: catalog version for database 16896 was not found. to FATAL: catalog version for database 16896 was not found.
```

It will be better if the error hint can indicate that scenario so
that a user can be informed to also restart the client app, or refresh its metadata cache to pick
the new OID.

The relevant code is:

```
ereport(ERROR,
                        (errcode(ERRCODE_DATABASE_DROPPED),
                         errmsg("catalog version for database %u was not found.", db_oid),
                         errhint("Database might have been dropped by another user")));
```

I updated the error hint to be more helpful (add recreated scenario, and client refresh):
```
HINT: Database may have been dropped and recreated. Ensure your client connection pool or metadata
cache is refreshed to pick up the new database OID.
```

Original commit: a89c939a03bc437d8aa8c2b045aee36523014041 / D50458

Test Plan: ./yb_build.sh release --cxx-test pg_catalog_version-test

Reviewers: kfranz, sanketh, fizaa

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D50599