[#16612] docdb: Fix transaction promotion race condition resulting in unnecessary abort
Summary:
This diff fixes a race condition where a transaction:
1. Starts with a write into a region-local table or region-local partition of
   a geo-partitioned table (to allow the transaction to start as local)
2. Proceeds to write multiple rows into a table that spans multiple regions,
   including the local region, where:

   a. the first row is written into a tablet where (despite the table spanning
     multiple regions) all replicas are in the local region

   b. a later row is written into a tablet where this is not the case

The writes in (2) may then be run in parallel, and it becomes possible for the
local write in (2a) to have not yet been processed by the tserver before the
promotion triggered by (2b) causes UpdateTransactionStatusLocation RPCs to
be send to the tablet in (2a). This results in the transaction participant
not recognizing the transaction and ultimately triggering an abort of the
transaction:

```
ERROR:  Move transaction status: Transaction f123ce6e-46b0-4be4-a216-0b32dd031323
expired or aborted by a conflict: 40001: Errors from tablet servers: [Operation expired
(yb/tablet/transaction_participant.cc:1163): Move transaction status: Transaction
f123ce6e-46b0-4be4-a216-0b32dd031323 expired or aborted by a conflict: 40001
 (pgsql error 40001)] (pgsql error 40001)
```

Test Plan: `ybd --cxx-test pgwrapper_geo_transactions_promotion-test --gtest_filter GeoTransactionsPromotionRF1Test.TestPromoteBeforeEarlierWriteRPCReceived`

Reviewers: sergei

Reviewed By: sergei

Subscribers: bkolagani, pjain, rthallam, ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D24438