[#16408] YSQL: Fix TestPgRegressIndex.testPgRegressIndex expected test output
Summary:
The unit test org.yb.pgsql.TestPgRegressIndex.testPgRegressIndex is always
failing now because the test output needs to be updated due to a recently
introduced table rewrite NOTICE output:

```
NOTICE:  table rewrite may lead to inconsistencies
DETAIL:  Concurrent DMLs may not be reflected in the new table.
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/19860. Set 'ysql_suppress_unsafe_alter_notice' yb-tserver gflag to true to suppress this notice.
```

In addition, the test output itself isn't reliable because of the following
error for statement `drop index idxpart0_pkey;`:

```
ERROR:  cannot drop index idxpart0_pkey because index idxpart_pkey requires it
HINT:  You can drop index idxpart_pkey instead.
```
vs
```
ERROR:  cannot drop index idxpart0_pkey because constraint idxpart0_pkey on table idxpart0 requires it
HINT:  You can drop constraint idxpart0_pkey on table idxpart0 instead.
```

Both are possible and which one gets reported depends upon the order in the
pg_depend scan output. Because pg_depend does not have a primary key, it uses
YB generated uuid and therefore the scan output order isn't fixed.

I updated the expected test output.
Jira: DB-5819

Test Plan: ./yb_build.sh release --java-test 'org.yb.pgsql.TestPgRegressIndex#testPgRegressIndex'

Reviewers: fizaa

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D36068