[PLAT-10710]Crash YBA if Operator thread crashes on Init based on a config
Summary:
- Based on global runtime config added support to crash YBA if Operator thread crashes on init.
- The global config `yb.kubernetes.operator.crash_yba_on_operator_init_failure` decides this.
- By default, the config is set to true.

Test Plan:
Manual testing, following are the logs:

```
2023-12-29T16:25:12.585Z  [error]  KubernetesOperator.java:284 [Thread-11] com.yugabyte.yw.common.operator.KubernetesOperator Kubernetes operator thread failed
java.lang.RuntimeException: Operator Initialization Failed
	at com.yugabyte.yw.common.operator.KubernetesOperator.lambda$init$0(KubernetesOperator.java:274)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-29T16:25:12.588Z  [info]  CoordinatedShutdownSupport.scala:63 [Thread-12] play.api.internal.libs.concurrent.CoordinatedShutdownSupport Starting synchronous coordinated shutdown with ServerStoppedReason reason and 2147513000 milliseconds timeout
2023-12-29T16:25:12.590Z  [info]  PekkoHttpServer.scala:519 [Thread-12] play.core.server.PekkoHttpServer Stopping Pekko HTTP server...
2023-12-29T16:25:12.601Z  [info]  PekkoHttpServer.scala:530 [application-pekko.actor.internal-dispatcher-3] play.core.server.PekkoHttpServer Unbinding /0.0.0.0:9000
2023-12-29T16:25:12.611Z  [info]  PekkoHttpServer.scala:549 [application-pekko.actor.internal-dispatcher-3] play.core.server.PekkoHttpServer Terminating server binding for /0.0.0.0:9000
```

Pod status:

```
NAME                         READY   STATUS             RESTARTS      AGE
vkumar-yugaware-yugaware-0   2/3     CrashLoopBackOff   4 (51s ago)   4m14s
```

Reviewers: anijhawan, dshubin

Reviewed By: anijhawan

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D31317