[#16460] YSQL: Improve error messages for transaction conflicts
Summary:
When a serialization error occurs the TServer returns an error status to a
Postgres backend with the error code, and an error message. These error
messages are directly reported to the Postgres client, and they will appear
similar to one of the following.

A transaction finds a conflict with another higher priority transaction while
running:

```
ERROR:  85560eb5-ddcc-41b1-b977-90cd10d93b87 conflicts with higher priority transaction: bd7a3f9a-1f08-4ae2-8116-ae7280ead34b
```

A transaction finds a conflict with already committed data:

```
ERROR:  Value write after transaction start: { days: 19436 time: 16:45:29.976488 } >= { days: 19436 time: 16:45:29.963593 }: kConflict
```

This commit modifies these error messages to align with Postgres conventions,
and includes additional log DETAIL information for specific transaction
conflicts.

```
ERROR:  could not serialize access due to concurrent update
DETAIL:  85560eb5-ddcc-41b1-b977-90cd10d93b87 conflicts with higher priority transaction: bd7a3f9a-1f08-4ae2-8116-ae7280ead34b
```

This commit focuses on refining error messages associated with explicit
kConflict errors and does not affect all errors with code 40001. Further
commits will address the remaining errors. Unaffected error messages include
those related to transactions that have been aborted due to deadlock or
timeout, transactions canceled because of conflicts with higher priority
transactions (e.g., when the cluster operates in fail-on-conflict mode), and
transactions requiring a read restart. These scenarios will retain their
original error messages.

An example of a transaction canceled due to a concurrent, higher priority
transaction in wait-on-conflict mode:

```
ERROR:  Transaction 2d9a3564-95a4-4710-8169-c50bdadcd9ba expired or aborted by a conflict: 40001
```

Test Plan:
Tests updated for the logging change:

./yb_build.sh --java-test 'org.yb.pgsql.TestPgTransparentRestarts'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgForeignKeyBatching'
./yb_build.sh --java-test 'org.yb.pgsql.TestOneOrTwoAdmins'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgExplicitLocks'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgForeignKey'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgForeignKeyBatching'
./yb_build.sh --cxx-test pg_libpq-test --gtest_filter '*SerializableColoring*'
./yb_build.sh --cxx-test pg_libpq_err-test --gtest_filter '*WithoutCommit*'
./yb_build.sh --cxx-test pg_ddl_atomicity-test --gtest_filter '*TestParallelDdl*'
./yb_build.sh --cxx-test pg_index_backfill-test --gtest_filter '*CreateIndexSimultaneously*'
./yb_build.sh --cxx-test pg_libpq-test --gtest_filter '*TxnConflictsForColocatedTables*'
./yb_build.sh --cxx-test pg_libpq-test --gtest_filter '*TxnConflictsForTablegroups*'
./yb_build.sh --cxx-test pg_libpq-test --gtest_filter '*TxnConflictsForColocatedTablesInLegacyColocatedDB*'
./yb_build.sh --cxx-test pg_mini-test --gtest_filter '*SerializableReadOnly*'
./yb_build.sh --cxx-test pg_mini-test --gtest_filter '*ForShare*'
./yb_build.sh --cxx-test pg_mini-test --gtest_filter '*ForUpdate*'
./yb_build.sh --cxx-test pg_mini-test --gtest_filter '*ForKeyShare*'
./yb_build.sh --cxx-test pg_mini-test --gtest_filter '*ForNoKeyUpdate*'
./yb_build.sh --cxx-test pg_mini-test --gtest_filter '*ConcurrentDelete*'

Reviewers: amartsinchyk, pjain

Reviewed By: amartsinchyk, pjain

Subscribers: smishra, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D23667