[BACKPORT 2.20.1][PLAT-11454] Ignore errors when expanding PVC, recreate STS, and then throw any PVC expansion error
Summary:
Original commit: ecc6bba6a8dab2bfb3e915b30ef856757de82884 / D30297
As per design [1] we want to do the following for a successful volume expansion:
1. delete sts --cascade=orphan
2. change PVC to new size, wait for pod to recognize new size
3. recreate sts (helm upgrade)

If there is an error at step 2, we still want to execute step 3 and then throw the exception.

~~This is possible if the tasks are declared within the same SubTaskGroup that ignores errors. This change moves the above three tasks within such a SubTaskGroup.~~

This change ignores the error at step 2 (with a try-catch that just logs the error), continues to step 3 that recreates the Sts, and finally runs the KubernetesPostExpansionCheckVolume that throws the exception if the actual volume is not of desired size.

[1] https://docs.google.com/document/d/17uICeDf02Uc_GdzSuwd5S9P7U50uTjpSxL2Meeoe6UI/edit?pli=1#heading=h.pbaouved4f6b

Test Plan:
1. Create universe with tserver volume size of 100Gb
2. Manually edit the PVC size to 105Gb (kubectl edit pvc), wait for pod to recognize new size (exec into tserver and df -kh)
3. From YBA UI, edit universe and change tserver volume size to 101Gb. YBA universe details still thinks volume size is increasing from 100Gb to 101Gb, so it will start the task. However, the actual PVC edit will fail. Verified with this change that the helm upgrade recreates the sts and then fails the task with exception message.
```
W 2023-11-17T04:18:27.629Z [ERROR] 183de49d-4561-4326-9743-dcb98c0019ae from TaskExecutor in TaskPool-1 - Failed to execute task type EditKubernetesUniverse UUID bbcf070a-aeb1-46af-b26f-9c192cc4e125 details ...
hit error.
java.lang.RuntimeException: SubTaskGroup ResizingDisk of type Provisioning at position 1: completed 3 out of 3 tasks failed.
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1191)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1149)
        at com.yugabyte.yw.commissioner.tasks.EditKubernetesUniverse.run(EditKubernetesUniverse.java:175)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:849)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1062)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Unable to patch PVC. Code: 1. Output: The PersistentVolumeClaim "ybsubbu-test--us-west1-a-lief-datadir0-ybsubbu-test--us-west1-a-lief-yb-tserver-0" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value
        at com.yugabyte.yw.common.ShellResponse.processErrors(ShellResponse.java:56)
        at com.yugabyte.yw.common.ShellKubernetesManager.expandPVC(ShellKubernetesManager.java:449)
        at com.yugabyte.yw.commissioner.tasks.subtasks.KubernetesCommandExecutor.run(KubernetesCommandExecutor.java:372)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:849)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1261)
        ... 6 common frames omitted
YW 2023-11-17T04:18:27.629Z [DEBUG] 183de49d-4561-4326-9743-dcb98c0019ae from TaskExecutor in TaskPool-1 - Task creator callstack:
com.yugabyte.yw.commissioner.TaskExecutor.createRunnableTask(TaskExecutor.java:335)
com.yugabyte.yw.commissioner.TaskExecutor.createRunnableTask(TaskExecutor.java:313)
com.yugabyte.yw.commissioner.Commissioner.submit(Commissioner.java:120)
com.yugabyte.yw.controllers.handlers.UniverseCRUDHandler.submitEditUniverse(UniverseCRUDHandler.java:994)
com.yugabyte.yw.controllers.handlers.UniverseCRUDHandler.updatePrimaryCluster(UniverseCRUDHandler.java:945)
com.yugabyte.yw.controllers.handlers.UniverseCRUDHandler.update(UniverseCRUDHandler.java:890)
com.yugabyte.yw.controllers.UniverseUiOnlyController.update(UniverseUiOnlyController.java:238)
v1.Routes$$anonfun$routes$1.$anonfun$applyOrElse$448(Routes.scala:9919)
play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:150)
play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:149)
play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
play.core.j.JavaAction$$anon$1.call(JavaAction.scala:119)
play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
com.yugabyte.yw.controllers.TokenAuthenticator.call(TokenAuthenticator.java:204)
com.yugabyte.yw.controllers.FailedRequestAction.call(FailedRequestAction.java:33)
```

Case 2:
Verified that if there is a failure in PVC expansion due to any error from the underlying cloud provider, the error is now raised and the task fails (but the statefulset is recreated).
Tested this in local env by setting the wait time for PVC expansion task to a low 1 sec.
{F128417}

Reviewers: #yba-api-review, anijhawan, dshubin, sanketh

Reviewed By: #yba-api-review, anijhawan

Subscribers: yugaware

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D31213