[#17159] YSQL: Fix secondary indexscan inconsistency on a concurrent delete
Summary:
### Issue

**Setup:** Bank Workload.

1. Writer: Performs a DELETE_INSERT operation to move balance from an old account to a new one.
2. Reader: Computes the total balance across all accounts to verify consistency.

Inconsistency error observed: missing money

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2025-05-31 03:34:33,162 [Thread-3] ERROR ExceptionsTracker - Failed to compare sums: Expected 10000 - actual 9000, IndexScan,  WHERE id >= 0
java.lang.AssertionError: Expected 10000 - actual 9000, IndexScan,  WHERE id >= 0
```

**Hypothesis:**

1. The issue occurs during a secondary index scan when it is reading the main table using ybctids from the index.
2. A concurrent DELETE occurs during the scan. This delete is available in the main table but not so in the index due to being too recent.
3. When the scan reaches the main table using the ybctid from the index, the ybctid is tombstoned.
4. This happens even though the delete's hybrid timestamp is higher than the index scan's read time, because the timestamp is still less than the global limit. The intent aware iterator reads records less than global limit.
5. Since the tombstoned record is in the range (read_time, global_limit], shouldn't this cause a read restart error instead of returning a inconsistent read?
6. No. Since the ybctid is tombstoned, ExecuteBatchKeys (in pgsql_operation.cc) receives a FetchResult::NotFound and recreates the iterator.
7. Recreating the iterator discards the max_seen_ht state, losing awareness of the recent delete tombstone. As a result, the read operation fails to raise a read restart error, which should have occurred.

### Approach

Refresh the iterator so that the iterator does not lose max_seen_ht state.
Jira: DB-6436

Test Plan:
Jenkins: rebase: 2024.2, urgent

Adds test PgLibPqTest.InconsistentIndexRead to simulate the above scenario of (1) secondary index scan (2) concurrent delete.
Test is authored by @pjain.

Backport-through: 2.20

Reviewers: pjain, sergei, dmitry

Reviewed By: sergei

Subscribers: smishra, pjain, yql

Differential Revision: https://phorge.dev.yugabyte.com/D44421