[#20073] CDCSDK: Fix query on pg_replication_slots before cdc_state_table creation
Summary:
Query on `pg_replication_slots` view fails before any cdc/xcluster stream is created in the universe. This is because it tries to lookup the
CDCStateTable which does not yet exist as it is created as part of the first cdc/xcluster stream creation.

**Steps to reproduce:**
Try the below steps on a new cluster without creating any cdc/xcluster streams.

```
yugabyte=# select * from pg_replication_slots where slot_name = 'test_replication_slot';
ERROR:  Timed out waiting for Table Creation
```
This revision updates the logic to only read cdc_state_table if a cdcsdk stream exists which guarantees that the cdc_state_table exists.
Jira: DB-9029

Test Plan: `./yb_build.sh --cxx-test cdcsdk_ysql-test --gtest_filter "*TestPgReplicationSlotsWithoutCDCStateTable*"`

Reviewers: skumar, asrinivasan

Reviewed By: skumar

Subscribers: yql, ybase, ycdcxcluster, bogdan

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D30577