Clear pipeline upon exceptions.
Summary:
Clear pipeline upon exceptions under Redis pipeline mode (including sync() and get()).

This is to avoid further exceptions, due to unflushed pipeline.

e.g:

2017-07-31 19:35:30,919 [INFO|com.yugabyte.sample.common.IOPSThread|IOPSThread] Caught Exception 10.129.63.57:6379
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
        at redis.clients.jedis.Protocol.process(Protocol.java:151)
        at redis.clients.jedis.Protocol.read(Protocol.java:215)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
        at redis.clients.jedis.Connection.getAll(Connection.java:310)
        at redis.clients.jedis.Connection.getAll(Connection.java:302)
        at redis.clients.jedis.Pipeline.sync(Pipeline.java:99)
        at com.yugabyte.sample.apps.RedisPipelinedKeyValue.flushPipelineIfNecessary(RedisPipelinedKeyValue.java:53)
        at com.yugabyte.sample.apps.RedisPipelinedKeyValue.doWrite(RedisPipelinedKeyValue.java:101)
        at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:300)
        at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:73)
2017-07-31 19:35:32,543 [ERROR|com.yugabyte.sample.apps.RedisPipelinedKeyValue|RedisPipelinedKeyValue] Caught Exception from redis pipeline 10.129.50.146:6379
redis.clients.jedis.exceptions.JedisDataException: Please close pipeline or multi block before calling this method.
        at redis.clients.jedis.Response.get(Response.java:33)
        at com.yugabyte.sample.apps.RedisPipelinedKeyValue$1.call(RedisPipelinedKeyValue.java:80)
        at com.yugabyte.sample.apps.RedisPipelinedKeyValue$1.call(RedisPipelinedKeyValue.java:77)
        at com.yugabyte.sample.apps.RedisPipelinedKeyValue.flushPipelineIfNecessary(RedisPipelinedKeyValue.java:57)
        at com.yugabyte.sample.apps.RedisPipelinedKeyValue.doRead(RedisPipelinedKeyValue.java:45)
        at com.yugabyte.sample.apps.AppBase.performRead(AppBase.java:323)
        at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:74)

In this case the first exception (redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.) would still be caught, and rethrown to be handled at the higher layers ( sleep/count and exit after 500 consecutive exceptions). However, clearing the pipeline should prevent the 2nd exception.

Test Plan: push to cluster. & launch redis load tester. take host down and check the logs.

Reviewers: karthik, hector, bharat

Reviewed By: bharat

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D2590