[PLAT-2588][Platform] Task Improvement - Make Backup task clean up processes on abort
Summary: The change aborts the backup tasks while also cleaning up the processes and the running the exit tasks like cleaning up files.

Test Plan:
I first created a test python program as

```
import sys
import atexit
import time
import signal
import atexit
from multiprocessing.pool import ThreadPool

pools=[]
def cleanup_on_exit(signum, frame):
    print "cleaning up"
    for pool in pools:
        print("Terminating...")
        pool.terminate()
    sys.exit()

def cleanup_normal():
    print "cleaning up normal"

def run():
    # Register normal cleanup
    atexit.register(cleanup_normal)
    pool = ThreadPool(2)
    pools.append(pool)
    print("Executing now")
    pool.apply(func1)

def func1():
    for i in range(10):
        print("Sleeping in loop ", i)
        time.sleep(2)

signal.signal(signal.SIGINT, cleanup_on_exit)
signal.signal(signal.SIGTERM, cleanup_on_exit)

pool = ThreadPool(1)
future = pool.apply_async(run)
try:
    while not future.ready():
        future.wait(timeout=1)
finally:
    pool.terminate()
```

Output:

```
Executing now
('Sleeping in loop ', 0)
cleaning up
Terminating...
cleaning up normal
```

This was tested by cancelling the future in another Java program. The main thread needs to be in a wait-loop (non-blocking) to handle the signal.
https://www.g-loaded.eu/2016/11/24/how-to-terminate-running-python-threads-using-signals/

Tested this by running a backup and saw that the file copying processes were killed. The callbacks registered to atexit are also invoked meaning the cleanup takes place.

```
2021-12-23 14:55:46.272 [error] TaskExecutor.java:787 [TaskPool-0] Failed to execute task type MultiTableBackup UUID 6f9894a9-282c-48be-bc0f-77177fe56d86 details {"nodeExporterUser":"prometheus","universeUUID":"a84943bc-0fb7-4add-8cdf-30f89c23f4b6","encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"sse":false,"storageConfigUUID":"4a77d80a-5858-413f-b52a-f1be9d0cc5e2","actionType":"CREATE","backupType":"PGSQL_TABLE_TYPE","tableUUIDList":[],"schedulingFrequency":0,"minNumBackupsToRetain":3,"timeBeforeDelete":86400000,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":8,"ignoreErrors":false,"customerUUID":"f33e3c9b-75ab-4c30-80ad-cba85646ea39","targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
java.util.concurrent.CancellationException: FinalizeUniverseUpdate : completed 1 out of 1 tasks. is cancelled.
```

Reviewers: vpatibandla, vkumar, sanketh, amalyshev

Reviewed By: amalyshev

Subscribers: oleg, jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D14498