[PG15][#19690] YSQL: Simplify side-by-side diff handling
Summary:
Cherry-pick of commit 58e31150e5dd7b9cc92824e79783cb1745466d29 from master.

Due to the amount of time it requires to maintain SideBySideDiff.java, switching to a much simpler, less full-featured implementation. (Mainly, no line numbers, and doesn't try to avoid clipping either side.)

This commit entirely removes errors from `SideBySideDiff.sanityCheckLinesMatch()`, that had the text:
```
java.lang.RuntimeException: SideBySideDiff sanity check failed: ...
```
Jira: DB-8491

Test Plan:
Jenkins: rebase: pg15, test regex: .*(PgRegress|YsqlDump|StringUtil).*

```
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressTabletSplit'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressIndex'
./yb_build.sh --java-test 'org.yb.pgsql.TestYsqlDump'
./yb_build.sh --java-test 'org.yb.util.TestStringUtil'
```
`TestPgRegressIndex` and `TestYsqlDump` will fail, but the error messages are meaningful.

Reviewers: jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D29908