ENG-2712: Too many open files causing YW to crash.
Summary:
The Java YBClient executor threads connection close was removed inadvertently by https://phabricator.dev.yugabyte.com/D3718#97423164. Restoring the connection closure in this change...

Test Plan:
mvn test -Dtest=org.yb.client.TestYBClient#testClientCreateDestroy
Without fix, it runs into:
```
java.lang.OutOfMemoryError: unable to create new native thread
	at org.yb.client.TestYBClient.testClientCreateDestroy(TestYBClient.java:102)
```
Jenkins

Reviewers: robert, sergei, bogdan

Reviewed By: bogdan

Subscribers: kannan, ram, ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D3874