[BACKPORT 2025.1][#26914] DocDB: Fix the HTTP 503 response on Master API requests
Summary:
The webserver’s static 503 response (used by endpoints like /api/v1/is-leader) was missing a second CRLF as required by the HTTP spec. Per RFC 7230, an HTTP response must terminate the header section with a blank line (CRLF following the headers). The previous static response only included a single CRLF after the status line, resulting in a malformed response when no body was present.

This change ensures the 503 response is properly terminated with two CRLFs, aligning with the HTTP specification and preventing issues in strict clients parsing the response.
Jira: DB-16345

Original commit: 375f36c15f4b5b4293e1a46ff681e62978428b86 / D43859

Test Plan:
Used the go repro from the github issue to validate the fix

Previous response before the fix:
Response: <nil>
Error: Get "http://127.0.0.1:7000/api/v1/is-leader": net/http: HTTP/1.x transport connection broken: unexpected EOF

New Response after the fix:
Response: &{503 Service Unavailable 503 HTTP/1.1 1 1 map[] 0xc00021c040 -1 [] true false map[] 0xc000148360 <nil>}
Error: <nil>

Reviewers: asrivastava, jhe

Reviewed By: jhe

Differential Revision: https://phorge.dev.yugabyte.com/D43903