[#13022]DST: Compilation errors on gcc11
Summary:
Commit 7301497eae13a0df84fbff303c7cd9de4961ae17 introduced compilation error on gcc11. This
diff fixes them. The following errors were noticed:

```
/-------------------------------------------------------------------------------
[2022-07-21T06:22:35.385Z] | COMPILATION FAILED
[2022-07-21T06:22:35.385Z] |-------------------------------------------------------------------------------
[2022-07-21T06:22:35.385Z] ent/src/yb/master/restore_sys_catalog_state.cc:282:5: error: multi-line comment [-Werror=comment]
[2022-07-21T06:22:35.385Z]   282 |     //                               /   \
[2022-07-21T06:22:35.385Z]       |     ^
[2022-07-21T06:22:35.385Z] ent/src/yb/master/restore_sys_catalog_state.cc:284:5: error: multi-line comment [-Werror=comment]
[2022-07-21T06:22:35.385Z]   284 |     //                              / \    /  \
[2022-07-21T06:22:35.385Z]       |     ^
[2022-07-21T06:22:35.385Z] cc1plus: all warnings being treated as errors
[2022-07-21T06:22:35.385Z]
[2022-07-21T06:22:35.385Z] Input files:
[2022-07-21T06:22:35.385Z]   src/yb/master/CMakeFiles/master.dir/__/__/__/ent/src/yb/master/restore_sys_catalog_state.cc.o
[2022-07-21T06:22:35.385Z]   ent/src/yb/master/restore_sys_catalog_state.cc
[2022-07-21T06:22:35.385Z] Output file (from -o): src/yb/master/CMakeFiles/master.dir/__/__/__/ent/src/yb/master/restore_sys_catalog_state.cc.o
[2022-07-21T06:22:35.385Z] \-------------------------------------------------------------------------------
```

```
/-------------------------------------------------------------------------------
[2022-07-21T06:22:25.963Z] | COMPILATION FAILED
[2022-07-21T06:22:25.963Z] |-------------------------------------------------------------------------------
[2022-07-21T06:22:25.963Z] src/yb/master/master_snapshot_coordinator.cc: In member function 'yb::Status yb::master::MasterSnapshotCoordinator::Impl::RestoreSysCatalogReplicated(int64_t, const yb::tablet::SnapshotOperation&, yb::Status*)':
[2022-07-21T06:22:25.963Z] src/yb/master/master_snapshot_coordinator.cc:466:5: error: missing initializer for member 'yb::master::SnapshotScheduleRestoration::non_system_tablets_to_restore' [-Werror=missing-field-initializers]
[2022-07-21T06:22:25.963Z]   466 |     });
[2022-07-21T06:22:25.963Z]       |     ^
[2022-07-21T06:22:25.963Z] cc1plus: all warnings being treated as errors
[2022-07-21T06:22:25.963Z]
[2022-07-21T06:22:25.963Z] Input files:
[2022-07-21T06:22:25.963Z]   src/yb/master/CMakeFiles/master.dir/master_snapshot_coordinator.cc.o
[2022-07-21T06:22:25.963Z]   src/yb/master/master_snapshot_coordinator.cc
[2022-07-21T06:22:25.963Z] Output file (from -o): src/yb/master/CMakeFiles/master.dir/master_snapshot_coordinator.cc.o
[2022-07-21T06:22:25.963Z] \-------------------------------------------------------------------------------
```

Test Plan: Jenkins

Reviewers: asrivastava

Reviewed By: asrivastava

Subscribers: jason, zyu, ybase, bogdan

Differential Revision: https://phabricator.dev.yugabyte.com/D18482