[BACKPORT 2025.1][#27148] YSQL: Make commit statement a DDL when running YSQL upgrade scripts
Summary:
Currently, if a DDL statement writes to PG catalog tables that generates
invalidation messages, we often will increment the catalog version in
`pg_yb_catalog_version` table and insert the captured invalidation messages into
`pg_yb_invalidation_messages` table. The new version and associated invalidation
messages will be broadcast to all PG backends on all the nodes via tserver
master heartbeat mechanism. Such a DDL statement is called `new-version` DDL
as it increments the catalog version.

Some DDL statements do not increment the catalog version (e.g., a simple CREATE
TABLE statement), we call these DDL statements `same-version DDL` as opposed to
the `new-version DDL` whose behavior is described above. Such a DDL does writes
to PG catalog tables and generate invalidation messages, but we assume that
those invalidation messages only serve to invalidate negative cache entries
because these DDL statements add new database objects rather than altering or
dropping an existing one. YSQL has disabled negative caching for such a case and
therefore those invalidation messages would become a no-op even if we tried to
apply them because the negative cache entries they are meant to remove do not
exist.

There is a special case in YSQL upgrade mode where we allow DML statements
directly write to PG catalog tables under the GUC
`yb_non_ddl_txn_for_sys_tables_allowed=1`. These DML statements also generate
invalidation messages. They do not cause catalog version to increase. If there
is no DDL statement following these DML statements, their messages are simply
dropped in the same way as a `same-version` DDL. But if they are followed by a
`new-version` DDL statement, then this can cause a difference between full
catalog cache refresh and incremental catalog cache refresh:

* A full catalog cache refresh takes care of those dropped invalidation messages
  because the entire catalog cache is refreshed
* Incremental catalog cache refreshes only broadcast and apply the invalidation
  messages generated by the DDL statement, those that are generated by the DMLs
  are ignored, which can cause stale cache problem.

In addition, YSQL does allow negative caching for some system catalog entries.
The assumption is that during normal operation, those system portion of catalog
tables do not change and therefore it is more efficient to allow negative
caching for them. But during YSQL upgrade, that assumption is no longer true:
the YSQL migrate script can actually alter those system catalog entries and
therefore we should not ignore invalidation messages generated by DMLs. In fact
the simple CREATE TABLE statement is turned into a `new-version DDL` if the GUC
`ysql_upgrade_mode` is set to true, that means we do need to invalidated
negative system cache entries during YSQL upgrade.

To fix this YSQL upgrade problem in incremental refresh mode, I changed to
classify COMMIT statement into a DDL statement that increments the catalog
version (but non-breaking). It is assumed that migrate scripts are well-formed
so that each block of DML statements will be properly terminated by a COMMIT
statement. In order to capture all the invalidation messages, I also made a
change to use snapshot isolation mode during YSQL upgrade. This is needed as a
simple work around so that we do not start subtransactions during YSQL upgrade.
Otherwise the COMMIT will only capture the invalidation messages generated by
the last DML statement preceding the COMMIT statement.

Note that this problem is more general because it can appear outside the YSQL
upgrade context. The fix here is not going to work universally beyond YSQL
upgrade context where we assume simple use case and can use snapshot isolation.
We are likely need to have transactional DDL support where we can come back to
fix the more general problem. At present, if customers need to use
`yb_non_ddl_txn_for_sys_tables_allowed=1` to directly write to catalog tables,
they need to explicitly increment the catalog version to trigger a full catalog
cache refresh in order to fix the stale cache created by the catalog writes.

I picked a few representative YSQL migrate scripts and put them into new unit
tests. These new unit tests would fail before this diff.
Jira: DB-16631

Original commit: 6af35186607383e17d52f615499cbd444664d83d / D43861

Test Plan:
(1) ./yb_build.sh --cxx-test pg_catalog_version-test   --gtest_filter PgCatalogVersionTest.InvalMessageYsqlUpgradeCommit*

(2) Manually backport the code change to 2024.2 and run
```
./yb_build.sh --java-test 'org.yb.pgsql.TestYsqlUpgrade'
```
Verify the tests passed and the test logs do not have the error `invalid transaction termination`.

Make a change to introduce `COMMIT` inside an anonymous block
```
diff --git a/src/yb/yql/pgwrapper/ysql_migrations/V59.6__21851__yb_backend_heap_snapshot.sql b/src/yb/yql/pgwrapper/ysql_migrations/V59.6__21851__yb_backend_heap_snapshot.sql
index 3c90be8758..32602d5a93 100644
--- a/src/yb/yql/pgwrapper/ysql_migrations/V59.6__21851__yb_backend_heap_snapshot.sql
+++ b/src/yb/yql/pgwrapper/ysql_migrations/V59.6__21851__yb_backend_heap_snapshot.sql
@@ -55,6 +55,7 @@ BEGIN;
         ) VALUES
           (0, 0, 0, 1255, 8086, 0, 'p');
       END IF;
+    COMMIT;
     END $$;
 COMMIT;
```

Run
```
./yb_build.sh --java-test 'org.yb.pgsql.TestYsqlUpgrade#migratingIsEquivalentToReinitdb'
```
Verify the test failed and the following error appeared in test logs:
```
java.lang.AssertionError: Process exited with code 1, message: <Error running upgrade_ysql: Network error (yb/yql/pgwrapper/libpq_utils.cc:412): Unable to upgrade YSQL cluster: Failed to apply migration 'V59.6__21851__yb_backend_heap_snapshot.sql' to a database template1: Execute failed: 7, message: ERROR:  invalid transaction termination
```

Reviewers: kfranz, sanketh, mihnea

Reviewed By: kfranz

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D43975