YSQL: add schema version mismatch error messages (#4810)
Summary:

Sometimes in YSQL, one can come across

```
ERROR:  Query error:
```

It is difficult to tell what this means and where it came from.  A stack
trace doesn't help much because it's caught high up at the pggate layer.

An accompanying message would make these error messages more
understandable.

Schema version mismatch errors are one example of this.  Only the YSQL
read path has been fixed to send back an error message through the RPC
response (commit d62b41442dd8e0c086de3d9b322986fd81eba19e).  Fix other
such cases, checked below:

- [x] YCQL read (`Tablet::HandleQLReadRequest`)
- [ ] YSQL read (`Tablet::HandlePgsqlReadRequest`)
- [x] YCQL write (`Tablet::KeyValueBatchFromQLWriteBatch`)
- [x] YSQL write (`Tablet::PreparePgsqlWriteOperations`)

Close: #4810

Test Plan:

1. Cause a schema version mismatch
1. Check that the error message looks like

   ```
   ERROR:  Query error: schema version mismatch for table 000030a9000030008000000000004000: expected 2, got 1
   ```

Reviewers: dmitry, alex

Reviewed By: alex

Differential Revision: https://phabricator.dev.yugabyte.com/D8694