[BACKPORT 2024.2][#28141] DocDB: Fix clone failure for an altered database
Summary:
Original commit: 1e4ddf8237dc29323b76f396be379a1d1fdaf960 / D50259
Not a clean backport. Added the fix inside the function ModifyLine
Currently, when the parent (original) database was altered using an ALTER DATABASE operation such as:
`ALTER DATABASE db1 SET "TimeZone" TO 'US/Central';`
Cloning such a database fails with the following error:
```
ERROR:  Clone operation aborted: ... ysqlsh:clone_pg_schema_uD0wh8:82: error: \connect: connection to server on socket "/tmp/.yb.127.0.0.1:5433/.s.PGSQL.5433" failed: FATAL:  database "db2" is not currently accepting connections
```
The reason for the failure is that when executing the ysql_dump to create the schema, we explicitly disallow connecting to the database after executing the CREATE DATABASE command. However, when the script has an ALTER DATABASE command, it will try to connect again to the clone database, which will return the previous error.

This is a protection mechanism that prevents the user from connecting to the clone database while the clone operation is still in progress. We allow connecting to the clone database at the end of the clone once the operation finishes successfully, and the user is guaranteed a complete clone.

Fixed the issue by adding a prefix and suffix for every `\connect -reuse-previous=on "dbname='db3'"` command, the prefix allows connecting to the db and then the suffix disallows connecting to the database. This allows multiple \connect statements to be successfully executed without sacrificing the protection mechanism.

Test Plan: ./yb_build.sh --cxx-test integration-tests_minicluster-snapshot-test --gtest_filter PgCloneTest.CloneWithAlterDatabaseSet

Reviewers: asrivastava, zdrudi, hsunder

Reviewed By: zdrudi

Subscribers: hsunder, ybase, svc_phabricator

Differential Revision: https://phorge.dev.yugabyte.com/D50381