[#16408] YSQL: Split TestPgRegressIndex.testPgRegressIndex
Summary:
The unit test org.yb.pgsql.TestPgRegressIndex.testPgRegressIndex oftens times
out with an error like:
```
org.junit.runners.model.TestTimedOutException: test timed out after 1800 seconds
```

I splitted the schedule `yb_index_serial_schedule` into two so that each has a
better chance not to time out. They each take about the same run time.
Jira: DB-5819

Test Plan:
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressIndex#testPgRegressIndex'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressIndex#testPgRegressIndex2'

On my dev vm debug build, testPgRegressIndex runs about 18:30 minutes,
testPgRegressIndex2 runs about 19 minutes.

Reviewers: fizaa

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D36224