[DB-12762] YSQL: import Restrict accesses to non-system views and foreign tables during pg_dump.
Summary:
This revision imports the PG upstream (REL_15_STABLE) commit: [[ https://github.com/postgres/postgres/commit/e81e53a0c1faf2b8f5fe8822d7218c91aeebea52 | e81e53a0c1faf2b8f5fe8822d7218c91aeebea52 ]], which fixes Postgres CVE-2024-7348.

Cherry-Pick Summary:
 - createplan.c:
 -- PG upstream commit e81e53a0c1faf2b8f5fe8822d7218c91aeebea52 introduce a new include `#include "tcop/tcopprot.h"` and YB commit 7e222b42902b5d73067e96ce58a26e679f11a618 introduced `#include "utils/selfuncs.h"`
 --- Resolved by including both and maintaining the order of includes.
 - guc.c:
 -- PG upstream commit e81e53a0c1faf2b8f5fe8822d7218c91aeebea52 introduced new GUC (`restrict_nonsystem_relation_kind`) which conflicted with YB introduced GUCs.
 --- Resolved by introducing the new GUC before the YB ones.
 - pg_dump.c
 -- Upstream commit introduced the forward declaration of the function set_restrict_relation_kind which caused a conflict with catalogTableExists introduced in YB commit 5198c37b411939691a0e3a5b03a8b5321867cbf9
  --- Resolved by declaring both the functions
 -- setup_connection: Upstream commit conflicted with YB commit 9a962aff2deccd2c765b47584e9cfce49fb4c96e
  --- Resolved by combining both

Original Commit Message:
```
Restrict accesses to non-system views and foreign tables during pg_dump.

When pg_dump retrieves the list of database objects and performs the
data dump, there was possibility that objects are replaced with others
of the same name, such as views, and access them. This vulnerability
could result in code execution with superuser privileges during the
pg_dump process.

This issue can arise when dumping data of sequences, foreign
tables (only 13 or later), or tables registered with a WHERE clause in
the extension configuration table.

To address this, pg_dump now utilizes the newly introduced
restrict_nonsystem_relation_kind GUC parameter to restrict the
accesses to non-system views and foreign tables during the dump
process. This new GUC parameter is added to back branches too, but
these changes do not require cluster recreation.

Back-patch to all supported branches.

Reviewed-by: Noah Misch
Security: CVE-2024-7348
Backpatch-through: 12
```
Jira: DB-12762

Test Plan:
`TestPgRegressContribPostgresFdw` was recently disabled by a5f4816ad247ac53965cb041f3163608da2174ae, so not porting the test changes to YB (`yb_pg_postgres_fdw.sql`) for now. Manually tested the revision by reproducing steps in upstream PG's test.

```
yugabyte=# create table tt27v_tbl (a int);
CREATE TABLE
yugabyte=# create view tt27v as select a from tt27v_tbl;
CREATE VIEW
yugabyte=# set restrict_nonsystem_relation_kind to 'view';
SET
yugabyte=# select a from tt27v where a > 0; -- Error
ERROR:  access to non-system view "tt27v" is restricted
yugabyte=# insert into tt27v values (1); -- Error
ERROR:  access to non-system view "tt27v" is restricted
yugabyte=# select viewname from pg_views where viewname = 'tt27v'; -- Ok to access a system view.
 viewname
----------
 tt27v
(1 row)

yugabyte=# reset restrict_nonsystem_relation_kind;
RESET
yugabyte=# select a from tt27v where a > 0; -- access is resetted
 a
---
(0 rows)
```

```
yugabyte=# CREATE FOREIGN TABLE ft1 (
c0 int,
c1 int NOT NULL,
c2 int NOT NULL,
c3 text,
c4 timestamptz,
c5 timestamp,
c6 varchar(10),
c7 char(10) default 'ft1'
) SERVER loopback;
WARNING:  'foreign data wrapper' is a beta feature!
LINE 1: CREATE FOREIGN TABLE ft1 (
        ^
HINT:  Set 'ysql_beta_features' yb-tserver gflag to true to suppress the warning for all beta features.
CREATE FOREIGN TABLE

yugabyte=# SET restrict_nonsystem_relation_kind TO 'foreign-table';
SET
yugabyte=# SELECT * from ft1 where c1 < 1; -- ERROR
ERROR:  access to non-system foreign table is restricted
yugabyte=# INSERT INTO ft1 (c1) VALUES (1); -- ERROR
ERROR:  access to non-system foreign table is restricted
yugabyte=# DELETE FROM ft1 WHERE c1 = 1; -- ERROR
ERROR:  access to non-system foreign table is restricted
yugabyte=# TRUNCATE ft1; -- ERROR
ERROR:  access to non-system foreign table is restricted
yugabyte=# RESET restrict_nonsystem_relation_kind;
RESET
```

Reviewers: skumar, devansh.saxena, jason

Reviewed By: jason

Subscribers: kramanathan, jason, yql

Differential Revision: https://phorge.dev.yugabyte.com/D40635