Fix build due to undeclared identifier SIGTERM
Summary:
https://phabricator.dev.yugabyte.com/D6467 resulted in a build failure:
```
In file included from src/yb/util/net/net_util.cc:71:
src/yb/util/subprocess.h:185:24: error: use of undeclared identifier 'SIGTERM'
   int pdeath_signal_ = SIGTERM;
                        ^
1 error generated.
```

This fixes that issue.

Test Plan: Jenkins

Reviewers: bogdan

Reviewed By: bogdan

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D6485