[#29534] YSQL: flaky test: TestDdlTransactionBlocks.yb_ddl_txn_block_tests
Summary:
The test `org.yb.pgsql.TestDdlTransactionBlocks.yb_ddl_txn_block_tests` is flaky because of an
error:

```
-- #29058: REINDEX of partitioned table works.
CREATE TABLE test_partitioned (i int, j int) PARTITION BY LIST (j);
CREATE INDEX NONCONCURRENTLY ON test_partitioned (i);
CREATE TABLE test_partitioned_odd PARTITION OF test_partitioned FOR VALUES IN (1, 3, 5, 7, 9);
CREATE TABLE test_partitioned_even PARTITION OF test_partitioned FOR VALUES IN (2, 4, 6, 8);
INSERT INTO test_partitioned SELECT (2 * g), g FROM generate_series(1, 9) g;
-- Mark all partitions are invalid before REINDEX.
UPDATE pg_index SET indisvalid = false
    WHERE indexrelid = 'test_partitioned_i_idx'::regclass;
UPDATE pg_index SET indisvalid = false
    WHERE indexrelid = 'test_partitioned_odd_i_idx'::regclass;
UPDATE pg_index SET indisvalid = false
    WHERE indexrelid = 'test_partitioned_even_i_idx'::regclass;
\c
REINDEX INDEX test_partitioned_i_idx;
ERROR:  Restarting a DDL transaction not supported
```

The reason for this error is due to read restart. After commit
8e147cca15973fe6d20072618930fad4674c5569 that does incremental refresh of relcache init file, the
"\c" operation is much faster than before. The read time selected for the REINDEX statement is based
upon safetime mechanism which is slightly older than current time. If it is older than the write
time of the previous UPDATE pg_index statement, we will see read restart error, which is intercepted
by PG and reported as "Restarting a DDL transaction not supported" error.

This can happen in real situation, but so far haven't heard any other case reported. To make the
test more reliable, I added a 2-second sleep before REINDEX statement to allow the safetime to
advance past the write time of the previous UPDATE pg_index statement to avoid read restart.

Also made another test log update to reflect the new HINT message.

Test Plan: ./yb_build.sh release --java-test org.yb.pgsql.TestDdlTransactionBlocks -n 10 --tp 1

Reviewers: kfranz, sanketh, patnaik.balivada

Reviewed By: sanketh

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D49808