[#5310] YSQL: Support row-level partition UPDATE across partitions
Summary:
Updating a row such that it should move to a different leaf partition
(physical partition) causes an error in Yugabyte:

```
CREATE TABLE ab (a int NOT NULL, b int NOT NULL) PARTITION BY LIST (a);
CREATE TABLE ab_a1 PARTITION OF ab FOR VALUES IN (1) PARTITION BY LIST (b);
CREATE TABLE ab_a1_b2 PARTITION OF ab_a1 FOR VALUES IN (2);
CREATE TABLE ab_a1_b3 PARTITION OF ab_a1 FOR VALUES IN (3);
INSERT INTO ab VALUES (1, 2);
UPDATE ab_a1 SET b = 3;

ERROR:  new row for relation "ab_a1_b2" violates partition constraint
DETAIL:  Failing row contains (1, 3).

```
Although PG 11.2 has support for row movement on UPDATE, this was
disabled for YB because of #9436. Since #9436 has been root caused and
fixed in D12382, enabling the PostgresQL code that performs row
movement

Test Plan:
ybd --scb --sj --java-test org.yb.pgsql.TestPgRegressPartitions
ybd --scb --sj --java-test org.yb.pgsql.TestPgForeignKey

Reviewers: dmitry, alex

Reviewed By: alex

Subscribers: zyu, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D12423