[#20084] YSQL: Improve logs for version mismatch errors
Summary:
- Add the ddl command tag to the `ddl_transaction_state` struct.
- Log catalog version increments (in `YbIncrementMasterDBCatalogVersionTableEntryImpl()` and `YbCallSQLIncrementCatalogVersions()`) : the current logs are scoped under the gflag `log_ysql_catalog_versions`, which is off by default. Move the logs outside of the scope of this gflag and include the current local catalog version and the command tag in the logged message.
- Add a test flag `TEST_ysql_hide_catalog_version_increment_log` to hide the log messages for the catalog version increment in java tests.
- In catalog manager, log the PG table OID for alter table operations on YSQL tables.
- Include the expected version and the actual version in catalog version mismatch errors.

Sample logs for catalog version increment:

Non-global DDL:
```
2024-04-29 10:10:48.382 EDT [3559] LOG:  YbIncrementMasterDBCatalogVersionTableEntryImpl: incrementing master catalog version (nonbreaking) for database 13251
2024-04-29 10:10:48.382 EDT [3559] DETAIL:  Local version: 1, node tag: ALTER TABLE.
```

Global DDL:
```
2024-04-29 10:11:17.690 EDT [3559] LOG:  YbCallSQLIncrementCatalogVersions: incrementing all master db catalog versions (breaking)
2024-04-29 10:11:17.690 EDT [3559] DETAIL:  Node tag: ALTER ROLE.
```

Sample catalog version mismatch error:

```
ERROR:  The catalog snapshot used for this transaction has been invalidated: expected: 4, got: 3: MISMATCHED_SCHEMA
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```
Jira: DB-9034

Test Plan: Jenkins

Reviewers: myang, tverona, jason

Reviewed By: myang, jason

Subscribers: jason, yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D34250