[#19921] YSQL: Ignore txn priority bound GUCs in read committed isolation
Summary:
`yb_transaction_priority_lower_bound` and `yb_transaction_priority_upper_bound`
don't make sense for read committed isolation since it provides
wait-on-conflict semantics even if enable_wait_queues is set to false by
always using the kHighestPriority for all RC transactions (see
7aad5389b1d956785c3736acb48236ea0de5fd22 for reasoning,
specifically point (2) in its commit summary).

This diff ensures that these GUCs are ignored in RC isolation. Without this diff, the
following bug can be seen:

```
Start a cluster with just the tserver gflag yb_enable_read_committed_isolation=true

create table demo (id bigint primary key, value int);
insert into demo values (123, 103);

session 1: set yb_transaction_priority_lower_bound to 0.1;
session 1: set yb_transaction_priority_upper_bound to 0.4;
session 2: set yb_transaction_priority_lower_bound to 0.6;
session 2: set yb_transaction_priority_upper_bound to 0.9;
session 1: begin transaction isolation level read committed;
session 2: begin transaction isolation level read committed;
session 1: update demo set value=1 where id=123;
<succeeds...>
session 2: update demo set value=2 where id=123;
<this succeeds as well instead of waiting!>
session 1: commit;
ERROR:  Transaction ********-****-4***-****-************ expired or aborted by a conflict: 40001
```
Jira: DB-8864

Test Plan:
./yb_build.sh release --java-test org.yb.pgsql.TestPgWithoutWaitQueuesIsolationRegress
Added yb_read_committed_insert_duplicate_key_error to yb_pg_isolation_schedule

Reviewers: tvesely, bkolagani, rsami

Reviewed By: tvesely, bkolagani

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D30114