[#31594] DocDB: Fix bad backport which broke fastdebug builds
Summary:
Backport revision https://phorge.dev.yugabyte.com/D53950 broke the fastdebug build because of the
following
```
08:39:05  /-------------------------------------------------------------------------------
08:39:05  | COMPILATION FAILED
08:39:05  |-------------------------------------------------------------------------------
08:39:05  ../../src/yb/yql/pggate/pg_session.cc: In member function 'yb::Status yb::pggate::PgSession::ReleaseSessionObjectLock(const YbcObjectLockId&, bool)':
08:39:05  ../../src/yb/yql/pggate/pg_session.cc:1544:24: error: variable 'debug_context' set but not used [-Werror=unused-but-set-variable]
08:39:05   1544 |   YbcFlushDebugContext debug_context {};
08:39:05        |                        ^~~~~~~~~~~~~
08:39:05  cc1plus: all warnings being treated as errors
08:39:05
```

This revision fixes the issue by removing `YbcFlushDebugContext debug_context` as it is no longer
being used in `PgSession::ReleaseSessionObjectLock`

Test Plan: Jenkins: rebase: 2025.2

Reviewers: pjain, myang

Reviewed By: pjain

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D54522