#5209 [YSQL] Ubuntu compilation fix
Summary:
`Format` function can't use `nullptr` due to the following error on Ubuntu

```
In file included from src/yb/util/status.h:49:0,
                 from src/yb/util/errno.h:37,
                 from src/yb/util/locks.h:46,
                 from src/yb/yql/pggate/pg_doc_op.h:22,
                 from src/yb/yql/pggate/pg_doc_op.cc:15:
src/yb/util/format.h: In function \u2018std::__cxx11::string yb::internal::FormatImpl(const char*, const Args& ...) [with Args = {char [32], char*, std::nullptr_t}]\u2019:
src/yb/util/format.h:84:68: error: argument 1 null where non-null expected [-Werror=nonnull]
   explicit FormatValue(const U& value) : value_(value), len_(strlen(value_)) {}
```

`SCHECK_*` macros uses `Format` internally as a result `nullptr` is restricted as well.

Test Plan: Jenkins

Reviewers: jason, alex, oleg

Reviewed By: alex, oleg

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D9010