ENG-2342: Return proper error in CQLInboundCall::RespondFailure().
Summary:
When CQL service queue was full, a serialized protobuf error response was returned to CQL client erroneously. The client received an incorrect length field and attempted to read more bytes than available causing read timeout.

We now return proper CQL OVERLOADED error response when CQL service queue is full. With the default retry policy, CQL client will retry the request at the next available host.

Test Plan:
Start a local cluster with --cql_service_queue_length 10
$ local_cluster_ctl.sh start --num-masters 1 --num-tservers 1 --replication_factor 1
$ java -jar ~/code/yugabyte/java/yb-loadtester/target/yb-sample-apps.jar -workload CassandraTimeseries -num_threads_read 16 -num_threads_write 2 -nodes 127.0.0.1:9042
...
com.datastax.driver.core.exceptions.OverloadedException: Queried host (/127.0.0.1:9042) was overloaded: CQL service queue full
	at com.datastax.driver.core.exceptions.OverloadedException.copy(OverloadedException.java:61)
	at com.datastax.driver.core.exceptions.OverloadedException.copy(OverloadedException.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:264)
        ...

Reviewers: bharat

Reviewed By: bharat

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D3386