ENG-4692 (#868): Enable access share mode for table lock
Summary:
We need to be able to lock table in access share mode to enable pg_dump to work. This diff allows locking of table in access share mode.
Note that we are not enforcing the lock, so it's likely that we'll hit an issue if "DROP TABLE" is run simultaneously while a table is locked in this mode.
We'll document that we don't enforce the lock mode even though it's allowed in grammar.

Test Plan:
```
postgres=# begin;
BEGIN
postgres=# lock table foo in access share mode;
LOCK TABLE

postgres=# insert into foo values(100,100);
INSERT 0 1

postgres=# commit;
COMMIT

postgres=# lock table foo in access share mode;
ERROR:  LOCK TABLE can only be used in transaction blocks

postgres=# begin;
BEGIN
postgres=# lock table foo in access exclusive mode;
ERROR:  ACCESS EXCLUSIVE not supported yet
LINE 1: lock table foo in access exclusive mode;
                          ^
HINT:  Please contact YugaByte for its release schedule.
postgres=# lock table foo in exclusive mode;
ERROR:  EXCLUSIVE not supported yet
LINE 1: lock table foo in exclusive mode;
                          ^
HINT:  Please contact YugaByte for its release schedule.
                                    ^
postgres=# lock table foo in share mode;
ERROR:  SHARE not supported yet
LINE 1: lock table foo in share mode;
                          ^
HINT:  Please contact YugaByte for its release schedule.
postgres=# lock table foo in row share mode;
ERROR:  ROW SHARE not supported yet
LINE 1: lock table foo in row share mode;
                          ^
HINT:  Please contact YugaByte for its release schedule.

postgres=# lock table foo;
ERROR:  ACCESS EXCLUSIVE lock mode not supported yet
LINE 1: lock table foo;
                   ^
HINT:  Please contact YugaByte for its release schedule.
```

pg_dump works now
```
./build/latest/postgres/bin/pg_dump -h localhost -p 5433 -U postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 10.4
-- Dumped by pg_dump version 10.4

```

Reviewers: mikhail, mihnea, robert, neil

Reviewed By: neil

Subscribers: kannan

Differential Revision: https://phabricator.dev.yugabyte.com/D6225