[PLAT-9179] Fix the restore as part of yb_platform_backup script
Summary:
We had a issue with the restore flow as part of `yb_platform_backup` script.
We were having `$(cat ${r_pth} | ${PYTHON_EXECUTABLE} -c ${version_command})` as part of computing the version of the platform from which the backup was computed.
The command substitution $(...) was causing the single quotes around the Python code to be treated as literal characters within the string, and they are not being evaluated as part of the Python code. This was causing the syntax error

```
File "<string>", line 1
'import
^
SyntaxError: EOL while scanning string literal
+ bp1=
```

This diff changes that to `eval cat ${r_pth} | ${PYTHON_EXECUTABLE} -c ${version_command}`
The eval command evaluates the entire string as if it were a command line, and within the eval context, the single quotes around the Python code are being treated as part of the command and are being evaluated correctly by the Python interpreter.

Test Plan:
Computed the backup using the script on the k8s platform.
Tried restoring the backup using the modified script.
Ensured that the restore was successful.

Reviewers: muthu, amalyshev, anijhawan

Reviewed By: muthu

Subscribers: anijhawan, yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D28124