[BACKPORT 2025.2][#28532] YSQL: Improve YB error message on concurrent table drop
Summary:
From the ticket https://github.com/yugabyte/yugabyte-db/issues/28532

```
create table sample (i int);

Session 1                                   session 2

BEGIN ISOLATION LEVEL REPEATABLE READ;

DROP TABLE sample;
                                            BEGIN ISOLATION LEVEL REPEATABLE READ;
                                            DROP TABLE sample;
commit;
                                            Failed with : ERROR:  cache lookup failed for relation 16401
```

In native PG, when we run the same test, session 2 shows a different but more **helpful** error
message:

```
ERROR:  table "sample" does not exist
```

Another example from https://github.com/yugabyte/yugabyte-db/issues/28563

```
create table dd (i int);
create materialized view mat as select * from dd;

Session 1                                   session 2
Begin isolation level repeatable read;

drop table dd cascade;

                                            BEGIN ISOLATION LEVEL REPEATABLE READ;

                                            refresh materialized view mat;

commit;
                                            ERROR:  could not open relation with OID 16418
```
In native PG, when we run the same test, session 2 shows a different but more **helpful** error
message:

```
ERROR:  relation "mat" does not exist
```

After debugging, I found a few places in PG code where it tries to resolve a relation in the context
of invalidation messages processing. The PG code loops until no more invalidation messages are
processed. In native PG, it claims no more invalidation messages are processed if
`SharedInvalidMessageCounter` remains the same across iterations. This logic needs to be adjusted
because in YB in addition to use the shared invalidation message buffer (which uses
`SharedInvalidMessageCounter`), YB also fetches invalidation messages from local tserver and then
directly apply the messages without putting the messages into the shared invalidation message
buffer.

I made a fix to also take the YB invalidation messages processing into consideration. In
addition to `SharedInvalidMessageCounter`, YB also uses `YbGetCatCacheDeltaRefreshes()` which is the
equivalent of `SharedInvalidMessageCounter`.

New unit tests are added, which would fail prior to the fix because different and less helpful error messages
were generated.

Original commit: f1d8dae48b98e6afd2a38ac8b35577d7a25bd4b7 / D49589

Test Plan:
./yb_build.sh release --cxx-test pg_ddl_concurrency-test --gtest_filter PgDDLConcurrencyWithObjectLockingTest.TableDrop
./yb_build.sh release --cxx-test pg_ddl_concurrency-test --gtest_filter PgDDLConcurrencyWithObjectLockingTest.TableDropCascade

Reviewers: sanketh, pjain

Reviewed By: pjain

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D49652