[BACKPORT 2025.1.0][#27072] YSQL: Exempt walsender created by connection manager from YSQL backend check
Summary:
As part of this Diff: https://phorge.dev.yugabyte.com/D42827 the walsender process is exempted from the YSQL backend check so that the index creation can proceed without waiting for the walsender to catch up to the latest catalog version.

With connection manager, the backend type of 'walsender' process used to get overridden with 'yb-conn-mgr worker' due to which even being a walsender process there was a wait upon walsender to catch up to the latest catalog version. Therefore it keeps on waiting with connection manager and throws an error:

```
ERROR: timed out waiting for postgres backends to catch up
  Detail: 1 backends on database 13515 are still behind catalog version 5.
  Hint: Run the following query on all tservers to find the lagging backends: SELECT * FROM pg_stat_activity WHERE backend_type != 'walsender' AND catalog_version < 5 AND datid = 13515;
```
This diff creates a new backend type `yb-conn-mgr walsender` to handle such scenario. i.e walsender created by the ysql connection manager. This fix is to exempt regular `walsender` along with `yb-conn-mgr walsender` process from YSQL backend check so that index creation can proceed without for walsender created by conn mgr as well.

The connection becomes sticky on creating a logical replication connection with connection manager.
Jira: DB-16561

Original commit: 9e36cc8d4fd7cf0634ed1faaa4afb62d566d9f1e / D44736

Test Plan: Make sure `org.yb.pgsql.TestPgReplicationSlot#testReplicationConnectionConsumptionWithCreateIndex` test passes with connection manager

Reviewers: vkushwaha, skumar, rbarigidad, stiwary

Reviewed By: rbarigidad

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D44899