[#11347] YSQL: Fix bug in ALTER TABLE ADD PRIMARY KEY
Summary:
Example test case that failed:

```
yugabyte=# CREATE TABLE t1(c0 money);
CREATE TABLE t1(c0 money);
CREATE TABLE
yugabyte=# INSERT INTO t1(c0) VALUES((0.7515708)::MONEY);
INSERT INTO t1(c0) VALUES((0.7515708)::MONEY);
INSERT 0 1
yugabyte=# ALTER TABLE  ONLY t1 NO FORCE ROW LEVEL SECURITY, ADD CONSTRAINT G PRIMARY KEY(c0);
ALTER TABLE  ONLY t1 NO FORCE ROW LEVEL SECURITY, ADD CONSTRAINT G PRIMARY KEY(c0);
ERROR:  could not open relation with OID 16384
```

In YSQL, ADD PRIMARY KEY is done by creating a new table with primary key and dropping the old
table. Although this code is YB specific but it is still done under the overall Postgres processing
flow of ALTER TABLE command, which is composed of several passes. Once the old table is dropped,
further passes should start to operate on the new table. However, 16384 is the OID of the old table
and is not updated to the new table's OID for next passes. As a result, after the old table is
dropped, the relcache lookup using 16384 will fail.

I made a change to update the table's OID to the new table's OID to avoid the relcache lookup error.

Test Plan: ./yb_build.sh debug --java-test 'org.yb.pgsql.TestPgAlterTableAddPrimaryKey'

Reviewers: alex

Reviewed By: alex

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D15364