[BACKPORT 2024.2][PLAT-16412] NPE fix for Auto node agent enabler shuts down executor service
Summary:
Original diff: https://phorge.dev.yugabyte.com/D41043 (4644c4a463fe898ec33877435078dba3357ab2df)

Installer instance can be null if there is no need.

2025-01-06T20:35:13.855Z  [error] a9fedcd7-2312-43c7-83f8-7c76e6170fff NodeAgentEnabler.java:458 [application-pekko.actor.default-dispatcher-958] com.yugabyte.yw.commissioner.NodeAgentEnabler Error encountered in scanning universes to enable node agents
java.lang.NullPointerException: Cannot invoke "com.yugabyte.yw.commissioner.NodeAgentEnabler$UniverseNodeAgentInstaller.getUniverseUuid()" because "installer" is null
	at com.yugabyte.yw.commissioner.NodeAgentEnabler.scanUniverses(NodeAgentEnabler.java:453)
	at com.yugabyte.yw.common.PlatformScheduler.lambda$schedule$0(PlatformScheduler.java:56)

Test Plan: Trivial, manually tested.

Reviewers: cwang

Reviewed By: cwang

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D41044