Merged PR 1494403: Updated users.c and remove unnecessary dependency
### Does this PR have any customer impact?
No

### Type (Feature, Refactoring, Bugfix, DevOps, Testing, Perf, etc)
bugfix

### Does it involve schema level changes? (Table, Column, Index, UDF, etc level changes)
No

### Are you introducing any new config? If yes, do you have tests with and without them being set?
No

### Release Note (Refer [Template](../docs/release_notes/pgmongo_template.md))

### Description
remove duplicated dependency which caused build error on github, example error log:
In file included from src/commands/users.c:22:
/usr/include/postgresql/pg_config.h:35: error: "CONFIGURE_ARGS" redefined [-Werror]

----
#### AI description  (iteration 1)
#### PR Classification
Code cleanup

#### PR Summary
Removed an unnecessary dependency to streamline the code.
- `users.c`: Removed the inclusion of `pg_config.h` as it was not needed.