Backport to 2.2: [YSQL][#6069] Enable copy from stdin to work with rows_per_transaction option.
Summary:
**Background**
In Postgres, there is a flag called `ybDataSent` in the `TransactionState` structure.
When output buffer is flushed, the flag gets set to true, marking that we cannot do a transparent restart anymore.

In `CopyFrom()` method, prior to processing, `ybDataSent` flag is used to verify if the current query is inside another transaction block (ie. nested transaction).
If so, an error will be thrown to disable `rows_per_transaction` option from being used.
This is to prevent previous transactions from getting committed while running batch commits.

**Problem**
Today, when COPY FROM query is sourced from STDIN, it runs `ReceiveCopyBegin()` function to flush the output buffer and ensure front-end knows it can send.
While flushing, `ybDataSent` flag also gets set to true even though it is not inside a nested transaction.

Eg.

```
create table t (a int);
copy t from stdin with (rows_per_transaction 10);
>> ERROR: ROWS_PER_TRANSACTION option is not supported in nested transaction

```
**Solution**
The flag should be explicitly turned off when it is not inside a nested transaction.
Before executing `ReceiveCopyBegin()` function, we should store the current state of `ybDataSent` to determine if it's inside a nested transaction.
After executing the flush,
  - keep the flag turned on to true if inside a transaction block
  - switch off flag to false if outside a transaction block.

Test Plan: Jenkins: rebase: 2.2

Reviewers: jason, mihnea

Reviewed By: mihnea

Subscribers: yql, zyu

Differential Revision: https://phabricator.dev.yugabyte.com/D9699