[#16374] DocDB: Improve error message when SAVEPOINT feature is attempted when disabled by --enable_pg_savepoint
Summary:
When this flag is set to false, use of SAVEPOINT related features in SQL
produces an error like:
```
2023-03-15 23:47:51.117 UTC [722541] ERROR:  SAVEPOINT <transaction> not supported yet at character 1
2023-03-15 23:47:51.117 UTC [722541] HINT:  See https://github.com/yugabyte/yugabyte-db/issues/1125. React with thumbs up to raise its priority
```

This is misleading because it implies the entire feature is not yet
supported whereas it's just unsupported because of gflag setting.

Also, the issue pointed to above (1125) --
https://github.com/yugabyte/yugabyte-db/issues/1125 -- seems to be out
of date because it claims that many implemented features are still
unimplemented.

This diff changes the error message to:
```
2023-03-15 23:32:20.676 UTC [680415] ERROR:  SAVEPOINT <transaction> not supported due to setting of flag --enable_pg_savepoints at character 1
```

3/29/2023 UPDATE:
error message is now:
```
ERROR:  SAVEPOINT <transaction> not supported due to setting of flag --enable_pg_savepoints
LINE 1: SAVEPOINT A
        ^
HINT:  flag may have set to false because savepoints do not currently work with xCluster replication (see https://github.com/yugabyte/yugabyte-db/issues/14308)
```

Fixes #16374

Test Plan:
```
yb_build.sh --sj  --cxx-test pgwrapper_pg_mini-test --gtest_filter
'*TestSavePointCanBeDisabled*'
```
Look at error message in test log.

3/29/2023 UPDATE:
replace that test with one that checks the error message:
```
yb_build.sh --java-test org.yb.pgsql.TestPgSavepoints
```

Reviewers: slingam, jhe, rsami, hsunder

Reviewed By: hsunder

Subscribers: ybase, rsami

Differential Revision: https://phabricator.dev.yugabyte.com/D23625