[#1127] YSQL: Collation Support (part 1)
Summary:
Currently YSQL has very limited support for collation. Collation is about text data sorting
rules and postgres provides collation support via the underlining OS library including
libc and libicu. Simply put, given two text values (aka strings) s1 and s2, collation sort
comparison must be done via strcoll(s1, s2) rather than strcmp(s1, s2).

Postgres supports two types of collations: deterministic collations and non-deterministic
collations. Postgres 11.2 only supports deterministic collations. Postgres 12 and beyond
support both deterministic collations and non-deterministic collations. Non-deterministic
collation comparison of s1 and s2 directly translates to strcoll(s1, s2), and deterministic
collation comparison uses strcmp(s1, s2) as a "tie-breaker" when strcoll(s1, s2) == 0.

This is the first change to support deterministic collation in YSQL to bring YSQL collation
support in sync with PG 11.2. With this change, the normal build will not have any behavior
change and YSQL will continue to report collation related errors. We'll produce a special
build when ICU is enabled:

YB_POSTGRES_WITH_ICU=1 ./yb_build.sh

The plan is that once we fully support deterministic collations in YSQL, we'll remove the
special build flag YB_POSTGRES_WITH_ICU=1 and make that the default. Before that,
we do need to have the env flag in order to trigger building postgres with ICU enabled
(postgres configure option --with-icu). Otherwise the macro USE_ICU will not be defined
and the the ICU relevant code will not be included. To simplify the build command, one
can also do a one time "export YB_POSTGRES_WITH_ICU=1" and then use the default
./yb_build.sh build command instead of adding the "YB_POSTGRES_WITH_ICU=1"
prefix every time.

Test Plan:
(1) regular build: ./yb_build.sh, verified that
(1.1) pg_collation has only 4 rows as before:
```
yugabyte=# select * from pg_collation;
 collname  | collnamespace | collowner | collprovider | collencoding | collcollate | collctype | collversion
-----------+---------------+-----------+--------------+--------------+-------------+-----------+-------------
 default   |            11 |        10 | d            |           -1 |             |           |
 C         |            11 |        10 | c            |           -1 | C           | C         |
 POSIX     |            11 |        10 | c            |           -1 | POSIX       | POSIX     |
 ucs_basic |            11 |        10 | c            |            6 | C           | C         |
(4 rows)
```
(1.2) We continue to report collation related errors:

```
yugabyte=# create collation nd (provider = 'libc', locale='');
ERROR:  CREATE COLLATION not supported yet
LINE 1: create collation nd (provider = 'libc', locale='');
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
yugabyte=# create table foo(id text collate "C");
ERROR:  COLLATE not supported yet
LINE 1: create table foo(id text collate "C");
                                 ^
HINT:  See https://github.com/YugaByte/yugabyte-db/issues/1127. Click '+' on the description to raise its priority
```

(2) ICU build: YB_POSTGRES_WITH_ICU=1 ./yb_build.sh, verified that
(2.1) pg_collation has many rows because it has imported many ICU collations from OS provided libicu library.
```
yugabyte=# select * from pg_collation limit 10;
  collname   | collnamespace | collowner | collprovider | collencoding | collcollate | collctype  | collversion
-------------+---------------+-----------+--------------+--------------+-------------+------------+-------------
 default     |            11 |        10 | d            |           -1 |             |            |
 C           |            11 |        10 | c            |           -1 | C           | C          |
 POSIX       |            11 |        10 | c            |           -1 | POSIX       | POSIX      |
 ucs_basic   |            11 |        10 | c            |            6 | C           | C          |
 en_US.utf8  |            11 |        10 | c            |            6 | en_US.utf8  | en_US.utf8 |
 en_US       |            11 |        10 | c            |            6 | en_US.utf8  | en_US.utf8 |
 und-x-icu   |            11 |        10 | i            |           -1 | und         | und        | 153.14
 af-x-icu    |            11 |        10 | i            |           -1 | af          | af         | 153.14.37
 af-NA-x-icu |            11 |        10 | i            |           -1 | af-NA       | af-NA      | 153.14.37
 af-ZA-x-icu |            11 |        10 | i            |           -1 | af-ZA       | af-ZA      | 153.14.37
(10 rows)

yugabyte=# select count(*) from pg_collation;
 count
-------
   789
(1 row)

```
(2.2) We can now create collation and also support column collation.
```
yugabyte=# create collation nd (provider = 'libc', locale='');
CREATE COLLATION
yugabyte=# create table foo(id text collate "C");
CREATE TABLE
```

Reviewers: mbautin, mihnea

Reviewed By: mihnea

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D11968