[BACKPORT 2.16][#15911, #15912] docdb: Fix transaction promotion/conflict resolution abort handling
Summary:
Original commit: 1ae14b8a9bfd537d7d6b7fe8aa4a6834e1f8a590 / D22669
This diff fixes several bugs in how we handle transactions aborted due to transaction conflict that are
about to or are currently undergoing the transaction promotion process.

1. We currently allow a transaction to start the promotion process from region-local
to global even when the transaction is in the kAborted state due to it expiring or being aborted
via conflict resolution. This results in the transaction failing to promote due to the
participants not recognizing the transaction id, and hits the following DFATAL:

```
E0131 13:03:05.436185 21190 transaction.cc:648] 8ab9625d-7104-4385-b243-f6f1edf9553d: Attempting to promote transaction not in running state
```

This diff prevents transactions that are in the kAborted state from attempting promotion by
performing that check before attempting promotion.

2. In the case where a transaction is undergoing promotion and is aborted due to conflict
resolution, YBTransaction may first find out about the abort through a failed
UpdateTransactionStatusLocation RPC to a participant, before learning about it through
heartbeats, resulting in the following misleading message bubbled up to the user:

```
ERROR: Not found: Move transaction status: Update transaction status location for unknown transaction: 5b7f475f-7146-4cec-a4a1-3db60f8979dc: . Errors from tablet servers: [Not found (yb/tablet/transaction_participant.cc:1078): Move transaction status: Update transaction status location for unknown transaction: 5b7f475f-7146-4cec-a4a1-3db60f8979dc]
```

This diff updates the error message to be more informative, and additionally removes
unnecessary retry logic that could cause retries in this case if the initial heartbeat
to the new transaction status tablet had completed (we already retry retryable errors
in the RPC layer).

3. In the case where we are informed about the transaction aborting by the old status
tablet after we send the initial heartbeat to the new status tablet but before we get a
response, we may run into the following DFATAL:

```
E0131 13:03:03.811609  3609 transaction.cc:1627] b7afa436-3d3e-437c-b70c-3452e31256a0: Transaction status promoted but not in promoting state
```

This diff updates the check to not emit the DFATAL if the transaction is instead in the
kAborted state.
Jira: DB-5319, DB-5320

Test Plan:
`ybd --gtest_filter GeoTransactionsPromotionTest.TestNoPromotionFromAbortedState`
`ybd --gtest_filter GeoTransactionsPromotionTest.TestPromotionReturningToAbortedState`

Reviewers: sergei, pjain, dsrinivasan, rsami

Reviewed By: rsami

Subscribers: ybase

Differential Revision: https://phorge.dev.yugabyte.com/D26101