[pg15] fix: CREATE TABLE LIKE INCLUDING DEFAULTS
Summary:
Old YB master commit 0294a9c70c116aec6d705412948d31717a0df586 added
AT_ColumnDefault case to YBCPrepareAlterTable.  At the time, the case
led to a no-op because "YugaByte alter isn't required".  Over time, that
case got more logic, but the core seems the same.

Upstream PG 50289819230d8ddad510879ee4793b04a05cf13b added
AT_CookedColumnDefault.  Certain queries, such as CREATE TABLE LIKE
INCLUDING DEFAULTS, now use AT_CookedColumnDefault instead of
AT_ColumnDefault.  Since that case is not explicitly handled in this
YB-owned code, it reaches the default case and throws

    ERROR:  This ALTER TABLE command is not yet supported.

Update YBCPrepareAlterTable to explicitly handle AT_CookedColumnDefault
the same way as AT_ColumnDefault.

Test Plan:
Test TestPgRegressTable yb_pg_create_table_like should now pass the
first 100 lines of output.

Jenkins: rebase: pg15

Reviewers: aagrawal, tfoucher

Reviewed By: aagrawal

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D33599