[#21706] YSQL: Fix schema version mismatch on back-to-back DDL statements
Summary:
From the bug report:

Encountered the below issue while executing Cross DB DDLs with DDL atomicity g-flag. The frequency of this is high 134 times in a ~18 mins run.

```
2024-03-26 14:00:23,228 [Thread-2] ERROR ExceptionsTracker - Exception occurred during DDL postgres_14 DDL query CREATE TABLE tempTable1_tb_1 AS SELECT * FROM tb_1 limit 1000000:

com.yugabyte.util.PSQLException: ERROR: schema version mismatch for table 0000400e000030008000000000004005: expected 3, got 2
```

Note:

1. We are running this on a RF 1 cluster, so all operations are being performed on the same node
2. I tried adding 250ms gap between each DDL transaction on the same database, this issue only occurred 3 times in a ~20 mins run.
3. Without DDL atomicity flags it’s working fine.

After debugging, I found this can happen when two related DDLs are executed
consecutively:

DROP INDEX idx1_tb_0;
CREATE MATERIALIZED VIEW mv2_tb_0 as SELECT k from tb_0 limit 10000

The first DROP INDEX statement increments the schema version of table tb_0.

```
Status PgDropIndex::Exec() {
  client::YBTableName indexed_table_name;
  Status s = pg_session_->DropIndex(table_id_, &indexed_table_name);
  if (s.ok() || (s.IsNotFound() && if_exist_)) {
    RSTATUS_DCHECK(!indexed_table_name.empty(), Uninitialized, "indexed_table_name uninitialized");
    PgObjectId indexed_table_id(indexed_table_name.table_id());

    pg_session_->InvalidateTableCache(table_id_, InvalidateOnPgClient::kFalse);
    pg_session_->InvalidateTableCache(indexed_table_id, InvalidateOnPgClient::kFalse);
    return Status::OK();
  }
  return s;
}

```

After the index is dropped from master DocDB, both the index and its base table
are invalidated from the PG backend table cache. But in tserver they are still
stored in pg client service's pg table cache. The DROP INDEX statement also
increments the catalog version but it takes a heartbeat delay for the new
catalog version to propagate to all the tservers, including this PG backend's
local tserver. The new catalog version will cause the pg client service to clear
its entire pg table cache (that's why adding 250ms gap between each DDL
transaction on the same database helps to reduce the occurrences of this bug).
But before that happens, the next DDL statement starts executing. There is a
subquery `SELECT k from tb_0 limit 10000` which triggers a read RPC to table
`tb_0`. This SELECT triggers loading table `tb_0` into PG backend's table cache
again. However this entry is fetched from the local tserver's pg table cache,
which is now stale. That's why we see this schema version mismatch error.

I made a change to pass `InvalidateOnPgClient::kTrue` for the call to invalidate
`indexed_table_id` (the base table tb_0 in this case) so that its stale entry is
also removed from local tserver's pg table cache. In this way the next DDL will
go to master to fetch the up-to-date schema for `tb_0` and we will not see the
schema version mismatch error.

The reason that this bug only shows up when DDL atomicity is enabled is that
the work flow is different. Without DDL atomicity, the DROP INDEX statement
returns faster without waiting for the schema version of `tb_0` gets bumped,
which happens at a later time. That's why the next DDL's read RPC to table
`tb_0` can use the current (to-be-stale) schema version and the tserver of
`tb_0` also still has the current schema version so there is no mismatch.
Jira: DB-10586

Test Plan:
Manual test
1. start a RF-1 release build local cluster with DDL atomicity enabled:

./bin/yb-ctl create --rf 1 --tserver_flags="allowed_preview_flags_csv=ysql_yb_ddl_rollback_enabled,ysql_yb_ddl_rollback_enabled=true,report_ysql_ddl_txn_status_to_master=true,ysql_ddl_transaction_wait_for_ddl_verification=true,log_ysql_catalog_versions=true,ysql_pg_conf_csv=log_statement=all" --master_flags="allowed_preview_flags_csv=ysql_yb_ddl_rollback_enabled,ysql_yb_ddl_rollback_enabled=true,report_ysql_ddl_txn_status_to_master=true,ysql_ddl_transaction_wait_for_ddl_verification=true,log_ysql_catalog_versions=true,ysql_pg_conf_csv=log_statement=all"

2. Run the sample app via this command:
/opt/jdk-17/bin/java -jar $HOME/code/yb-stress-test/tools/sample-app/target/yb-stress-sample-apps.jar --workload SqlCrossDBLoadWithDDL --num_of_tables_in_db 1 --uuid be8ef4cb-ec72-4679-a488-5af1eb848d39 --uuid_marker 52aca9cd-a953-4992-8c98-52746a2fc009 --num_writes -1 --num_reads -1 --num_threads_write 2 --num_threads_read 0 --num_unique_keys 3000000000 --num_value_columns 30 --default_postgres_database postgres --use_datatypes true --nodes 127.0.0.1:5433 --username yugabyte --per_db_catalog_mode true --batch_size 5 --num_of_non_colocated_databases 1 --num_of_colocated_databases 0  --num_of_parallel_ddls 1

Verify that without the fix the schema version mismatch error described as above
appears in the test output, after the fix it no longer appears.

Reviewers: fizaa

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D34009