[#14365] YSQL: Handle backups of range-partitioned indexes with null values in partition bounds
Summary:
Backups for range-partitioned indexes with null values in their split points fail because `yb_get_range_split_clause` does not handle null values.
Test `TestYSQLTabletSplitRangeUniqueIndexOnHiddenColumn` failed consistently after D19896 was landed. The test and D19896 together uncovered a issue in `yb_get_range_split_clause`.
Before this diff, the implementation of `yb_get_range_split_clause` assumes there is no null value in split points of range-partitioned relations
because this is enforced by parser for pre-split range relations.
```
CREATE TABLE tbl (k int, PRIMARY KEY (k ASC)) SPLIT AT VALUES ((NULL));
ERROR:  cannot specify NULL in range bound

CREATE TABLE tbl (k int);
CREATE UNIQUE INDEX idx ON tbl(k ASC) SPLIT AT VALUES ((NULL));
ERROR:  cannot specify NULL in range bound
```

However, there can be null values in split points of indexes after tablet splitting.
Example:
```
CREATE TABLE tbl (k INT PRIMARY KEY, v INT)
CREATE UNIQUE INDEX idx ON tbl (v ASC)
INSERT INTO tbl SELECT *, null FROM generate_series(1, 10000)
```
In the example above, split points of index idx have the pattern: (null, <ybctid>).

This diff solves this issue by making `yb_get_range_split_clause` return an empty string when there is any null value in split points of a range relation. This implies when there is any null value in splits points of a range relation, ysql_dump will not supply the SPLIT AT VALUES clause for this relation. Backup && restore will rely on `CatalogManager::RepartitionTable` to re-created this relation with correct partition bounds.

Test Plan:
(1)
./yb_build.sh --cxx-test tools_yb-backup-test_ent --gtest_filter YBBackupTest.TestYSQLTabletSplitRangeUniqueIndexOnHiddenColumn

(2)
Manual test to make sure yb_get_range_split_clause
throws a warning when there is any null value in split points.
Example:
Test on an index that is split into 3 tablets on its hidden column
with the following 3 tablets:
tablet-1 boundaries: [ "", (null, <ybctid-1>) )
tablet-2 boundaries: [ (null, <ybctid-1>), (null, <ybctid-2>) )
tablet-3 boundaries: [ (null, <ybctid-2>), "" )

```
yugabyte=# \pset null '(null)'
Null display is "(null)".
yugabyte=# select yb_get_range_split_clause('idx'::regclass);
WARNING:  NULL value present in split points
DETAIL:  Specifying NULL value in SPLIT AT VALUES clause is not supported.
 yb_get_range_split_clause
---------------------------

(1 row)
```

Reviewers: tverona, skedia, jason

Reviewed By: jason

Subscribers: bogdan, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D20150