[#17993] docdb: Fix build failure due to 0298142a3e178b91a60769b039a65d1bb247e235
Summary:
Fix compile error from 0298142a3e178b91a60769b039a65d1bb247e235 due to problematic merge
(`yb::IsDebug()` changed to `yb::kIsDebug` in master but commit adds new use of `yb::IsDebug()`):

```
  /-------------------------------------------------------------------------------
  | COMPILATION FAILED
  |-------------------------------------------------------------------------------
  In file included from /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20240417035947-ac36057f7c-almalinux8-x86_64-gcc11/installed/uninstrumented/include/glog/logging.h:86,
                   from ../../src/yb/util/logging.h:51,
                   from ../../src/yb/util/status_log.h:16,
                   from ../../src/yb/util/status.h:305,
                   from ../../src/yb/util/result.h:23,
                   from ../../src/yb/util/enums.h:32,
                   from ../../src/yb/util/stack_trace_tracker.h:18,
                   from ../../src/yb/util/stack_trace_tracker.cc:13:
  ../../src/yb/util/stack_trace_tracker.cc:28:45: error: 'IsDebug' is not a member of 'yb'; did you mean 'kIsDebug'?
     28 | DEFINE_RUNTIME_bool(track_stack_traces, yb::IsDebug(), "Whether to enable stack trace tracking");
        |                                             ^~~~~~~
  ../../src/yb/util/flags/flag_tags.h:240:3: note: in expansion of macro '_DEFINE_flag'
    240 |   _DEFINE_flag(bool, name, default_value, description); \
        |   ^~~~~~~~~~~~
  ../../src/yb/util/stack_trace_tracker.cc:28:1: note: in expansion of macro 'DEFINE_RUNTIME_bool'
     28 | DEFINE_RUNTIME_bool(track_stack_traces, yb::IsDebug(), "Whether to enable stack trace tracking");
        | ^~~~~~~~~~~~~~~~~~~
  ../../src/yb/util/stack_trace_tracker.cc:28:45: error: 'IsDebug' is not a member of 'yb'; did you mean 'kIsDebug'?
     28 | DEFINE_RUNTIME_bool(track_stack_traces, yb::IsDebug(), "Whether to enable stack trace tracking");
        |                                             ^~~~~~~
  ../../src/yb/util/flags/flag_tags.h:240:3: note: in expansion of macro '_DEFINE_flag'
    240 |   _DEFINE_flag(bool, name, default_value, description); \
        |   ^~~~~~~~~~~~
  ../../src/yb/util/stack_trace_tracker.cc:28:1: note: in expansion of macro 'DEFINE_RUNTIME_bool'
     28 | DEFINE_RUNTIME_bool(track_stack_traces, yb::IsDebug(), "Whether to enable stack trace tracking");
        | ^~~~~~~~~~~~~~~~~~~
```
Jira: DB-7054

Test Plan: Jenkins: urgent, compile only

Reviewers: asrivastava

Reviewed By: asrivastava

Subscribers: ybase

Differential Revision: https://phorge.dev.yugabyte.com/D34804