[BACKPORT 2.11.2][PLAT-2741][Platform] Multiple iTest failures due to "Error[ERROR: could not serialize access due to read/write dependencies among transactions Detail"
Summary:
If either transaction were running at the Repeatable Read isolation level, both would be allowed to commit; but since there is no serial order of execution consistent with the result, using Serializable transactions will allow one transaction to commit and will roll the other back with this message:
ERROR:  could not serialize access due to read/write dependencies among transactions

Test Plan: Itest passed https://jenkins.dev.yugabyte.com/view/Dev/job/dev-itest-pipeline/577/ and manual run passed.

Reviewers: nbhatia, amalyshev, sb-yb

Reviewed By: sb-yb

Subscribers: yugaware, jenkins-bot

Differential Revision: https://phabricator.dev.yugabyte.com/D14910