[#11382] YSQL: ysql_dump fails for the index over HASH NULL FIRST key
Summary:
This diff solves the backup issue regarding a HASH NULL FIRST key.
Backup taken from the Platform 2.6.6.0-b10 produces the following statement for the index:
```
CREATE INDEX some_index ON myschema.some_table USING lsm (r1 NULLS FIRST HASH, r2 ASC NULLS FIRST, r3 ASC) SPLIT INTO 4 TABLETS WHERE ((r4 = false) AND (r5 = false) AND (r6 = false));
```
Attempt to restore backup (Platform 2.11) with this statement fails due to the non-existent index.
Error message:
```
ERROR:  syntax error at or near "HASH"
LINE 1: ...myschema.some_table USING lsm (r1 NULLS FIRST HASH, r2...
```

However, NULLS FIRST/NULLS LAST makes no sense for a HASH column.
To resolve the issue,
(1) I checked the root cause. Before this diff, we allow users to create an index with syntax like:
```
CREATE TABLE tbl (h1 int);
CREATE INDEX idx on tbl (h1 HASH NULLS FIRST);
```
When issuing the request to create this index, `AddColumn()` in `pggate.cc` ignores NULLS FIRST/LAST sort ordering options
for HASH columns, but `index_create()` inserts an index tuple with specified index options:` HASH` and `NULLS FIRST` into `pg_index`.
During backup, the index tuple stored in `pg_index` is used to retrieve the index sort options, thus the wrong index definition statement is returned.

(2) Ignore NULLS FIRST/NULLS LAST index option for HASH columns,
and issue a notice to tell users the NULLS FIRST/NULLS LAST sort ordering option is ignored.

(3) For backup, Ignore NULLS FIRST/NULLS LAST index option for a HASH column.

In summary, by these three steps, we will not affect existing users because an actually created
table ignores NULLS FIRST and NULLS LAST for a HASH column, backup will be consistent
(ignores any existing NULLS FIRST/NULLS LAST index option), explicit notice is added to show to users,
and inserted pg_index's index tuple `indoption` field will not set NULLS FIRST/NULLS LAST for hash columns.

Test Plan: ybd --java-test 'org.yb.pgsql.TestPgRegressIndex'

Reviewers: mihnea, oleg, mtakahara

Reviewed By: mtakahara

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D16273