[#18413] YSQL: Inconsistent schema version mismatch reported for SELECT and INSERT
Summary:
When the table schema version increments due to a DDL statement, we report
schema version mismatch error, but there is a difference between SELECT and
INSERT:

```
yugabyte=# select * from foo;
ERROR:  schema version mismatch for table 000033f5000030008000000000004000: expected 1, got 0
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

vs

```
yugabyte=# begin;
BEGIN
yugabyte=# insert into foo values (1);
ERROR:  schema version mismatch for table 000033f5000030008000000000004000: expected 1, got 0 (compt
with prev: 0)
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

The extra text in the error message ` (compt with prev: 0)` isn't meaningful in
YSQL context. It is a result of code sharing between YCQL and YSQL. We should
remove the extra error text for YSQL because it is confusing for users.
Jira: DB-7403

Test Plan:
Manual test. After the fix, for SELECT and INSERT we report identical `schema version mismatch`.

```
yugabyte=# begin;
BEGIN
yugabyte=# select * from foo;
ERROR:  schema version mismatch for table 000033f5000030008000000000004000: expected 1, got 0
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

```
yugabyte=# begin;
BEGIN
yugabyte=# insert into foo values (1);
ERROR:  schema version mismatch for table 000033f5000030008000000000004000: expected 1, got 0
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

Reviewers: dsrinivasan, tverona

Reviewed By: dsrinivasan

Subscribers: yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D27256