[BACKPORT 2.19.2][#18216] ysql: Implement creating/managing client context in shared memory for Ysql Connection Manager
Summary:
Original commit: e88c9dd04710e49d57676ddcf3fcbbc23a6cd5b7 / D26672
Ysql Connection Manager uses Odyssey in the `transaction` pooling mode. This mode has a few limitations (like: `WITH HOLD CURSORS`, `TEMP TABLES`, `SET STATEMENTS`).

This diff is regarding handling the limitation of session parameters in Ysql Connection Manager.
Shared memory will be used to store the client’s context, at the beginning of each transaction Ysql Conn Mgr will send a special packet (SET SESSION PARAMETER packet) which will restore the client's context on the current session. There will be a shared memory segment for each client connection.

 The following details will be stored in the shared memory as the client’s context.
  - Database oid
  - User oid
  - Key-value pair of changed session parameters.

This shared memory will be created during the time of authentication via the auth passthrough request, the database and user oid will be the same as that was used during the authentication.

A list of names of changed session parameters will be stored, at the end of the transaction this list will be used to store the key-value pair of changed session parameters in the shared memory.

This diff specifically addresses the cleanup of shared memory in scenarios where the client connection is lost but the cluster is still functioning correctly. Other cases, such as tserver crashes, will be handled in future code changes.

Please note the following considerations:

- The maximum number of concurrent shared-memory connections is limited by the operating system's shmmax setting. To support a higher number of concurrent clients connecting to the Ysql Connection Manager, this limit may need to be adjusted.
- When adding a test for Ysql Connection Manager, it is important to ensure that the connection is properly closed at the end of the test. This applies regardless of whether the connection object is defined within a try-catch block with resource management.
Jira: DB-7233

Test Plan:
Java test for testing session parameters limitation in the Ysql Connection Manager.
```
./yb_build.sh --java-test org.yb.ysqlconnmgr.TestSessionParameters
```

Manual testing:
- Check if the shared memory cleanup is happening properly.
```
Use `ipcs` and count the number of shared memory segments.
Start the cluster, create a connection to Ysql Connection Manager, perform some queries and close it.
Run `ipcs` again and ensure that number of shared memory segments remains unchanged.
```
- Ensure that non-superuser roles/users are unable to set the session parameters which can only be set by a super user.
```
yugabyte=# create user u1;
CREATE ROLE
yugabyte=# set role  u1;
SET
yugabyte=> set log_min_error_statement = "debug3";
ERROR:  permission denied to set parameter "log_min_error_statement"
yugabyte=> set role yugabyte;
SET
yugabyte=# set log_min_error_statement = "debug3";
SET
```

Reviewers: nkumar, smishra

Reviewed By: nkumar

Subscribers: yql, ybase, nkumar, tverona, smishra

Differential Revision: https://phorge.dev.yugabyte.com/D28110