[#4248] [yb-admin] Allow removal of dead master peer without special use_hostport flag
Summary:
Removal of a dead master peer via yb-admin involves a special boolean use_hostport flag which is then passed on to the ChangeConfig. This diff makes the default value of use_hostport to true so that removal works without additional non-obvious flags.

When use_hostport is true, the dead master is specified in the ChangeConfig(REMOVE_SERVER) to the leader master as a host:port instead of a UUID and the leader master is then responsible for mapping the host:port to the UUID.

Added a unit test to verify this.

Fixed a minor mem leak.

Test Plan:
1. Add a unit test for this scenario, verify it passes.
2. Test manually with a yb-ctl cluster with a stopped master.

```
    22:20 $ /tmp/yugabyte-2.1.4.0/bin/yb-admin --master_addresses=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_all_masters
    Master UUID                             RPC Host/Port           State   Role
    5615154d2f0d4e9ab0d094f7d6dc7e18        127.0.0.1:7100          NETWORK_ERROR   UNKNOWN
    3f5d878fb5c04c259812493c4949f111        127.0.0.2:7100          ALIVE           LEADER
    c49dd1862f494b7ca1bb146fa68f93a1        127.0.0.3:7100          ALIVE           FOLLOWER
    dev-server-sanketh-3:~/code/yugabyte [yb-admin ↓·151↑·143|⚑ 7]
    22:20 $ /tmp/yugabyte-2.1.4.0/bin/yb-admin --master_addresses=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 change_master_config REMOVE_SERVER 127.0.0.1 7100
    Error: Network error (yb/util/net/socket.cc:537): Unable to change master config: recvmsg error: Connection refused (system error 111)
    dev-server-sanketh-3:~/code/yugabyte [yb-admin ↓·151↑·143|⚑ 7]
    22:21 $ build/latest/bin/yb-admin --master_addresses=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 change_master_config REMOVE_SERVER 127.0.0.1 7100
    dev-server-sanketh-3:~/code/yugabyte [yb-admin ↓·151↑·143|⚑ 7]
    22:21 $ /tmp/yugabyte-2.1.4.0/bin/yb-admin --master_addresses=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_all_masters
    Master UUID                             RPC Host/Port           State   Role
    3f5d878fb5c04c259812493c4949f111        127.0.0.2:7100          ALIVE           LEADER
    c49dd1862f494b7ca1bb146fa68f93a1        127.0.0.3:7100          ALIVE           FOLLOWER
```

Reviewers: hector, raju, bogdan

Reviewed By: bogdan

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D8344