[BACKPORT 2024.1][DB-10610] YSQL: import Detect integer overflow while computing new array dimensions
Summary:
Backport Description:
No merge Conflicts:

Original Description:

This patch imports the following upstrean PG commit that fixes CVE-2023-5869.
[[https://github.com/postgres/postgres/commit/c48008f599fd0e3bca2923ff5b40b559ae1e4e2e | c48008f599fd0e3bca2923ff5b40b559ae1e4e2e]]

```
Detect integer overflow while computing new array dimensions.

array_set_element() and related functions allow an array to be
enlarged by assigning to subscripts outside the current array bounds.
While these places were careful to check that the new bounds are
allowable, they neglected to consider the risk of integer overflow
in computing the new bounds.  In edge cases, we could compute new
bounds that are invalid but get past the subsequent checks,
allowing bad things to happen.  Memory stomps that are potentially
exploitable for arbitrary code execution are possible, and so is
disclosure of server memory.

To fix, perform the hazardous computations using overflow-detecting
arithmetic routines, which fortunately exist in all still-supported
branches.

The test cases added for this generate (after patching) errors that
mention the value of MaxArraySize, which is platform-dependent.
Rather than introduce multiple expected-files, use psql's VERBOSITY
parameter to suppress the printing of the message text.  v11 psql
lacks that parameter, so omit the tests in that branch.

Our thanks to Pedro Gallegos for reporting this problem.

```
JIRA: DB-10610

Original commit: 54776ab9f38d36ba4490ab510ae54aae90c580ad / D37202

Test Plan:
== Automated Testing ==
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressArrays#testPgRegressArrays'

== Manual Testing ==

```
db1=# create temp table arr_pk_tbl (pk int4 primary key, f1 int[]);
CREATE TABLE
db1=# insert into arr_pk_tbl values(10, '[-2147483648:-2147483647]={1,2}');
INSERT 0 1
db1=# update arr_pk_tbl set f1[2147483647] = 42 where pk = 10;
ERROR:  array size exceeds the maximum allowed (134217727)
db1=# update arr_pk_tbl set f1[2147483646:2147483647] = array[4,2] where pk = 10;
ERROR:  array size exceeds the maximum allowed (134217727)
```

Reviewers: skumar, devansh.saxena

Reviewed By: devansh.saxena

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D38327