[PLAT-10298]Block Update/Create KMS operation if permissions are insufficient
Summary:
Create and Edit KMS for Hashicorp did not check for permissions other than list and read, which is
not sufficient for universe key operations.

Test Plan:
Manually test failure of create and edit when insufficiet permissions are given

Error thrown in the logs:
```
YW 2023-09-07T04:15:32.012Z [ERROR] c15b2aa8-4921-4745-886f-31befb569999 from HashicorpEARServiceUtil in TaskPool-1 - Error occurred in testEncryptDecrypt key in Hashicorp KMS with config UUID 'd1086105-1abc-4b63-b612-5cc844619be4'.
com.bettercloud.vault.VaultException: Hashicorp Vault responded with HTTP status code: 403
Response body: {"errors":["1 error occurred:\n\t* permission denied\n\n"]}

	at com.yugabyte.yw.common.kms.util.hashicorpvault.VaultAccessor.checkForResponseFailure(VaultAccessor.java:227)
	at com.yugabyte.yw.common.kms.util.hashicorpvault.VaultAccessor.writeAt(VaultAccessor.java:368)
	at com.yugabyte.yw.common.kms.util.hashicorpvault.VaultTransit.encryptString(VaultTransit.java:118)
	at com.yugabyte.yw.common.kms.util.HashicorpEARServiceUtil.testEncryptDecrypt(HashicorpEARServiceUtil.java:369)
	at com.yugabyte.yw.common.kms.services.HashicorpEARService.createAuthConfigWithService(HashicorpEARService.java:79)
	at com.yugabyte.yw.common.kms.services.EncryptionAtRestService.updateAuthConfig(EncryptionAtRestService.java:249)
	at com.yugabyte.yw.commissioner.tasks.EditKMSConfig.run(EditKMSConfig.java:73)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:831)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1044)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
YW 2023-09-07T04:15:32.012Z [ERROR] c15b2aa8-4921-4745-886f-31befb569999 from HashicorpEARService in TaskPool-1 - Error while trying to check/create a key in the vault for config UUID 'd1086105-1abc-4b63-b612-5cc844619be4'.
com.yugabyte.yw.common.PlatformServiceException: Error occurred in testEncryptDecrypt key in Hashicorp KMS with config UUID 'd1086105-1abc-4b63-b612-5cc844619be4'.
	at com.yugabyte.yw.common.kms.util.HashicorpEARServiceUtil.testEncryptDecrypt(HashicorpEARServiceUtil.java:385)
	at com.yugabyte.yw.common.kms.services.HashicorpEARService.createAuthConfigWithService(HashicorpEARService.java:79)
	at com.yugabyte.yw.common.kms.services.EncryptionAtRestService.updateAuthConfig(EncryptionAtRestService.java:249)
	at com.yugabyte.yw.commissioner.tasks.EditKMSConfig.run(EditKMSConfig.java:73)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:831)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1044)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
YW 2023-09-07T04:15:32.014Z [ERROR] c15b2aa8-4921-4745-886f-31befb569999 from TaskExecutor in TaskPool-1 - Failed to execute task type EditKMSConfig UUID fd47b26b-2068-4377-ad31-52f1973ba19b details {"platformVersion":"2.19.3.0-PRE_RELEASE","customerUUID":"f33e3c9b-75ab-4c30-80ad-cba85646ea39","configUUID":"d1086105-1abc-4b63-b612-5cc844619be4","kmsConfigName":"dkumar-switch","kmsProvider":"HASHICORP","providerConfig":{"name":"dkumar-switch"}, hit error.
java.lang.RuntimeException: Error updating KMS Configuration for customer f33e3c9b-75ab-4c30-80ad-cba85646ea39 and kms provider HASHICORP
	at com.yugabyte.yw.commissioner.tasks.EditKMSConfig.run(EditKMSConfig.java:77)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:831)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1044)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
YW 2023-09-07T04:15:32.014Z [DEBUG] c15b2aa8-4921-4745-886f-31befb569999 from TaskExecutor in TaskPool-1 - Task creator callstack:
com.yugabyte.yw.commissioner.TaskExecutor.createRunnableTask(TaskExecutor.java:325)
com.yugabyte.yw.commissioner.TaskExecutor.createRunnableTask(TaskExecutor.java:312)
com.yugabyte.yw.commissioner.Commissioner.submit(Commissioner.java:120)
com.yugabyte.yw.controllers.EncryptionAtRestController.editKMSConfig(EncryptionAtRestController.java:494)
v1.Routes$$anonfun$routes$1.$anonfun$applyOrElse$212(Routes.scala:9020)
play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:150)
play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:149)
play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
play.core.j.JavaAction$$anon$1.call(JavaAction.scala:119)
play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
com.yugabyte.yw.controllers.TokenAuthenticator.call(TokenAuthenticator.java:193)
com.yugabyte.yw.controllers.FailedRequestAction.call(FailedRequestAction.java:33)
com.yugabyte.yw.controllers.AuditAction.call(AuditAction.java:31)
com.yugabyte.yw.rbac.handlers.AuthorizationHandler.call(AuthorizationHandler.java:78)
play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:175)
YW 2023-09-07T04:15:32.017Z [DEBUG] c15b2aa8-4921-4745-886f-31befb569999 from TaskExecutor in TaskPool-1 - Completed task EditKMSConfig in 0s
```

Reviewers: skurapati

Reviewed By: skurapati

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D28341