[#17023] YSQL: Improve drop database in per-database catalog version mode
Summary:
There are two types of DDL statements:
* new-version DDL: those that cause catalog version to increment;
* same-version DDL: those that do not cause catalog version to increment;

For example, create database statement is a same-version DDL while drop database
statement is a new-version DDL.

I studied to see why drop database is new-version DDL. I found that after a
database is dropped, then
(1) any attempt to connect to this database will fail
(2) any existing connection to this database will fail on next query if any
metadata lookup is needed

I made an experiment to make drop database a same-version DDL and I have the
following findings in global catalog version mode (i.e., when per-database catalog
version mode is off):

For (1), nothing changes if I made drop database a same-version DDL and we
get the same error:

```
ysqlsh: FATAL:  database "db1" does not exist
```

For (2), we get an error message that is less helpful if I made drop database a
same version DDL. For example

```
db1=# select * from foo;
ERROR:  Table <unknown_table_name> (000040000000300080000000000004eb) not found in Raft group
00000000000000000000000000000000
LINE 1: select * from foo;

```
If we keep drop database as a new-version DDL then we see a more helpful error
message:

```
db1=# select from foo;
FATAL:  Could not reconnect to database
HINT:  Database might have been dropped by another user
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>

```

In per-database catalog version mode, after I made drop database statement a
same-version DDL, both (1) and (2) continue to show same results. This means
whether drop database statement is same-version DDL or not, there is no
user visible difference.

The reason we need drop database to be a new-version DDL is that we only recheck
that the database is still valid during catalog cache refresh. After an error
like the above, we call `YbGetMasterCatalogVersionFromTable` to get the latest catalog
version, if the catalog version does not change, there will be no catalog
refresh and that's why the original less helpful error would be reported as is.

If there is a new catalog version then we do catalog cache refresh, during which
we recheck the validity of the database and find that the database is already
dropped. At that time instead of reporting the original error, we report the new
error that the database is already dropped, which is more helpful.

For per-database catalog version mode, once we hit the above error, we call
`YbGetMasterCatalogVersionFromTable`, which has a different code path for
per-database catalog version where when the row for the dropped database is not
found, we report the following error that is more helpful:
```
            if (!has_data)
                ereport(ERROR,
                    (errcode(ERRCODE_DATABASE_DROPPED),
                     errmsg("catalog version for database %u was not found.", db_oid),
                     errhint("Database might have been dropped by another user")));
```

Therefore, in per-database catalog version mode, we can make drop database a
same-version DDL. In particular, there is no update needed for the unit test
PgCatalogVersionTest.DBCatalogVersionDropDB. In addition, because drop database
is a global-ddl statement in per-database catalog version mode, it is more impactful
to make it a same-version DDL.

Test Plan: YB_EXTRA_MASTER_FLAGS="--log_ysql_catalog_versions=true --vmodule=master_heartbeat_service=2" YB_EXTRA_TSERVER_FLAGS="--log_ysql_catalog_versions=true --ysql_pg_conf_csv=log_min_messages=DEBUG1 --vmodule=heartbeater=2,ybc_pggate=2,pggate=1" ./yb_build.sh --cxx-test pg_catalog_version-test

Reviewers: jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D24800