[pg15] fix: Prioritise wholerow var of rel_type_id vartype over RECORDOID vartype in target list
Summary:
D31677 made the change to use vartype == RECORDOID for wholerow var junk attribute in `add_row_identity_columns` for YB relations.

This causes issues in the scenario where wholerow vars of both vartype - RECORDOID and  rel_type_id - are present.  Consider the following example:

```
create table test (id int unique);
insert into test values (1), (2), (3);
explain (costs off) select test from test;
    QUERY PLAN
------------------
 Seq Scan on test     /* target list has wholerow var with vartype == rel_type_id, no issues  */
(1 row)

explain (costs off) delete from test WHERE test = row(3);
                QUERY PLAN
------------------------------------------
 Delete on test
   ->  Seq Scan on test         /* target list has wholerow var with vartype == RECORDOID, no issues  */
         Filter: (test.* = '(3)'::record)
(3 rows)

explain (costs off) delete from test WHERE test = ANY (select test from test);
                   QUERY PLAN
-------------------------------------------------
 Delete on test
   ->  Hash Join
         Hash Cond: (test.* = test_1.*)
         ->  Seq Scan on test.        /* target list has whole row var with vartype == RECORDOID, mismatches with below  */ <--- problem
         ->  Hash
               ->  HashAggregate
                     Group Key: test_1.*
                     ->  Seq Scan on test test_1.  /* target list has whole row var with vartype == rel_type_id */
(8 rows)

```

As a result, the last query, ie,
```
delete from test WHERE test = ANY (select test from test);

```
throws
ERROR:  attribute 1 of type record has wrong type
DETAIL:  Table has type record, but query expects test.

The above DELETE query is a simplified version of one that is executed by `REFRESH MATERIALIZED VIEW CONCURRENTLY`.

The root cause of the issue is that for a given varattno , `add_vars_to_targetlist` adds the first var that it sees to the target list and ignores any subsequent vars that have the same varattno. Fix the issue by prioritizing wholerow var of rel_type_id vartype over any previously added wholerow var of RECORDOID vartype in the target list.

Test Plan:
Jenkins: rebase: pg15
./yb_build.sh --java-test org.yb.pgsql.TestPg15Regress#testPg15Regress

To test this change on all the tests that run on YB master branch, I created a revision D32425 on the master containing changes from D31677 and D32285. Detective result: https://detective-gcp.dev.yugabyte.com/D32425

Reviewers: jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D32285