[#11981] ysql [Test] Add table definition for int8_tbl in yb_pg_window_schedule
Summary:
Commit b3017a7 added tests for grouping sets.

However, table definition for int8_tbl was missing, resulting in
```
ERROR:  relation "int8_tbl" does not exist
LINE 2:   (select *, q1 = 1 as x from int8_tbl i1) as t
```
This revision adds the missing dependency.

Test Plan: mvn test -Dtest=org.yb.pgsql.TestPgRegressWindow

Reviewers: myang, ssong

Reviewed By: myang, ssong

Subscribers: jason, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D16365