[BACKPORT 2.8][#11425] YSQL: Fix foreign data wrapper (FDW) dangling reference bug
Summary:
For the new test case added, the symptom of this bug appears as a syntax error

```
ERROR:  syntax error at end of input
CONTEXT:  remote SQL command: DEALLOCATE
```

The DEALLOCATE SQL command is auto-composed by FDW code:

```
    /* If we created a prepared statement, destroy it */
    if (fmstate->p_name)
    {
        char        sql[64];
        PGresult   *res;

        snprintf(sql, sizeof(sql), "DEALLOCATE %s", fmstate->p_name);

```

The reason for this bug is that the memory of fmstate->p_name is already freed and fmstate->p_name
becomes a dangling reference. We end up composing some garbage characters after DEALLOCATE. When
processing of the COPY command, for FWD we need to ensure the allocated memory for fmstate->p_name
stays longer than a per tuple memory context. I made a change to use the query memory context
instead. For non-FWD case, we continue to have the YB optimization to use the per tuple memory
context.

I expanded the existing test schedule yb_pg_foreign_data_schedule and pulled in from
postgres_fdw.sql just the test case of this bug to limit the scope of this diff. We can later pull
in more test cases from postgres_fdw.sql separately.

One test change I made is that in order for the test to successfully run within our java test
framework, I added to the original test code:

```
                     host '$$||current_setting('listen_addresses')||$$',
```

Otherwise, the default localhost IP 127.0.0.1 is used to connect to the loopback server and that
will fail because the loopback server reuses the same host:port of the postgres server which is
automatically assigned by the test driver. For example it may look like 127.153.254.206:12782.
Connecting to 127.153.254.206:12782 succeeds but connecting to 127.0.0.1:12782 fails which resulted
in test failure.

Original commit: D15526 / ecf085037e698e4e9322084d38ee22a04410d7c7

Test Plan:
Jenkins: rebase: 2.8
./yb_build.sh debug --java-test 'org.yb.pgsql.TestPgRegressForeignData'

Reviewers: fizaa

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D15602