[BACKPORT 2.20][#19965] YSQL: publication for all tables caused ddl error in per-db mode
Summary:
To reproduce the bug:

1. Create a cluster and convert it into per-database catalog version mode
```
yugabyte=# select * from pg_yb_catalog_version;
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               1 |                     1
  13242 |               1 |                     1
  13243 |               1 |                     1
  13245 |               1 |                     1
  13246 |               1 |                     1
(5 rows)
```
The above query output indicates that the cluster is running in per-database
catalog version mode.

2. Create a publication for all tables
```
yugabyte=# CREATE PUBLICATION testpub_foralltables FOR ALL TABLES;
CREATE PUBLICATION
```

The following DDL statement fails
```
yugabyte=# ALTER USER yugabyte SUPERUSER;
ERROR:  cannot update table "pg_yb_catalog_version" because it does not have a replica identity and publishes updates
HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
CONTEXT:  SQL function "yb_increment_all_db_catalog_versions" statement 1
```

The error comes from the function `CheckCmdReplicaIdentity`. Publication is a
newly supported feature in YSQL. In per-database catalog version mode, we
internally call function `yb_increment_all_db_catalog_versions` to update
`pg_yb_catalog_version` table. In global-database catalog version mode, we
directly issue an update on `pg_yb_catalog_version` table which by-passes
various PG layer checks including `CheckCmdReplicaIdentity`. I made a change in
`CheckCmdReplicaIdentity` to allow `pg_yb_catalog_version` to mimic the update
of `pg_yb_catalog_version` under the global catalog version mode. New unit test
added.

Original commit: 409594ecac2968a0c0dfd21b25dc2ee7917a7c0c / D30260

NOTE: publication isn't supported in 2.20, so the unit test has a change from
ASSERT_OK to ASSERT_NOK for the `CREATE PUBLICATION` statement. This
backport isn't technically needed but it makes further per-db catalog version mode
backports clean.

Test Plan:
(1) ./yb_build.sh --cxx-test pg_catalog_version-test
(2) Run the same test in per-database catalog version mode

YB_EXTRA_DAEMON_FLAGS="--ysql_enable_db_catalog_version_mode=true --allowed_preview_flags_csv=ysql_enable_db_catalog_version_mode" ./yb_build.sh reinitdb
YB_EXTRA_DAEMON_FLAGS="--ysql_enable_db_catalog_version_mode=true --allowed_preview_flags_csv=ysql_enable_db_catalog_version_mode" ./yb_build.sh --cxx-test pg_catalog_version-test

Reviewers: stiwary, jason, dsrinivasan

Reviewed By: stiwary

Subscribers: yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D30852