[pg15] fix: remerge grammar for CREATE LANGUAGE
Summary:
YB initial merge 55782d561e55ef972f2470a4ae887dd791bb4a97 incorrectly
merged YB master c809ee076f6cbcb1db3f811c28d1dcb6d7c5e42b enabling
grammar rules and upstream PG 3fbd4bb6f494dd70cc5075536a754261853de167
moving those rules.  This results in CREATE LANGUAGE statement in
regress test yb_create_language to fail with

    ERROR:  DROP LANGUAGE not supported yet

Remerge properly, and add to pg15_tests a case that makes sure that
statement now passes.

Test Plan:
On Almalinux 8:

    #!/usr/bin/env bash
    set -e
    ./yb_build.sh fastdebug --gcc11
    pg15_tests/test_D29662.sh fastdebug --gcc11

Jenkins: rebase: pg15

Reviewers: fizaa, tfoucher

Reviewed By: tfoucher

Subscribers: tfoucher, aagrawal, yql

Differential Revision: https://phorge.dev.yugabyte.com/D31379