[#10456] ysql: Import Fix detaching partitions with cloned row triggers
Summary:
commit was 0b83c47216b0fe71a8a0e880eb550a09f06dad38

commit message was:

    When a partition is detached, any triggers that had been cloned from its
    parent were not properly disentangled from its parent triggers.
    This resulted in triggers that could not be dropped because they
    depended on the trigger in the trigger in the no-longer-parent table:
      ALTER TABLE t DETACH PARTITION t1;
      DROP TRIGGER trig ON t1;
        ERROR:  cannot drop trigger trig on table t1 because trigger trig on table t requires it
        HINT:  You can drop trigger trig on table t instead.

    Moreover the table can no longer be re-attached to its parent, because
    the trigger name is already taken:
      ALTER TABLE t ATTACH PARTITION t1 FOR VALUES FROM (1)TO(2);
        ERROR:  trigger "trig" for relation "t1" already exists

    The former is a bug introduced in commit 86f575948c77.  (The latter is
    not necessarily a bug, but it makes the bug more uncomfortable.)

    To avoid the complexity that would be needed to tell whether the trigger
    has a local definition that has to be merged with the one coming from
    the parent table, establish the behavior that the trigger is removed
    when the table is detached.

    Backpatch to pg11.

    Author: Justin Pryzby <pryzby@telsasoft.com>
    Reviewed-by: Amit Langote <amitlangote09@gmail.com>
    Reviewed-by: Álvaro Herrera <alvherre@alvh.no-ip.org>
    Discussion: https://www.postgresql.org/message-id/flat/20200408152412.GZ2228@telsasoft.com

Test Plan: Build Yugabyte DB and run test suite via Jenkins

Reviewers: amartsinchyk, myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D13739