[#16275] docdb: fix yb_backup dependent unit tests on newer versions of python3
Summary:
This diff moves the boto imports into the sole function in yb_backup that uses boto. This function
is only used by the s3 code path. Since unit tests use the nfs backup option, they do not use this
function and thus with this change the backup script doesn't try to import boto because it never
runs the offending function.

Test Plan:
`ybd --cxx-test yb-backup-test --gtest_filter YBBackupTest.TestYCQLBackupWithDefinedPartitions`

With this diff, this test passes. Without it, I get:
```
Traceback (most recent call last):
  File "/Users/zdrudi/code/yugabyte-db/build/debug-clang-dynamic-arm64-ninja/tests-tools/../../../managed/devops/bin/yb_backup.py", line 29, in <module>
    from botocore.session import get_session
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/session.py", line 25, in <module>
    import botocore.configloader
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/configloader.py", line 20, in <module>
    import botocore.exceptions
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored.requests.exceptions import ConnectionError
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
../../src/yb/tools/yb-backup/yb-backup-test.cc:549: Failure
Failed
```

Reviewers: slingam, mhaddad, oleg

Reviewed By: oleg

Subscribers: jenkins-bot, ybase, slingam, bogdan, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D23267