[BACKPORT 2025.2][#28920] YSQL: Fix "Expecting a used read time" error with parallel append
Summary:
Original commit: 7fea402fe1cb9ab6151537b121924a49e958e43a / D49967
Parallel plans can run into the following error

```
ERROR:  Expecting a used read time from the previous RPC but didn't find one
CONTEXT:  parallel worker
```

For example, the following query runs using parallel append

```
SELECT variance(unique1::int4), sum(unique1::int8), regr_count(unique1::float8, unique1::float8)
FROM (SELECT * FROM tenk1
      UNION ALL SELECT * FROM tenk1
      UNION ALL SELECT * FROM tenk1
      UNION ALL SELECT * FROM tenk1) u;
```

The explain plan

```
 Finalize Aggregate
   Output: variance(tenk1.unique1), sum((tenk1.unique1)::bigint), regr_count((tenk1.unique1)::double precision, (tenk1.unique1)::double precision)
   ->  Gather
         Output: (PARTIAL variance(tenk1.unique1)), (PARTIAL sum((tenk1.unique1)::bigint)), (PARTIAL regr_count((tenk1.unique1)::double precision, (tenk1.unique1)::double precision))
         Workers Planned: 3
         ->  Partial Aggregate
               Output: PARTIAL variance(tenk1.unique1), PARTIAL sum((tenk1.unique1)::bigint), PARTIAL regr_count((tenk1.unique1)::double precision, (tenk1.unique1)::double precision)
               ->  Parallel Append
                     ->  Seq Scan on public.tenk1
                           Output: tenk1.unique1
                     ->  Seq Scan on public.tenk1 tenk1_1
                           Output: tenk1_1.unique1
                     ->  Seq Scan on public.tenk1 tenk1_2
                           Output: tenk1_2.unique1
                     ->  Seq Scan on public.tenk1 tenk1_3
                           Output: tenk1_3.unique1
```

demonstrates that this is a parallel append plan.

A parallel worker does the following:

1. YBCRestorePgSessionState(): to use the same read_time_serial_no (and some other state) as the leader PG backend.

2. RestoreSnapshot(): restore the snapshot from the serialized snapshot. This picks the current read time serial number from PgTxnManager to be used for the snapshot (which is set to be the same as the read_time_serial_no from the leader PG backend). Note that this function is called for both the active snapshot and the transaction snapshot. For YB, only the `yb_read_point_handle` matters. Most of the other snapshot data is irrelevant.

3. RestoreTransactionSnapshot(): this sets the transaction snapshot to be the same as the restored snapshot. As part of this, PG calls `GetSnapshotData()` internally for some initialization. But as part of YB, `GetSnapshotData()` calls `PgTxnManager::ResetTransactionReadPoint()`. This increments the read_time_serial_no in PgTxnManager.

4. PushActiveSnapshot(asnapshot): This ends up restoring the read_time_serial_no in PgTxnManager back to the desired non-incremented value (i.e., as as the leader PG backend's read_time_serial_no)

In Step 3, `ResetTransactionReadPoint` ends up resetting the read_time_manipulation to NONE. This is problematic because as part of 3484013e6330 / D33815, the read_time_manipulation is set to ENSURE_READ_TIME_IS_SET on both the parallel workers and the leader PG backend. Resetting it to NONE causes the read time to not be picked on PgClientSession and instead rely on the remote tserver to pick it. This causes the `Expecting a used read time` error since there are multiple simultaneous read RPCs from various workers.

To fix this, call YBCPgEnsureReadPoint() after RestoreTransactionSnapshot(). After the fix, the query no longer fails with the above mentioned error.

**Additional changes:**

Also, serialize and restore yb_read_point_handle in SerializeSnapshot and RestoreSnapshot functions.

**Changes compared to master:**
1. SET yb_enable_parallel_append = on; Because yb_enable_parallel_append is false by default on 2025.2

Test Plan:
Jenkins: urgent

./yb_build.sh release --java-test 'org.yb.pgsql.TestPgRegressAggregates'

**Additional details:**

The above query spawns three parallel workers. Each of these parallel workers have a read time serial number of 1427 as can be seen from the below logs

```
ts1|pid1401398|:12660|http://127.101.5.216:27586 I0128 19:58:48.459244 1401433 pg_client_session.cc:3090] Session id 10 (pid 1402220):  Regular DML/ DDL op: txn_serial_no: 699, read_time_se
rial_no: 1427; Read op: 000034d9000030008000000000004020;
ts1|pid1401398|:12660|http://127.101.5.216:27586 I0128 19:58:48.459262 1401433 pg_client_session.cc:3433] vlog3: Session id 10 (pid 1402220): Resetting read point for session kind kPlain re
ad point reset requested: 0 use catalog session: 0 change in read time serial number 1424, 1427
ts1|pid1401398|:12660|http://127.101.5.216:27586 I0128 19:58:48.459268 1401433 pg_client_session.cc:3487] vlog3: Session id 10 (pid 1402220): Reset read time: { read: <invalid> local_limit:
 <invalid> global_limit: <invalid> in_txn_limit: <invalid> serial_no: 0 }
ts1|pid1401398|:12660|http://127.101.5.216:27586 I0128 19:58:48.459295 1401433 pg_client_session.cc:3186] vlog2: Session id 10 (pid 1402220): Performing RPC: pid=1402220, session_kind=kPlai
n, ops=[R:tenk1], read_time=not set yet, read_time_serial_no=1427, txn=none
ts1|pid1401398|:12660|http://127.101.5.216:27586 I0128 19:58:48.459352 1402894 pg_client_session.cc:3090] Session id 10 (pid 1402220):  Regular DML/ DDL op: txn_serial_no: 699, read_time_se
rial_no: 1427; Read op: 000034d9000030008000000000004020;
ts1|pid1401398|:12660|http://127.101.5.216:27586 E0128 19:58:48.459369 1402894 pg_client_session.cc:3743] Session id 10 (pid 1402220): Expecting a used read time from the previous RPC but d
idn't find one
ts1|pid1401398|:12660|http://127.101.5.216:27586 I0128 19:58:48.459595 1402894 pg_client_session.cc:3090] Session id 10 (pid 1402220):  Regular DML/ DDL op: txn_serial_no: 699, read_time_serial_no: 1427; Read op: 000034d9000030008000000000004020;
ts1|pid1401398|:12660|http://127.101.5.216:27586 E0128 19:58:48.459614 1402894 pg_client_session.cc:3743] Session id 10 (pid 1402220): Expecting a used read time from the previous RPC but didn't find one
```

Reviewers: pjain, smishra

Reviewed By: pjain

Subscribers: yql, jason

Differential Revision: https://phorge.dev.yugabyte.com/D50028