[#12990] ysql: Import rename pipe type to orafce_pipe due conflict with pipe function from unistd.h
Summary:
This diff imports orafce/orafce@1f162a6 which renames the `pipe` type in `pipe.c` to
`orafce_pipe` to fix the following compile error:

```
src/postgres/third-party-extensions/orafce/pipe.c:94:3: error: redefinition of 'pipe' as different kind of symbol
    } pipe;
        ^
/usr/include/unistd.h:437:12: note: previous definition is here
    extern int pipe (int __pipedes[2]) __THROW __wur;

```

The compile error arises from a conflict with the typedef `pipe` in `pipe.c`, and the `pipe()` function in `unistd.h`.

Test Plan:
Jenkins.

Also built locally on Ubuntu 22.04/clang12 where the above error appeared.

Reviewers: zyu

Reviewed By: zyu

Subscribers: yql, ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D17851