ENG-5282 #1740 gcc7 release build compilation fix
Summary:
There is a false positive `array-bounds` error (due to agressive -O3 optimization in release build) is
fixed in slice_transform_test.cc

```
In file included from src/yb/rocksdb/slice_transform.h:34:0,
                 from src/yb/rocksdb/util/slice_transform_test.cc:24:
src/yb/util/slice.h: In member function ‘virtual void rocksdb::SliceTransformTest_CapPrefixTransform_Test::TestBody()’:
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
```

Using Slice(const std::string&) constructor instead of Slice() or Slice(const char* s) for "" (empty string) solves the issue.
Problem is very specific for this particular place. There is no issue with creation of Slice from "" all the time.

Test Plan: Compile release build with gcc7

Reviewers: raju, mikhail

Reviewed By: mikhail

Differential Revision: https://phabricator.dev.yugabyte.com/D6874