[BACKPORT 2024.2] [#25072] DocDB: Fix false corruption detection during colocated index read
Summary:
When index is colocated to the indexed table we perform index read using single query.
At the first step the index table is read, to fetch row keys from the indexed table.
On the second step indexed table is read using those keys.
If row key does not exist on the second step, the corruption is being reported.

It could happen that transaction apply happens in parallel to read and this row was just removed by recently committed transaction.
So read finds this row on the first step, but does not see it on the second step raising the corruption error.
Actually read restart mechanism detects that read is not consistent and should be restarted.
But this particular corruption detection logic ignores read restart.

The failure message looks like this one:
```
ERROR: ybctid DocKey([], [16754]) not found in indexed table. index table id is 00004007000030008000000000000a76
```

Fixed by checking read restart before reporting such corruption.

Updated param naming in PgDdlAtomicityStressTest to be more used friendly.
Also fixed the following issues found by this test:
1) Potential crash because of head use after free if AbortTransaction response is received during tablet shutdown.
2) TServer could wait until OpenTable timeout (2min) during shutdown.
3) TServer could wait tablet validation timeout (2min) during shutdown.
Jira: DB-14202
Original commit: ca9a3e7a9ccdefafe57d6027c948c2fa96788a3f/D40235

Test Plan: ./yb_build.sh fastdebug --gcc11 --gtest_filter PgDdlAtomicityStressTest.Main/colocated -n 20

Reviewers: myang, dmitry

Reviewed By: dmitry

Subscribers: ybase, yql, dmitry

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D40474