ENG-2459: Create redis table crashed master leader sometimes.
Summary:
The client captures default for number of tablets for redis (or any other) table create, using the number of tservers from master leader and multiplies it by yb_num_shards_per_tserver. In the case where none of the tserver's heartbeated to a newly elected master leader, this could be 0 and the processing of this request on server causes a division by 0 in partition.cc.

Fix is to ensure server catches the 0 value, tried to default it, otherwise return a error status.

Some misc minor code dedup and lint/alignment fixes.

Test Plan:
Jenkins.
Local yb-ctl create and setup_redis create quickly. It returned:
```Unable to setup Redis keyspace and table: Invalid argument (yb/common/wire_protocol.cc:149): Error creating table system_redis.redis on the master: num_tablets should be greater than 0. Client would need to wait for master leader get heartbeats from tserver.
```
Next call to setup_redis succeeded.
Added unit test

Reviewers: bogdan, pritam.damania

Reviewed By: pritam.damania

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D3639