[#16004] YSQL: Colocation GA alter table add primary key, drop constraint pk not working for colocated tables
Summary:
This diff fixes the ALTER TABLE ADD PRIMARY KEY and DROP CONSTRAINT PK issues for colocated tables.
Issue Repro:
```
CREATE TABLE tbl_no_pk (k INT, v INT) WITH (colocation = true);
ALTER TABLE tbl_no_pk ADD PRIMARY KEY (k ASC);
ERROR:  cannot use 'colocation=true/false' with tablegroup
```
```
CREATE TABLE tbl_pk (k INT, v INT, PRIMARY KEY(k ASC)) WITH (colocation = true);
ALTER TABLE tbl_pk DROP CONSTRAINT tbl_pk_pkey;
ERROR:  cannot use 'colocation=true/false' with tablegroup
```
The root cause of the issue is as follows:
(1) We disallow users to specify colocation WITH option with TABLEGROUP.
(2) In YB, for ALTER TABLE ADD/DROP PRIMARY KEY, we re-create a new table with/without primary key.
(3) During the creation of the new table, in function `YBCloneRelationSetPrimaryKey`, the original colocation option of the old table is copied from pg_class reloptions field and underlying tablegroup of the old table is chosen, which failed the check enforced in (1).
The fix is to skip finding underlying tablegroup for colocated tables in colocated database in `YBCloneRelationSetPrimaryKey` and there is another place after the check enforced by (1) to pick up the tablegroup for the new table in `YBCCreateTable`.

In addition to the main issue mentioned above, the prevention of users from using underlying tablegroups of a colocated database is added.
Example:
```
CREATE TABLE invalid_tbl (k int) TABLEGROUP "default";
ERROR:  cannot use tablegroups in a colocated database
```

Test Plan:
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressColocation#testPgRegressColocation'
./yb_build.sh --java-test 'org.yb.pgsql.TestPgAlterTableChangePrimaryKey#tablesInColocatedDb'

Reviewers: tverona, dsrinivasan, fizaa

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D22883