[YSQL] #1193: Delete old index entries properly during UPDATE and DELETE.
Summary:
This revision resolves the issue that duplicate key violation in unique index is raised when the
key has been deleted:

```
postgres=# create table t (k int primary key, v int);
postgres=# create unique index on t (v);
postgres=# insert into t values (1, 1);
postgres=# delete from t where k = 1;
postgres=# insert into t values (1, 1);
ERROR:  Query error: Duplicate key found in primary key or unique index
```

Two underlying issues are addressed in this revision:
1. For DELETE statement, the index information of the base table is not fetched so the indexes
   are not updated in a DELETE operation.
2. For both UPDATE and DELETE statements, the tuple description in the execution slot of the
   subplan that reads from the base table contains the junk "ybctid" and "wholerow" attributes and
   does not match the tuple being written. This causes ExecDeleteIndexTuples to read the old tuple
   columns incorrectly. To address this issue, ExecDeleteIndexTuples creates its own execution slot
   for the tuple instead.

Test Plan: yb_create_index

Reviewers: mihnea

Reviewed By: mihnea

Subscribers: neha, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D6471