[BACKPORT 2.16][DB-5855] xCluster Configuration - Data Type Missing in the Type.Java List
Summary:
Original diff: a3feedb5d461f1e49ca82c2d847c188de099e422 / D23620

This PR fixes the issue wherein we had a couple of datatypes missing (specifically because of a column of type oid) in the Type.java file because of which xCluster replication setup was failing with the error:

```
java.lang.IllegalArgumentException: The provided data type doesn't map to know any known one: yb.DataType
```

Test Plan:
Jenkins: java only

Added one more test to verify the fix:
```
ybd --java-test org.yb.pgsql.TestGetTableSchema
```

Reviewers: vpatibandla, abharadwaj

Reviewed By: abharadwaj

Subscribers: jenkins-bot, ybase, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D23840