Revert changes to copy tests introduced by fix for #12791
Summary:
The commit 6953c67c9427cb552cded04d2404dca39a509118 caused many PgRegressTests
to become flaky. They all  fail in an indeterministic manner with the following signature:
```
ERROR:  Query error: Restart read required at: { read: { physical: 1667610605837699 } local_limit: { physical: 1667610605837699 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
```
It is not clear what the root cause of the error is, and there were tests failing
with this signature before. However the addition of new tests to yb_pg_copy.source as part
of afore-mentioned commit has made the failure rate higher. yb_pg_copy.source is a dependency
for a large number of PgRegressTests.

Since this has caused a lot of tests to become flaky, revert the changes to
yb_pg_copy for now and bring it back after the underlying ReadRestart error is fixed.

Also revert D20720 (Commit fbee536c7fede05d32c271292108207679f520c8)
which was introduced because of the changes to yb_pg_copy

Test Plan:
./ybd --java-test org.yb.pgsql.TestPgRegressArrays -n 25 --tp 4
on Mac build
The test fails almost 100% of the time without this change and passes 100% of the time with the change.

./ybd --java-test org.yb.pgsql.TestPgRegressPgMisc -n 25 --tp 4
to test the revert of the changes to yb_pg_errors

Reviewers: jason, zyu

Reviewed By: jason, zyu

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D20908