[#28506] YSQL: Fix 'org.yb.pgsql.TestYsqlUpgrade#migratingIsEquivalentToReinitdb' to avoid prosqlbody
Summary:
If adding a new view, test fails as follows:

```
java.lang.AssertionError: Table 'pg_proc': Column #28 (prosqlbody) mismatch: ...
Expected row: Row[oid=java.lang.Long::1234567890,proname=java.lang.String::_pg_char_octet_length,pronamespace=java.lang.String::information_schema, ...
Actual row:   Row[oid=java.lang.Long::1234567890,proname=java.lang.String::_pg_char_octet_length,pronamespace=java.lang.String::information_schema, ...
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.yb.AssertionWrappers.lambda$0(AssertionWrappers.java:62)
	at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:46)
	at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:62)
	at org.yb.pgsql.BasePgSQLTest.assertRow(BasePgSQLTest.java:1503)
	at org.yb.pgsql.TestYsqlUpgrade.lambda$69(TestYsqlUpgrade.java:2037)
	at java.base/java.util.TreeMap.forEach(TreeMap.java:1002)
	at org.yb.pgsql.TestYsqlUpgrade.assertMigrationsWorked(TestYsqlUpgrade.java:1998)
	at org.yb.pgsql.TestYsqlUpgrade.migratingIsEquivalentToReinitdb(TestYsqlUpgrade.java:1112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The only difference between the expected and the actual row is in `funcid` which has shifted due to creation of the view.

This diff attempts to exclude prosqlbody column check for while comparing entries of pg_proc table.
Jira: DB-18192

Test Plan: ./yb_build.sh --java-test 'org.yb.pgsql.TestYsqlUpgrade#migratingIsEquivalentToReinitdb'

Reviewers: myang, asaha

Reviewed By: myang

Differential Revision: https://phorge.dev.yugabyte.com/D46538