[#15245] YSQL: Preserve table grants, policies, dependent views, statistics objects after ALTER TABLE ADD/DROP pkey
Summary:
In YB, when we alter a table's primary key, we rename the table, create a replacement table, migrate the old table's data and dependent objects, and then drop the old table (see D10057).

Currently, the migration to the replacement table may be incomplete as we don't account for some dependent objects/metadata:

1) Views/materialized views:
```
yugabyte=# CREATE TABLE test (id int);
CREATE TABLE
yugabyte=# CREATE VIEW test_v AS SELECT * FROM test;
CREATE VIEW
yugabyte=# CREATE MATERIALIZED VIEW test_mv AS SELECT * FROM test;
SELECT 0
yugabyte=# ALTER TABLE test ADD PRIMARY KEY (id); -- test_v and test_mv are dropped.
NOTICE: drop cascades to 2 other objects
DETAIL: drop cascades to materialized view test_mv
drop cascades to view test_v
ALTER TABLE
yugabyte=# SELECT * FROM test_v;
ERROR: relation "test_v" does not exist
LINE 1: SELECT * FROM test_v;
           ^
yugabyte=# SELECT * FROM test_mv;
ERROR: relation "test_mv" does not exist
LINE 1: SELECT * FROM test_mv;
           ^
```
2) Policies:
```
yugabyte=# CREATE TABLE test (id int);
CREATE TABLE
yugabyte=# CREATE POLICY dummy ON test;
CREATE POLICY
yugabyte=# SELECT * FROM pg_policy WHERE polrelid='test'::regclass::oid;
 polname | polrelid | polcmd | polpermissive | polroles | polqual | polwithcheck
---------+----------+--------+---------------+----------+---------+--------------
 dummy   |    16384 | *      | t             | {0}      |         |
(1 row)

yugabyte=# ALTER TABLE test ADD PRIMARY KEY (id); -- "dummy" policy is dropped.
ALTER TABLE
yugabyte=# SELECT * FROM pg_policy WHERE polrelid='test'::regclass::oid;
 polname | polrelid | polcmd | polpermissive | polroles | polqual | polwithcheck
---------+----------+--------+---------------+----------+---------+--------------
(0 rows)
```

3) Stats and extended stats objects:
```
yugabyte=# CREATE TABLE test(id int, t int);
CREATE TABLE
yugabyte=# INSERT INTO test VALUES (1, 1);
INSERT 0 1
yugabyte=# CREATE STATISTICS s1(dependencies) on id, t FROM test;
CREATE STATISTICS
yugabyte=# ANALYZE test;
ANALYZE
yugabyte=# SELECT * FROM pg_statistic_ext;
 stxrelid | stxname | stxnamespace | stxowner | stxkeys | stxkind | stxndistinct |             stxdependencies
----------+---------+--------------+----------+---------+---------+--------------+------------------------------------------
    16395 | s1      |         2200 |    13290 | 1 2     | {f}     |              | {"1 => 2": 1.000000, "2 => 1": 1.000000}
(1 row)

yugabyte=# SELECT starelid FROM pg_statistic;
 starelid
----------
    16395
    16395
(2 rows)

yugabyte=# ALTER TABLE test ADD PRIMARY KEY (id); -- s1 is dropped and entries in pg_statistic are deleted.
ALTER TABLE
yugabyte=# SELECT * FROM pg_statistic_ext;
 stxrelid | stxname | stxnamespace | stxowner | stxkeys | stxkind | stxndistinct | stxdependencies
----------+---------+--------------+----------+---------+---------+--------------+-----------------
(0 rows)

yugabyte=# SELECT starelid FROM pg_statistic;
 starelid
----------
(0 rows)
```

4) Other metadata like `pg_class.relacl`, `pg_class.relrowsecurity`, `pg_class.reltuples`, `pg_attribute.attstattarget`, `pg_attribute.attacl`:
```
yugabyte=# CREATE TABLE test(id int);
CREATE TABLE
yugabyte=# INSERT INTO test VALUES (1);
INSERT 0 1
yugabyte=# ANALYZE test;
ANALYZE
yugabyte=# ALTER TABLE test ENABLE ROW LEVEL SECURITY;
ALTER TABLE
yugabyte=# CREATE USER user1;
CREATE ROLE
yugabyte=# CREATE USER user2;
CREATE ROLE
yugabyte=# GRANT ALL ON test TO user1;
GRANT
yugabyte=# GRANT SELECT (id) ON test TO user2;
GRANT
yugabyte=# ALTER TABLE test ALTER id SET STATISTICS 123;
ALTER TABLE
yugabyte=# SELECT relacl, relrowsecurity, reltuples FROM pg_class WHERE oid='test'::regclass::oid;
                       relacl                       | relrowsecurity | reltuples
----------------------------------------------------+----------------+-----------
 {yugabyte=arwdDxt/yugabyte,user1=arwdDxt/yugabyte} | t              |         1
(1 row)

yugabyte=# SELECT attstattarget, attacl FROM pg_attribute WHERE attrelid='test'::regclass::oid AND attname='id';
 attstattarget |       attacl
---------------+--------------------
           123 | {user2=r/yugabyte}
(1 row)

yugabyte=# ALTER TABLE test ADD PRIMARY KEY (id);
ALTER TABLE
yugabyte=# SELECT relacl, relrowsecurity, reltuples FROM pg_class WHERE oid='test'::regclass::oid;
 relacl | relrowsecurity | reltuples
--------+----------------+-----------
        | f              |         0
(1 row)

yugabyte=# SELECT attstattarget, attacl FROM pg_attribute WHERE attrelid='test'::regclass::oid AND attname='id';
 attstattarget | attacl
---------------+--------
            -1 |
(1 row)

```

This diff fixes the above as follows:

1) Views and materialized views: Before we rename the old table, we keep track of the table's dependent views and their underlying queries (deparsed). Then, before dropping the old table, we replace the views' queries with the deparsed queries that we previously stored. Since the new table has the old table's original name, the deparsed queries would now be referencing the new table.

2) Policy objects and grants: Recreate these for the replacement table. Copy old table's `pg_class.relacl`, `pg_class.relrowsecurity` values and its attributes' `pg_attribute.attacl` values.

3) Stats and extended stat. objects: Recreate extended stat. objects for the new table and insert copies of the old table's `pg_statistic` entries with the updated `starelid` and `stattnum` values. Copy old table's attributes' `pg_attribute.attstattarget` values.

4) Other metadata: Copy old table's `pg_class.relacl`, `pg_class.relrowsecurity`, `pg_class.reltuples` and its attributes' `pg_attribute.attacl`, `pg_attribute.attstattarget` values.

Relevant doc: https://docs.google.com/document/d/1KR6ufOBOKZ1itH65f_dAEacDkny78rb_zSMMcEkigQ0/edit

Test Plan:
`./yb_build.sh --java-test 'org.yb.pgsql.TestPgAlterTableChangePrimaryKey'`

Specifically,
for views/materialized views: TestPgAlterTableChangePrimaryKey#viewsAndMaterializedViews
for policies and permissions: TestPgAlterTableChangePrimaryKey#policiesAndPermissions
for stats and extended stats objects: TestPgAlterTableChangePrimaryKey#statistics
for other metadata: covered by the previous tests - `pg_class.relacl`, `pg_class.attacl` and `pg_class.relrowsecurity` in policiesAndPermissions and `pg_class.reltuples` and `pg_class.attstattarget` in statistics

Reviewers: dmitry, jason, alex, myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D22344