[#7534] YSQL: Support ALTER TABLE ADD PRIMARY KEY for colocated tables
Summary:
Currently for a table in a colocated database or in a tablegroup,
altering table to add primary key fails with the following error,

CREATE DATABASE clc WITH colocated = true;
CREATE DATABASE
You are now connected to database "clc" as user "yugabyte".
CREATE TABLE nopk_c (id int);
CREATE TABLE
INSERT INTO nopk_c VALUES (3);
INSERT 0 1
INSERT INTO nopk_c VALUES (4);
INSERT 0 1
clc=# ALTER TABLE nopk_c ADD PRIMARY KEY (id);
ALTER TABLE nopk_c ADD PRIMARY KEY (id);
ERROR:  adding primary key to a colocated table is not yet implemented

Since we now support add primary key, we can remove this error.
The existing tests already have some test code paths for the cases
once the above error is removed and they are now enabled.

Also fixed a potential null pointer SEGV in get_tablegroup_name when
the tuple is not found.

Test Plan:
ybd debug --verbose --java-test org.yb.pgsql.TestPgAlterTableAddPrimaryKey
ybd debug --verbose --java-test org.yb.pgsql.TestPgRegressTablegroup

Reviewers: mihnea, dsrinivasan, alex

Reviewed By: alex

Differential Revision: https://phabricator.dev.yugabyte.com/D11069