[pg15] fix: CREATE TABLE LIKE INCLUDING INDEXES
Summary:
CREATE TABLE LIKE INCLUDING INDEXES has YB-specific logic to get the pk
constraint so that by the time of DefineRelation, it can be used to
create the main table appropriately based on PK.  Upstream PG
50289819230d8ddad510879ee4793b04a05cf13b changes the order of operations
so that the pk information is calculated later after DefineRelation in
new expandTableLikeClause.  YB pg15 initial merge
55782d561e55ef972f2470a4ae887dd791bb4a97 tries to adapt to this change
by collecting the pk information in the new expandTableLikeClause, but
that is not sufficient as it is too late by that point.

YB master:
- ProcessUtilitySlow
  - transformCreateStmt
    - transformTableLikeClause
      - if ((table_like_clause->options & CREATE_TABLE_LIKE_INDEXES) && relation->rd_rel->relhasindex)
        - cxt->yb_likepkconstraint = lappend(cxt->yb_likepkconstraint, primary_key);
    - stmt->constraints = list_concat(stmt->constraints, cxt.yb_likepkconstraint);
  - DefineRelation

YB pg15 (before this change):
- ProcessUtilitySlow
  - **yb_constraints = &stmt->constraints
  - transformCreateStmt
    - transformTableLikeClause
      - if (table_like_clause->options & (CREATE_TABLE_LIKE_DEFAULTS | CREATE_TABLE_LIKE_GENERATED | CREATE_TABLE_LIKE_CONSTRAINTS | CREATE_TABLE_LIKE_INDEXES))
        - cxt->likeclauses = lappend(cxt->likeclauses, table_like_clause);
    - cxt.alist = list_concat(cxt.alist, cxt.likeclauses);
    - result = lappend(cxt.blist, stmt); result = list_concat(result, cxt.alist); result = list_concat(result, save_alist);
  - DefineRelation
  - expandTableLikeClause
    - *yb_constraints = lappend(*yb_constraints, primary_key);

According to the PG commit, the order change is due to a bug related to
table inheritance, which YB currently doesn't support.  But even if YB
did support it, according to the commit message, it doesn't seem to
affect PK indexes.  So resurrect the operations that used to exist in
order to get the PK constraint early in transformTableLikeClause as
before.

YB pg15 (after this change):
- ProcessUtilitySlow
  - transformCreateStmt
    - transformTableLikeClause
      - if (table_like_clause->options & (CREATE_TABLE_LIKE_DEFAULTS | CREATE_TABLE_LIKE_GENERATED | CREATE_TABLE_LIKE_CONSTRAINTS | CREATE_TABLE_LIKE_INDEXES))
        - cxt->likeclauses = lappend(cxt->likeclauses, table_like_clause);
      - if (IsYugaByteEnabled() && (table_like_clause->options & CREATE_TABLE_LIKE_INDEXES) && relation->rd_rel->relhasindex)
        - *yb_pk_constraint = primary_key;
    - cxt.alist = list_concat(cxt.alist, cxt.likeclauses);
    - stmt->constraints = lappend(stmt->constraints, yb_like_clause_pk_constraint);
    - result = lappend(cxt.blist, stmt); result = list_concat(result, cxt.alist); result = list_concat(result, save_alist);
  - DefineRelation
  - expandTableLikeClause

Test Plan:
Regress test yb_pg_create_table_like of Java test TestPgRegressTable
should now get

    ERROR:  duplicate key value violates unique constraint "inhg_pkey"

as expected.

Jenkins: rebase: pg15

Reviewers: aagrawal, tfoucher

Reviewed By: aagrawal

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D33965