[#27597] YSQL: Guard against usage of stale/ inconsistent catalog cache
Summary:
Without object locking enabled (controlled by the gflag `enable_object_locking_for_table_locks`), catalog caches on PG backends can be stale because invalidation messages corresponding to newer catalog versions are processed sometime after they are received over heartbeats (which is an async mechanism). So, new DDLs might not wait and purge the catalog cache before executing on a table. With object locking, a catalog cache is purged based on invalidation messages after a lock on the table(s) being operated on are acquired (see 9891ccbf7c).

This can lead to issues such as:

```
Session 1:
                                                                               Session 2:
                                                                               create table t1(i int);
SELECT * from test;
-- catalog cache populated for test
                                                                               ALTER TABLE t1 add column new bigint; --> increments catalog version to 4
                                                                               -- Alter succeeds.
ALTER TABLE t1 alter column new type smallint;
-- Alter succeeds.

Consider the case when the heartbeat with catalog version 4
is yet to arrive from master. So, this PG backend doesn't have
information about the new column ABC in the cache. When doing
the alter type, it fetches the pg_attribute entry for this new column
and makes the necessary changes. When writing back the changes
to the system catalog, it uses the cached pg_class entry to prepare
the new pg_class record. And the cache entry has a relnatts of 1
and not 2. So relnatts is overwritten to 1 again.

SELECT COUNT(*) from t1; ------> on some other session 3 fails. Every new connection creation also fails with this error.
ERROR:  invalid attribute number 2 for t1
```

### Fix

If `yb_fail_catalog_write_on_catalog_version_mismatch` is enabled, catalog writes performed as part of DDLs will check if the local catalog version of the PG backend issuing the write is the same as the latest catalog version on master. If the catalog version is different, the cache on the PG backend could be stale and a catalog version mismatch error is thrown. This avoids a catalog corruption.

The check is disabled if object locking is enabled. There was a weaker form of catalog version check (with breaking version only) for reads/ writes to user tables -- that too was disabled if object locking is turned on (ab5bdf78).

Further, this gflag is off by default because it has an undesired effect that auto-ANALYZE might cause a concurrent legitimate DDL on unrelated object(s) to face this version mismatch error.

### Other changes:

Earlier yb-master didn't override the `Read()` rpc. It was using `TabletServiceImpl::Read()` and it would in turn call the master versions of `GetTabletForRead()` or `SkipCatalogVersionChecks()` which would result in calling `SCOPED_LEADER_SHARED_LOCK`. After this change, `MasterTabletServiceImpl::Write()` also calls `SkipCatalogVersionChecks()`. However, `MasterTabletServiceImpl::Write()` already calls `SCOPED_LEADER_SHARED_LOCK`, so re-acquiring the lock in `SkipCatalogVersionChecks()` results in a FATAL. Specifically, `RWMutex::CheckLockState` in `RWMutex::TryReadLock()` expects `LockState::NEITHER` as the state, but a read lock is already acquired. This patch introduces `MasterTabletServiceImpl::Read()` that acquires the shared lock on catalog manager and gets rid of the `SCOPED_LEADER_SHARED_LOCK` calls in `SkipCatalogVersionChecks()` and `GetTabletForRead()`.

Further, the YQLVirtualTable::GetIterator function was taking a `SCOPED_LEADER_SHARED_LOCK`. This changes remove that too because we now already have the lock acquired in the master read rpc entry point.

Test Plan: ./yb_build.sh release --java-test org.yb.pgsql.TestPgRegressDDLIsolationNoTxnDDLNoObjectLocking#testWithHighHeartbeatDelay

Reviewers: sanketh, myang

Reviewed By: sanketh

Subscribers: ybase, rthallam, zdrudi, smishra, jason, yql

Differential Revision: https://phorge.dev.yugabyte.com/D45073