[#29686] YSQL: Fix InsertIntoContainer specialization
Summary:
The `InsertIntoContainer`'s specialization for the `boost::container::small_vector` is invalid because second template parameter has the `size_t` type (i.e. is is non-type template parameter ) and `class... Args` can't be used for this kind of parameters.

This diff reimplements the `InsertIntoContainer` template. Now function is implemented for containers which has `emplace_back` or `emplace` methods.

**Note:**
Auxiliary variable `dependent_false` is used for `static_assert` to simplify the compilation error message in case of using unsupported class

```
error: static assertion failed due to requirement 'dependent_false': InsertIntoContainer is not supported for this container type.
```

vs

```
error: static assertion failed due to requirement 'sizeof(std::unordered_map<int, int, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, int>>>) == 0': InsertIntoContainer is not supported for this container type.
```

Test Plan: Jenkins

Reviewers: sergei, arybochkin, timur, esheng, hsunder

Reviewed By: sergei

Subscribers: ybase, yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D49015