[yugabyted] Fix crash in yugabyted when run by python3 and YBAdminProxy.get_cluster_rf() returns None.
Summary:
yugabyted uses this expression to print the status bar:

```
status += ("| {:" + str(20 + extra_len) + "}: {:<82} |\n").format(k, v)
```

On my dev-server I observed crashes when the cluster was down and I ran `yugabyted status`:
```
[zdrudi@dev-server-zdrudi yugabyte-db]$ ./bin/yugabyted status
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 2352, in run
    args.func()
  File "./bin/yugabyted", line 369, in status
    Output.print_out(self.get_status_string())
  File "./bin/yugabyted", line 1832, in get_status_string
    status += ("| {:" + str(20 + extra_len) + "}: {:<82} |\n").format(k, v)
TypeError: unsupported format string passed to NoneType.__format__
```
I didn't see this crash on my macbook, though. I believe the issue is a python version change. On OS X running "python" on a default shell will run python2. However on my dev server "python" runs python3.

There is different behaviour between python2 and python3 on string formatting.

```
% python3
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "{:<82}".format(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to NoneType.__format__
```

```
% python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 19 2020, 20:48:48)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "{:<82}".format(None)
'None                                                                              '
```

Test Plan: Ran on my dev server. Crash no longer observed.

Reviewers: sanketh, sgarg-yb, nikhil

Reviewed By: nikhil

Subscribers: nikhil

Differential Revision: https://phabricator.dev.yugabyte.com/D19305