ysql: add newline b/w errmsg and YBCGetStackTrace
Summary:
`YBCGetStackTrace` is appended to ysqlsh error messages when
`yb_debug_report_error_stacktrace` is on.  It looks a bit ugly because
the top frame, `YBCGetStackTrace`, is printed on the same line as the
error message.  Add a newline to separate the message and stack trace.

Test Plan:
    ./bin/ysqlsh <<EOT
    set yb_debug_report_error_stacktrace = on;
    abc;
    EOT

expect

    SET
    ERROR:  syntax error at or near "abc"
        @     0x7f65a8bc794f  YBCGetStackTrace (src/yb/common/ybc_util.cc:292)
        @           0x9ba2db  errmsg (src/postgres/src/backend/utils/error/elog.c:868)
    ...

not

    SET
    ERROR:  syntax error at or near "abc"    @     0x7fd9ad4dd351  YBCGetStackTrace (src/yb/common/ybc_util.cc:292)
        @           0x9b9788  errmsg (src/postgres/src/backend/utils/error/elog.c:868)
    ...

Reviewers: mihnea, mbautin

Reviewed By: mbautin

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D12012