[#8249] YSQL: Allow any hash column in index to be an expression based column
Summary:
- Rearrange the grammar rules to allow a group of expressions for HASH while limiting the ASC/DESC sort option to accept a standalone expression.
- Directly create the IndexElem objects for an expression group instead of adding each column name/expression to IndexElem.yb_name_list then expanding it in another grammar rule.
- Treat an index key expression list as a HASH key by default. This helps avoid obscure error in the situations such as the following:

1. A column group specified as the first index key item
```
CREATE INDEX ON test_method ((h2, h1), r2 DESC, r1);
```
before: it was erroneously rejected
```
ERROR:  only hash column group is allowed
LINE 1: ...ATE INDEX test_method_h2_h1_r2_r1_idx ON test_method ((h2, h1), ...
```

after: no error, (h2, h1) accepted as the hash key.
```
    "test_method_h2_h1_r2_r1_idx" lsm ((h2, h1) HASH, r2 DESC, r1 ASC)
```

2. A column group specified as non-first key item
```
CREATE INDEX ON test_method (r1 DESC, (h2, h1));
```
before:

```
ERROR:  syntax error at or near ","
LINE 1: CREATE INDEX ON test_method (r1 DESC, (h2, h1));
                                                 ^
```
after:
```
ERROR:  hash column not allowed after an ASC/DESC column
LINE 1: CREATE INDEX ON test_method (r1 DESC, (h2, h1));
                                              ^
```

Test Plan:
- Manual tests
-- Reported test case
-- CREATE INDEX combinations with single/multiple column/expression with/without explicit HASH keyword
- Add test cases to yb_create_index.sql.

Reviewers: dsrinivasan, rskannan, mihnea

Reviewed By: mihnea

Subscribers: myang, jason, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D11860