[#26127] DocDB: Invalidate db table cache on release of exclusive object locks
Summary:
Commit https://github.com/yugabyte/yugabyte-db/commit/47c5cf2fc56ebd0d7deb8b8a06731fd63c07adbc introduced mechanism for release of exclusive object locks that are taken as part of DDL execution.

This revision builds on top of the above path and adds mechanism to invalidate db table cache on all tservers as part of the exclusive locks release, essentially invalidating the cache early as opposed to waiting for the subsequent tserver-master heartbeat to do it.

Note - This invalidation uses the existing tserver cache invalidation mechanism, and so the master ends up sending a full update for all the dbs. This can be optimized to send version of the db touched by the ddl alone. This work is tracked by https://github.com/yugabyte/yugabyte-db/issues/26451.

**Upgrade/Downgrade safety**
1. `ReleaseObjectLockRequestPB` & `SysObjectLockEntryPB` are protected by test flag which is disabled by default.
2. `YsqlCatalogVersionPB` & `DBCatalogVersionDataPB` were moved to a different file but were not modified.
Jira: DB-15454

Test Plan:
Jenkins: urgent

./yb_build.sh --cxx-test='TEST_F(ExternalObjectLockTest, ExclusiveLockReleaseInvalidatesCatalogCache) {'
./yb_build.sh --cxx-test='TEST_F(ExternalObjectLockTest, ConsecutiveAltersSucceedWithoutCatalogVersionIssues) {'

1. The first test fails when table locking feature is disabled. Take away is that with the table locking feature, statements wouldn't hit the retry statements due to schema/catalog version mismatch path because we end up invalidating the catalog cache early (exclusive object lock release path as opposed to tserver-master heartbeat path).
2. Without the feature, the second test occasionally fails with the following error when a higher value for tserver-master heartbeat interval is used. With changes in this revision, the test always passes.
```
yugabyte=# alter table t1 add column c4 int;
ERROR:  duplicate key value violates unique constraint "pg_attribute_relid_attnum_index"
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

Reviewers: amitanand, zdrudi, rthallam, myang

Reviewed By: zdrudi, myang

Subscribers: sanketh, ybase, yql

Differential Revision: https://phorge.dev.yugabyte.com/D42539