[pg15] fix: "could not determine which collation"
Summary:
Multiple tests fail with the following message:

    ERROR:  could not determine which collation to use for string hashing
    HINT:  Use the COLLATE clause to set the collation explicitly.

The failing code is YB code introduced by YB pg15
161efd6fe7dfa52896dd7e5c0c8641082ab4ef1d with the following terse
explanation:

> PG introduced support for collation in the hashing functions (https://github.com/postgres/postgres/commit/5e1963fb764e9cc092e0f7b58b28985c311431d9). This diff disables it for YB (this is open for review).

Following up with Arpan, this was done because hashtable->tab_collations
is NULL in YB.  But the way it was carried out was flawed because it
substituted with InvalidOid rather than DEFAULT_COLLATION_OID as done in
other areas in the relevant upstream PG commit
5e1963fb764e9cc092e0f7b58b28985c311431d9.  Fix that.

Update tests:

- TestPg15Regress: add test case in yb_pg15 regress test.
- test_types_string.sh: yb_pg_collate now passes because it previously
  failed at four places all due to this error.
- test_D29546.sh: TestPgPrefetchControl#testLimitPerformance now passes.
  This wasn't explicitly tested as failing before because the
  granularity was only at the top level TestPgPrefetchControl, not the
  four subtests under it.  Split it up to be more granular to expect some
  of those subtests to pass and the others to fail with specific failure
  messages.

Test Plan:
On Almalinux 8:

    #!/usr/bin/env bash
    set -e
    ./yb_build.sh fastdebug --gcc11
    pg15_tests/run_shell_tests.sh fastdebug --gcc11

Jenkins: rebase: pg15

Reviewers: aagrawal

Reviewed By: aagrawal

Subscribers: tfoucher, yql

Differential Revision: https://phorge.dev.yugabyte.com/D31395