[#6500] Platform: DB safe guard: implement version-id
Summary: The cluster config version ID should be incremented whenever there is a corresponding change in YW for the universe metadata. This is to protect against restoring a stale platform backup that has incorrect universe metadata and then performing some operation on the universe that causes more issues due to the incorrect information.

Test Plan:
Run through various universe operations and ensure nothing fails and that the cluster config version always matches the universe version. Manually change the universe version and try and run an operation, verify that it fails. Manually change the universe version to -1 to test backwards compatibility, run an operation and see that it succeeds and that the universe version is set to the cluster config version moving forwards.

Example of stacktrace when the universe version doesn't match the cluster config version:

```
2020-12-02 14:45:49.398 ERROR SetUniverseKey.java:54 [TaskPool-1] Error executing task SetUniverseKey(eba1d294-56ca-44a7-bb00-5b7122420f39), error='Universe version does not match cluster config version'
java.lang.RuntimeException: Universe version does not match cluster config version
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.checkUniverseVersion(UniverseTaskBase.java:1198)
	at com.yugabyte.yw.commissioner.tasks.SetUniverseKey.run(SetUniverseKey.java:33)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Reviewers: sanketh, sb-yb, arnav, spotachev

Reviewed By: spotachev

Subscribers: yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D10016