[#12736] DocDB: Remove master library from yb-tserver executable
Summary:
yb-tserver was linked to master as part of the call_home addition. call_home was acting as a god class that could run on both master and tserver RpcServers and access all their internal members.
It also was causing yb-tserver to inherit all catalog_manager gFlags, even the ones that it does not need.
Removed the link and converted call_home to a partial class that handles generic RpcServer collectors, and moved master and tserver specific collectors to master_call_home and tserver_call_home respectively.

Moved start_pgsql_proxy to tablet_server_main so that its not included in yb-master. Moved gflags from common to master: cluster_uuid in yugabyted and replication_factor in MiniYBCluster.java

Some tests were incorrectly setting gFlags on tserver that is never used. Since now these flags are completely removed it throws an error
```
ERROR: unknown command line flag

```
These tests have been fixed.

This removed 43 Test and 135 prod flags from yb-tserver:
TEST_crash_during_sys_catalog_restoration
TEST_disable_cdc_state_insert_on_setup
TEST_exit_unfinished_deleting
TEST_exit_unfinished_merging
allow_consecutive_restore
cdc_state_table_num_tablets
cdc_wal_retention_time_secs
check_bootstrap_required
disable_universe_gc
enable_replicate_transaction_status_table
enable_transaction_snapshots
master_backup_svc_queue_length
TEST_slowdown_master_async_rpc_tasks_by_ms
retrying_ts_rpc_max_delay_ms
unresponsive_ts_rpc_retry_limit
unresponsive_ts_rpc_timeout_ms
TEST_slowdown_backfill_alter_table_rpcs_ms
TEST_slowdown_backfill_job_deletion_ms
defer_index_backfill
index_backfill_rpc_max_delay_ms
index_backfill_rpc_max_retries
index_backfill_rpc_timeout_ms
index_backfill_tablet_split_completion_poll_freq_ms
index_backfill_tablet_split_completion_timeout_sec
index_backfill_wait_for_alter_table_completion_ms
ysql_index_backfill_rpc_timeout_ms
TEST_slow_cluster_config_load_secs
master_ignore_deleted_on_load
TEST_catalog_manager_check_yql_partitions_exist_for_is_create_table_done
TEST_catalog_manager_simulate_system_table_create_failure
TEST_consider_all_local_transaction_tables_local
TEST_crash_after_creating_single_split_tablet
TEST_crash_server_on_sys_catalog_leader_affinity_move
TEST_create_table_leader_hint_min_lexicographic
TEST_delay_sys_catalog_reload_secs
TEST_disable_tablet_deletion
TEST_fault_crash_after_registering_split_children
TEST_hang_on_namespace_transition
TEST_inject_latency_during_remote_bootstrap_secs
TEST_inject_latency_during_tablet_report_ms
TEST_name_transaction_tables_with_tablespace_id
TEST_reject_delete_not_serving_tablet_rpc
TEST_return_error_if_namespace_not_found
TEST_sequential_colocation_ids
TEST_simulate_crash_after_table_marked_deleting
TEST_simulate_slow_system_tablet_bootstrap_secs
TEST_simulate_slow_table_create_secs
TEST_skip_placement_validation_createtable_api
TEST_slowdown_alter_table_rpcs_ms
TEST_tablegroup_master_only
TEST_validate_all_tablet_candidates
auto_create_local_transaction_tables
blacklist_progress_initial_delay_secs
catalog_manager_check_ts_count_for_create_table
catalog_manager_inject_latency_in_delete_table_ms
catalog_manager_report_batch_size
catalog_manager_wait_for_new_tablets_to_elect_leader
cluster_uuid
disable_index_backfill
disable_index_backfill_for_non_txn_tables
disable_truncate_table
enable_delete_truncate_xcluster_replicated_table
enable_register_ts_from_raft
enable_transactional_ddl_gc
enable_truncate_on_pitr_table
enable_ysql_tablespaces_for_placement
heartbeat_safe_deadline_ratio
hide_pg_catalog_table_creation_logs
master_drop_table_after_task_response
master_enable_metrics_snapshotter
master_failover_catchup_timeout_ms
master_ignore_stale_cstate
master_tombstone_evicted_tablet_replicas
master_ts_rpc_timeout_ms
max_create_tablets_per_ts
metrics_snapshots_table_num_tablets
partitions_vtable_cache_refresh_secs
replication_factor
tablet_creation_timeout_ms
tablet_force_split_threshold_bytes
tablet_split_high_phase_shard_count_per_node
tablet_split_high_phase_size_threshold_bytes
tablet_split_low_phase_shard_count_per_node
tablet_split_low_phase_size_threshold_bytes
tablet_split_size_threshold_bytes
transaction_table_num_tablets
transaction_table_num_tablets_per_tserver
txn_table_wait_min_ts_count
use_create_table_leader_hint
ysql_tablespace_info_refresh_secs
TEST_pause_catalog_manager_bg_loop_end
TEST_pause_catalog_manager_bg_loop_start
catalog_manager_bg_task_wait_ms
load_balancer_initial_delay_secs
sys_catalog_respect_affinity_task
balancer_load_max_standard_deviation
TEST_load_balancer_handle_under_replicated_tablets_only
TEST_load_balancer_wait_after_count_pending_tasks_ms
allow_leader_balancing_dead_node
enable_global_load_balancing
enable_load_balancing
leader_balance_threshold
leader_balance_unresponsive_timeout_ms
load_balancer_count_move_as_add
load_balancer_drive_aware
load_balancer_ignore_cloud_info_similarity
load_balancer_max_concurrent_adds
load_balancer_max_concurrent_moves
load_balancer_max_concurrent_moves_per_table
load_balancer_max_concurrent_removals
load_balancer_max_concurrent_tablet_remote_bootstraps
load_balancer_max_concurrent_tablet_remote_bootstraps_per_table
load_balancer_max_over_replicated_tablets
load_balancer_num_idle_runs
load_balancer_skip_leader_as_remove_victim
transaction_tables_use_preferred_zones
hide_dead_node_threshold_mins
TEST_master_extra_list_host_port
master_consensus_svc_num_threads
master_consensus_svc_queue_length
master_remote_bootstrap_svc_num_threads
master_remote_bootstrap_svc_queue_length
master_rpc_timeout_ms
master_svc_num_threads
master_svc_queue_length
master_tserver_svc_num_threads
master_tserver_svc_queue_length
master_yb_client_default_timeout_ms
TEST_timeout_non_leader_master_rpcs
TEST_master_fail_transactional_tablet_lookups
master_inject_latency_on_tablet_lookups_ms
master_slow_get_registration_probability
tablet_report_limit
create_cluster
master_addresses
master_replication_factor
TEST_delay_sys_catalog_restore_on_followers_secs
TEST_skip_sending_restore_finished
schedule_restoration_rpcs_out_of_band
schedule_snapshot_rpcs_out_of_band
skip_crash_on_duplicate_snapshot
snapshot_coordinator_poll_interval_ms
TEST_ysql_catalog_write_rejection_percentage
max_concurrent_restoration_rpcs
max_concurrent_restoration_rpcs_per_tserver
master_leader_lock_stack_trace_ms
master_log_lock_warning_ms
max_concurrent_snapshot_rpcs
max_concurrent_snapshot_rpcs_per_tserver
snapshot_coordinator_cleanup_delay_ms
TEST_mark_snasphot_as_failed
TEST_sys_catalog_write_rejection_percentage
copy_tables_batch_bytes
notify_peer_of_removal_from_cluster
sys_catalog_write_timeout_ms
create_initial_sys_catalog_snapshot
enable_ysql
initial_sys_catalog_snapshot_path
master_auto_run_initdb
use_initial_sys_catalog_snapshot
enable_tablet_split_of_pitr_tables
enable_tablet_split_of_xcluster_replicated_tables
max_queued_split_candidates
outstanding_tablet_split_limit
outstanding_tablet_split_limit_per_tserver
prevent_split_for_small_key_range_tablets_for_seconds
prevent_split_for_ttl_tables_for_seconds
process_split_tablet_candidates_interval_msec
sort_automatic_tablet_splitting_candidates
tablet_split_limit_per_table
long_term_tasks_tracker_keep_time_multiplier
tasks_tracker_keep_time_multiplier
tasks_tracker_num_long_term_tasks
tasks_tracker_num_tasks
tserver_unresponsive_timeout_ms
generate_partitions_vtable_on_changes
use_cache_for_partitions_vtable
ysql_transaction_bg_task_wait_ms

Fixes #12736

Test Plan:
MasterTest.TestCallHome
MasterTest.TestCallHomeFlag
TabletServerTest.TestCallHome
TabletServerTest.TestCallHomeFlag
dependency_graph:
test_master_main, test_tablet_server_main, test_call_home, test_catalog_manager

Verified Cluster creation in various modes do not use undefined flags:
./bin/yb-ctl create
./bin/yugabyted create
Platform Deployment
K8 Platform Deployment

./yb_build.sh release --lto full
export YB_LINUXBREW_DIR=/opt/yb-build/brew/linuxbrew-20181203T161736v9
 ./build-support/tserver_lto.sh

Reviewers: bogdan, sergei, jhe, mbautin

Reviewed By: mbautin

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D17858