[BACKPORT 2025.1.0][#27024] YSQL: Handle correctness issues with sequences in Connection Manager
Summary:
When connection manager is enabled such that it provides support for sequences using: `ysql_conn_mgr_sequence_support_mode=pooled_with_currval_lastval`
there is a gap in implementation which can lead to errors for the client. Here is an example scenario:

```
yugabyte=# select nextval('my_seq');
 nextval
---------
       1
(1 row)

-- Logical connection switches to a physical connection where nextval('my_seq') was never fired
yugabyte=# select currval('my_seq');
ERROR:  currval of sequence "my_seq" is not yet defined in this session
```

This behaviour is altered for this particular value of the flag `ysql_conn_mgr_sequence_support_mode` to instead report predetermined values:
- currval returns the start value of the sequence if no nextval calls were made for the relevant sequence on that physical connection
- lastval returns 0 if no nextval calls were made on any sequence on that physical connection

Jira: DB-16497

No merge conflicts while raising this diff

Original commit: 417758faed2098671921db899b2ef3faaaefdc38 / D43779

Test Plan: Jenkins: all tests

Reviewers: skumar, mkumar, asrinivasan, stiwary

Reviewed By: asrinivasan

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D45056