[BACKPORT 2024.2][#25976] YSQL: Send serialized expression version in DocDB request
Summary:
Original commit: 5275733aebd4162214513632c92fc112c7b43433 / D42054

Backport changes:
* PgGate's AddQual clause was refactored after 2024.2. Move the expression version setting to the
  read op initialization.
* `PG_MAJORVERSION_NUM` does not exist in PG11. Replace the constant with a hardcoded `11`. This
  change only exists in 2024.2 and there's no risk that 2024.2 will change major versions.

Send `expression_serialization_version` in requests to DocDB, equal to either the current version or the major version compatibility mode. Docdb passes down the version number until the spot where the expression is deserialized, so that we can properly handle each possible case.

Additionally, before this diff, `GetCurrentPgVersion` used substrings + stroi to get the current version from the version string. Using PG_MAJORVERSION_NUM gives just the number we are interested in, allowing some code to be removed and eliminating the need for some of the error handling.

**Upgrade/Rollback safety:**
DocDB doesn't require this field, so it is upgrade safe.
Jira: DB-15310

Test Plan:
Apply the patch
```lang=diff
diff --git src/postgres/src/backend/executor/ybExpr.c src/postgres/src/backend/executor/ybExpr.c
index b220d83d20..1f79062c9e 100644
--- src/postgres/src/backend/executor/ybExpr.c
+++ src/postgres/src/backend/executor/ybExpr.c
@@ -499,8 +499,7 @@ YbCanPushdownExpr(Expr *pg_expr, List **colrefs)
         * Respond with false if pushdown disabled in GUC, or during a YSQL major
         * upgrade.
         */
-       if (!yb_enable_expression_pushdown ||
-               yb_major_version_upgrade_compatibility > 0)
+       if (!yb_enable_expression_pushdown)
                return false;

        return !yb_pushdown_walker((Node *) pg_expr, colrefs);
diff --git src/yb/yql/pgwrapper/pg_wrapper.cc src/yb/yql/pgwrapper/pg_wrapper.cc
index 4da11001b6..8dd5417e60 100644
--- src/yb/yql/pgwrapper/pg_wrapper.cc
+++ src/yb/yql/pgwrapper/pg_wrapper.cc
@@ -334,7 +334,6 @@ DEFINE_NON_RUNTIME_PG_PREVIEW_FLAG(bool, yb_enable_query_diagnostics, false,
 DEFINE_RUNTIME_PG_FLAG(int32, yb_major_version_upgrade_compatibility, 0,
     "The compatibility level to use during a YSQL Major version upgrade. Allowed values are 0 and "
     "11.");
-DEFINE_validator(ysql_yb_major_version_upgrade_compatibility, FLAG_IN_SET_VALIDATOR(0, 11));

 DECLARE_bool(enable_pg_cron);
```

This removes validation from `ysql_yb_major_version_upgrade_compatibility` and allows expression pushdown to still occur when compatibility mode is enabled. This will be possible when some pushdowns are allowed (#25973).

```lang=sql
CREATE TABLE t (a INT);
INSERT INTO t VALUES (1);
```

**Basic case (PG11 version)**

```lang=sql
SET yb_debug_log_docdb_requests = true;
SELECT * FROM t WHERE a = 1;
```

```
Applying operation: { READ active: 1 read_time: ... expression_serialization_version: 11 }
```

**Invalid Version Case**
./build/latest/bin/yb-ts-cli set_flag --server_address 127.0.0.1:9100 --force ysql_yb_major_version_upgrade_compatibility 10

```lang=sql
SET yb_debug_log_docdb_requests = true;
SELECT * FROM t WHERE a = 1;
ERROR:  Unsupported expression version: 10
```

```
Applying operation: { READ active: 1 read_time: ... expression_serialization_version: 10 }
```

Reviewers: hsunder, fizaa

Reviewed By: hsunder

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D42499