[PG15] YSQL: Change to sdiff for side-by-side diffs
Summary:
git cherry-pick of commit 10c3e050d049db7f1d22a66e7c9c65845fe223a7 from master branch.

On MacOS, `diff` appears to have a bug:
```
$ cat > a.txt
1234567890
^D
$ cat > b.txt
^D
$ diff --width=33 --side-by-side a.txt b.txt
1234567890    <
$ diff --width=34 --side-by-side a.txt b.txt
123456789       <
```

The test referenced in the test plan suffers from this problem on my MacOS workstation, showing an error in the sanity checks that's caused by clipping of the LHS. More generally, the unpredictable truncation of one character when getting more space to work with could lead to flakiness. In the referenced test, still using `diff` instead of `sdiff`, changing the extra space from 12 to 14 works, but changing it to 13 doesn't.

`sdiff` doesn't seem to have this problem, after I've tried it out on a number of cases and with many different widths.

Test Plan:
On a Mac, run the following:
```
./yb_build.sh --java-test 'org.yb.pgsql.TestYsqlDump#ysqlDumpWithYbMetadata'
```

This test is broken in PG15, so it will fail with or without this change. However, with this change, the failure will look something like:
```
expected:<SET [client_min_messages = warning];> but was:<SET [xmloption = content];>
```
Rather than the confusing output:
```
java.lang.RuntimeException: SideBySideDiff sanity check failed: line 280 from the lhs file is
SPLIT AT VALUES ((1000), (5000), (10000), (15000), (20000), (25000), (30000), (35000), (55000), (85000), (110000), (150000), (250000), (300000), (350000), (400000), (450000), (500000), (1000000));<EOL>
but the diff tool implies it should be
SPLIT AT VALUES ((1000), (5000), (10000), (15000), (20000), (25000), (30000), (35000), (55000), (85000), (110000), (150000), (250000), (300000), (350000), (400000), (450000), (500000), (1000000))<EOL>
```

Reviewers: jason

Reviewed By: jason

Subscribers: aagrawal, yql, jason

Differential Revision: https://phorge.dev.yugabyte.com/D29655