[PLAT-3514][Platform] Task Improvement - Add wait method in task executor to gracefully abort subtasks running loops to check status
Summary:
Replace the Thread.sleep with abort-aware waitFor equivalent method of the TaskExecutor, so that status check loops can be aborted faster and cleaner.
Also, made a minor fix to set the user task UUID to subtasks.

Test Plan:
Added unit test + manual test involving full move ran.

Manual test output:

```
2022-03-28 21:59:51.074 [error] TaskExecutor.java:586 [TaskPool-3] Error occurred in subtask taskType : subtasks.WaitForDataMove, taskState: Aborted
java.util.concurrent.CancellationException: task-info {taskType : EditUniverse, taskState: Abort}, task {EditUniverse(f68071b3-7115-440e-a0b4-1783107673c6)} is aborted while waiting.
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.waitFor(TaskExecutor.java:1066)
	at com.yugabyte.yw.commissioner.AbstractTaskBase.waitFor(AbstractTaskBase.java:221)
	at com.yugabyte.yw.commissioner.tasks.subtasks.WaitForDataMove.run(WaitForDataMove.java:85)
```

Reviewers: sb-yb, amalyshev

Reviewed By: amalyshev

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D16255