[#26365] YSQL: Preserve read time history in case of committing YB txn at the middle of SQL txn
Summary:
For handling postgres transactions YSQL creates YB transaction under the hood.
In the vast majority of cases YSQL commits YB transaction when postgres commits its transaction.
But there is the scenario with COPY statement when YSQL commits YB transaction earlier and create new YB transaction (i.e. YSQL commits YB transaction at the middle of postgres transaction).
Commit at the middle is the performance optimization to avoid having too large YB transaction (i.e. transaction which modifies/creates too many elements).
Committing transaction at the middle breaks postgres snapshot mechanism because YSQL uses read times for it. And old read time became unusable after committing YB transaction.

Example:
- YSQL starts postrges transaction and create snapshot at current read time
- YB transaction has `serial_no` 1 and read time used for snapshot is also 1
- during COPY operation YSQL commits current YB transaction and starts new one. Now transaction `serial_no` is 2 and read time is also changed to 2
- YSQL restores previously created snapshot which was created at read time 1
- On attempt to make any operations the following error will be risen
```
 ERROR: Bad read time serial no 1 while [2, 2] is expected
```

To solve this issue it is necessary to have mechanism to preserve old read points in case of committing YB transaction. The diff implements such mechanism.
- The `PgTxnManager::DisableReadTimeHistoryCutoff ` method is created to temporary disable read point history cutoff
- The `read_time_serial_no_history_min` field is added into the `PgPerformOptionsPB` protobuf to control the read time history cleanup process in `PgClientSession`. Before to the change `PgClientSession` cleared up read time history in case of changing of `txn_serial_no`. Now the changing of `txn_serial_no` is ignored and `PgClientSession` will cleanup all read time history records lesser than `read_time_serial_no_history_min`

Upgrade/Rollback safety:
The `pg_client.proto` is used for communication between pggate and local t-server only. So any modification of the this file are upgrade/rollback safe.
Jira: DB-15718

Test Plan:
New unit test is introduced

```
./yb_build.sh --gtest_filter PgCopyTest.HugeCopyFrom
```

Reviewers: fizaa, pjain, myang, patnaik.balivada

Reviewed By: patnaik.balivada

Subscribers: smishra, yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D43102