Reduce java logs.
Summary:
Noticed in YW that when a process is being created, wait-for-server step dumps a bunch of these while waiting for 'ping' to succeed. For example:
```
2018-05-18 18:29:02.599 WARN  TabletClient.java:696 [New I/O boss #34] [Peer fakeUUID -> 10.150.0.11:7100] Unexpected exception Connection refused: /10.150.0.11:7100 from downstream on [id: 0x8374fe41]
java.net.ConnectException: Connection refused: /10.150.0.11:7100
                           at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
                           at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
                           at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
                           at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
                           at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
                           at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
                           at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                           at java.lang.Thread.run(Thread.java:745)
```

Also removed the last check for RF1->RF3 which is always failing due to new tservers not getting load (and is not really a feature we support yet).

Test Plan: Jenkins: java only

Reviewers: hector, pritam.damania

Reviewed By: hector

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D4848