[#19690] YSQL: Simplify side-by-side diff handling
Summary:
Due to the amount of time it requires to maintain SideBySideDiff.java, switching to a much simpler, less full-featured implementation. (Mainly, no line numbers, and doesn't try to avoid clipping either side.)

This commit entirely removes errors from `SideBySideDiff.sanityCheckLinesMatch()`, that had the text:
```
java.lang.RuntimeException: SideBySideDiff sanity check failed: ...
```
Jira: DB-8491

Test Plan:
Jenkins: test regex: PgRegress|YsqlDump|StringUtil

```
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressAnalyze'
```
Then, change a blank line (I used line 133, but it shouldn’t matter) to the # character in `yb_analyze.out` and run the same command. Verify both inline and side-by-side diffs are present in the log, and the assertion failure message is useful.

```
./yb_build.sh --java-test 'org.yb.pgsql.TestYsqlDump#ysqlDumpWithYbMetadata'
```
Then, change a blank line (I used line 134, but it shouldn’t matter) to the # character in `yb_ysql_dump.data.sql` and run the same command. Verify both inline and side-by-side diffs are present in the log, and the assertion failure message is useful.
```
./yb_build.sh --java-test 'org.yb.util.TestStringUtil'
```

Reviewers: jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D29850