[BACKPORT 2025.2][#30083] YSQL: Improve CREATE DATABASE logging by adding txn_id
Summary:
In debugging some CREATE DATABASE errors:

```
I0122 08:46:27.362665 27451 catalog_manager.cc:9309] Enqueuing keyspace for Transaction Verification: yugabyte_4 [id=00004112000030008000000000000000]
```

It will be better to include the transaction id which can be used to connect with other logs such as:

```
I0122 08:46:27.736816 25147 tablet_service.cc:531] T 00000000000000000000000000000000 P d6be60ff301a49bbbe3936ab7f373133 [state=RUNNING]: Write failed: Operation failed. Try again (yb/docdb/conflict_resolution.cc:106): e144cd0b-fb77-4292-b93c-47f1395541b2 conflicts with same priority transaction (pri: 18446744073709551615): 015fa4e1-cf84-47eb-8013-8decf7d70e60 (transaction error 3)
```
Because the first log does not have the transaction id, we can only guess it is e144cd0b-fb77-4292-b93c-47f1395541b2 because later we see:

```
I0122 08:46:27.738026 27434 catalog_manager.cc:9349] Namespace transaction failed, deleting: yugabyte_4 [id=00004112000030008000000000000000]
```

I made changes to add transaction id to the above first and last log, in this way we can easily
connect the logs together.

Original commit: 09a50ca92908858d3f2af5bd2d6df8d97896fdd2 / D49861

Test Plan:
Manual test: (diff based upon commit ae2a56c345eb59b51572ddb014cccc189ff4cdc2 where
`yb_fallback_to_legacy_catalog_read_time` defaults to true)
(1) start RF-1 local cluster
./bin/yb-ctl create --rf 1

(2) start two ysqlsh sessions, and run the following commands concurrently:
(2.1) in one ysqlsh session, run create database commands:
```
create database d0;
create database d1;
create database d2;
......
create database d97;
create database d98;
create database d99;
```

(2.2) in another ysqlsh session, run create table commands:
```
create table t0 (id int);
create table t1 (id int);
create table t2 (id int);
......
create table t997 (id int);
create table t998 (id int);
create table t999 (id int);
```
Look at errors such as
```
ERROR:  Keyspace 'd49' already exists
```

Then look into yb-master.INFO for matching logs:

```
I0123 01:28:07.357136 2516773 catalog_manager.cc:9309] Enqueuing keyspace for Transaction Verification: d49 [id=00004031000030008000000000000000], txn_id: 7eceecb0-cd34-476b-bf9f-be4ff4a2f7b4
```

Note `txn_id: 7eceecb0-cd34-476b-bf9f-be4ff4a2f7b4`

Look for more logs with `7eceecb0-cd34-476b-bf9f-be4ff4a2f7b4`:

```
I0123 01:28:07.357136 2516773 catalog_manager.cc:9309] Enqueuing keyspace for Transaction Verification: d49 [id=00004031000030008000000000000000], txn_id: 7eceecb0-cd34-476b-bf9f-be4ff4a2f7b4
```

```
I0123 01:28:08.252511 2515976 tablet_service.cc:531] T 00000000000000000000000000000000 P ff0b5587a26949219055c0b67b4672b0 [state=RUNNING]: Write failed: Operation failed. Try again (yb/docdb/conflict_resolution.cc:1033): 7eceecb0-cd34-476b-bf9f-be4ff4a2f7b4 conflict with concurrently committed data. Value write after transaction start: doc ht ({ physical: 1769131688247454 }) > read time ({ physical: 1769131688245187 logical: 4095 }), key: SubDocKey(DocKey(CoTableId=00000001000030008001000000001f4a, [], [13529]), []): kConflict (transaction error 3)
```

```
I0123 01:28:08.264290 2516874 catalog_manager.cc:9351] Namespace transaction failed, deleting: d49 [id=00004031000030008000000000000000], txn_id: 7eceecb0-cd34-476b-bf9f-be4ff4a2f7b4
```

We can now clearly see the transaction for `create database d49;` has txn_id
`7eceecb0-cd34-476b-bf9f-be4ff4a2f7b4` and it failed due to a conflict.

Reviewers: kfranz, sanketh, bkolagani

Reviewed By: bkolagani

Subscribers: yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D49882