[#23264] YSQL: pg_partman: disable undo_partition
Summary:
`undo_partition` undos a partition set created by pg_partman. This function moves the data from the child tables
 to the given target table .

Currently undo_partition call fails with transaction abort error.
```
create schema partman;
create extension pg_partman schema partman;

CREATE SCHEMA partman_test;

CREATE TABLE partman_test.id_taptest_table (
    col1 bigint
    , col2 text not null default 'stuff'
    , col3 timestamptz DEFAULT now()
    , col4 text) PARTITION BY RANGE (col1);
 CREATE INDEX ON partman_test.id_taptest_table (col3);
CREATE TABLE partman_test.undo_taptest (LIKE partman_test.id_taptest_table INCLUDING ALL);

SELECT partman.create_parent('partman_test.id_taptest_table', 'col1', 'native', '5', p_jobmon := false, p_start_partition := '3000000000');
INSERT INTO partman_test.id_taptest_table (col1, col4) VALUES (generate_series(3000000001,3000000009), 'stuff'||generate_series(3000000001,3000000009));
SELECT partman.undo_partition('partman_test.id_taptest_table', 10, p_target_table := 'partman_test.undo_taptest');
```

Output

```
ERROR:  Transaction aborted: cc736d92-ce68-454d-8efa-c7a06207e722
CONTEXT: SQL statement "SELECT partition_type
    , partition_interval
    , datetime_string
    , control
    , epoch
                                                                                                       FROM partman.part_config
WHERE parent_table = p_parent_table"
PL/pgSQL function show_partitions(text,text,boolean) line 27 at SQL statement
SQL statement "SELECT partition_tablename                    FROM partman.show_partitions(p_parent_table, 'ASC', TRUE) LIMIT 1"
PL/pgSQL function partman.undo_partition(text,integer,text,boolean,numeric,text,text[],boolean) line 264 at SQL statement
DETAIL:
HINT:
CONTEXT:  PL/pgSQL function partman.undo_partition(text,integer,text,boolean,numeric,text,text[],boolean) line 516 at RAISE
```

As part of undo_partition, all data from child partitions is moved out to the target table. (undo_taptest in this case) and
after that the child table is detached from the parent table. This is done in an iterative manner looping through each child.

Since transactional DDL is not supported yet , the DMLs (deleting data from child tables)
and DDLs (detaching child tables) are causing conflicts.

This diff disables `undo_partition` function by early exiting.
Jira: DB-12190

Test Plan: jenkins: compile only

Reviewers: hsunder, jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D36771