[#25541] YSQL: fix bug in alter database refresh collation
Summary:
When doing collation test for PG 15 to ensure YB behaves as PG, I found a failed
test:

```
yugabyte=# CREATE DATABASE test_db5 LOCALE 'en_US.UTF-8' COLLATION_VERSION = 'blar' TEMPLATE template0;
CREATE DATABASE
yugabyte=#
yugabyte=# ALTER DATABASE test_db5 REFRESH COLLATION VERSION;
NOTICE:  changing version from blar to 2.28
ERROR:  Transaction for catalog table write operation 'pg_database_datname_index' not found
yugabyte=# ALTER DATABASE test_db5 REFRESH COLLATION VERSION;
```

The reason is that PG 15 introduced a new node type: `T_AlterDatabaseRefreshCollStmt` but
it is currently not classified as a ddl (while `T_AlterCollationStmt` which
existed in PG 11 already classified as DDL).

I added new unit tests to make sure YB behaves as PG when collation version is
changed which happens when there is a version change of the OS-supplied libc
or libicu library.

Test Plan: ./yb_build.sh debug --java-test org.yb.pgsql.TestPgRegressTypesString#schedule

Reviewers: kfranz, sanketh, mihnea

Reviewed By: kfranz

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D41843