[#7151] ysql: disallow tampering with postgres role
Summary:
ALTER ROLE postgres can do several things that cause backfill to stop working. Jason found two:

ALTER ROLE postgres CONNECTION LIMIT 0
ALTER ROLE postgres RENAME TO grespost

This change disallows these breaking commands for the postgres role.

Test Plan:
Build yugabyte DB and run test suite via Jenkins
```
yugabyte=# ALTER ROLE postgres RENAME TO grespost;
ERROR:  cannot rename postgres
yugabyte=# ALTER ROLE postgres CONNECTION LIMIT 0;
ERROR:  cannot set connection limit for postgres
yugabyte=# ALTER ROLE postgres CONNECTION LIMIT -1;
ALTER ROLE
yugabyte=# ^D\q
```

Reviewers: jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D10564