[#26549] YSQL: Redirect hnsw access method to ybhnsw
Summary:
Before this change, migration scripts containing `CREATE INDEX ... USING hnsw ...` statements from PgVector would fail in YB because YB's equivalent of `hnsw` is named `ybhnsw`. This update automatically maps `hnsw` to `ybhnsw` in `CREATE INDEX` statements, ensuring the correct indexes are created seamlessly. When this substitution occurs, the following message is logged:
```
LOG: substituting access method "ybhnsw" for "hnsw" in YugabyteDB```

The other warning messages of some other index AM substitutions: (btree -> lsm, hash -> lsm, gin -> ybgin) have been adjusted to match the above format. The relevant regress tests were updated for this as well.

Additionally, any attempt to set a GUC parameter with the "hnsw." prefix now triggers the existing validation mechanism for invalid configuration names, resulting in the following error:
```
ERROR:  invalid configuration parameter name "hnsw.ef_search"
DETAIL:  "hnsw" is a reserved prefix.
```

Test Plan: ./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressThirdPartyExtensionsPgvector'

Reviewers: telgersma, jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D42967