[#6904] Platform: UnitTests for application config for various production deployments.
Summary:
Add unittests for all the deployment configuration.
This loads configs for respective deployment with all the fallbacks and compares
against expected resolved configuration.
The test covers:
    - replicated
    - helm
    - yugabyted
Note: No test added for dev application.conf in this PR though there is no
reason why it cannot be added.

On failure the test will generate a filtered view of the actual deployment config with few deployment specific environment variables and parameter values hard-coded. This config is stored in file named with prefix `candidate-` under `/tmp` folder.
An entry is added to generated file if any of these conditions are met:
      - There is existing entry for that path in expected config
      - The path is one of the special (ALWAYS_GENERATE_PATH_PREFIXES
         like "yb. or "db." )
      - The path exist in both configs but the values do not match

This should allow us to make intrusive config changes with confidence
and ensure that our changes are getting resolved correctly i.e. not
incorrectly overridden etc.

Example log for failed test:
```
[info] Test com.yugabyte.yw.ConfigTest.singleKey(test.replicated.params.conf, replicated.expected.conf, envRepl) [0] started
[info] Test com.yugabyte.yw.ConfigTest.singleKey(test.helm.params.conf, helm.expected.conf, envHelm) [1] started
----------------------------------------------------------------------------------------------------
  Actual config written to: /tmp/helm.expected.conf-5523010180921619498.candidate
----------------------------------------------------------------------------------------------------
[error] Test com.yugabyte.yw.ConfigTest.singleKey(test.helm.params.conf, helm.expected.conf, envHelm) [1] failed: junit.framework.AssertionFailedError:
[error] Expected: db.default.url = "jdbc:postgresql://localhost:5432/yugaware"
[error] Actual: db.default.url = "jdbc:postgresql://127.0.0.1:5432/yugaware" expected:<Quoted("jdbc:postgresql://localhost:5432/yugaware")> but was:<Quoted("jdbc:postgresql://127.0.0.1:5432/yugaware")>, took 0.037 sec
...
[error]     at com.yugabyte.yw.ConfigTest.singleKey(ConfigTest.java:116)
[error]     ...

$ diff /home/sbapat/code/yugabyte-db/managed/src/test/resources/helm.expected.conf   /tmp/helm.expected.conf-5523010180921619498.candidate
11a12,13
> db.default.port = 5432
> db.default.url = "jdbc:postgresql://127.0.0.1:5432/yugaware"
```

Additional changes
- This change also renames yugabyted specific config file which was named
  `application.default.conf` to `application.yugabyte.conf`

- Both helm and replicated had a bug that flywaydb plugin was added twice.
  This PR change also fixes that bug.

Test Plan: This is a testonly change (mostly)

Reviewers: sanketh, wesley, arnav, daniel

Reviewed By: daniel

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D10656