[BACKPORT 2025.1][#3109][#27203] YSQL: Fix PG error when executing multiple truncate statements
Summary:
With transactional DDL, when executing the `TRUNCATE` statement after another `TRUNCATE` statement, we get an error. Specifically, the following example
fails:

```
yugabyte=# create table t(id int);
CREATE TABLE

yugabyte=# begin;
yugabyte=*# TRUNCATE TABLE t;
TRUNCATE TABLE
yugabyte=*# TRUNCATE TABLE t;
ERROR:  could not open file "base/13515/0": No such file or directory
```

This happens because when we try to truncate a table that has already been truncate in the same sub-transaction id, we end up going through the PG code path for
non-rollbackable truncate. This is a bug because we never want to go through the PG code path. This revision fixes the bug by checking for `!IsYBRelation`.

As a side change, I've also enabled table locks in transactional DDL test since transactional DDL depends on table locks feature.
Jira: DB-1839, DB-16690

Original commit: 23b0cb5f2121f3549064de9aac7b621755f558f7 / D44101

Test Plan: ./yb_build.sh --java-test 'org.yb.pgsql.TestDdlTransactionBlocks'

Reviewers: fizaa, #db-approvers

Reviewed By: fizaa, #db-approvers

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D44168