ENG-4692 (#868): Enable support for read only transactions
Summary:
Enable support for read only transactions
```
BEGIN TRANSACTION READ ONLY;

BEGIN TRANSACTION;
SET TRANSACTION READ ONLY;
```

Note that pg_dump still does not work because we don't support LOCK yet:
```
$ ./build/latest/postgres/bin/pg_dump -h localhost -p 5433 -U postgres
pg_dump: [archiver (db)] query failed: ERROR:  LOCK not supported yet
LINE 1: LOCK TABLE public.foo IN ACCESS SHARE MODE
        ^
HINT:  Please contact YugaByte for its release schedule.
pg_dump: [archiver (db)] query was: LOCK TABLE public.foo IN ACCESS SHARE MODE
```

Test Plan:

`
Try using read only in BEGIN TRANSACTION /SET TRANSACTION statements:
```
postgres=# begin;
BEGIN
postgres=# set transaction isolation level repeatable read, read only;
SET

postgres=# set transaction isolation level repeatable read, read write;
ERROR:  TRANSACTION READ WRITE mode not supported yet
LINE 1: set transaction isolation level repeatable read, read write;
                                                         ^
HINT:  Please contact YugaByte for its release schedule.

postgres=# begin transaction;
BEGIN
postgres=# set transaction read only;
SET
postgres=# set transaction isolation level repeatable read read only;
SET
postgres=# set transaction isolation level read committed read only;
SET
postgres=# set transaction isolation level read uncommitted read only;
SET

postgres=# begin transaction read only;
BEGIN

postgres=# begin transaction read write;
ERROR:  TRANSACTION READ WRITE mode not supported yet
LINE 1: begin transaction read write;
                          ^
HINT:  Please contact YugaByte for its release schedule.
```

Validate that read only transactions can only read data and cannot modify data
```
postgres=# begin transaction isolation level read committed read only;
BEGIN
postgres=# insert into foo values(1,1);
ERROR:  cannot execute INSERT in a read-only transaction
postgres=# commit;
ROLLBACK

postgres=# begin transaction isolation level read committed read only;
BEGIN
postgres=# select * from foo;
 a  | b
----+----
  1 |  1
 11 | 11
(2 rows)

postgres=# drop table foo;
ERROR:  cannot execute DROP TABLE in a read-only transaction

postgres=# show transaction_read_only;
 transaction_read_only
-----------------------
 on
(1 row)

postgres=# begin transaction isolation level read committed;
BEGIN
postgres=# show transaction_read_only;
 transaction_read_only
-----------------------
 off
(1 row)
```

Reviewers: mikhail, neil, mihnea

Reviewed By: mihnea

Subscribers: ravi, kannan

Differential Revision: https://phabricator.dev.yugabyte.com/D6213