[#30112] YSQL: make yb_max_saop_merge_streams user-settable
Summary:
For the bucket-based indexes project, there are currently three GUCs:

- yb_enable_derived_equalities
- yb_enable_derived_saops
- yb_max_saop_merge_streams

GUCs yb_enable_derived_equalities and yb_enable_derived_saops are
user-settable.  yb_max_saop_merge_streams is superuser-settable.  The
reason for that was that it was unsafe for potentially returning rows in
the wrong order because that part was not yet implemented.  But that
part did get implemented by commit
c2ec266bd7650a219c7015646ccd6719e9775b25 titled "[#29072] YSQL: Merge
sort support for bucketized indexes, executor part".  So relax the
restriction now, letting normal users set yb_max_saop_merge_streams.

While at it, remove all outdated references to issue #29072.

Test Plan:
On Almalinux 8, fastdebug, gcc13 build, run the following in ysqlsh:

    create user bob;
    \c - bob
    set yb_max_saop_merge_streams = 123;

Expect success.  Before this change, get

    ERROR:  permission denied to set parameter "yb_max_saop_merge_streams"

Backport-to: 2025.2

Reviewers: amartsinchyk

Reviewed By: amartsinchyk

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D49917