[BACKPORT 2.19.1.1109][PLAT-9257][PLAT-9260] Fix Azure orphaned resource deletion + Allow cgconfig to increase cgroup limit
Summary:
Original commit for PLAT-9257: 47e3a4e20a6a / D26179
Original commit for PLAT-9260: d9e3f78aa406 / D26168

Fix Azure orphaned resource deletion. Right now, bad argument is being passed for listing disks
which leads to the orphaned resource cleanup function exiting without deleting any of the orphaned
resources. This diff removes that bad argument.

Error due to bad argument:
```
2023-06-14T05:40:10.494Z  [debug] 39d04631-e7e1-4979-8af1-592c631d2eb4 ShellProcessHandler.java:276 [TaskPool-DestroyUniverse(423c4494-ce78-4eaa-bb56-49f88f63596f)-1] com.yugabyte.yw.common.ShellProcessHandler TypeError: request() got an unexpected keyword argument 'filter'
```

This diff also fixes deletion of orphaned public IPs. The current code was not breaking out of for-loop after deletion of orphaned NICs, fixed that.

[BACKPORT 2.19.1.1109][PLAT-9260] allow cgconfig to increase cgroup limit

changing the memory values of limit_in_bytes and memsw.limit_bytes follows
the rules:
1. when initially setting the values, memory.limit_in_bytes must be set first
2. when INCREASING the values, memory.memsw.limit_in_bytes must be set first
3. when DECREASING the values, memory.limit_in_bytes must be set first
I think what they are trying to do is memory.memsw.limit_in_bytes must be

By adding retries, the first attempt may fail, leaving us with no
cgroups. The retry will then come in and correctly set the values,
and the resize node can continue.

This comes with the caveat of deleting the cgroup, so we should not
use this workflow without restarting the tserver.

Test Plan:
PLAT-9257: Tested manually.

PLAT-9260: Tested resize node

Reviewers: cdavid, muthu, rtsisyk, Viji, dshubin

Reviewed By: cdavid

Subscribers: muthu, yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D26558