[#19876] DocDB: Add more debug info for investigating read path failure with error Expecting hybrid time
Summary:
Recently, we ran into an issue where `SELECT`(s) were seeing the following error
```
ERROR:  Expecting hybrid time with ValueType kHybridTime, found <unknown KeyEntryType : 153>
```
which could imply 2 things:
- in the read path, we accidentally process a non provisional record (from the code, this doesn't seem likely)
- we somehow end up writing a provisional record without the HT which results in the error during the read path.

upon looking at a few sst files, we didn't find any instance of provisional records with missing hybrid timestamp, so couldn't really get to the root cause of the issue. Adding additional debug logs that output relevant information for
the next time we hit the issue could help in investigating the root cause.
Jira: DB-8817

Test Plan: Jenkins

Reviewers: rthallam, sergei, mbautin

Reviewed By: rthallam, sergei

Subscribers: ybase

Differential Revision: https://phorge.dev.yugabyte.com/D30033