[#24431] YSQL: Supplement read restart error with more info
Summary:
### Motivation

Read restart errors are a common occurence in YugabyteDB.

Mitigation strategy varies case-by-case. Well known approaches:

1. Use READ COMMITTED isolation level. A popular mitigation strategy.
2. Increase ysql_output_buffer_size. This is applicable for large SELECTs that have a low read restart rate.
3. Use the deferrable mode. This is for background tasks that scan a lot of rows.
4. Leverage time sync service. Best option but still early.

However, these mitigitation strategies do not always work. Such cases require addressing the underlying problem. Currently, the logs lack sufficient detail, leading to speculation rather than concrete diagnosis.

### Examples

#### Running CREATE/DROP TEMP TABLE concurrently results in a read restart error

```
2025-04-04 01:57:32.353 UTC [587443] ERROR:  Restart read required at:  read: { days: 20182 time: 01:57:32.350502 } local_limit: { days: 20182 time: 01:57:32.350502 } global_limit: <min> in_txn_limit: <max> serial_no: 0 } (yb_max_query_layer_retries set to 0 are exhausted)
```

Users do not expect this error because TEMP TABLEs  are local to each pg backend. Moreover, increasing ysql_output_buffer_size does not mitigate the error here because read restart errors on DDLs cannot be retried yet. That said, users find it helpful to understand the root cause of the error. After this revision, the log becomes

```
2025-04-04 01:57:32.353 UTC [587443] DETAIL:  restart_read_time: { read: { days: 20182 time: 01:57:32.350502 } local_limit: { days: 20182 time: 01:57:32.350502 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }, original_read_time: { read: { days: 20182 time: 01:57:32.096749 } local_limit: { days: 20182 time: 01:57:32.098414 } global_limit: { days: 20182 time: 01:57:32.596749 } in_txn_limit: <max> serial_no: 0 }, table: template1.pg_yb_invalidation_messages [ysql_schema=pg_catalog] [00000001000030008001000000001f90], tablet: 00000000000000000000000000000000, leader_uuid: f1ac558309244cbab385761b531980f0, key: SubDocKey(DocKey(CoTableId=901f0000-0000-0180-0030-000001000000, [], [13515, 10]), [SystemColumnId(0)]), start_time: 2025-04-04 01:57:32.094965+00
```

**Cause:** The read restart error is returned when accessing the `pg_yb_invalidation_messages` table in the above example.
**Mitigation:** Avoid creating TEMP TABLEs from mutliple sessions concurrently. Note: The issue is fixed by table-level locking.

#### CREATE INDEX NONCONCURRENTLY

CREATE INDEX NONCONCURRENTLY accesses both the user table as well as syscatalog. How can the user identify whether the read restart error occurred due to a concurrent DDL or DML?

```
[ts-1] 2025-04-04 04:25:47.694 UTC [665450] DETAIL:  restart_read_time: { read: { days: 20182 time: 04:25:47.512991 } local_limit: { days: 20182 time: 04:25:47.512991 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }, original_read_time: { read: { days: 20182 time: 04:25:47.012991 } local_limit: { days: 20182 time: 04:25:47.512991 } global_limit: { days: 20182 time: 04:25:47.512991 } in_txn_limit: <max> serial_no: 0 }, table: yugabyte.test_table [ysql_schema=public] [000034cb000030008000000000004000], tablet: bf9d2bf8908b43d4b8b5ff75b169bf11, leader_uuid: 6d60cea932ca41498fee5ad07c375d18, key: SubDocKey(DocKey(0x0a73, [5], []), [ColumnId(1)])
```

**Cause:** In the above log, the error occurs on the user table.
**Mitigation:** Stop concurrent writes when creating the INDEX.

The read restart can also be on a catalog table. Example:

```
[ts-1] 2025-04-04 02:17:48.392 UTC [592811] DETAIL:  restart_read_time: { read: { days: 20182 time: 02:17:48.326938 } local_limit: { days: 20182 time: 02:17:48.326938 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }, original_read_time: { read: { days: 20182 time: 02:17:48.023542 } local_limit: { days: 20182 time: 02:17:48.024082 } global_limit: { days: 20182 time: 02:17:48.523542 } in_txn_limit: <max> serial_no: 0 }, table: yugabyte.pg_attribute [ysql_schema=pg_catalog] [000034cb0000300080010000000004e1], tablet: 00000000000000000000000000000000, leader_uuid: e941d4ee43bc40a8b4303eab317f52fd, key: SubDocKey(DocKey(CoTableId=e1040000-0000-0180-0030-0000cb340000, [], [16384, 5]), []), start_time: 2025-04-04 02:17:48.022154+00
[ts-1] 2025-04-04 02:17:48.392 UTC [592811] STATEMENT:  CREATE INDEX NONCONCURRENTLY non_concurrent_idx_0 ON test_table(key)
```

#### Read restarts on absent keys

Users sometimes report that they notice read restart errors even though they are no conflicting keys. To better observe such scenarios, print a key on which read restart error occurred. There can be multiple such keys, so we print the first one we encounter.

Here's an example fixed by #25214.

Setup

```
CREATE TABLE keys(k1 INT, k2 INT, PRIMARY KEY(k1 ASC, k2 ASC));
INSERT INTO keys(k1, k2) VALUES (1, 1);
```

The following query

```
INSERT INTO keys(k1, k2) VALUES (0, 0), (9, 9) ON CONFLICT DO NOTHING
```

results in a read restart error even though none of 0 or 9 conflict with 1.

```
2025-04-04 17:55:03.013 UTC [955800] DETAIL:  restart_read_time: { read: { days: 20182 time: 17:55:03.012147 } local_limit: { days: 20182 time: 17:55:03.012147 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }, original_read_time: { read: { days: 20182 time: 17:55:02.983152 } local_limit: { days: 20182 time: 17:55:03.483152 } global_limit: { days: 20182 time: 17:55:03.483152 } in_txn_limit: { days: 20182 time: 17:55:03.011777 } serial_no: 0 }, table: yugabyte.keys [ysql_schema=public] [000034cb000030008000000000004000], tablet: 2a19ede71f7e4389b1ca682e87318b32, leader_uuid: 7010bbec8ec94110b5e2316bca5319f4, key: SubDocKey(DocKey([], [1, 1]), [SystemColumnId(0)]), start_time: 2025-04-04 17:55:03.010743+00
```

This helps us understand where the read restart error occurred. It occurs on key = (1, 1), not relevant to the INSERT ON CONFLICT statement. The key field helps diagnose such scenarios.

**Mitigation:** See 1bcb09cf49ab for the fix.

#### Local Limit Fixes

Commits d67ba1234996 and 02ced43d3b4e fix some bugs with the local llimit mechanism. Identifying the value of local limit when the issue occurs is fairly straightforward. The error message has local limit.

```
[ts-1] 2025-04-04 02:17:48.392 UTC [592811] DETAIL:  restart_read_time: { read: { days: 20182 time: 02:17:48.326938 } local_limit: { days: 20182 time: 02:17:48.326938 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }, original_read_time: { read: { days: 20182 time: 02:17:48.023542 } local_limit: { days: 20182 time: 02:17:48.024082 } global_limit: { days: 20182 time: 02:17:48.523542 } in_txn_limit: <max> serial_no: 0 }, table: yugabyte.pg_attribute [ysql_schema=pg_catalog] [000034cb0000300080010000000004e1], tablet: 00000000000000000000000000000000, leader_uuid: e941d4ee43bc40a8b4303eab317f52fd, key: SubDocKey(DocKey(CoTableId=e1040000-0000-0180-0030-0000cb340000, [], [16384, 5]), []), start_time: 2025-04-04 02:17:48.022154+00
[ts-1] 2025-04-04 02:17:48.392 UTC [592811] STATEMENT:  CREATE INDEX NONCONCURRENTLY non_concurrent_idx_0 ON test_table(key)
```

#### pg_partman faces read restart errors

pg_partman faces a read restart error on max query

```
ERROR:  Restart read required at: { read: { physical: 1730622229379200 } local_limit: { physical: 1730622229379200 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
CONTEXT: SQL statement "SELECT max(id)::text FROM public.t1_p100000"
```

**Cause:** This is because there is no range index on the tablet 1_p100000 to retrieve the max value efficiently using the index.

A log such as

```
2025-04-04 18:55:31.936 UTC [963409] DETAIL:  restart_read_time: { read: { days: 20182 time: 18:55:31.934321 } local_limit: { days: 20182 time: 18:55:31.934321 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }, original_read_time: { days: 20182 time: 18:55:31.738805 }, table: yugabyte.tokens_idx [ysql_schema=public] [000034cb000030008000000000004003], tablet: {tokens_idx_tablet_id1}, leader_uuid: {ts2_peer_id}, key: SubDocKey(DocKey([], [300, "G%\xf8S\xde\xb0h\xe6)\xa3G0\x96\xae\x9e9\xf7r\xbe\xc3\x00\x00!!"]), [SystemColumnId(0)]), start_time: 2025-04-04 18:55:31.933012+00
```

informs us the table on which the read restart error occurred. If the table is an index such as tokens_idx, the query is using an index scan.

**Upgrade/Rollback safety:**

Adds a new key restart_read_key to tserver.proto. The key is marked optional. When absent an empty value is printed in its stead.
Jira: DB-13338

Test Plan:
Jenkins

Backport-through: 2024.2

Reviewers: smishra, pjain

Reviewed By: pjain

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D42883