ENG-3055: Fix ScopedPendingOperation to return Status::Busy error when unavailable.
Summary:
Fix ScopedPendingOperation to return Status::Busy error when unavailable instead of IllegalState.
IllegalState error will cause the client to mark the tablet replica as down.

Test Plan:
```
cqlsh> create table t (k int primary key, v text);
cqlsh> copy t (k, v) from 'data.txt';
cqlsh> select * from t limit 1;
 k     | v
-------+-------
 17012 | hello
cqlsh> truncate t;
cqlsh> select * from t;
SyntaxException: SQL error (yb/yql/cql/ql/ptree/process_context.cc:181): Invalid SQL Statement. Resource busy (yb/common/wire_protocol.cc:196): Failed Read(tablet: 522c2e754acf4d128445f23bfb4aeb90, num_ops: 1, num_attempts: 1) to tablet 522c2e754acf4d128445f23bfb4aeb90 on tablet server 79c02da809e349b7b1efdb32fbe136ea (127.0.0.1:8100) after 1 attempt(s): RocksDB store is busy
select * from t;
^^^^^^
 (error -11)
cqlsh> select * from t;

 k | v
---+---

(0 rows)
```

Reviewers: sergei

Reviewed By: sergei

Subscribers: mikhail, ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D4346