[BACKPORT 2024.1][#22821] YSQL: Preserve local limit in a multi-page read
Summary:
Original commit: 02ced43d3b4e1c71ac4f51fdcba7d9154ba095d4 / D35750

### Issue

We set the read time explicitly in pg_op.cc for subsequent pages. This sets the read time on consistent read point. Consistent read point thinks this is a new read point and clears out all the local limit values stored. This will cause the local limit to advance, leading to read restart errors.

### Fix

Clear out paging read time field before passing the response back to the pg layer from tserver's pg client session. Except for catalog sessions since they do not follow used_read_time logic.

### History

1c2e37de was introduced to use the same read time across all pages of a read. This was done as follows: docdb sets a read_time in the paging state and passes back to Pg. Pg would then copy paste the same paging state in the next RPC to docdb. Docdb would then pick the read time from the paging state to ensure that the same snapshot is used.

b97a8810 was a follow-up fix after 1c2e37de. After this fix, PG, sets the read time in the subsequent rpc requests using the read time from the paging state, instead of relying on docdb to use the read time from the copy pasted paging state.

Currently, we do not need the paging state read time (sans upgrade reasons) for

1. Plain sessions have used_read_time logic that sets the read time of subsequent RPCs.
2. DDL sessions use distributed transactions from the start and the used_read_time for that is also handled.

Catalog sessions require paging read time at the moment. We do not clear paging read time for catalog requests when sending back the response to pggate.

### Reason for backport

Reduces the number of occurrences of error

```
ERROR: Attempted to restart when session does not require restart
```

See GH issue #20735 for hypothesized RCA for the error. Pg sends read time to pg client session in several cases. One of the common cases is paging read where the pggate layer resends the read time it receives from pg client session in the response of the previous RPC. This change limits such scenarios only to catalog reads and catalog reads do not raise read restart errors.

**Upgrade/Rollback safety:**

The used read time logic is present in local proxy. Since the local proxy is upgraded along with the Pg layer, no upgrade issues are expected.
Jira: DB-11718

Test Plan: Jenkins: compile only

Reviewers: pjain, sergei, dmitry

Reviewed By: pjain

Subscribers: ybase, yql, svc_phabricator

Differential Revision: https://phorge.dev.yugabyte.com/D38425