[BACKPORT-2.14][PLAT-4484][PLAT-4486] Allow resuming paused universes with EAR enabled.
Summary:
This commit skips to set universe keys only if universe is paused
and no task is running. Today, the only update which can run on a
paused universe is the Resume task.
Note, if we explicitly add in a check for Resume task it
could re-introduce this regression if we add a similar task Resume
which could run on a paused Universe.

Original commit: 599b66b55de7cd26fa690c92b0fad8d732a6ccef/D18754

Test Plan:
Create a universe and enable Encryption at Rest. Pause the universe
and Resume it. This exception stack trace does not show up anymore-
```
2022-07-26T20:51:02.130Z  [error] 9d5be4dc-46cc-40e1-b2ce-587c96f386d2 SetUniverseKey.java:78 [application-akka.actor.default-dispatcher-1017] com.yugabyte.yw.commissioner.SetUniverseKey Error sending universe encryption key to node 10.9.207.214:7100
org.yb.client.ConnectionResetException: [Peer fakeUUID -> 10.9.207.214:7100] Connection reset on [id: 0x7093649c]
	at org.yb.client.TabletClient.cleanup(TabletClient.java:671)
	at org.yb.client.TabletClient.exceptionCaught(TabletClient.java:731)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
	at org.yb.client.TabletClient.handleUpstream(TabletClient.java:641)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:536)
	at org.jboss.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:236)
	at org.jboss.netty.handler.timeout.ReadTimeoutHandler$ReadTimeoutTask$1.run(ReadTimeoutHandler.java:276)
	at org.jboss.netty.channel.socket.ChannelRunnableWrapper.run(ChannelRunnableWrapper.java:40)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Reviewers: hzare, nsingh

Reviewed By: nsingh

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D18778