[#7359] YSQL: Support adding primary key to a table with tablespace
Summary:
Currently altering a table to add primary key fails with the following
error, if the table is associated with a tablespace:

CREATE TABLE test_tab(id int) TABLESPACE tblspace
ALTER TABLE testschema.test_tab ADD CONSTRAINT test_tab_pkey PRIMARY KEY (id);
ERROR:  adding primary key to a table with a tablespace is not yet implemented;

Today this step errors out if the table has custom tablespace set, because
at the time this was implemented, tablespaces were not enabled yet. Now that
tablespaces are enabled this no longer needs to error out.

Test Plan: ybd --scb --sj --java-test org.yb.pgsql.TestPgRegressTablespaces

Reviewers: dsrinivasan, mihnea, alex

Reviewed By: mihnea, alex

Differential Revision: https://phabricator.dev.yugabyte.com/D10816