[#15362] YSQL: Lower copy default for colocated table
Summary:
This fix temporarily resolves the following issue:

On a colocated table, all write batches go to 1 tablet, For a batch size of 20,000 and 5 column table, 100k (20k * 5) key values are inserted in 1 batch to doc db, where as in the non-colocated case, the 100k key values are inserted to 8 tablets in parallel (for Linh’s RF-1 experiment). For all the KVs, the intent checks and various other checks needs to be made, which increase the latency. With packed row, the size of the batch was getting reduced from 100K to 20K, and thus packed_row helped reduce the latency. While we continue to look at the cause of latency - potentially the intent aware iterator.

We lower the copy default for colocated table until a proper fix is put in place.

Test Plan:
```
t=# create table t (v int) with (colocation = true);
CREATE TABLE
t=# set yb_default_copy_from_rows_per_transaction_for_colocated_table=2;
SET
t=# copy t from stdin;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> 1
>> 2
>> 3
>> 4
>> 5
>> 6
>> 7
>> #
>> \.
ERROR:  invalid input syntax for integer: "#"

t=# select * from t order by v;
 v
---
 1
 2
 3
 4
 5
 6
(6 rows)
```

Reviewers: smishra, rthallam

Reviewed By: rthallam

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D21821