[#26129] YSQL: fix PgRegressRunner failed test regex
Summary:
Java PG regress tests run schedules and normally report the names of
failed tests within those schedules.  The logic to collect failed tests
uses a regex over the test output.  Ever since the regex was created
(commit b7c49abdd60bc5661ed94c5d794ffdbff98e6b70), it did not properly
handle tests with dots in them, such as "collate.icu.utf8".  Such test
names were rare until commit b7b7cf040343733f98f057bb3af7194052ee30b9
changed pretty much all tests that YB runs to have dots in them.

Fix the regex to handle dots.  While at it, fix the adjacent comment as
well to be up-to-date with b7b7cf040343733f98f057bb3af7194052ee30b9.

Jira: DB-15456

Test Plan:
Apply

    diff --git i/src/postgres/src/test/regress/sql/yb.orig.tablegroup.sql w/src/postgres/src/test/regress/sql/yb.orig.tablegroup.sql
    index 9ffab04bd1..6c7ff3a388 100644
    --- i/src/postgres/src/test/regress/sql/yb.orig.tablegroup.sql
    +++ w/src/postgres/src/test/regress/sql/yb.orig.tablegroup.sql
    @@ -1,3 +1,4 @@
    +SELECT 1;
     --
     -- YB_TABLEGROUP Testsuite: Testing Statments for TABLEGROUP.
     --
    diff --git i/src/postgres/src/test/regress/sql/yb.orig.tablegroup_dml.sql w/src/postgres/src/test/regress/sql/yb.orig.tablegroup_dml.sql
    index d2b3261a2b..cea6fdd9a8 100644
    --- i/src/postgres/src/test/regress/sql/yb.orig.tablegroup_dml.sql
    +++ w/src/postgres/src/test/regress/sql/yb.orig.tablegroup_dml.sql
    @@ -1,3 +1,4 @@
    +SELECT 1;
     --
     -- Tablegroups
     --

Run

    ./yb_build.sh fastdebug --gcc11 --java-test TestPgRegressTablegroup

Get

    java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb.orig.tablegroup, yb.orig.tablegroup_dml]

Backport-through: 2.20
Close: #26129
Jenkins: java only

Reviewers: kfranz

Reviewed By: kfranz

Subscribers: kfranz, yql

Differential Revision: https://phorge.dev.yugabyte.com/D42035