[#12821] ysql: Add logic to support status column which indicates the status of the copy command
Summary:
In D17134, the pg_stat_progress_copy view has yb_status column but its implementation was left out.

This issue implements the logic which fulfills yb_status column so that the status is still accessible after the COPY command finishes.

The bytes processed progress update call is moved from CopyLoadRawBuf() back to CopyFrom().
This movement aligns bytes processed count with tuples processed count.

Test Plan:
```
yugabyte=# COPY copy_tab FROM '/tmp/dat.txt';
ERROR:  duplicate key value violates unique constraint "copy_tab_pkey"
yugabyte=# SELECT relid::regclass, yb_status, command, type, bytes_processed, tuples_processed FROM pg_stat_progress_copy;
  relid   | yb_status |  command  | type | bytes_processed | tuples_processed
----------+-----------+-----------+------+-----------------+------------------
 copy_tab | ERROR     | COPY FROM | FILE |              0 |                0
(1 row)

yugabyte=# truncate copy_tab;
TRUNCATE TABLE
yugabyte=# COPY copy_tab FROM '/tmp/dat.txt';
COPY 11
yugabyte=# SELECT relid::regclass, yb_status, command, type, bytes_processed, tuples_processed FROM pg_stat_progress_copy;
  relid   | yb_status |  command  | type | bytes_processed | tuples_processed
----------+-----------+-----------+------+-----------------+------------------
 copy_tab | SUCCESS   | COPY FROM | FILE |              56 |               11
(1 row)

yugabyte=# COPY copy_tab FROM '/tmp/dat.txt' (skip 2);
COPY 9
yugabyte=# SELECT relid::regclass, yb_status, command, type, bytes_processed, tuples_processed FROM pg_stat_progress_copy;
  relid   | yb_status |  command  | type | bytes_processed | tuples_processed
----------+-----------+-----------+------+-----------------+------------------
 copy_tab | SUCCESS   | COPY FROM | FILE |              56 |                9
(1 row)
```

Reviewers: smishra, lnguyen

Reviewed By: lnguyen

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D17504