[#2396]: Fix Xcode 11 compilation
Summary:
After update to Xcode 11 build fails:
```
In file included from src/yb/rocksdb/db/db_impl_experimental.cc:24:
In file included from src/yb/rocksdb/db/db_impl.h:39:
In file included from src/yb/rocksdb/db/compaction_job.h:44:
src/yb/rocksdb/db/internal_stats.h:83:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WAL_FILE_BYTES,
    ^
src/yb/rocksdb/statistics.h:167:3: note: previous declaration is here
  WAL_FILE_BYTES,   // Number of bytes written to WAL
```

Fixed by using enum class for InternalDBStatsType.

Test Plan: Jenkins

Reviewers: timur, mikhail

Reviewed By: timur, mikhail

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D7260