[#19894] YSQL: Fix crash in pg_replication_slots view due to incorrect cdc_state_table iteration
Summary:
As part of https://phorge.dev.yugabyte.com/D29776, we added support for iterating the cdc_state_table and finding whether a stream (replication slot) is active or inactive.

There was an implementation mistake in the iteration of the state table. Each entry returned from the result must be checked using `RETURN_NOT_OK` before use which was not being done. If we try to consume the value of a `Result<T>` without calling `ok()` on it beforehand, it leads to a crash in DEBUG mode.

In the case of `pg_replication_slots` view, it leads to the following stack trace:
```
F20231108 10:41:38 ../../src/yb/util/status.cc:663] Check failed: value
    @        0x10e01ee20  google::LogDestination::LogToSinks()
    @        0x10e01df7c  google::LogMessage::SendToLog()
    @        0x10e01e920  google::LogMessage::Flush()
    @        0x10e0228f8  google::LogMessageFatal::~LogMessageFatal()
    @        0x10e01f860  google::LogMessageFatal::~LogMessageFatal()
    @        0x11ca4f160  yb::StatusCheck()
    @        0x10662d4dc  yb::Result<>::get_ptr()
    @        0x10662af68  yb::Result<>::operator->()
    @        0x1065ea48c  yb::tserver::PgClientServiceImpl::Impl::ListReplicationSlots()
    @        0x1065ea0b0  yb::tserver::PgClientServiceImpl::ListReplicationSlots()
    @        0x10e71addc  _ZZZN2yb7tserver17PgClientServiceIf11InitMethodsERK13scoped_refptrINS_12MetricEntityEEENK4$_20clENSt3__110shared_ptrINS_3rpc11InboundCallEEEENKUlPKNS0_31PgListReplicationSlotsRequestPBEPNS0_32PgListReplicationSlotsResponsePBENSA_10RpcContextEE_clESF_SH_SI_
 ...
```

This was not caught by any of the unit tests because all of the unit tests run with VLOG level 4 for `cdc*` modules. So the following log statement was executed as part of the unit test which does the `ok()` check as part of the `entry ?` expression. So we never got a crash in unit tests.

```
VLOG(1) << "CDCStateTableRange row: "
          << (entry ? yb::ToString(*entry) : entry.status().ToString());
```
https://github.com/yugabyte/yugabyte-db/blob/9a25b41ed3f1b03773f95d58e6524f07d352ce43/src/yb/cdc/cdc_state_table.cc#L419-L420

This revision ensures that we do the `RETURN_NOT_OK` check and makes the logic similar to how the table is iterated in other parts of the codebase.
Jira: DB-8838

Test Plan:
Steps to reproduce the issue without the fix are below. The commands work fine after the fix.

```
bin/ysqlsh
yugabyte=# create table t1 (id int primary key, name text, l_name varchar, hours float);
yugabyte=# create publication pub for all tables;
yugabyte=# select pg_create_logical_replication_slot('test_replication_slot', 'yboutput');
yugabyte=# select * from pg_replication_slots;
ERROR:  recvmsg error: Connection refused
```

New test case. The test fails without the fix and passes after it.

```
./yb_build.sh --cxx-test cdcsdk_ysql-test --gtest_filter "*TestPgReplicationSlotsView*"
```

Reviewers: dsrinivasan, skumar

Reviewed By: dsrinivasan

Subscribers: ybase, yql, bogdan

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D30053