Fix build after compile error on messenger.cc
Summary:
MacOS build seems to have an issue with < 0 check on size_t that was introduced in D6346

FAILED: src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o
/Users/amitanand/code/yugabyte/build-support/compiler-wrappers/c++  -Dyrpc_EXPORTS -Isrc -I../../ent/src -I../../src -isystem /usr/local/opt/openssl/include -isystem ../../thirdparty/installed/clang_uninstrumented/include -isystem ../../thirdparty/installed/common/include -isystem /usr/local/opt/icu4c/include -Werror -fno-strict-aliasing -msse4.2 -Wall -Wno-sign-compare -Wno-deprecated -Winvalid-pch -pthread -DBOOST_BIND_NO_PLACEHOLDERS -DROCKSDB_PLATFORM_POSIX -DROCKSDB_USING_THREAD_STATUS=0 -DBOOST_ERROR_CODE_HEADER_ONLY -DYB_COMPILER_TYPE=clang -DYB_COMPILER_VERSION=902.0.39.1 -DROCKSDB_LIB_IO_POSIX -DBZIP2 -DSNAPPY -DZLIB -D__STDC_FORMAT_MACROS -Wno-deprecated-declarations -DGFLAGS=gflags -Wnon-virtual-dtor -Werror=enum-compare -Werror=reorder -Werror=switch -Werror=return-type -Werror=non-virtual-dtor -Werror=string-plus-int -Werror=return-stack-address -Werror=implicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wthread-safety-analysis -DOS_MACOSX -D_GLIBCXX_USE_CXX11_ABI=0 -DYB_HEADERS_NO_STUBS=1 -ggdb -O1 -fno-omit-frame-pointer -Wno-ambiguous-member-template -Wimplicit-fallthrough -Qunused-arguments -fPIC -DYB_EDITION_NS_PREFIX=enterprise:: -DTCMALLOC_ENABLED -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC   -std=gnu++14 -MD -MT src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o -MF src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o.d -o src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o -c ../../src/yb/rpc/messenger.cc

( cd "/Users/amitanand/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja" && YB_THIRDPARTY_DIR=/Users/amitanand/code/yugabyte/thirdparty /usr/bin/clang++ -Dyrpc_EXPORTS -Isrc -I../../ent/src -I../../src -isystem /usr/local/opt/openssl/include -isystem ../../thirdparty/installed/clang_uninstrumented/include -isystem ../../thirdparty/installed/common/include -isystem /usr/local/opt/icu4c/include -Werror -fno-strict-aliasing -msse4.2 -Wall -Wno-sign-compare -Wno-deprecated -Winvalid-pch -pthread -DBOOST_BIND_NO_PLACEHOLDERS -DROCKSDB_PLATFORM_POSIX -DROCKSDB_USING_THREAD_STATUS=0 -DBOOST_ERROR_CODE_HEADER_ONLY -DYB_COMPILER_TYPE=clang -DYB_COMPILER_VERSION=902.0.39.1 -DROCKSDB_LIB_IO_POSIX -DBZIP2 -DSNAPPY -DZLIB -D__STDC_FORMAT_MACROS -Wno-deprecated-declarations -DGFLAGS=gflags -Wnon-virtual-dtor -Werror=enum-compare -Werror=reorder -Werror=switch -Werror=return-type -Werror=non-virtual-dtor -Werror=string-plus-int -Werror=return-stack-address -Werror=implicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wthread-safety-analysis -DOS_MACOSX -D_GLIBCXX_USE_CXX11_ABI=0 -DYB_HEADERS_NO_STUBS=1 -ggdb -O1 -fno-omit-frame-pointer -Wno-ambiguous-member-template -Wimplicit-fallthrough -Qunused-arguments -fPIC -DYB_EDITION_NS_PREFIX=enterprise:: -DTCMALLOC_ENABLED -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC -std=gnu++14 -MD -MT src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o -MF src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o.d -o src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o -c ../../src/yb/rpc/messenger.cc )  # Compiler exit code: 1.

/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/yb/rpc/messenger.cc:358:19: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
  if (reactor_idx < 0 || reactor_idx >= reactors_.size()) {
      ~~~~~~~~~~~ ^ ~
1 error generated.

Input files:
  src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o
  src/yb/rpc/messenger.cc
Output file (from -o): src/yb/rpc/CMakeFiles/yrpc.dir/messenger.cc.o

Test Plan: ybd on mac.

Reviewers: mikhail, kannan

Reviewed By: kannan

Subscribers: kannan, eng

Differential Revision: https://phabricator.dev.yugabyte.com/D6721