[#15932] YSQL: Fix flaky test yb_create_table_like
Summary:
The test `yb_create_table_like` in `TestPgRegressMisc#testPgRegressMiscSerial` is flaky and the test
can fail with
```
java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb_create_table_like]
```

After debugging, I found that the following output isn't stable:

```
\d liketemptest
                     Table "pg_temp_2.liketemptest"
 Column |       Type       | Collation | Nullable |       Default
--------+------------------+-----------+----------+---------------------
 k      | integer          |           | not null |
 v1     | text             |           |          | 'hello world'::text
 v2     | integer          |           |          |
 v3     | double precision |           |          |
Indexes:
    "liketemptest_pkey" PRIMARY KEY, btree (k ASC)
    "liketemptest_v3_key" UNIQUE CONSTRAINT, btree (v3 ASC)
    "liketemptest_v1_idx" btree (v1 ASC)
Check constraints:
    "temptest_v2_check" CHECK (v2 > 0)
```

Temporary schema name may be pg_temp_1, pg_temp_2, etc. As a result the above output isn't
stable.

I made a change to make the test output stable by
(1) store the output of `\d liketemptest` into a file
(2) read the file back into a string
(3) use regexp_replace to change pg_temp_1, pg_temp_2 or the like to pg_temp_xxx

Test Plan:
./yb_build.sh debug --java-test 'org.yb.pgsql.TestPgRegressMisc#testPgRegressMiscSerial' --tp 1 -n 5

No longer see
```
java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb_create_table_like]
```

Reviewers: tverona, ena

Reviewed By: ena

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D24228