[#11887] YSQL: Include information about the index table when ybctid DocKey isn't found in main table
Summary:
Sometimes, support people face the following error in server log:
```
ERROR:  Query error: ybctid DocKey([], ["@{..."]) not found in indexed table
```
The query leading to the above error is complex, involving JOINs over multiple tables and indexes.

Currently support people spend a lot of time trying to separate the query into smaller pieces so that the underlying index / table with missing DocKey can be found.
Since we don't have direct access to customer data, this requires some back and forth between customer and support people.

We can boost troubleshooting efficiency by including the index table Id in the error message.

This would save support people a lot of time when dealing with complex queries.

Test Plan:
New test case is not included in the revision because there is no unit test precedent on data corruption.
In case of corruption, the log would read something like this:

```
ERROR:  Query error: ybctid DocKey([], ["@{..."]) not found in indexed table. index table id is 000033e1000030008000000000000a5e
```

Build yugabyte db and run test suite via Jenkins

Reviewers: smishra, amartsinchyk

Reviewed By: amartsinchyk

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D16204