[DB-5855] xCluster Configuration - Data Type Missing in the Type.Java List
Summary:
This PR fixes the issue wherein we had a couple of datatypes missing (specifically because of a column of type `oid`) in the Type.java file because of which xCluster replication setup was failing with the error:

```
java.lang.IllegalArgumentException: The provided data type doesn't map to know any known one: yb.DataType
```

Test Plan:
Jenkins: java only

Added one more test to verify the fix:

```
ybd --java-test org.yb.pgsql.TestGetTableSchema
```

Reviewers: skumar, sanketh, hzare, vpatibandla, rvenkatesh

Reviewed By: hzare, vpatibandla

Subscribers: ycdcxcluster, jenkins-bot, yugaware, vpatibandla, bseetharaman, ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D23620