[BACKPORT 2024.2][#28216] YSQL: Add compiler errors to Odyssey build for more compile-time checking
Summary:
NOTE: Clean backport. Had to fix 1 compilation error due to different compiler version, see detail
at the end

These warnings are now added as errors (by either removing the flag turning off the warning or
adding a flag to enable it):
- `implicit-fallthrough`: unannotated fall-through between switch labels.
  - If an intended fallthrough is there, we need to add the line `yb_od_attribute_fallthrough`
  - This has been added in all places in current codebase so compilation succeeds
- `uninitialized`: Reading uninitialized variables becomes an error
- `enum-conversion`: Comparison of enum value to another enum's value is an error, enum can't be
  converted to a float implicitly, etc.
  - This is explicitly added since this is not present in `-Wall`

The following diagnostics are only enabled as errors in Clang, since compilation fails with GCC due to some
other issues that will need to be fixed:
- `incompatible-pointer-types`: Incompatible pointer types cannot be assigned

These commits have been cherry-picked from Odyssey to fix compiler errors:
- https://github.com/yandex/odyssey/commit/3f57e6c11e61ce005b2bae1a832bf4297a9bea48: Fixes
  uninitialized va_list being used in logger

Original commit: d92c635badc2d7296531979313c0953d55a21ccc / D48808

Extra error which was found in gcc11 fastdebug build which has been fixed:

```
../../src/odyssey/sources/yb_oid_entry.c: In function ‘yb_handle_oid_pkt_server’:
../../src/odyssey/sources/yb_oid_entry.c:296:12: error: ‘route_oid’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  296 |         if (route_oid != (int)oid_val) {
      |            ^
cc1: all warnings being treated as errors
```

It is fixed by initializing `route_oid` to -1

Test Plan:
Existing tests are enough. In fact, we need only check connection manager compiles fine and run
connection manager test suite

Jenkins: test regex: .*ysqlconnmgr.*

Reviewers: skumar, mkumar, asrinivasan, vikram.damle

Reviewed By: mkumar

Subscribers: yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D48911