[#30243] CDC: Throw error when pg_current_wal_lsn() is called
Summary: pg_current_wal_lsn() returns the current WAL write position. This API is not supported as each tablet has its own WAL in YB. Introduced an error message when pg_current_wal_lsn() is called stating feature not supported.

Test Plan:
```
SELECT * from pg_current_wal_lsn();
```
Expected output:

```
ERROR:  pg_current_wal_lsn() is not yet supported
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/30243. React with thumbs up to raise its priority.
```

Reviewers: sumukh.phalgaonkar, skumar

Reviewed By: sumukh.phalgaonkar

Subscribers: svc_phabricator, yql, ycdcxcluster

Differential Revision: https://phorge.dev.yugabyte.com/D50281