[BACKPORT 2025.1][#27872] YSQL: disable object locking for global catalog version mode
Summary:
Some PgCatalogVersionTest tests fail under global catalog version mode when
object locking is enabled because of check failure:

```
tests-pgwrapper_pg_catalog_version-test__PgCatalogVersionEnableAuthTest_PgCatalogVersionEnableAuthTest.ChangeUserPassword_2__error.log:[m-1] F0626 02:45:02.420627 108474 catalog_manager.cc:10178] Check failed: FLAGS_ysql_enable_db_catalog_version_mode
```

Because when object locking is enabled, we also need to propagate invalidation
messages. But invalidation messages are not supported for global catalog version
mode. Currently there is no plan to support invalidation messages for global
catlaog version mode because that mode is obsolete and will be deprecated.
Therefore this diff makes a change to disable object locking when
--ysql_enable_db_catalog_version_mode=false.
Jira: DB-17480

Original commit: 3295b10fcaacdec595f2ba37b6e3ad790c0eb159 / D45218

Test Plan:
(1)
Manually make a change to turn on `--enable_object_locking_for_table_locks` by
default:
```
diff --git a/src/yb/common/common_flags.cc b/src/yb/common/common_flags.cc
index d29013adce..c13646656b 100644
--- a/src/yb/common/common_flags.cc
+++ b/src/yb/common/common_flags.cc
@@ -140,7 +140,7 @@ TAG_FLAG(TEST_hide_details_for_pg_regress, hidden);
 DEFINE_NON_RUNTIME_uint32(max_replication_slots, 10,
      "Controls the maximum number of replication slots that are allowed to exist on a cluster.");

-DEFINE_RUNTIME_PREVIEW_bool(enable_object_locking_for_table_locks, false,
+DEFINE_RUNTIME_PREVIEW_bool(enable_object_locking_for_table_locks, true,
     "This test flag enables the object lock APIs provided by tservers and masters - "
     "AcquireObject(Global)Lock, ReleaseObject(Global)Lock. These APIs are used to "
     "implement pg table locks.");
```

Run the test command:

./yb_build.sh release --cxx-test pg_catalog_version-test

All the tests passed except for:

```
PgCatalogVersionTest.InvalMessageMinimalRetention
PgCatalogVersionTest.InvalMessageWaitOnVersionGap
```

These two unit tests still fail because when object lock is released,
currently we only propagate the catalog version but not the associated
invalidation messages. On seeing a newer catalog version in shared
memory, PG backend sends a RPC to local tserver for the messages but
the request cannot be satisfied. As a result PG backend performed a full
catalog refresh. Both tests were not expecting any full catalog refreshes.
Therefore they failed. Once we integrate catalog version and
invalidation messages during object lock release, they should pass.

(2) verify that --enable_object_locking_for_table_locks=true requires
ysql_enable_db_catalog_version_mode=true:
(2.1) This command successfully starts the cluster:
```
./bin/yb-ctl create --rf 1 --tserver_flags "ysql_enable_db_catalog_version_mode=false,enable_object_locking_for_table_locks=false,allowed_preview_flags_csv=enable_object_locking_for_table_locks" --master_flags "ysql_enable_db_catalog_version_mode=false,enable_object_locking_for_table_locks=false,allowed_preview_flags_csv=enable_object_locking_for_table_locks"

```
(2.2) This command fails to start the cluster
```
./bin/yb-ctl create --rf 1 --tserver_flags "ysql_enable_db_catalog_version_mode=false,enable_object_locking_for_table_locks=true,allowed_preview_flags_csv=enable_object_locking_for_table_locks" --master_flags "ysql_enable_db_catalog_version_mode=false,enable_object_locking_for_table_locks=true,allowed_preview_flags_csv=enable_object_locking_for_table_locks"

```
Look at error logs:
```
disk-1$ cat master.err
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0707 17:04:15.126183 1236939 common_flags.cc:149] Invalid value '1' for flag 'enable_object_locking_for_table_locks': Requires ysql_enable_db_catalog_version_mode to be true
F0707 17:04:15.126448 1236939 flags.cc:675] Check failed: _s.ok() Bad status: Invalid argument (yb/util/flags/flags.cc:856): ERROR: failed validation of new value 'true' for flag 'enable_object_locking_for_table_locks'
 : common_flags.cc:149] Invalid value '1' for flag 'enable_object_locking_for_table_locks': Requires ysql_enable_db_catalog_version_mode to be true
*** Check failure stack trace: ***
disk-1$ cat tserver.err
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0707 17:04:15.161190 1236942 common_flags.cc:149] Invalid value '1' for flag 'enable_object_locking_for_table_locks': Requires ysql_enable_db_catalog_version_mode to be true
F0707 17:04:15.161397 1236942 flags.cc:675] Check failed: _s.ok() Bad status: Invalid argument (yb/util/flags/flags.cc:856): ERROR: failed validation of new value 'true' for flag 'enable_object_locking_for_table_locks'
 : common_flags.cc:149] Invalid value '1' for flag 'enable_object_locking_for_table_locks': Requires ysql_enable_db_catalog_version_mode to be true
*** Check failure stack trace: ***
```

Reviewers: bkolagani, kfranz, sanketh, mihnea, amitanand

Reviewed By: bkolagani

Subscribers: yql, amitanand, rthallam

Differential Revision: https://phorge.dev.yugabyte.com/D45289