[#30295,#1872] YSQL: Fix flaky test TestPgRegressPgAsync#testIsolationPgRegress
Summary:
Context: The first LISTEN on a node starts a "notifications poller" background worker, which in turn initialises a virtual wal on the host tserver. The last UNLISTEN on the node terminates this background worker. The pg_client_service cleans up the associated virtual wal asynchronously via CleanupSessions(). The max virtual wal per tsever is controlled by gflag cdc_max_virtual_wal_per_tserver, whose default value is 5.

The test yb.port.async-notify has six permutations. All of these permutations are executed on sessions that connect to the same tserver. At the end of each permutation, `UNLISTEN *` is executed, which triggers async cleanup of virtual wal. But because of the async nature, it is possible that none of the first five virtual wals is cleaned up by the time the sixth permutation starts. This happens intermittently on fastdebug/tsan build, causing the sixth permutation to fail with:
```
ERROR:  notifications poller background worker failed to initialize
DETAIL:  Failed to create VirtualWAL for stream: 8e9230cbff6529bbc8452f65f9e0792c & session_id: 19 as max capacity reached for VirtualWAL on tserver
```

Fix the test failure by increasing cdc_max_virtual_wal_per_tserver to 10.

Test Plan:
./yb_build.sh fastdebug --java-test 'org.yb.pgsql.TestPgRegressPgAsync#testIsolationPgRegress' -n 20
./yb_build.sh tsan --java-test 'org.yb.pgsql.TestPgRegressPgAsync#testIsolationPgRegress' -n 20

Depends on D51071

Reviewers: jason, sumukh.phalgaonkar

Reviewed By: jason

Differential Revision: https://phorge.dev.yugabyte.com/D51110