[BACKPORT 2025.2][#29992] docdb: Vector Index: corruption error is shown for tablet partitions in the yb-admin output
Summary:
yb-admin does not display tablet partitions correctly for vector index, it shows corruption/decoding error:
```
Tablet-UUID                      	Range                                                    	Leader-IP       	Leader-UUID
5ee5d6db3b5d4b388b118039aca9c82c 	range: [<start>, Corruption (yb/dockv/primitive_value.cc:1631): Error when decoding range components of a document key: while consuming primitive values from 8000: Cannot decode value type <unknown KeyEntryType : -128> from the key encoding format: "\x80\x00": 8000) 	127.0.0.1:9100  	b7007f332d73420f9521cff8184e5023
a0d5261782614e71a0c53c832f7cd1fd 	range: [Corruption (yb/dockv/primitive_value.cc:1631): Error when decoding range components of a document key: while consuming primitive values from 8000: Cannot decode value type <unknown KeyEntryType : -128> from the key encoding format: "\x80\x00": 8000, <end>) 	127.0.0.1:9100  	b7007f332d73420f9521cff8184e5023
```
This happens because yb-admin uses vector index's schema to decode vector index's tablets, which is incorrect for this particular case because vector index is colocated on the indexed table tablets and vector index's schema does not correspond to these tablets.

This change fixes this by using the indexed table tablets for the vector index table.
Fixed output:
```
Tablet-UUID                      	Range                                                    	Leader-IP       	Leader-UUID
5ee5d6db3b5d4b388b118039aca9c82c 	hash_split: [0x0000, 0x7FFF]                             	127.0.0.1:9100  	b7007f332d73420f9521cff8184e5023
a0d5261782614e71a0c53c832f7cd1fd 	hash_split: [0x8000, 0xFFFF]                             	127.0.0.1:9100  	b7007f332d73420f9521cff8184e5023
```

Original commit: 587967683bc6c57a97f01efc37b137d89eca702f / D49685

Test Plan:
Jenkins

Manual:
```
1. Create simple table and vector index:
CREATE EXTENSION vector;
CREATE TABLE test (id bigserial PRIMARY KEY, embedding vector(1)) split into 2 tablets;
CREATE INDEX ON test USING ybhnsw (embedding vector_l2_ops);

2. Run `yb-admin list_tablets test_embedding_idx`
```

Reviewers: hsunder, sergei

Reviewed By: hsunder

Subscribers: ybase

Differential Revision: https://phorge.dev.yugabyte.com/D49738