Fixed bug in yb-ctl for stopping processes, when os.kill raises an exception
Summary:
Replaced `os.errno.ESRCH` with `errno.ESRCH` as it has been removed since
Python 3.7 (3.8 being default on Ubuntu 20.04).

Test Plan:
Temporarily added a `raise OSError` to verify that
`AttributeError: module 'os' has no attribute 'errno'` is no longer raised.

Reviewers: skedia, rahuldesirazu

Reviewed By: rahuldesirazu

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D12721