[#21955] YSQL: Fix MemTracker build failure on 2.18
Summary:
Fixes the following compile errors that are hit on 2.18 right now:
```
src/yb/util/mem_tracker.cc:287:36: error: out-of-line definition of 'CreateChild' does not match any declaration in 'yb::MemTracker'
shared_ptr<MemTracker> MemTracker::CreateChild(int64_t byte_limit,
                                   ^~~~~~~~~~~
src/yb/util/mem_tracker.cc:302:27: error: reference to non-static member function must be called; did you mean to call it with no arguments?
          create_metrics, metric_name);
                          ^~~~~~~~~~~
                                     ()
src/yb/util/mem_tracker.cc:316:13: error: constructor for 'yb::MemTracker' must explicitly initialize the member 'rand_' which does not have a default constructor
MemTracker::MemTracker(int64_t byte_limit, const string& id,
            ^
src/yb/util/mem_tracker.h:515:20: note: member is declared here
  ThreadSafeRandom rand_;
                   ^
src/yb/util/random.h:175:7: note: 'yb::ThreadSafeRandom' declared here
class ThreadSafeRandom {
      ^
3 errors generated.
```

Also, add back the definition of `GetDbBlockCacheNumShardBits` which was deleted in D33829.
Jira: DB-10871

Test Plan:
```
./yb_build.sh --cxx-test pg_catalog_perf-test
```

Reviewers: zdrudi, asrivastava

Reviewed By: asrivastava

Subscribers: asrivastava, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D34086