[#10792] ysql: Add YB operations to validate replication info
Summary:
This diff introduces functionality to validate that the current cluster configuration can support tablespace operations before changes are made to the database. This diff supports this validation for `ALTER TABLE SET TABLESPACE`.

Validation is introduced as a best-effort process. It will not catch all problems (e.g. a node can fail at any time, after validation but before a tablespace operation, and would only be reported as an under-replicated state) but should catch tablespace alterations that cannot be satisfied at the time of the request.

Future work includes adding the same validation pipeline to `CREATE TABLESPACE` and `CREATE TABLE SET TABLESPACE`.

Test Plan:
**Automated Tests**
Changes were made to yb_tablespaces.{sql/out} based on the functionality added in this diff.
Run: `./bin/yugabyted --scb --sj --java-test org.yb.pgsql.TestPgRegressTablespaces`

Placement information conversion tests were moved to `placement_info-test.cc`
Run: `./yb_build.sh --cxx-test placement_info-test`

**Manual Tests**
In order to verify the expected results of the added feature, consult the following steps for local, manual verification:
1. Start up a set of servers emulating varied placement.
```
export IP1=127.0.0.1
export IP2=127.0.0.2
export IP3=127.0.0.3
export IP4=127.0.0.4

bin/yugabyted start                            \
  --base_dir=$HOME/yugabyte/$IP1/yugabyte-data      \
  --listen=$IP1                               \
  --master_flags "placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1a" \
  --tserver_flags "placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1a"

bin/yugabyted start                            \
  --base_dir=$HOME/yugabyte/$IP2/yugabyte-data      \
  --listen=$IP2                               \
  --join=$IP1                                 \
  --tserver_flags "placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1b"

bin/yugabyted start                            \
  --base_dir=$HOME/yugabyte/$IP3/yugabyte-data      \
  --listen=$IP3                               \
  --join=$IP1                                 \
  --tserver_flags "placement_cloud=aws,placement_region=ap-south-1,placement_zone=ap-south-1a"

bin/yugabyted start                            \
  --base_dir=$HOME/yugabyte/$IP4/yugabyte-data      \
  --listen=$IP4                               \
  --join=$IP1                                 \
  --tserver_flags "placement_cloud=aws,placement_region=eu-west-2,placement_zone=eu-west-2c"
```
2. Start a new connection to the database: `./bin/ysqlsh`
3. In the SQL shell, run:
```
yugabyte=# CREATE TABLESPACE us_east_1a_zone_tablespace
  WITH (replica_placement='{"num_replicas": 1, "placement_blocks": [
    {"cloud":"aws","region":"us-east-1","zone":"us-east-1a","min_num_replicas":1}]}');

yugabyte=# CREATE TABLE single_zone_table (id INTEGER, field text)
  TABLESPACE us_east_1a_zone_tablespace SPLIT INTO 1 TABLETS;

yugabyte=# CREATE TABLESPACE multi_region_tablespace
  WITH (replica_placement='{"num_replicas": 3, "placement_blocks": [
    {"cloud":"aws","region":"us-east-1","zone":"us-east-1b","min_num_replicas":1},
    {"cloud":"aws","region":"ap-south-1","zone":"ap-south-1a","min_num_replicas":1},
    {"cloud":"aws","region":"eu-west-2","zone":"eu-west-2c","min_num_replicas":1}]}');

yugabyte=# CREATE TABLESPACE dne_tablespace
  WITH (replica_placement='{"num_replicas": 1, "placement_blocks": [
    {"cloud":"nonexistent","region":"nowhere","zone":"area51","min_num_replicas":1}]}');
```
At this point, you should see that the `reltablespace` column for the `pg_class` entry corresponding to the table should reflect `us_east_1a_zone_tablespace`, which you can confirm with the SQL query `SELECT * FROM pg_class JOIN pg_tablespace ON pg_class.reltablespace = pg_tablespace.oid WHERE pg_class.relname='single_zone_table'`.

Additionally, there should be a single tablet on the tablet server placed in `us-east-1a`, which you can confirm in the `Tables` view in the master web UI at `localhost:7000` by navigating to the particular table modified. The RaftConfig should look similarly to the screenshot below:
{F19898}
4. Now, again in the SQL shell, run:
```
yugabyte=# ALTER TABLE single_zone_table SET TABLESPACE multi_region_tablespace;
```
Now you should see that the `reltablespace` column for the `pg_class` entry corresponding to the table has changed and should reflect `multi_region_tablespace`, which you can again confirm with the following SQL query: `SELECT * FROM pg_class JOIN pg_tablespace ON pg_class.reltablespace = pg_tablespace.oid WHERE pg_class.relname='single_zone_table'``.

After some time, the UI should also change, now with three tablets, one on each of the tablet servers in this tablespace. You can confirm once more in the `Tables` view in the web UI at `localhost:7000` by navigating to the particular table modified. The RaftConfig should look similarly to the screenshot below:
{F19900}

5. Finally, run
```
yugabyte=# ALTER TABLE single_zone_table SET TABLESPACE dne_tablespace;
```
You should see the following error:
```
ERROR:  Invalid argument: Not enough tablet servers in nonexistent:nowhere:area51. Need at least 1 but only have 0.
```
and confirm that the `reltablespace` column for the `pg_class` entry is unchanged from `multi_region_tablespace`, rerunning the SQL query: `SELECT * FROM pg_class JOIN pg_tablespace ON pg_class.reltablespace = pg_tablespace.oid WHERE pg_class.relname='single_zone_table'``, while the UI also remains unchanged.

Reviewers: jason, dmitry

Reviewed By: jason

Subscribers: dmitry, sergei, jason, bogdan

Differential Revision: https://phabricator.dev.yugabyte.com/D13898