ysql: Import Relax transactional restrictions on ALTER TYPE ... ADD VALUE (redux).
Summary:
Commit was 212fab9926b2f0f04b0187568e7124b70e8deee5

Commit message was:

    Originally committed as 15bc038f (plus some follow-ups), this was
    reverted in 28e07270 due to a problem discovered in parallel
    workers.  This new version corrects that problem by sending the
    list of uncommitted enum values to parallel workers.

    Here follows the original commit message describing the change:

    To prevent possibly breaking indexes on enum columns, we must keep
    uncommitted enum values from getting stored in tables, unless we
    can be sure that any such column is new in the current transaction.

    Formerly, we enforced this by disallowing ALTER TYPE ... ADD VALUE
    from being executed at all in a transaction block, unless the target
    enum type had been created in the current transaction.  This patch
    removes that restriction, and instead insists that an uncommitted enum
    value can't be referenced unless it belongs to an enum type created
    in the same transaction as the value.  Per discussion, this should be
    a bit less onerous.  It does require each function that could possibly
    return a new enum value to SQL operations to check this restriction,
    but there aren't so many of those that this seems unmaintainable.

    Author: Andrew Dunstan and Tom Lane, with parallel query fix by Thomas Munro
    Reviewed-by: Tom Lane
    Discussion: https://postgr.es/m/CAEepm%3D0Ei7g6PaNTbcmAh9tCRahQrk%3Dr5ZWLD-jr7hXweYX3yg%40mail.gmail.com
    Discussion: https://postgr.es/m/4075.1459088427%40sss.pgh.pa.us

Test Plan:
```
yugabyte=# begin transaction;
BEGIN
yugabyte=# CREATE TYPE test AS ENUM ();
CREATE TYPE
yugabyte=# ALTER TYPE test add value 'b1';
ALTER TYPE
yugabyte=# end transaction;
COMMIT
yugabyte=# \dT+ test;
                                      List of data types
 Schema | Name | Internal name | Size | Elements |  Owner   | Access privileges | Description
--------+------+---------------+------+----------+----------+-------------------+-------------
 public | test | test          | 4    | b1       | yugabyte |                   |
(1 row)

yugabyte=# begin transaction;
BEGIN
yugabyte=# ALTER TYPE test add value 'b3';
ALTER TYPE
yugabyte=# SELECT 'b3'::test;
ERROR:  unsafe use of new value "b3" of enum type test
LINE 1: SELECT 'b3'::test;
               ^
HINT:  New enum values must be committed before they can be used.
```
Verify existing test suite passes.

yb_pg_enum.out is slightly different from enum.out because of the lack of support for SAVEPOINT.

Reviewers: myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D12163