[BACKPORT 2.20][#14984] YSQL: Ignore empty placement_uuid during ALTER TABLE SET TABLESPACE placement validation
Summary:
Original commit: 8e57d464897f146d20e95e917c02b0519e6728f1 / D29607
### Problem
When the cluster has a placement_uuid set, ALTER TABLE SET TABLESPACE fails with "Not enough live tablet servers to create table" even when creating a table in the same tablespace succeeds.

  - The reason behind this is that when verifying that there are live tablet servers in a tablespace, `CREATE TABLE` supplies the correct placement_uuid for the tablespace, while `ALTER TABLE` supplies an empty uuid. This causes the check to fail during `ALTER TABLE SET TABLESPACE`, which checks that there are T-Servers matching the supplied placement uuid:
```
void CatalogManager::GetTsDescsFromPlacementInfo(const PlacementInfoPB& placement_info,
                                                 const TSDescriptorVector& all_ts_descs,
                                                 TSDescriptorVector* ts_descs) {
  ts_descs->clear();
  for (const auto& ts_desc : all_ts_descs) {
    if (placement_info.has_placement_uuid()) {
      string placement_uuid = placement_info.placement_uuid();
      if (ts_desc->placement_uuid() == placement_uuid) {
        ts_descs->push_back(ts_desc);
      }
    } else if (ts_desc->placement_uuid() == "") {
      // Since the placement info has no placement id, we know it is live, so we add this ts.
      ts_descs->push_back(ts_desc);
    }
  }
}
```
  - How the `placement_info` descriptor is generator differs for `CREATE TABLE` and `ALTER TABLE`.
    - `CREATE TABLE` does an RPC to master (`CatalogManager::CreateTable`) that gets the tablespace info from the YsqlTablespaceManager.
    - `ALTER TABLE`, however, gets the tablespace placement info on the Postgres side (`yb_get_tablespace_options`), which just reads the corresponding `pg_tablespace` row. The problem with this is that `pg_tablespace` does not contain the placement_uuids that we need.

### Solution
Fill in the`placement_uuid` with the live cluster's placement uuid on master when doing an validating an `ALTER TABLE SET TABLESPACE` with no supplied `placement_uuid`.
Jira: DB-4233

Test Plan:
### Unit tests
`org.yb.pgsql.TestTablespaceWithPlacement`

### Manual repro
```
bin/yb-ctl create                             \
  --rf 1                                      \
  --placement_info "aws.us-east-1.us-east-1a" \
  --tserver_flags "placement_uuid=node1"

  bin/yb-admin modify_placement_info aws.us-east-1.us-east-1a 1 node1
```

Then in `ysqlsh`:
```
CREATE TABLESPACE us_east_1a_zone_tablespace
  WITH (replica_placement='{"num_replicas": 1, "placement_blocks": [
    {"cloud":"aws","region":"us-east-1","zone":"us-east-1a","min_num_replicas":1}]}');
CREATE TABLE table1 (id INT);
ALTER TABLE table1 SET TABLESPACE us_east_1a_zone_tablespace;
```
This fails with
```
ERROR:  Not enough live tablet servers to create table with replication factor 1. Need at least 1 tablet servers whereas 0 are alive.
```

### Alternate repro using `yugabyted`
```
./bin/yugabyted start --ui false                           \
  --base_dir=~/127.0.0.1/yugabyte-data \
  --listen=127.0.0.1                                \
  --master_flags "placement_uuid=b661881e-c90d-411f-8a22-2282bbaf74e8,placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1a" \
  --tserver_flags "placement_uuid=b661881e-c90d-411f-8a22-2282bbaf74e8,placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1a"
sleep 5
./bin/yugabyted start --ui false                           \
  --base_dir=~/127.0.0.2/yugabyte-data \
  --listen=127.0.0.2                                \
  --join=127.0.0.1                                  \
  --master_flags "placement_uuid=b661881e-c90d-411f-8a22-2282bbaf74e8,placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1b" \
  --tserver_flags "placement_uuid=b661881e-c90d-411f-8a22-2282bbaf74e8,placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1b"
./bin/yugabyted start --ui false                           \
  --base_dir=~/127.0.0.3/yugabyte-data \
  --listen=127.0.0.3                                \
  --join=127.0.0.1                                  \
  --master_flags "placement_uuid=b661881e-c90d-411f-8a22-2282bbaf74e8,placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1c" \
  --tserver_flags "placement_uuid=b661881e-c90d-411f-8a22-2282bbaf74e8,placement_cloud=aws,placement_region=us-east-1,placement_zone=us-east-1c"
```
Then in `ysqlsh`:
```
CREATE TABLESPACE us_east_1a_zone_tablespace
  WITH (replica_placement='{"num_replicas": 1, "placement_blocks": [
    {"cloud":"aws","region":"us-east-1","zone":"us-east-1a","min_num_replicas":1}]}');
CREATE TABLESPACE us_east_1b_zone_tablespace
  WITH (replica_placement='{"num_replicas": 1, "placement_blocks": [
    {"cloud":"aws","region":"us-east-1","zone":"us-east-1b","min_num_replicas":1}]}');
CREATE TABLE table1 (id INT) TABLESPACE us_east_1a_zone_tablespace;
CREATE TABLE table2 (id INT) TABLESPACE us_east_1b_zone_tablespace;
ALTER TABLE table2 SET TABLESPACE us_east_1a_zone_tablespace;
```
The last command fails with
```
ERROR:  Not enough live tablet servers to create table with replication factor 1. Need at least 1 tablet servers whereas 0 are alive.
```

Reviewers: asrivastava, dsrinivasan

Reviewed By: dsrinivasan

Subscribers: bogdan, tverona, ybase, rahuldesirazu

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D31891