[BACKPORT 2.18]Fix the issue [TIMEOUT]]] issue with Slf4jLogger
Summary:
The issue of
```
akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger
specified in config can't be loaded
[akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException:
Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
```
kept recurring even with machine restarts, force git clean with sbt
1.7.2. Reinstalls of sbt didn't work as well.
Adding `-Dakka.logger-startup-timeout=30s` worked.

Test Plan:
Manually where sbt kept failing.
The issue first got fixed when added this configuration to `/usr/local/etc/sbtopts`
.sbtopts should be the correct place though.

Reviewers: amalyshev, anijhawan

Reviewed By: anijhawan

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D24848