[#13769] ysql: Put OverrideTcmallocGcThresholdForPg under TCMALLOC_ENABLED
Summary:
centos-clang12-tsan build is broken:
https://jenkins.dev.yugabyte.com/job/yugabyte-db-phabricator/18699/consoleText
```
[2022-08-24T23:28:37.645Z] src/yb/util/mem_tracker.cc:214:6: error: unused function 'OverrideTcmallocGcThresholdForPg' [-Werror,-Wunused-function]
[2022-08-24T23:28:37.645Z] void OverrideTcmallocGcThresholdForPg() {
[2022-08-24T23:28:37.645Z]      ^
[2022-08-24T23:28:37.645Z] 1 error generated.
```
The above was introduced by commit 28962e87b56b7fb4f4dec877d249b744163ce689

This revision puts OverrideTcmallocGcThresholdForPg under TCMALLOC_ENABLED conditional def.

Test Plan: centos-clang12-tsan build passes.

Reviewers: ssong

Reviewed By: ssong

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D19174