ysql: improve ALTER TABLE [RE]SET errmsg
Summary:
The ALTER TABLE SET error message says

    ERROR:  ALTER TABLE SET name not supported yet

The "name" should be reloptions, so it doesn't make sense, but just get
rid of "name" altogether because it's simpler.

Same goes for ALTER TABLE RESET.

Adjust some tests for this.  Port the ALTER TABLE SET and ALTER TABLE
RESET portions of the alter_table regress test to yb_pg_alter_table.

Depends on D12077

Test Plan:
    ./yb_build.sh --java-test org.yb.pgsql.TestPgRegressAggregates
    ./yb_build.sh --java-test org.yb.pgsql.TestPgRegressPartitions
    ./yb_build.sh --java-test org.yb.pgsql.TestPgRegressTable

Reviewers: myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D12081