[#7400] ysql: Prevent drop of database when there is active connection to the DB
Summary:
@RunningJon reported the following:

Session 1, connect to database foo.
Session 2, connect to yugabyte database and drop database foo.
Session 1, execute any query. The query will hang because session 2 dropped the database you are in.

In PostgreSQL, you can't drop a database when there is a session connected to it.

The revision activates the check on other backend before the DB is dropped.

Note: this change only applies to same node.
The database can still be dropped when there are connections to the db from other nodes.

Test Plan:
In session 1:
```
yugabyte=# \c test;
You are now connected to database "test" as user "yugabyte".
test=# SELECT current_database();
 current_database
------------------
 test
(1 row)
```
In session 2:
```
yugabyte=# drop database test;
ERROR:  database "test" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

Reviewers: alex, neil, jason

Reviewed By: jason

Subscribers: jason, mbautin, mihnea, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D10744