Merged PR 1435275: Fixing empty document handling on addToSet transition
### Does this PR have any customer impact?
No.

### Type (Feature, Refactoring, Bugfix, DevOps, Testing, Perf, etc)
Bugfix.

### Does it involve schema level changes? (Table, Column, Index, UDF, etc level changes)
No.

### Are you introducing any new config? If yes, do you have tests with and without them being set?
No.

### Release Note (Refer [Template](../docs/release_notes/pgmongo_template.md))

### Description

This PR fixes a bad input error when an empty document expression was handled by an addToSet transition.

```
[direct: mongos] test> db.coll1.aggregate([ { $group: { _id: "$_id", items: { $addToSet: { $getField: { field: "a", input: { b: 1 } } } } } } ])
MongoServerError: [ActivityId=03940874-08ea-4df5-ad67-9e1f87499861] Bad input format for addToSet transition.
```

The new implementation will ignore the empty document and continue the aggregation execution.

----
#### AI description  (iteration 1)
#### PR Classification
Bug fix to handle empty documents in the `addToSet` transition.

#### PR Summary
This pull request fixes the handling of empty documents in the `addToSet` transition within the BSON aggregation pipeline.
- `oss/pg_helio_api/src/aggregation/bson_aggregates.c`: Added a check to ensure `addToSet` transition skips empty documents.
- `oss/pg_helio_api/src/test/regress/sql/bson_aggregation_pipeline_tests_add_to_set_group.sql` and `oss/pg_helio_api/src/test/regress/expected/bson_aggregation_pipeline_tests_add_to_set_group.out`: Added new test cases to verify the correct handling of empty documents in the `addToSet` transition.