[#3069] [YSQL] yb-admin command to delete namespace, table and index
Summary:
Since YSQL DDLs are not transactional yet, it's possible to result in a scenario where a namespace is present in YB metadata but not in postgres. This can happen if the creation partly succeeds - i.e. namespace is created in YB, but before it was created in postgres system tables, the operation was terminated (due to intermittent network issue or node failure for example).

In this scenario, the namespace is unusable since postgres system tables are unaware of its existence and it just lies around in YB metadata. We should add a yb-admin command to delete namespace that can help recover in such situations.

Another example is https://github.com/yugabyte/yugabyte-db/issues/3032.

We need a way to clean up and remove tables, namespaces, and indexes in case of DDL consistency issues.

Usage:
Delete namespace by name:
```
yb-admin delete_namespace ysql.namespace_name
yb-admin delete_namespace ycql.namespace_name
```

Delete namespace by ID
```
yb-admin delete_namespace_by_id <id>
```

Delete table by name
```
yb-admin delete_table ysql.namespace_name table_name
yb-admin delete_table ycql.namespace_name table_name
```

Delete table by ID
```
yb-admin delete_table_by_id <id>
```

Delete index by name
```
yb-admin delete_index ysql.namespace_name index_name
yb-admin delete_index ycql.namespace_name index_name
```

Delete index by ID
```
yb-admin delete_index_by_id <id>
```
Note that for YSQL, these commands will only delete data from master and not from postgres. These are only meant to be used to clean up master state in case of cluster errors or inconsistencies.

Test Plan:
Tested manually.

Created inconsistent state:
```
yugabyte=# create database nehatest;
ERROR:  Already present: Keyspace 'nehatest' already exists
yugabyte=# \l
                                   List of databases
      Name       |  Owner   | Encoding | Collate |    Ctype    |   Access privileges
-----------------+----------+----------+---------+-------------+-----------------------
 postgres        | postgres | UTF8     | C       | en_US.UTF-8 |
 system_platform | postgres | UTF8     | C       | en_US.UTF-8 |
 template0       | postgres | UTF8     | C       | en_US.UTF-8 | =c/postgres          +
                 |          |          |         |             | postgres=CTc/postgres
 template1       | postgres | UTF8     | C       | en_US.UTF-8 | =c/postgres          +
                 |          |          |         |             | postgres=CTc/postgres
 yugabyte        | postgres | UTF8     | C       | en_US.UTF-8 |
(5 rows)

yugabyte=# create database nehatest;
ERROR:  Already present: Keyspace 'nehatest' already exists
yugabyte=# drop database nehatest;
ERROR:  database "nehatest" does not exist
yugabyte=# create database nehatest;
ERROR:  Already present: Keyspace 'nehatest' already exists
```

Ran `yb-admin delete_namespace ysql.nehatest` and namespace was successfully deleted.

Also, tested delete table and delete index.

Reviewers: bogdan, mihnea

Reviewed By: mihnea

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D7657