[Backport 2.14][PLAT-3725] Add k8s_parent.py entrypoint script
Summary:
Original commit: 23f300d32ca322048f6d511ec973f5ba63a6afbd

This script is used on Kubernetes environments. It starts the DB
process as a child. When the DB process exits or crashes, k8s_parent
script finds the core_pattern and copies any core dump file(s) to the
persistent volume.

It also makes sure that the signals sent by container runtime are
propagated to the DB process correctly. Zombie reaping is still
handled by Tini.

Chart diff: https://phabricator.dev.yugabyte.com/D17818

Test Plan:
Installed Helm chart with this script available, the database
processes were child of k8s_parent. Tini => parent => yb-master => …

Sent SIGTERM to the Tini process:
- yb-tserver received the TERM signal and it was terminated.
- k8s_parent tried to find any core files and then terminated.

```
2022-06-29 14:40:28,722 [INFO] k8s_parent.py: sending 15 to the child process
*** Aborted at 1656513628 (unix time) try "date -d @1656513628" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x7) received by PID 50 (TID 0x7f1d85107100) from PID 7; stack trace: ***
    @     0x7f1d842e69f3 __GI_epoll_wait
    @          0x29ca74d  boost::asio::detail::epoll_reactor::run()
    @          0x29c564c  boost::asio::detail::scheduler::run()
    @          0x29c216d  yb::tserver::(anonymous namespace)::TabletServerMain()
    @          0x29bb279 main
    @     0x7f1d84220825 __libc_start_main
    @          0x269202e _start
2022-06-29 14:40:28,757 [INFO] k8s_parent.py: core_pattern is: /core.%e.%p.%t
2022-06-29 14:40:28,757 [INFO] k8s_parent.py: Copying latest 5 core files to '/mnt/disk0/cores' using glob '/*core*'
2022-06-29 14:40:28,758 [INFO] k8s_parent.py: Copied 0 core files to '/mnt/disk0/cores'
```
- Similar thing happens when we delete the pod, yb-tserver receives
  TERM signal.

Sent SIGQUIT to the yb-tserver process:
- yb-tserver terminated with a core dump.
- k8s_parent copied the core dump file to the volume.
```
2022-06-29 14:43:51,661 [INFO] k8s_parent.py: core_pattern is: /core.%e.%p.%t
2022-06-29 14:43:51,661 [INFO] k8s_parent.py: Copying latest 5 core files to '/mnt/disk0/cores' using glob '/*core*'
2022-06-29 14:43:51,662 [INFO] k8s_parent.py: Copying core file '/core.yb-tserver.80.1656513831'
2022-06-29 14:43:52,590 [INFO] k8s_parent.py: '/dircore' is not a regular file, skipping
2022-06-29 14:43:52,590 [INFO] k8s_parent.py: '/coredirfake' is not a regular file, skipping
2022-06-29 14:43:52,591 [INFO] k8s_parent.py: Copying core file '/core-old-8'
2022-06-29 14:43:52,591 [INFO] k8s_parent.py: Copying core file '/core-old-7'
2022-06-29 14:43:52,591 [INFO] k8s_parent.py: Copying core file '/core-old-6'
2022-06-29 14:43:52,591 [INFO] k8s_parent.py: Copying core file '/core-old-5'
2022-06-29 14:43:52,592 [INFO] k8s_parent.py: Reached max allowed core files, skipping the rest
2022-06-29 14:43:52,592 [INFO] k8s_parent.py: Copied 5 core files to '/mnt/disk0/cores'
```

1. core_pattern using current working directory (copy is skipped as the
   CWD is same as persistent volume destination):
```
2022-06-23 09:45:48,892 [INFO] k8s_parent.py: core_pattern is: core.%e.%p.%t

2022-06-23 09:45:48,892 [INFO] k8s_parent.py: Skipping copy of core files: '/mnt/disk0/cores' and '/mnt/disk0/cores' are the same directories
2022-06-23 09:45:48,892 [INFO] k8s_parent.py: Copied 0 core files to '/mnt/disk0/cores'
```

2. core_pattern using pipe method (we can't do anything here, so we
   exit):
```
2022-06-24 13:57:24,227 [INFO] k8s_parent.py: Core files will be copied to '/mnt/disk0/cores'
2022-06-24 13:57:24,227 [INFO] k8s_parent.py: core_pattern is: |tee /teecore.%e.%p.%t
2022-06-24 13:57:24,227 [WARNING] k8s_parent.py: Core dumps might not get collected: failure while creating the core dump directory: ValueError: core_pattern starts with |, can't do anything useful
…
2022-06-24 13:58:41,166 [INFO] k8s_parent.py: core_pattern is: |tee /teecore.%e.%p.%t
Traceback (most recent call last):
  File "/home/yugabyte/tools/k8s_parent.py", line 172, in <module>
    files_copied = copy_cores(cores_dir)
  File "/home/yugabyte/tools/k8s_parent.py", line 101, in copy_cores
    dir_path = get_core_dump_dir()
  File "/home/yugabyte/tools/k8s_parent.py", line 60, in get_core_dump_dir
    raise ValueError("core_pattern starts with |, can't do anything useful")
ValueError: core_pattern starts with |, can't do anything useful
```

3. core_pattern is some directory path which doesn't exist
   inside the container filesystem beforehand.
```
2022-06-24 13:44:36,192 [INFO] k8s_parent.py: Core files will be copied to '/mnt/disk0/cores'
2022-06-24 13:44:36,192 [INFO] k8s_parent.py: core_pattern is: /var/core/dump/core.%e.%p.%t
…
2022-06-24 13:45:47,291 [INFO] k8s_parent.py: core_pattern is: /var/core/dump/core.%e.%p.%t
2022-06-24 13:45:47,291 [INFO] k8s_parent.py: Copying latest 5 core files to '/mnt/disk0/cores' using glob '/var/core/dump/*core*'
2022-06-24 13:45:47,292 [INFO] k8s_parent.py: Copying core file '/var/core/dump/core.yb-tserver.36.1656078347'
2022-06-24 13:45:48,255 [INFO] k8s_parent.py: Copied 1 core files to '/mnt/disk0/cores'
```

Reviewers: sanketh

Reviewed By: sanketh

Differential Revision: https://phabricator.dev.yugabyte.com/D18113