[#12248] [2.12] YSQL: Give error when user tries to create table using unsupported collation
Summary:
As of D16239, collations nds-x-icu, nds-DE-x-icu, nds-NL-x-icu are no longer supported.

Since we don't plan to backport D16239 to 2.12 branch due to the dependency changes which are not desirable in a minor release, this issue

1. adds error when user tries to create table with unsupported collation or alias unsupported collation.
2. gives warning when user references deprecated collation with this syntax:
```
'a'  COLLATE "nds-x-icu"
```
This is only for 2.12 branch since the 3 unsupported collations are already removed in 2.13+.
yb_upgrade_db.out and yb_upgrade_db.sql are added so that future collation patches from 2.13+ wouldn't have conflict in backporting.
They contain the statements exercising the scenarios shown in manual testing.

Test Plan:
Jenkins: rebase: 2.12

With this patch:
```
yugabyte=# CREATE TABLE collate_test_fail(b text COLLATE "nds-x-icu");
ERROR:  collation no longer supported and will be dropped in next release
LINE 1: CREATE TABLE collate_test_fail(b text COLLATE "nds-x-icu");
                                              ^
yugabyte=# create collation nds from "nds-x-icu";
ERROR:  cannot create collation based on deprecated collation

yugabyte=# select * from collate_test_fail where b like 'a'  COLLATE "nds-x-icu";
WARNING:  collation is deprecated
LINE 1: select * from collate_test_fail where b like 'a'  COLLATE "n...
                                                          ^
 b
---
(0 rows)
```

./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressFeature'

Reviewers: myang, alex

Reviewed By: myang, alex

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D16661