[#28864] YSQL: Disallow BNL when inner table is temp
Summary:
Batched Nested Loop (BNL) joins fail when the inner relation is a temporary table, causing either a cache lookup error in release builds or an assertion failure in debug builds.

```
CREATE TEMP TABLE tmp2 (id int, name text);
CREATE TABLE reg2 (id int, name varchar(10));

INSERT INTO tmp2 VALUES (1, 'A'), (2, 'B'), (3, 'C');
INSERT INTO reg2 VALUES (1, 'A'), (2, 'B'), (3, 'C');

CREATE INDEX tmp2_idx ON tmp2(id, name);

ANALYZE tmp2;
ANALYZE reg2;

/*+ YbBatchedNL(tmp2 reg2) */
SELECT * FROM tmp2 JOIN reg2 ON tmp2.id = reg2.id AND tmp2.name = reg2.name;
```

on release builds:
```
ERROR: cache lookup failed for type 0
```
on debug builds:
```
Assert(!(cur->sk_flags & (SK_ROW_HEADER | SK_SEARCHNULL | SK_SEARCHNOTNULL)));
```

The root cause is that PG's btree implementation (used by temporary indexes) doesn't support multi-column search arrays as scan keys.

This revision simply prevents BNL from being considered when the inner relation is temporary, as there is no benefit to batching in this scenario anyway.

Test Plan: ./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressJoinPlans'

Reviewers: mtakahara

Reviewed By: mtakahara

Subscribers: mtakahara, yql

Differential Revision: https://phorge.dev.yugabyte.com/D47340