[pg15] fix: remove duplicate code from past merge
Summary:
Thanks to the faulty YB pg15 initial merge
55782d561e55ef972f2470a4ae887dd791bb4a97 of dbcommands.c dropdb, the
code block corresponding to

    if (CountOtherDBBackends(db_id, &notherbackends, &npreparedxacts))

was duplicated.  It should have only left one copy.  Each copy was moved
to that location on both sides:

- YB master: 1833bb095a2590a3cac9cb0ff8122e127decda0f
- Upstream PG: 9fab25c6cd1f943284b8e0014007cd5750d54308

Thereafter, YB pg15 merge 4e9241bd7675351ad26285e2cf124207ca09fa6d
cleanly merged dbcommands.c, where the changes by YB master
5e0cc5a2b4e1962a86261d971bce7f4ac82d6bab only affected the first copy
and not the second.  Consequently, some tests fail with YSQL Connection
Manager enabled.  For example, TestPgRegressPlanner:

    ERROR: database "base_scans_cost_model" is being accessed by other users
      Detail: There is 1 other session using the database.

Fix by removing the second copy.  Tests are still failing with YSQL
Connection Manager for other reasons.

Test Plan: Jenkins: rebase: pg15, enable connection manager, all tests

Reviewers: rbarigidad

Reviewed By: rbarigidad

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D38022