[#21467, #24153] Docdb: Add Read sequences as of time - sequences support for clone part 2
Summary:
Currently, if we try to clone to a time before a drop sequence happened on the original table, clone fails with the following error:
```
ERROR:  Unable to find relation for sequence 16384
```

The reason for the failure is that ysql_dump is unable to get the last_value of the dropped sequence. This is because the sequence is dropped and we cannot perform read as of time to the `system_postgres.sequences_data` table.

This diff adds the ability to **read** the sequences_data table as of a point in time in the past using the `yb_read_time` GUC variable. The yb_read_time didn't cover reading sequences in the past, as sequences operations use an independent YBSession and different RPCs than the `Perform` RPC used in most other read/write operations. This diff extends yb_read_time GUC to cover `ReadSequenceTuple` RPC. An example of usage:

```
CREATE SEQUENCE seq_1;
db1=# SELECT * FROM seq_1;
 last_value | log_cnt | is_called
------------+---------+-----------
          1 |       0 | f

db1=# SELECT (EXTRACT (EPOCH FROM CURRENT_TIMESTAMP)*1000000)::decimal(38,0);
     numeric
------------------
 1727315135780060

db1=# SELECT nextval('seq_1');
 nextval
---------
       1

db1=# SELECT * FROM seq_1;
 last_value | log_cnt | is_called
------------+---------+-----------
        100 |       0 | t

db1=# SET yb_read_time TO 1727315135780060;
SET
db1=# SELECT * FROM seq_1;
 last_value | log_cnt | is_called
------------+---------+-----------
          1 |       0 | f
```
**Upgrade/Rollback safety:**
Only adding in a new optional field `read_time` to `PgReadSequenceTupleRequestPB`.
- If an old message is sent to a service with the new format, the read_time field is set to 0 "default" and the read request will be executed as of the latest time (the default behaviour before this diff).
- If a new message is sent to a service with an older message format, the read_time field will be ignored and the read happens as of the current time.
Knowing that this message only affects pure read requests, no undesired inconsistency is introduced.

Jira: DB-10350, DB-13040

Test Plan:
./yb_build.sh --cxx-test integration-tests_sequence_utility-itest --gtest_filter SequencesUtilTest.ReadSequencesAsOfTime

Also Enabled the following PITR tests for clone and all of them passed after this diff:
PgsqlSequenceUndoDropSequence
PgsqlSequenceVerifyPartialRestore
PgsqlSequencePartialCleanupAfterRestore

Example to run one of them:
./yb_build.sh --cxx-test yb-admin-snapshot-schedule-test --gtest_filter ColocationAndRestoreType/YbAdminSnapshotScheduleTestWithYsqlColocationRestoreParam.PgsqlSequenceUndoDropSequence/3

3 and 4 are the parameters for clone (non-colocation and colocation respectively)

Reviewers: hsunder, asrivastava, mlillibridge

Reviewed By: asrivastava

Subscribers: yql, slingam, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D38392