[#19049] ysql: Use appropriate database for control connection in Ysql Connection Manager
Summary:
Ysql Connection Manager needs a control connection on which it will execute internal queries.
As of now `template1` database is being used to create control connections.
But this blocks the `CREATE DATABASE` statement.
```
postgres=# create database db1;
ERROR:  source database "template1" is being accessed by other users
DETAIL:  There are 30 other sessions using the database.
```

Since users can destroy any database (even yugabyte), the database for the control connection can not be hardcoded.
This diff adds a flag `ysql_conn_mgr_internal_conn_db`, which will be the database used to create a control connection.
Jira: DB-7865

Test Plan:
Added java test for working of `CREATE DATABASE` query.
`./yb_build.sh --java-test org.yb.ysqlconnmgr.TestMisc#testCreateDb`

Reviewers: nkumar, tverona, kkg

Reviewed By: nkumar, kkg

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D28542