Fix traceback missing during build error.
Summary:
Import was missing causing:
```
17/12/07 09:21:31 INFO DAGScheduler: Job 1 failed: collect at /n/jenkins/workspaces/yugabyte-phabricator@2/build-support/run_tests_on_spark.py:674, took 312.714731 s
Traceback (most recent call last):
  File "/n/jenkins/workspaces/yugabyte-phabricator@2/build-support/run_tests_on_spark.py", line 731, in <module>
    main()
  File "/n/jenkins/workspaces/yugabyte-phabricator@2/build-support/run_tests_on_spark.py", line 677, in main
    traceback.print_exc()
NameError: global name 'traceback' is not defined
```

Test Plan: Jenkins.

Reviewers: mikhail

Reviewed By: mikhail

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D3667