[#14814] YSQL: Exception handling in pushdown framework
Summary:
We had basic error handling since we implemented the expression
pushdown, though there were a number of flaws, some of them were
quite severe:
- Any Postgres error's severity was treated as ERROR, it meant elog or
  ereport interrupted execution flow, regardless of severity. The
  DEBUG, LOG, WARNING etc. severities are not supposed to do that;
- No support for PG_TRY / PG_CATCH;
- No support for localization.

This commit address those issues. It updates macros: elog, ereport,
PG_TRY, PG_CATCH, PG_END_TRY, PG_RE_THROW defined in elog.h to behave
differently in multi-thread environment, that means if Postgres code
is invoked from DocDB.

The elog, ereport macros use different functions to start and finish
error composing sequence in multi-thread mode. Rather than put
error info into global ErrorData, these functions put error info into
thread-local YbgStatus. Regular errXXX() functions are modified
for multi-thread mode to fill out the elog.c private data structure
(YbgErrorData) linked with YbgStatus. Some of them do nothing,
as we do not support yet Postgres' error details, hints, context, etc.
When the error composing sequence is finishing, for errors with severity
ERROR or higher, the data from the YbgErrorData structure is transferred
to YbgStatus and longjmp to current error handler is performed.

The error handler, compatible with PG_TRY, is set by the
PG_SETUP_ERROR_REPORTING macro and removed by PG_STATUS_OK. The
PG_SETUP_ERROR_REPORTING(); and PG_STATUS_OK() must appear in a
function returning YbgStatus, and must surround code calling YbGate
functions. It is recommended to put PG_SETUP_ERROR_REPORTING(); as
the first statement in the function body and PG_STATUS_OK(); as the
last, however it is not required, just be aware that PG_STATUS_OK()
returns current YbgStatus from the function, empty YbgStatus is
success. PG_SETUP_ERROR_REPORTING and PG_STATUS_OK calls must not
be nested. Failure to surround code with PG_SETUP_ERROR_REPORTING and
PG_STATUS_OK is not critical if it does not emit errors. It is OK if
code raises an error in PG_TRY block, but if uncaught it would kill
tserver.

This framework change does not make too much difference yet, DocDB
executes limited parts of Postgres code yet where not too many errors are raised.
Though the framework now preserves SQL error codes and error location and removes
DocDB status types from the error message, so Yugabyte errors look more like
respective Postgres error:
```
yugabyte=# \set VERBOSITY verbose
yugabyte=# select * from foo where 2 / v = 1;
ERROR:  22012: division by zero
LOCATION:  int4div, int.c:820
```
In future pushdown code will be easier to debug. In addition to correct location info,
elog/ereport would also put a message to the DocDB log. Also it adds a framework
to unit test YBGate and Postgres code.

Removes undocumented env variable YB_PG_REPORT_ERROR_STATUS that might be
used to log extra info about DocDB status received by Postgres.

Test Plan:
ybd --cxx-test=docdb_pgapi-test
ybd --java-test org.yb.pgsql.TestPgLocale#testDivisionByZeroMessage

Reviewers: dmitry, mbautin, mihnea, sergei, jason

Reviewed By: jason

Subscribers: yql, bogdan

Differential Revision: https://phabricator.dev.yugabyte.com/D21788