[PLAT-7702] Preventing volume expansion if there are stale PVCs in namespace
Summary:
If there are extra tserver PVCs in the namespace - probably left behind from a previous universe shrink operation - the expand volume workflow will fail. This is because, the workflow will expand all the PVCs found in the namespace and wait for an attached pod to finish file system resize. We have a few options to fix this issue:
1. Tolerate extra PVCs in the namespace. So ignore error conditions on PVCs when it is waiting for file system resize.
2. Delete the PVCs (along with the pod) when shrinking a universe.
3. Add a pre-check to fail early if there are orphaned PVCs in the namespace.

Option 1 would lead to not waiting for file system expansion even for attached volumes. This can lead to further errors downstream in the workflow.
Option 2 can be considered, but there can be other causes for orphaned PVCs. So this does not fix the issue well enough.

This diff implements option (3).

Test Plan:
1. Created  orphaned PVCs in the namespace. Then manually verified that the workflow fails with an error.
```
YW 2023-03-16T00:28:40.675Z [INFO] f0bb3751-c47f-4bbe-b878-6f46e7008f6c from KubernetesCheckVolumeExpansion in TaskPool-EditKubernetesUniverse-0 - Verifying that there are no orphan PVCs
YW 2023-03-16T00:28:40.675Z [INFO] f0bb3751-c47f-4bbe-b878-6f46e7008f6c from KubernetesCheckVolumeExpansion in TaskPool-EditKubernetesUniverse-0 - PVCs present in namespace [ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-2, ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-1, ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-0] should be same as attached PVCs [ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-1, ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-0]
YW 2023-03-16T00:28:40.679Z [ERROR] f0bb3751-c47f-4bbe-b878-6f46e7008f6c from TaskExecutor in TaskPool-EditKubernetesUniverse-0 - Failed to execute task type KubernetesCheckVolumeExpansion UUID 9d8215f3-32b3-4408-97a6-f1d157a4d123 details {"platformVersion":"2.17.3.0-PRE_RELEASE","config":{"OVERRIDES":"","KUBECONFIG":"/opt/yugaware/keys/f21405d6-0fb2-456e-a45c-4557eaf3d8bc/ef659b1b-c9ef-48f2-9591-0a0ed692ac2a/55eac7e2-c765-475f-8a13-d13c9084d021/yugabyte-helm.kube-system.k8s-portal-gke.conf","STORAGE_CLASS":"yb-standard"},"newNamingStyle":true,"namespace":"yb-admin-subbu-univ","providerUUID":"f21405d6-0fb2-456e-a45c-4557eaf3d8bc","helmReleaseName":"ybsubbu-univ-2aej"}, hit error.
java.lang.RuntimeException: Please remove these orphan PVCs from namespace yb-admin-subbu-univ before attempting this operation: [ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-2]
```
Also see attached screenshot of how this error surfaces on the UI.
{F35429}

2. After above step, manually deleted the PVC and verified that without orphaned PVCs in the namespace, volume expansion works as expected.
```
YW 2023-03-16T01:58:10.924Z [INFO] 20f68e6e-3624-4530-82db-a310f4cb0201 from KubernetesCheckVolumeExpansion in TaskPool-EditKubernetesUniverse-0 - Verifying that there are no orphan PVCs
YW 2023-03-16T01:58:10.924Z [INFO] 20f68e6e-3624-4530-82db-a310f4cb0201 from KubernetesCheckVolumeExpansion in TaskPool-EditKubernetesUniverse-0 - PVCs present in namespace [ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-1, ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-0] should be same as attached PVCs [ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-1, ybsubbu-univ-2aej-datadir0-ybsubbu-univ-2aej-yb-tserver-0]
```

Reviewers: sanketh, vkumar, anijhawan, bgandhi

Reviewed By: anijhawan, bgandhi

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D23490