[#28963] YSQL: Fix link error with compilecmds
Summary:
98881cf009c5 / D47013 introduced a link error by calling YBCGetGFlags() in pg_yb_common.c.

Sample error:
```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
ld.lld: error: undefined symbol: YBCGetGFlags
>>> referenced by pg_yb_common.c:181 ...
```

The symbol is undefined since YBCGetGFlags is called in pg_yb_common.c and pg_yb_common.o is linked to initdb. However, YBCGetGFlags is part of the yb_pggate lib and this lib is not linked with compilecmds.

Remove an if condition. Thus, linking yb_pggate when building the compilecmds target as well.
Jira: DB-18701

Test Plan:
Jenkins

./yb_build.sh compilecmds

Reviewers: jason, smishra

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D47509