[PLAT-6234] Add foreign key constraint for access_key.provider_uuid
Summary:
Given that there was no constraint ensuring referential integrity, it is very much possible that there are dangling
references and migration can fail.
Thus we to be on the safer side and avoid data loss

- we will create `access_key_no_provider_bak` table and copy any access_key rows that will be deleted in next step.
- Then delete any dangling reference rows from the `access_key` table
- Finally introduce the constraint.

Test Plan:
Tried the sql on dev portal.
Indeed as ewxpected there were 4 dangling references on dev portal

```
yugaware=*# ALTER TABLE IF EXISTS access_key
    ADD CONSTRAINT fk_access_key_provider_uuid
        FOREIGN KEY (provider_uuid) REFERENCES provider (uuid)
	    ON DELETE CASCADE ON UPDATE CASCADE;
	    ERROR:  insert or update on table "access_key" violates foreign key constraint "fk_access_key_provider_uuid"
	    DETAIL:  Key (provider_uuid)=(XXXXXXXXXXXXXXXXXXXXXX) is not present in table "provider".
```

But after doing the multi step process from this migration things complete successfully and all the data is backed up in case customer wants it.
Rolledback the portal to original state.

NOTE: We should be deleting the the `access_key_bak ` after few releases. I will file tacking ticket before submitting this diff.

Reviewers: yshchetinin, hzare, nsingh

Reviewed By: nsingh

Subscribers: jenkins-bot, sanketh, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D20961