[pg15] fix: start DDL transaction for VACUUM ANALYZE
Summary:
Context: PG in commit 6776142a07afb4c28961f27059d800196902f5f1 reworked the parsetree for VACUUM and ANALYZE.

ANALYZE in YB must be executed inside a DDL transaction as it can update catalog relations. The initial merge commit 55782d561e55ef972f2470a4ae887dd791bb4a97 incorrectly incorporated the above change in this context - it started a DDL transaction for ANALYZE but not for VACUUM ANALYZE. As a result, VACUUM ANALYZE, when trying to update catalog tables, throws:
   ERROR:  Transaction for catalog table write operation '<relation_name>' not found

Fix it by starting a DDL transaction for VACUUM ANALYZE as well.

TestPgRegressThirdPartyExtensionsPgHintPlan passes with this change. It started failing after D33614 in which TRUNCATE reset reltuples to -1 and VACUUM ANALYZE tried to set it to 0. Before  D33614, TRUNCATE reset reltuples to 0, and hence VACUUM ANALYZE did not need to update it.

Clean up the related incorrect expected output added by D30960.

Test Plan:
Jenkins: rebase: pg15
   ./pg15_tests/test_lint.sh
   ./yb_build.sh --java-test org.yb.pgsql.TestPgRegressThirdPartyExtensionsPgHintPlan -n 10
   ./yb_build.sh --java-test org.yb.pgsql.TestPgMisc#testVacuum -n 10

Reviewers: jason

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D33765