[BACKPORT 2.12] [#12004] YSQL: Explicit locking statement doesn't create a transaction when using READ COMMITTED in YSQL that maps to REPEATABLE READ
Summary:
This backport to 2.12 fixes two bugs in code as mentioned in the original commit
summary below. The first bug which is a regression due to D15991 isn't valid for
2.12 since D15991 isn't backported to 2.12. The second fix is still valid. Also,
the changes that fix the first bug are still cherry-picked since they don't
change any behaviour in 2.12 and will moreover ensure safety by throwing a merge
conflict when an attempt to cherry-pick D15991 to 2.12 is made.

If yb_enable_read_committed_isolation=false, a "READ COMMITTED" transaction in
YSQL maps to SNAPSHOT ISOLATION in docdb. Currently, a user running with
yb_enable_read_committed_isolation=false is not able to issue a "select ... for
update" as the first statement, if a txn was started with "begin transaction
isolation level read committed;".

This is because no transaction seems to be created if three conditions occur -

(i) "yb_enable_read_committed_isolation=false",
(ii) a READ COMMITTED txn is started in YSQL, and
(iii) the first statement is a "SELECT ... FOR UPDATE" or any other explicit
locking statement.

```
yugabyte=# begin transaction isolation level read committed;
BEGIN
yugabyte=# select * from test where k=1 for update;
ERROR:  Not implemented: Read request with row mark types must be part of a transaction: OPERATION_NOT_SUPPORTED
yugabyte=#
```

There are 2 bugs in code that cause this (only if present together) - one is a
regression which is the cause, another is a bug in read committed implementation
which, if corrected, masks the regression. More details -

(1) The regression:

As part of D15991, RunHelper::Apply() in pg_session.cc doesn't set read_only to
false for a "SELECT ... FOR UPDATE" type of statement if the pg_isolation_level
is READ COMMITTED. Before this diff, read_only was set to false for explicit
locking statements always irrespective of the isolation level. Not setting
read_only to false, causes no transaction to be started if that is the first
operation in the YSQL transaction block.

(2) Day-0 bug, which if fixed separately, it would mask bug (1):

In xact.c, we set pg_isolation_level to XactIsoLevel. And, as part of D15383, we
have extra logic to set it to XACT_REPEATABLE_READ if XactIsoLevel is
XACT_READ_COMMITTED and read committed mode is on. This is the place where READ
COMMITTED isolation maps to REPEATABLE READ if
yb_enable_read_committed_isolation=false (i.e., the old behaviour when read
committed isolation was not implemented).

But, we forgot to add the same logic before calling
YBCPgSetTransactionIsolationLevel() in assign_XactIsoLevel(). This diff adds
that. Not adding that logic causes "READ COMMITTED" isolation in ysqlsh to use
READ COMMITTED in doc db even if yb_enable_read_committed_isolation=false.

Bug (1) is a regression (D15991) and bug (2) was part of the READ COMMITTED
isolation implementation (D15383). Bug (2) along with bug (1) results in the bad
behaviour above.

Original commit: 331a48b927dba2b90e8cd05267b78fc6fa71d01a / D16866

Test Plan:
Jenkins: urgent
./yb_build.sh --java-test org.yb.pgsql.TestPgTransactions#testMiscellaneous

Reviewers: dmitry, mtakahara

Reviewed By: mtakahara

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D17146