[#11645] YSQL: Fix flaky test yb_feature_temp
Summary:
The test yb_feature_temp in TestPgRegressFeature.testPgRegressFeature is flaky and the test
can fail with
```
java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb_feature_temp]
```

After debugging, I found that the following output isn't stable:

```
\d temptest
            Table "pg_temp_2.temptest"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           | not null |
 v1     | integer |           |          |
 v2     | integer |           |          |
Indexes:
    "temptest_pkey" PRIMARY KEY, btree (k ASC)
    "temptest_v1_idx" UNIQUE, btree (v1 ASC)
    "temptest_v2_idx" hash (v2)
```

Temporary schema name may be `pg_temp_1`, `pg_temp_2`, etc. As a result the above output isn't
stable.

I made a change to make the test output stable by
(1) store the output of `\d temptest` into a file that can be auto-removed as part of
    test cleanup after the test completes
(2) read the file back into a ysqlsh variable as a text value
(3) use regexp_replace to change pg_temp_1, pg_temp_2 or the like to pg_temp_xxx

Test Plan:
./yb_build.sh debug --java-test 'org.yb.pgsql.TestPgRegressFeature' --tp 1 -n 5

No longer see
```
java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb_feature_temp]
```

Reviewers: jason, tverona, dsrinivasan

Reviewed By: dsrinivasan

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D20465