[#17598] Make destructor of GarbageCollector virtual
Summary:
The `GarbageCollector` has protected non-virtual destructor and virtual function. As a result each subclass of `GarbageCollector` requires to declare virtual destructor. Without such declaration compilation fails due to error like this

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
../../src/yb/tserver/pg_response_cache.cc:195:24: error: 'yb::tserver::PgResponseCache::Impl' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
class PgResponseCache::Impl : public GarbageCollector, public std::enable_shared_from_this<Impl> {
```

Solution is to declare virtual destructor in `GarbageCollector` class.

**Note:** In additional to core changes some cleanup in the MemTracker class were made:
- use boost::small_vector instead of std::vector for garbage collectors to avoid (reduce) memory allocations while calling garbage collectors
- substitute hand made code with standard algorithms `std::erase_if` / `boost::remove_erase_if`

Test Plan: Jenkins

Reviewers: sergei, timur

Reviewed By: sergei

Subscribers: bogdan

Differential Revision: https://phorge.dev.yugabyte.com/D25819