[#18629] YSQL: flaky test: TestPgRegressMisc.testPgRegressMiscSerial in tsan build
Summary:
The test TestPgRegressMisc.testPgRegressMiscSerial in tsan build has timed out
before it completes all the tests in the schedule. Under tsan build a test
can take longer time to run:

```
  /** @return a timeout multiplier to apply in tests based on the build type */
  public static double getTimeoutMultiplier() {
    if (isTSAN())
      return 3;
    if (isASAN())
      return 1.5;
    return 1;
  }
```

I spinned off more test schedules from the original one so that each schedule
can pass under tsan build.
Jira: DB-7556

Test Plan:
(1) ./yb_build.sh tsan --java-test 'org.yb.pgsql.TestPgRegressMisc#testPgRegressMiscSerial'
(2) ./yb_build.sh tsan --java-test 'org.yb.pgsql.TestPgRegressMisc#testPgRegressMiscSerial2'
(3) ./yb_build.sh tsan --java-test 'org.yb.pgsql.TestPgRegressMisc#testPgRegressMiscSerial3'
(4) ./yb_build.sh tsan --java-test 'org.yb.pgsql.TestPgRegressMisc#testPgRegressMiscSerial4'

Before the change, (1) failed with the following message:
org.junit.runners.model.TestTimedOutException: test timed out after 1800 seconds
        at org.yb.pgsql.TestPgRegressMisc.testPgRegressMiscSerial(TestPgRegressMisc.java:45)

After the change, all the above 4 tests passed.

Reviewers: jason, dsrinivasan

Reviewed By: dsrinivasan

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D27785