ENG-5280 #1189 Use boost::atomic for 16-bytes structures
Summary:
For std::atomic `gcc-7` generates non lock-free code for 16 bytes structures even in case `-mcx16` flags is
used for compilation.
Solution is to substitute `std::atomic` with `boost::atomic` for all 16 bytes structures used in YB code

Also false positive `array-bounds` error (due to agressive `-O3` optimization in `release` build) is
fixed in `slice_transform_test.cc`

```
In file included from src/yb/rocksdb/slice_transform.h:34:0,
                 from src/yb/rocksdb/util/slice_transform_test.cc:24:
src/yb/util/slice.h: In member function ‘virtual void rocksdb::SliceTransformTest_CapPrefixTransform_Test::TestBody()’:
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
```

Using `Slice()` explicitly instead of implicit `Slice(const char* s)` constructor for `""` (empty string) solves the issue.
Problem is very specific for this particular place. There is no issue with creation of `Slice` from `""` all the time.

Test Plan: build  and run YB cluster in `debug` and `release` mode with using gcc-7 (`ubuntu` 16+ have gcc-7 as a default compiler)

Reviewers: raju, mikhail, sergei

Reviewed By: sergei

Subscribers: ybase, bogdan

Differential Revision: https://phabricator.dev.yugabyte.com/D6800