[BACKPORT 2.25.0.1143][PLAT-15489]Remote denial of service (DDoS) on authentication with invalid admin tokens
Summary:
https://phorge.dev.yugabyte.com/D35345 migration V349 converts API token to hashed form. This caused significant delays. So https://phorge.dev.yugabyte.com/D37083 introduced `2$userUUID$apiToken`.
CLI clients could not parse `$` as the separator without `''`. So https://phorge.dev.yugabyte.com/D37463 changed it to `3.userUUID.apiToken`

YBM team reported this issue with the concern that occasionally the clients could end up with an invalid api token and this leads the YBA to max out on CPU and become unresponsive. This is due to the loop that was introduced in D35345.

The change introduces a Global runtime config `yb.user.disable_v1_api_token` that can be used to skip the V1 token loop entirely. If this is set to true, the follow error is thrown while using only the API token without the version number and userUUID with separators (either `$` or `.`):
```
2024-10-24T15:46:51.537Z  [error] 6f508e27-701b-4d49-baaa-13097d031794 Users.java:548 [application-pekko.actor.default-dispatcher-669] com.yugabyte.yw.models.Users Error while authenticating API token
com.yugabyte.yw.common.PlatformServiceException: API Token version 1 is disabled. Please reissue the token. To allow this version of token, please set yb.user.disable_v1_api_token config to false.
        at com.yugabyte.yw.models.Users.authWithApiToken(Users.java:527)
        at com.yugabyte.yw.controllers.TokenAuthenticator.getCurrentAuthenticatedUser(TokenAuthenticator.java:153)
        at com.yugabyte.yw.controllers.TokenAuthenticator.call(TokenAuthenticator.java:190)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:184)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
        at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:104)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:66)
        at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
        at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
        at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
        at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
        at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:230)
        at org.apache.pekko.stream.impl.Transform.apply(TraversalBuilder.scala:169)
        at org.apache.pekko.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:532)
        at org.apache.pekko.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:458)
        at org.apache.pekko.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:450)
        at org.apache.pekko.stream.scaladsl.RunnableGraph.run(Flow.scala:772)
        at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:138)
        at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:139)
        at play.core.server.PekkoHttpServer.$anonfun$runAction$3(PekkoHttpServer.scala:467)
        at org.apache.pekko.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:49)
        at org.apache.pekko.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:59)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
        at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
        at com.yugabyte.yw.common.logging.MDCPropagatingDispatcher$1.run(MDCPropagatingDispatcher.java:72)
        at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
        at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
        at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
        at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Original commit: 4d236f0eb5942180bcdbb778cf78e90a93a0c9cd / D39418

Test Plan:
  # Authenticate using all 3 versions when the runtime config is false - Login successful

  # Enable runtime config, authenticate using all 3 tokens, version 2 and 3 pass while version 1 throws the error in the summary

Reviewers: sneelakantan, amalyshev, nbhatia, daniel

Reviewed By: amalyshev

Subscribers: yugaware, svc_phabricator, daniel

Differential Revision: https://phorge.dev.yugabyte.com/D39481