#1687 [YSQL] Support YSQL tables in yb-admin commands
Summary:
For now SQL table name is not unique as SQL schema name is ignored by YB cluster.
As a result `CatalogManager` can’t find SQL table by name.
Solution is to resolve table id by table name on `yb-admin` side and send command to YB cluster with table id. `CatalogManager` will not search table by name with such approach.
In case `yb-admin` finds multiple table with same name error message is printed. User is able to call same `yb-admin` command once again by specifying table id instead of table name.

Example:
- DB `yugabyte` has 3 tables with name `common_table` in 3 different schemas

```
yugabyte=# \dt *.common_table
             List of relations
  Schema  |     Name     | Type  |  Owner
----------+--------------+-------+----------
 schema_1 | common_table | table | yugabyte
 schema_2 | common_table | table | yugabyte
 schema_3 | common_table | table | yugabyte
(3 rows)
```

- list tablets of SQL table by table name (will fail)

```
09:57 $ yb-admin list_tablets ysql.yugabyte common_table
Error: Invalid argument (yb/tools/yb-admin_client.cc:354): Namespace 'ysql.yugabyte' has multiple tables named 'common_table', specify table id instead
```

- call same command but with table id instead of table name

```
09:58 $ yb-admin list_tablets tableid.000030a9000030008000000000004003
Tablet UUID                      	Range                                                    	Leader
aaf2eabd172a40e7ad65885ecca98beb 	partition_key_start: "" partition_key_end: "\177\377"    	127.0.0.1:9100
c9b99d7a7448451ea2e2d31d5764ecc3 	partition_key_start: "\177\377" partition_key_end: ""    	127.0.0.1:9100
```

Note:
- in case of using table id it should be prefixed with `tableid.`
- `yb-admin` command `list_tables` + argument `with_table_id` can be used to show table id for all tables

```
10:05 $ yb-admin list_tables include_db_type include_table_id | grep common_table
ysql.yugabyte.common_table tableid.000030a9000030008000000000004003
ysql.yugabyte.common_table tableid.000030a9000030008000000000004006
ysql.yugabyte.common_table tableid.000030a9000030008000000000004009
```

- table id of table in concrete schema can be determined by the following SQL query

```
yugabyte=# SELECT n.nspname AS "Schema",
          c.relname AS "Name",
          '0000' || lpad(to_hex(d.oid::int), 4, '0') || '00003000800000000000' || lpad(to_hex(c.oid::int), 4, '0') AS "Table ID"
        FROM (pg_class c
             LEFT JOIN pg_namespace n ON n.oid = c.relnamespace)
             CROSS JOIN pg_database AS d

        WHERE n.nspname = 'schema_1' AND c.relname='common_table' AND d.datname=current_database();

  Schema  |     Name     |             Table ID
----------+--------------+----------------------------------
 schema_1 | common_table | 000030a9000030008000000000004003
(1 row)
```

Test Plan:
New unit test is introduced:

```./yb_build.sh --cxx-test yb-admin-test```

Reviewers: oleg, mihnea, jason, neha

Reviewed By: neha

Subscribers: neha, yql, bogdan

Differential Revision: https://phabricator.dev.yugabyte.com/D8168