[#33323] YSQL: Fix regressed pushdown tests due to index birth_time changes
Summary:
Commit 7dd192f0d83e / D53646 replaced WaitForBackends with WaitForLockers on the create index concurrently path when object locking is enabled, and added a short WaitForBackends phase in the end before marking the index ready. Index is marked valid despite timeout errors or existence of lagging backends.

The change regressed the following pushdown tests
1. both `TestPgPushdown.aggregatesVar` and `TestPgPushdown.aggregatesConst` were asserting that the reads pushdown the filter and also increment the `handler_latency_yb_ysqlserver_SQLProcessor_Transactions` by just 1. WaitForYsqlBackendsCatalogVersion is rejected with TryAgain until TimeSinceElectedLeader exceeds master_ysql_operation_lease_ttl_ms (30s). CREATE INDEX's short wait gives up at 20s, so leftover pg_stat_activity polls can still run during later SELECTs and inflate `SQLProcessor_Transactions` thus regressing the tests.
```
ts1|pid438931|:20379|http://127.94.189.168:23380 2026-08-18 22:00:02.857 UTC [439329] LOG:  execute <unnamed>: SELECT COUNT(id),COUNT(v),SUM(id),SUM(v),MAX(id),MAX(v),MIN(id),MIN(v),AVG(id),AVG(v) FROM aggregate
ts1|pid438931|:20379|http://127.94.189.168:23380 2026-08-18 22:00:02.966 UTC [439329] LOG:  execute <unnamed>: /*+SeqScan(aggregate)*/SELECT COUNT(id),COUNT(v),SUM(id),SUM(v),MAX(id),MAX(v),MIN(id),MIN(v),AVG(id),AV
G(v) FROM aggregate
ts1|pid438931|:20379|http://127.94.189.168:23380 2026-08-18 22:00:03.037 UTC [439329] LOG:  execute <unnamed>: /*+IndexOnlyScan(aggregate aggregate_index)*/SELECT COUNT(id),COUNT(v),SUM(id),SUM(v),MAX(id),MAX(v),MIN
(id),MIN(v),AVG(id),AVG(v) FROM aggregate WHERE v > 2500
ts1|pid438931|:20379|http://127.94.189.168:23380 2026-08-18 22:00:03.072 UTC [439599] LOG:  execute <unnamed>: SELECT count(*) FROM pg_stat_activity WHERE backend_type != 'walsender' AND backend_type != 'yb-conn-mgr
 walsender' AND backend_type != 'yb auto analyze backend' AND backend_type != 'yb index backfill' AND backend_type != 'yb matview refresh' AND catalog_version < 7 AND datid = 13665 AND pid != 439329
ts3|pid439050|:11523|http://127.199.60.201:32339 2026-08-18 22:00:03.116 UTC [439598] LOG:  execute <unnamed>: SELECT count(*) FROM pg_stat_activity WHERE backend_type != 'walsender' AND backend_type != 'yb-conn-mgr
 walsender' AND backend_type != 'yb auto analyze backend' AND backend_type != 'yb index backfill' AND backend_type != 'yb matview refresh' AND catalog_version < 7 AND datid = 13665
ts1|pid438931|:20379|http://127.94.189.168:23380 2026-08-18 22:00:03.151 UTC [439329] LOG:  execute <unnamed>: /*+IndexScan(aggregate aggregate_index)*/SELECT COUNT(id),COUNT(v),SUM(id),SUM(v),MAX(id),MAX(v),MIN(id)
,MIN(v),AVG(id),AVG(v) FROM aggregate WHERE v > 2500
ts2|pid438989|:16421|http://127.12.184.201:23315 2026-08-18 22:00:03.215 UTC [439596] LOG:  execute <unnamed>: SELECT count(*) FROM pg_stat_activity WHERE backend_type != 'walsender' AND backend_type != 'yb-conn-mgr
 walsender' AND backend_type != 'yb auto analyze backend' AND backend_type != 'yb index backfill' AND backend_type != 'yb matview refresh' AND catalog_version < 7 AND datid = 13665
22:00:03.227 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:41)] Assertion error:
java.lang.AssertionError: 'handler_latency_yb_ysqlserver_SQLProcessor_Transactions' count delta assertion failed for query '/*+IndexScan(aggregate aggregate_index)*/SELECT COUNT(id),COUNT(v),SUM(id),SUM(v),MAX(id),MAX(v),MIN(id),MIN(v),AVG(id),AVG(v) FROM aggregate WHERE v > 2500' expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.yb.AssertionWrappers.lambda$assertEquals$38(AssertionWrappers.java:594)
        at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:46)
        at org.yb.AssertionWrappers.assertEquals(AssertionWrappers.java:594)
        at org.yb.pgsql.BasePgSQLTest$MetricCountChecker.check(BasePgSQLTest.java:1027)
        at org.yb.pgsql.BasePgSQLTest$QueryExecutionMetricChecker.afterQueryExecution(BasePgSQLTest.java:1009)
        at org.yb.pgsql.BasePgSQLTest.verifyQuery(BasePgSQLTest.java:1068)
        at org.yb.pgsql.BasePgSQLTest.verifyStatementMetric(BasePgSQLTest.java:1077)
        at org.yb.pgsql.TestPgPushdown$AggregatePushdownTester.verifyPushdown(TestPgPushdown.java:1793)
        at org.yb.pgsql.TestPgPushdown$AggregatePushdownTester.test(TestPgPushdown.java:1781)
```
2. `TestPgPushdown.in_secondaryIndex` asserts that the query execution time with index is better by 1.3 times than the sequential scan execution. It is unclear why the test regressed, and the failures don't seem to show up when run locally. From one of the jenkins failure logs, it can be seen that the waitforbackends query might be run in concurrent to the selects and thus affecting the instrumentation time (again due to the issue described in 1 above)
```
m3|pid55125|:32188 I0818 14:44:09.863633 55193 ysql_backends_manager.cc:152] WaitForYsqlBackendsCatalogVersion: database_oid: 13665 catalog_version: 7 requestor_ts_uuid: "{ts1_peer_id}" requestor_pg_backend_pid: 55577
java.lang.AssertionError: Query 'com.yugabyte.jdbc.PgStatement@2a05a961' took 41 ms! Expected 40 ms at most
	at org.junit.Assert.fail(Assert.java:89)
...
ts1|pid55220|:21784 2026-08-18 14:44:10.395 UTC [55813] STATEMENT:  SELECT count(*) FROM pg_stat_activity WHERE backend_type != 'walsender' AND backend_type != 'yb-conn-mgr walsender' AND backend_type != 'yb auto analyze backend' AND backend_type != 'yb index backfill' AND backend_type != 'yb matview refresh' AND catalog_version < 7 AND datid = 13665 AND pid != 55577
ts1|pid55220|:21784 2026-08-18 14:44:10.395 UTC [55813] LOG:  failed to abort DML transaction during shutdown: Shutdown connection
ts2|pid55281|:10225 2026-08-18 14:44:10.395 UTC [55504] LOG:  checkpoint starting: shutdown immediate
```

This revision makes the following changes
- fixes `TestPgPushdown.aggregatesVar` and `TestPgPushdown.aggregatesConst` by changing the assert to just check for pushdown as opposed to relying on the per node global `handler_latency_yb_ysqlserver_SQLProcessor_Transactions` metric's delta to be 1.
- sets the ysql lease TTL to 10s in `TestPgPushdown` so the waitforbackends can complete inside last phase of CREATE INDEX, and not interfere with subsequent test instrumentation activity.

Test Plan:
Jenkins

./yb_build.sh release --java-test 'org.yb.pgsql.TestPgPushdown#in_secondaryIndex' -n 20 --tp 1
./yb_build.sh release --java-test 'org.yb.pgsql.TestPgPushdown#aggregatesVar' -n 20 --tp 1
./yb_build.sh release --java-test 'org.yb.pgsql.TestPgPushdown#aggregatesConst' -n 20 --tp 1

Reviewers: patnaik.balivada

Reviewed By: patnaik.balivada

Subscribers: ybase

Differential Revision: https://phorge.dev.yugabyte.com/D57020