[#14114] DocDB: Throw detailed error message when a deadlock is detected
Summary:
In the exisiting implementation, we return a generic error message when transactions are aborted due to a deadlock.

This diff addresses the issue by returning a detailed error info when transactions are aborted due to a deadlock. Introduced a new flag `clear_deadlocked_txns_info_older_than_seconds`. The deadlock detector now stores transactions aborted due to a deadlock, and we prune the list every `transaction_deadlock_detection_interval_usec`. The info gets removed if it is older than `clear_deadlocked_txns_info_older_than_seconds`.

The transaction coordinator now checks with the deadlock detector before reporting `ABORTED` for a txn that it is unable to find. If the txn is found at the deadlock detector, `GetTransactionStatusResponsePB` resp is populated with an newly added field `AppStatusPB reason`, which contains detailed info on the deadlock error.

Deadlocked transactions waiting in the wait-queue are aborted in 2 ways:
1. When the txn participant isn't able to find the txn, we directly poll the status tablet for the waiter's status.
2. The txn participant responds with the status it is last aware of (in this case, `ABORTED`).

Since both these codepaths use `GetTransactionStatusResponsePB`, we explicitly check if `reason` is populated and return back the detailed error, if any.

Note: In some cases, it is still possible that we return a generic error. When a waiter txn is notified that all of its blockers have been aborted, it re-runs conflict resolution. When `PrepareMetadata` is executed, the participant returns a generic error message if the txn is not found.
This can happen as the waiter txn too could been aborted as part of the deadlock, but that signal got delayed. If we deterministically abort just one txn when we find a deadlock (https://github.com/yugabyte/yugabyte-db/issues/14165), it should probably solve this issue.
Jira: DB-3597

Test Plan:
Reverting back the newly added test because of another issue https://github.com/yugabyte/yugabyte-db/issues/18100

Steps to manually test the feature:
Create a cluster using
```
./bin/yb-ctl create --rf=3 --data_dir ~/yugabyte-data --tserver_flags 'ysql_num_shards_per_tserver=1,enable_wait_queues=true,enable_deadlock_detection=true,enable_intentsdb_page=true'
```

Create a table using
```
create table test (k int primary key, v int);
insert into test select generate_series(1,11), 0;
```

Spawn transactions and create deadlocks. Should see error similar to the below
```
ERROR:  Transaction 6640330e-d7b6-4c6e-8fec-8d8e2b3311c3 aborted due to deadlock.
6640330e-d7b6-4c6e-8fec-8d8e2b3311c3 -> 12673b67-3ccb-4a90-8a3c-7ed72d92b8c8 -> 6640330e-d7b6-4c6e-8fec-8d8e2b3311c3
: 40P01
```

Reviewers: rsami, pjain, sergei

Reviewed By: rsami

Subscribers: esheng, ybase, bogdan

Differential Revision: https://phorge.dev.yugabyte.com/D26099