[#19987] build: fix compilation on release gcc11
Summary:
Fix maybe-uninitialized compilation error on almalinux8 release gcc11
introduced by commit f63fb345e134549a87e75eb03f6c965652f39f22, titled

    [#19932] AutoFlag Apply delay

Interestingly, the same issue is in two places, but the compiler is
happy after fixing just the first.  Still, fix the second place.

Original error snippet:

    ../../src/yb/integration-tests/auto_flags-itest.cc:795:24: error: ‘*(std::pair<bool, unsigned int>*)((char*)&result + offsetof(std::optional<std::pair<bool, unsigned int> >,std::optional<std::pair<bool, unsigned int> >::<unnamed>.std::_Optional_base<std::pair<bool, unsigned int>, true, true>::<unnamed>)).std::pair<bool, unsigned int>::first’ may be used uninitial
    ized [-Werror=maybe-uninitialized]
      795 |   ASSERT_FALSE(result->first);
          |                        ^
    ../../src/yb/integration-tests/auto_flags-itest.cc:770:8: note: ‘result’ declared here
      770 |   auto result = ASSERT_RESULT(client_->ValidateAutoFlagsConfig(config));
          |        ^~~~~~
Jira: DB-8958

Test Plan:
On almalinux 8,

    ./yb_build.sh release --gcc11

Close: #19987
Jenkins: compile only

Reviewers: hsunder

Reviewed By: hsunder

Subscribers: ybase

Differential Revision: https://phorge.dev.yugabyte.com/D30327