Update ycql.md
1. add `location` column to avoid the errors for `INSERT` statement. (L98)

```
$ node yb-cql-helloworld.js
Creating keyspace ybdemo
Creating table employee
Inserting row with: INSERT INTO ybdemo.employee (id, name, age, language) VALUES (1, 'John', 35, 'NodeJS', '{ "city": "San Francisco", "state": "California", "lat": 37.77, "long": 122.42 }');
There was an error Too Many Arguments
INSERT INTO ybdemo.employee (id, name, age, language) VALUES (1, 'John', 35, 'NodeJS', '{ "city": "San Francisco", "state": "California", "lat": 37.77, "long": 122.42 }');
                                                      ^^^^^^
const ycql = require('yb-ycql-driver');
 (ql error -306) ResponseError: Too Many Arguments
INSERT INTO ybdemo.employee (id, name, age, language) VALUES (1, 'John', 35, 'NodeJS', '{ "city": "San Francisco", "state": "California", "lat": 37.77, "long": 122.42 }');
                                                      ^^^^^^
 (ql error -306)
    at FrameReader.readError (/Users/tichimura/ybworkspace/node_modules/yb-ycql-driver/lib/readers.js:326:15)
    at Parser.parseBody (/Users/tichimura/ybworkspace/node_modules/yb-ycql-driver/lib/streams.js:194:66)
    at Parser._transform (/Users/tichimura/ybworkspace/node_modules/yb-ycql-driver/lib/streams.js:137:10)
    at Parser.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Parser.Writable.write (node:internal/streams/writable:334:10)
    at Protocol.ondata (node:internal/streams/readable:754:22)
    at Protocol.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
Shutting down
```

2.  remove `JSON.parse()` as it doesn't work correctly(L111)

```
$ node yb-cql-helloworld.js
Creating keyspace ybdemo
Creating table employee
Inserting row with: INSERT INTO ybdemo.employee (id, name, age, language, location) VALUES (1, 'John', 35, 'NodeJS', '{ "city": "San Francisco", "state": "California", "lat": 37.77, "long": 122.42 }' );
undefined:1
[object Object]
 ^
const ycql = require('yb-ycql-driver');

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /Users/tichimura/ybworkspace/yb-cql-helloworld.js:45:25
    at RequestHandler.next [as _callback] (/Users/tichimura/ybworkspace/node_modules/yb-ycql-driver/lib/utils.js:726:14)
    at /Users/tichimura/ybworkspace/node_modules/yb-ycql-driver/lib/request-handler.js:251:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```