[#27768] YSQL: Replace pg_stat_activity's RSS with PSS
Summary:
We already had the function `yb_pg_stat_get_backend_rss_mem_bytes` and a corresponding column `rss_mem_bytes` in `pg_stat_activity`. However, RSS (resident set size) is not a great measurement, because it counts all of the shared memory that a process uses. For example, if we have two processes, each using the same 50MB shared library and each having 75MB of private memory, their RSS would be 75 + 50 = 125MB. Summing the RSS of `n` backends results in counting the shared memory portion `n` times!

PSS (proportional set size) is a more reasonable measurement. It's calculated as the process's private memory, plus its proportion of the shared memory. In the example above, the PSS of each process would be 75 + (50 / 2) = 100MB. Summing the PSS of `n` backends results in `SHARED_MEM / n` * `n`, so we don't overcount anything.

This diff adds another function `yb_pg_stat_get_backend_pss_mem_bytes` that returns the PSS for a given backend ID, and replaces the `rss_mem_bytes` column in pg_stat_activity with `pss_mem_bytes`.

== Renaming the column vs adding a new column ==
Adding a new column means that PSS and RSS co-exist, and the user is responsible for understanding what the difference is between the two. Since PSS is a generally better metric to use (it's more fair, it sums more accurately), keeping both RSS and PSS just risks confusion.

Replacing the column has to be done in two phases:
1. Rename the column
2. Alter the view definition to use the pss function instead of the rss function.

Renaming the column has potential downsides:
* any scripts that reference `rss_mem_bytes` will break. This will happen loudly though, so fixing it should be straightforward.
* any dependent views will have modified definitions in `pg_views`.

```lang=sql
CREATE VIEW view1 AS SELECT 1 AS rss;
CREATE VIEW view2 AS SELECT rss FROM view1;
CREATE VIEW view3 AS SELECT * FROM view1;
ALTER VIEW view1 RENAME COLUMN rss TO pss;

SELECT viewname, definition FROM pg_views WHERE viewname IN ('view1', 'view2', 'view3');
 viewname |         definition
----------+----------------------------
 view1    |  SELECT 1 AS pss;
 view2    |  SELECT view1.pss AS rss+
          |    FROM view1;
 view3    |  SELECT view1.pss AS rss+
          |    FROM view1;
```

However, dependant views will still select successfully, because the view definition is stored referring to attribute numbers instead of column names.
```lang=sql
 SELECT * FROM view1;
 pss
-----
   1

SELECT * FROM view2;
 rss
-----
   1

SELECT * FROM view3;
 rss
-----
   1
```

If users have built any views on top of pg_stat_activity, they may experience some misleading results.

=== Why the migration needs to rename the column even though it's recreating the view ===
`CREATE OR REPLACE VIEW` cannot change column names. Although the `REPLACE` keyword sounds like it would be equivalent to `DROP` and `CREATE`, views have special rules. If we want to rename a field, we have to use `ALTER VIEW RENAME COLUMN ...`. If we want to change a field's definition, we have to use `CREATE OR REPLACE VIEW`. If we want to change a field's name and definition, we have to do both.

See this simple example:

```lang=sql
create table t (a int);
insert into t values (1);
create view v as select a from t;
select * from v;
 a
---
 1
(1 row)

alter view v rename column a to b;
select * from v;
 b
---
 1
(1 row)

create or replace view v as select a as c from t;
ERROR:  cannot change name of view column "b" to "c"
HINT:  Use ALTER VIEW ... RENAME COLUMN ... to change name of view column instead.
```

== `smaps` vs `smaps_rollup` ==
`/proc/<pid>/smaps` produces hundreds of lines of output, each for a specific region of memory:
```
7f3fc94ae000-7f3fc94c2000 r--p 002de000 08:02 455211619                  /net/dev-server-telgersma/share/code/yugabyte-db/build/release-clang19-dynamic-ninja/lib/libpg_client_proto.so
Size:                 80 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                  80 kB
Pss:                  13 kB
Shared_Clean:          0 kB
Shared_Dirty:         80 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:           44 kB
Anonymous:            80 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd mr mw me ac sd
```

The consumer is responsible for summing up the Rss and Pss manually.

`proc/<pid>/smaps_rollup` produces an already-summed output, so we could use the Rss and Pss directly from the output.

However, `smaps_rollup` is a newer feature, not available on all linux kernels, so if we chose to use `smaps_rollup`, we'd still have to support `smaps`. This means we would have code that is only tested on older kernel versions, which opens us up to some risk. It is simpler and safer to keep things unified and use the lowest common denominator.
Jira: DB-17371

Test Plan:
```
./yb_build.sh --java-test TestYbPgStatActivity
./yb_build.sh --java-test TestYsqlUpgrade
./yb_build.sh --java-test TestPgRegressRules
```

This diff reworks the TestYbPgStatActivity to avoid needing to fetch allocated memory, RSS, and PSS seperately for each test.

= Benchmarking ==

Process:
1. created a cluster with `bin/yb-ctl restart --tserver_flags "ysql_catalog_preload_additional_tables=true"` to use a bit more memory by default for each backend.
2. Created SQL functions to read RSS / PSS from pg_stat_activity 10000 times.
```lang=sql
CREATE OR REPLACE FUNCTION run_pss_sum_loop()
RETURNS void AS $$
DECLARE
    i INT := 0;
    result BIGINT;
BEGIN
    FOR i IN 1..10000 LOOP
        SELECT sum(pss_mem_bytes) INTO result FROM pg_stat_activity;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION run_rss_sum_loop()
RETURNS void AS $$
DECLARE
    i INT := 0;
    result BIGINT;
BEGIN
    FOR i IN 1..10000 LOOP
        SELECT sum(rss_mem_bytes) INTO result FROM pg_stat_activity;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
```

Then ran this function 3 times with a different number of idle backends each time. (The minimum number of backends is 3, because we have some bgworkers + the backend running the pg_stat_activity queries).

On my devserver (n2d-standard-4, 4 vCPUs, 16 GB Memory), the results are:

| number of backends | sum(PSS) (MB) | PSS per proc (MB) | Before change (avg ms per pg_stat_activity query) | After change (avg ms per pg_stat_activity query) |
| 3 | 190 | 63 | 0.61 | 0.59 |
| 53 | 2253 | 43 | 0.76 | 0.78 |
| 153 | 6361 | 42 | 1.04 | 1.10 |
| 302 | 12212 | 40 | 1.39 | 1.63 |

We see that the difference is more pronounced as the memory size grows larger, as expected. The benchmarks were limited to memories reachable on my devserver, but the timings should be able to be linearly extrapolated - the number of page table entries should grow roughly linearly as memory increases (R^2 = 0.999). The graph of these roughly predicts that at ~60GB of PG memory usage, the new accurate PSS  should be ~6ms per invocation compared to 4.5-5ms per invocation before this change. (see [[ https://github.com/yugabyte/yugabyte-db/issues/27768#issuecomment-3045667895 | graph ]])

Actual values will differ - maybe fewer backends with higher memory consumption per backend will have different patterns, and the data may be extrapolated too far. But even if it's 10x slower than expected, it should be only ~60ms on a 64GB node close to OOM, for a view that is only queried periodically.

Reviewers: smishra, jason, kramanathan

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D45024