[BACKPORT 2.14][#13250] YSQL: ysql_dump should set up a sequence's current value
Summary:
This diff fixes the backup issue related to Sequence, which can lead to a unique constraint violation.

Problem:
During backup, a sequence's current value is not set up in `ysql_dump`.
Thus, after restoration, the sequence's initial value is set to a default value.
Any table that uses a sequence to generate primary key values
suffers from the unique constraint violation problem.
See the example below:
```
# create table and insert data to increment sequence value
yugabyte=# create table tbl (k serial primary key, v int);
yugabyte=# insert into tbl(v) select * from generate_series(1,50);

# backup && restore

# test sequence
yugabyte=# insert into tbl(v) values (200);
ERROR:  duplicate key value violates unique constraint "tbl_pkey"
yugabyte=# insert into tbl(v) values (200);
ERROR:  duplicate key value violates unique constraint "tbl_pkey"
yugabyte=# select nextval('tbl_k_seq');
 nextval
---------
       3
(1 row)
```

Solution:
Setting up a value for a sequence is part of dumping sequence data in `pg_dump.c`.
During our backup/restore process,
`ysql_dump` only creates schema with the flag `--schema-only`,
and skips the dumping data part.
This diff includes dumping sequence data in `ysql_dump` with the flag `--schema-only`.
Dumping sequence data only uses `pg_catalog.setval` to set a sequence's current value
to its `last_value`: the last value allocated by any session.
With this diff,
`ysql_dump_debug --include-yb-metadata --serializable-deferrable --schema-only`
generates the following extra statement for the example above in its output dump file:
```
SELECT pg_catalog.setval('public.tbl_k_seq', 100, true);
```
Our default sequence cache size is set to 100, so the sequence value is set correctly.

Original Commit: https://github.com/yugabyte/yugabyte-db/commit/a38eba232e20b763db841095c749ac24ebbcbbfc
Original Differential Revision: https://phabricator.dev.yugabyte.com/D18266

Test Plan:
./yb_build.sh --java-test org.yb.pgsql.TestYbBackup#testSequence
./yb_build.sh --java-test org.yb.pgsql.TestYsqlDump

Reviewers: mihnea, tverona, alex, myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D19311