Allow SET SESSION TRANSACTION and DROP DATABASE
Summary:
Accept a couple of statement for our tests to run.
- DROP DATABASE is not fully working yet because we don't support CASCADE.
- Although accepted, some statements cannot be documented as supported until our "initdb" is working.

Test Plan:
Run pgsql test.

Because this work, TestPgTransactions.java already failed with the following errors.
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 92.623 s <<< FAILURE! - in org.yb.pgsql.TestPgTransactions
[ERROR] testTransactionConflicts(org.yb.pgsql.TestPgTransactions)  Time elapsed: 69.072 s  <<< ERROR!
java.util.concurrent.TimeoutException: Task with a timeout of 30000 ms took 30000 ms to complete: SQL statement (PG backend pid: 29679): INSERT INTO test(h, r, v) VALUES (101, 101, 20200)
	at org.yb.pgsql.TestPgTransactions.testTransactionConflicts(TestPgTransactions.java:115)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TestPgTransactions.testTransactionConflicts:115->BasePgSQLTest.executeWithTimeout:485->BaseYBTest.runWithTimeout:387->BaseYBTest.handleTaskTimeout:339 » Timeout
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

Reviewers: mikhail, mihnea

Reviewed By: mihnea

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D5594