[#30491] YSQL: fix bug that caused create index timeout
Summary:
Concurrent Index creations hit time out error in one of the runs,
```
ERROR: timed out waiting for postgres backends to catch up
  Detail: 1 backends on database 16385 are still behind catalog version 1005.
  Hint: Run the following query on all tservers to find the lagging backends: SELECT * FROM pg_stat_activity WHERE backend_type != "walsender" AND backend_type != "yb-conn-mgr walsender" AND backend_type != "yb auto analyze backend" AND backend_type != "yb index backfill" AND backend_type != "yb matview refresh" AND catalog_version < 1005 AND datid = 16385;
  Where: Catalog Version Mismatch: A DDL occurred while processing this query.
```

After debugging, I saw 3 PG backends all trying to create different indexes around the same time.

B1 (pid 263928) increments catalog version to 1004, set its local version to 1004
B2 (pid 260990) increments catalog version to 1005, set its local version to 1005
B3 (pid 261517) increments catalog version to 1006, set its local version to 1006

Normally, we would expect

B1 waiting for everyone else to reach 1004
B2 waiting for everyone else to reach 1005
B3 waiting for everyone else to reach 1006

But due to this code:

```
static void
YbWaitForBackendsCatalogVersion()
{
    if (yb_disable_wait_for_backends_catalog_version)
        return;

    /*
     * We don't get the current catalog version after
     * YBDecrementDdlNestingLevel(), so we have to send another RPC to fetch
     * it.  This is needed because YbGetCatalogCacheVersion() may be behind in
     * case other DDLs happened concurrently.  This also means the version we
     * are waiting on may be higher than necessary in case other DDLs finished
     * before we collect the version.
     */
    uint64_t    catalog_version = YbGetMasterCatalogVersion();

    Assert(catalog_version >= YbGetCatalogCacheVersion());
```

We end up with

B1 waiting for everyone else to reach 1006
B2 waiting for everyone else to reach 1005
B3 waiting for everyone else to reach 1006

Note that B1 started with 1003, after incrementing, it sets its local version to 1004, but it does
not trust that 1004 was a result of its own incrementing of 1003, so it makes a RPC to master, which
in this case, it reads back 1006. So it ends up doing the same as B3.

The problem is that while B1 is waiting for everyone else to reach 1006, its own local version remains
at 1004. This will hang B2 because B2 is waiting for everyone else including B1 to reach 1005. It will
also hang B3 because B3 is waiting for everyone else including B1 to reach 1006.

Likewise, while waiting, B2's local version remains at 1005. This will hang B3 because B3 is
waitingfor everyone else including B2 to reach 1006.

So B1 hangs there at 1004. Because of that, B2 is waiting for B1 to reach 1005, B3 is waiting for
both B1 and B2 to reach 1006. Eventually all 3 waits timed out.

I made two changes in this diff:

(1) changed the call YbGetMasterCatalogVersion() to YbGetNewCatalogVersion(), which would give 1004
for B1 in case of the reported bug, also avoids a RPC call to master.
(2) moved the block of code that sets backend type to YB_INDEX_BACKFILL_DDL earlier so that the
entire CREATE INDEX statement will be filtered out. For the above
scenario, B1, B2, B3 are all filtered out as candidates to wait for.

In order to do (2), I added a new helper function to include all the original YB code involved.

Test Plan:
./yb_build.sh fastdebug --cxx-test pg_concurrent_ddls-test --gtest_filter=PgConcurrentCreateIndexWithSlowBackfillTest.SlowBackfillTest --gcc13 -n 10 --tp 1
./yb_build.sh fastdebug --cxx-test pg_concurrent_ddls-test --gtest_filter=PgConcurrentCreateIndexWithSlowBackfillTest.PartitionedSlowBackfillTest --gcc13 -n 10 --tp
./yb_build.sh fastdebug --gcc13 --gtest_filter PgIndexBackfillTest.CatVerBumps -n 100
./yb_build.sh fastdebug --gcc13 --cxx-test pg_backends-test

Reviewers: sanketh

Reviewed By: sanketh

Subscribers: yql, svc_phabricator

Differential Revision: https://phorge.dev.yugabyte.com/D50821