[BACKPORT 2026.1][#33543] YSQL: Fix pggate_test_select build break on 2026.1
Summary:
d8ba74f4b0 ([BACKPORT 2026.1][#33543], D57537) changed the skip intents parameter of
YBCPgNew{Insert,Select} from a bool to YbcPgSkipIntentsOptimizationInfo and converted every
call site in its tree. That tree predated 5680bada28 ([BACKPORT 2026.1][#30900], D57419),
which landed 105 minutes earlier and added PggateTestRowBounds; its two call sites still
pass a bool, so 2026.1 tip does not compile:

  ../../src/yb/yql/pggate/test/pggate_test_select.cc:1506:22: error: no matching function
  for call to 'YBCPgNewInsert'

Master is unaffected -- #30900 landed there in June, two months before #33543, so the
conversion covered these sites. This is a 2026.1-only fix-forward; there is no original
commit on master. But to work around CSI format check failure, added below.

Original commit: 608714176580b4daf79b00ab5138bab6f42bfe98 / D57427

Test Plan:
Jenkins: urgent, rebase: 2026.1
./yb_build.sh release --cxx-test pggate_test_select

Reviewers: #db-approvers, pjain, amartsinchyk, smishra, steve.varnau

Reviewed By: steve.varnau

Subscribers: ybase, yql

Differential Revision: https://phorge.dev.yugabyte.com/D57580