[BACKPORT 2026.1][#32129] YSQL: Disable skip intents for Modifying CTEs and add new test
Summary:
This fixes a "Restart read required" error and adds a test case to
yb.orig.ddl_txn_visibility.sql documenting the architectural difference
between YB and PG in how visibility is determined for statements
containing interleaved modifying CTEs (tracked as GHI #10142).

In PG, visibility within the same transaction uses `CommandId`, which is
fixed at the start of the statement, so reads do not see same-statement
CTE writes. In YB, visibility within the same transaction is determined
by the `in_txn_limit`, which is picked at the start of the read operation.
When that read is forced to execute after the CTE write, the chosen
`in_txn_limit` includes the write, so it sees the write that just occurred.

If the table was created in the same transaction, YB uses the "skip
intents" optimization. When the MCTE read occurs after a skip-intents
write, sometimes we can see a "Restart read required" error. Currently
the query layer cannot retry a skip-intents write safely, leading to
a query error such as:

```
ERROR:  Restart read required (query layer retry isn't possible because we have skipped intents write)
```

To avoid `Restart read` error in such a situation,  I moved the check
for modifying CTEs into `ExecutorStart` so that the skip-intents
optimization is proactively disabled for the entire query before
execution begins. This ensures that any subsequent writes from the CTE
will use regular transactional intents. In other words, we use the old mechanism
which results in no read restart error because the write is now part of the same
transaction and so it doesn't raise a read restart error. Note that even in this case,
the intent write time will be higher than the read time that is chosen.
The check `stmt_may_write_reason = 5` inside `YbMaybeDisableSkipIntentsForCurrentTxn`
is removed as it is now redundant.

Disabling the skip intents optimization for Modifying CTEs does not
significantly impact the optimization's real-world benefits. The skip
intents fast-path is designed to provide massive throughput boosts for
bulk data loading (e.g., CREATE TABLE AS SELECT). Modifying CTEs are
typically used for complex, point-in-time transactional operations on
established tables, not for bulk loading millions of rows into a newly
created table within the same transaction.

Original commit: 1518a00722 / D54419

Test Plan:
(1) ./yb_build.sh release --java-test 'org.yb.pgsql.TestDdlTransactionBlocks' -n 10 --tp 1

Note that this test randomly set true or false to the value of
`--ysql_yb_enable_new_relation_fastpath_write_in_txn_blocks`
which ensures that we get consistent YB output regardless of whether
skip intents optimization is enabled or not.

(2) ./yb_build.sh release --cxx-test pg_skip_intents_metrics-test

Reviewers: pjain

Reviewed By: pjain

Subscribers: yql, jason

Differential Revision: https://phorge.dev.yugabyte.com/D56805