[#28504] DocDB: Restore DECLARE_bool() lines accidentally removed from pg_packed_row-test.cc
Summary:
Commit 30b045971e ([BACKPORT 2024.2][#28504] DocDB: Fix
PgTxnTest.FlushLargeTransaction in ASAN, D53518) accidentally removed
the DECLARE_bool() declarations for enable_leader_failure_detection and
enable_load_balancing that had been added moments earlier by
eeedb9d429 ([BACKPORT 2024.2][#31455] DocDB: Fix
PgPackedRowTest.BigValue/kV2 in TSAN, D53524).

The declarations are still required because both tests that the two
commits modified (PgPackedRowTest.BigValue and
PgTxnTest.FlushLargeTransaction) ANNOTATE_UNPROTECTED_WRITE the
corresponding FLAGS_* variables.

As a result, src/yb/yql/pgwrapper/pg_packed_row-test.cc currently fails
to compile on origin/2024.2 with:

  error: use of undeclared identifier 'FLAGS_enable_leader_failure_detection'
  error: use of undeclared identifier 'FLAGS_enable_load_balancing'

The equivalent backport pair on 2025.2 (d9002e61d4 / 6d3c82a301, D53516)
has the same breakage and is fixed by a companion diff.

Restore the two DECLARE_bool() lines. No functional change.

Test Plan:
Jenkins. The branch currently fails to compile, so local
test runs are not possible without this patch applied; CSI will validate.

Jenkins: rebase: 2024.2
Jenkins: urgent

Reviewers: mlillibridge

Reviewed By: mlillibridge

Subscribers: ybase, yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D53632