[#27192][#28198] DocDB: Retry exclusive lock requests amidst ysql lease membership changes
Summary:
Currently, in flight exclusive lock requests could fail with errors like below due to changes in ysql lease membership
```
ERROR: TSLocalLockManager not found
ERROR: Object Lock Manager shutting down
```

This revision addresses the issue by retrying the exclusive lock requests upon encountering such errors.
Jira: DB-16678, DB-17849

Test Plan:
Jenkins
./yb_build.sh --cxx-test='TEST_F(PgObjectLocksTest, RetryExclusiveLockOnTserverLeaseRefresh) {'

Reviewers: amitanand, zdrudi

Reviewed By: zdrudi

Subscribers: ybase, yql

Differential Revision: https://phorge.dev.yugabyte.com/D46180