[BACKPORT 2025.1][#3109][#27125] YSQL: Fix ANALYZE command when executing using multiple transactions
Summary:
The `ANALYZE` statement when executed outside of an explicit transaction block can be executed in multiple YB transactions. Those cases are:
1. Outside of txn block and processing more than 1 relation
2. Autovacuum worker (Unsupported in YSQL)

1 PG (& YB) txn is created per relation so that we can release the locks for that relation after we are done processing it instead of waiting for all relations to be processed.

The above mentioned cases end up with the `ERROR:  Transaction for catalog table write operation 'pg_class' not found` errors. Full example:
```
yugabyte=# create table test (a int primary key, b text);
CREATE TABLE
yugabyte=# create table test2 (a int primary key, b text);
CREATE TABLE
yugabyte=# analyze test, test2;
ERROR:  Transaction for catalog table write operation 'pg_class' not found
```

This happens because the DDL state is only set for the first transaction (`PostgresMain`)  but not for the transactions that get created internally by the `vacuum` function. DDL state is stored in `pg_yb_utils` and it allows us to detect DDL statements and increment catalog and breaking versions. We have checks in place in `pg_session.cc` to ensure that any catalog write happens only when this DDL state is set (`txn_manager.IsDdlMode()`). This check fails and leads to the mentioned error. This check protects from inconsistent reads from catalog tables and also ensures we bump up the catalog version.

Note that the `COPY` command doesn't lead to this error because it doesn't do any catalog writes, hence doesn't require the DDL state.

This revision fixes the bug by also setting the DDL state for the transactions created internally in the `vacuum` function. The DDL state must be set for all transactions which do catalog writes. Hence, a similar fix has also been made to `ALTER TABLE DETACH PARTITION CONCURRENTLY` code.

There are several other places where multiple PG (& YB) txns are started but we don't need to add similar logic:
1. index_drop: `DROP INDEX CONCURRENTLY` is unsupported in YB.
2. indexcmds.c: The DDL state is set for the multiple transactions via the `YBIncrementDdlNestingLevel` function call
3. cluster.c: `CLUSTER` statements are unsupported in YB.
4. movedb: `ALTER DATABASE SET TABLESPACE` is unsupported
5. _SPI_commit: This is the commit point of a transaction. Future txn will set the DDL state in pg_yb_utils.c
6. ttl_index.c: This is an extension which doesn't do DDLs.
7. reindex: `CONCURRENTLY` option is unsupported
Jira: DB-1839, DB-16612

Original commit: bbaf5f829069a3e9e06e369755734fa31d0223d4 / D44196

Test Plan: ./yb_build.sh --java-test 'org.yb.pgsql.TestDdlTransactionBlocks'

Reviewers: myang, patnaik.balivada, pjain, aagrawal

Reviewed By: aagrawal

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D44740