[Backport 2.8][PLAT-580] Fix sync api bug with previously-existing xcluster configs
Summary:
Previously, the sync operation would fail when importing a new config while
there is a separate, already-existing config with the following error:
```
2022-01-14 06:35:24.475 [debug] TaskExecutor.java:709 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Invoking run() of task XClusterConfigSync(universe=e78b8495-f09e-45be-bd33-b08734142d30)
2022-01-14 06:35:24.475 [info] XClusterConfigSync.java:40 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Running XClusterConfigSync(universe=e78b8495-f09e-45be-bd33-b08734142d30)
2022-01-14 06:35:24.838 [info] AsyncYBClient.java:1901 [New I/O worker #226] Discovered tablet YB Master for table YB Master with partition ["", "")
2022-01-14 06:35:24.970 [info] XClusterConfigSync.java:109 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Found XClusterConfig(test-config) between source(e66286bd-d672-4e25-936a-7c7c5d688ae4) and target(e78b8495-f09e-45be-bd33-b08734142d30): status(Running), tables([000033e1000030008000000000004108, 000033e1000030008000000000004105])
2022-01-14 06:35:24.973 [info] XClusterConfigSync.java:133 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Updated existing XClusterConfig(9a8d50ab-77fc-4a12-8422-9922f29c672a)
2022-01-14 06:35:24.973 [info] XClusterConfigSync.java:109 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Found XClusterConfig(fail-config) between source(e66286bd-d672-4e25-936a-7c7c5d688ae4) and target(e78b8495-f09e-45be-bd33-b08734142d30): status(Running), tables([000033e1000030008000000000004008])
2022-01-14 06:35:24.975 [info] XClusterConfigSync.java:128 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Created new XClusterConfig(5727a83f-ac0e-4829-a2c9-abf0550a21de)
2022-01-14 06:35:24.976 [error] XClusterConfigSync.java:54 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] XClusterConfigSync(universe=e78b8495-f09e-45be-bd33-b08734142d30) hit error : java.util.HashSet cannot be cast to io.ebean.bean.BeanCollection
2022-01-14 06:35:24.976 [debug] LocalYBClientService.java:31 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Closing client masters=10.150.0.202:7100.
2022-01-14 06:35:24.985 [error] TaskExecutor.java:814 [TaskPool-SyncXClusterConfig(universe=e78b8495-f09e-45be-bd33-b08734142d30)-0] Failed to execute task type subtasks.xcluster.XClusterConfigSync UUID 304d81cb-4892-433f-830f-95514f6089c1 details {"nodeExporterUser":"prometheus","universeUUID":"e78b8495-f09e-45be-bd33-b08734142d30","encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"sourceXClusterConfigs":[],"targetXClusterConfigs":["9a8d50ab-77fc-4a12-8422-9922f29c672a"]}, hit error.
java.lang.RuntimeException: java.lang.ClassCastException: java.util.HashSet cannot be cast to io.ebean.bean.BeanCollection
        at com.yugabyte.yw.commissioner.tasks.subtasks.xcluster.XClusterConfigSync.run(XClusterConfigSync.java:55)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:710)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1005)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.util.HashSet cannot be cast to io.ebean.bean.BeanCollection
        at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.addBeanToCollectionWithCreate(BeanPropertyAssocMany.java:262)
        at io.ebeaninternal.server.query.SqlTreeNodeManyRoot.load(SqlTreeNodeManyRoot.java:39)
        at io.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:328)
        at io.ebeaninternal.server.query.CQuery.checkForDifferentBean(CQuery.java:490)
        at io.ebeaninternal.server.query.CQuery.readUntilDifferentBeanStarted(CQuery.java:481)
        at io.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:472)
        at io.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:544)
        at io.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:575)
        at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:394)
        at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:133)
        at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:452)
        at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1596)
        at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1574)
        at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1474)
        at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:428)
        at com.yugabyte.yw.models.XClusterConfig.getByTargetUniverseUUID(XClusterConfig.java:180)
        at com.yugabyte.yw.commissioner.tasks.subtasks.xcluster.XClusterConfigSync.syncXClusterConfigs(XClusterConfigSync.java:138)
        at com.yugabyte.yw.commissioner.tasks.subtasks.xcluster.XClusterConfigSync.run(XClusterConfigSync.java:51)
        ... 8 common frames omitted
```

Original diff: https://phabricator.dev.yugabyte.com/D14766

Test Plan:
1. Create an xcluster config via platform.
2. Create a second xcluster config (for same source/target universe pair, but different tables) manually via yb-admin.
3. Run sync api, verify it succeeds and imports the manually-created xcluster config.

Reviewers: sb-yb, muthu

Reviewed By: muthu

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D14832