[BACKPORT 2024.1][PLAT-14809][YBA CLI]Support Master Key Rotation
Summary:
Support MKR in the universe security operations
Security sub command in universe:
```
./yba universe security
Error: required flag(s) "name" not set
Usage:
  yba universe security [flags]
  yba universe security [command]

Available Commands:
  ear         Encryption-at-rest settings for a universe

Flags:
  -f, --force              [Optional] Bypass the prompt for non-interactive usage.
  -n, --name string        [Required] The name of the universe for the operation.
  -s, --skip-validations   [Optional] Skip validations before running the CLI command.
  -h, --help               help for security

Global Flags:
  -a, --apiToken string    YugabyteDB Anywhere api token.
      --config string      Config file, defaults to $HOME/.yba-cli.yaml
      --debug              Use debug mode, same as --logLevel debug.
      --disable-color      Disable colors in output. (default false)
  -H, --host string        YugabyteDB Anywhere Host (default "http://localhost:9000")
  -l, --logLevel string    Select the desired log level format. Allowed values: debug, info, warn, error, fatal. (default "info")
  -o, --output string      Select the desired output format. Allowed values: table, json, pretty. (default "table")
      --timeout duration   Wait command timeout, example: 5m, 1h. (default 168h0m0s)
      --wait               Wait until the task is completed, otherwise it will exit immediately. (default true)
```

EAR command for universe:
```
./yba universe security ear -h
Encryption-at-rest settings for a universe

Usage:
  yba universe security ear [flags]

Aliases:
  ear, encryption-at-rest, kms

Flags:
      --operation string     [Required] Enable or disable encryption-at-rest in a universe. Allowed values: enable, disable, rotate-universe-key, rotate-kms-config.
      --config-name string   [Optional] Key management service configuration name for master key. Required for enable and rotate-kms-config operations, ignored otherwise.
  -h, --help                 help for ear

Global Flags:
  -a, --apiToken string    YugabyteDB Anywhere api token.
      --config string      Config file, defaults to $HOME/.yba-cli.yaml
      --debug              Use debug mode, same as --logLevel debug.
      --disable-color      Disable colors in output. (default false)
  -f, --force              [Optional] Bypass the prompt for non-interactive usage.
  -H, --host string        YugabyteDB Anywhere Host (default "http://localhost:9000")
  -l, --logLevel string    Select the desired log level format. Allowed values: debug, info, warn, error, fatal. (default "info")
  -n, --name string        [Required] The name of the universe for the operation.
  -o, --output string      Select the desired output format. Allowed values: table, json, pretty. (default "table")
  -s, --skip-validations   [Optional] Skip validations before running the CLI command.
      --timeout duration   Wait command timeout, example: 5m, 1h. (default 168h0m0s)
      --wait               Wait until the task is completed, otherwise it will exit immediately. (default true)
```

Changes to go-client: https://github.com/yugabyte/platform-go-client/commit/c3a4e13c42d8bf2f3d2174049956043558091eac

Original commit: 011830f62e2df077836a6607f0c22d2255e820e5 / D37835

Test Plan:
Tested out commands:

To change Master Key config of the universe
`./yba universe security ear --name dkumar --operation rotate-kms-config --config-name dkumar-aws-cli `

Enable EAR on a universe which has it disabled:
`./yba universe security ear --name dkumar --operation enable --config-name dkumar-aws-cli `

Disable EAR
`./yba universe security ear --name dkumar --operation disable `

Rotate universe key
`/yba universe security ear --name dkumar --operation rotate-universe-key`

Reviewers: sneelakantan, skurapati

Reviewed By: skurapati

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D37854