[PLAT-7617][PLAT-7616] Add runtime config for enabling attach/detach feature. Enable locking after detaching
Summary:
Add runtime configuration called `yb.attach_detach.enabled` default to false, which will block api calls to the attach/detach feature if not enabled.

Also, lock (set updateInProgress=true and updateSucceeded=false) the universe on the source platform when detaching. This will prevent changes to the universe to make sure that nothing is modified when we attach the universe to the target platform. When we attach the universe to the target platform, unlock the universe on the target platform (set updateInProgress=false and updateSucceeded=true).

During detach, if api fails, we will try in our best capabilities to unlock the universe. In the `yb_attach_detach.py` script, if the `run` action is run and the `attach` api fails, we will abort and unlock the universe on the source platform.

Test Plan:
*Adding runtime config*
Go to UI and enable the `yb.attach_detach.enabled` flag. i.e. `yb.attach_detach.enabled=true`. Make sure we can make api calls to the apis in attachDetachController.java. Disable `yb.attach_detach.enabled` flag. ie. set `yb.attach_detach.enabled=false`. Performing any api call or using the `yb_attach_detach.py` script should fail with error below/something similar:

```cw-mbp-fmd6n:bin cwang$ python3  ./yb_attach_detach.py -v -u 7182b4ca-984b-4a51-9cc7-67b69526fd46 attach    -td 900799d7-0013-4a7b-a079-e31d471976f4   -pd http://localhost:9000 -f /Users/cwang/Downloads/cwang-aws-interesting.tar.gz
2023-03-14 11:40:36,556 INFO:

2023-03-14 11:40:36,556 INFO: -----------------Arguments----------------------------
2023-03-14 11:40:36,556 INFO: univ_uuid: 7182b4ca-984b-4a51-9cc7-67b69526fd46
2023-03-14 11:40:36,556 INFO: verbose: True
2023-03-14 11:40:36,556 INFO: name: attach
2023-03-14 11:40:36,556 INFO: api_token_dest: 90********************************f4
2023-03-14 11:40:36,556 INFO: platform_host_dest: http://localhost:9000
2023-03-14 11:40:36,556 INFO: file: /Users/cwang/Downloads/cwang-aws-interesting.tar.gz
2023-03-14 11:40:36,556 INFO: ------------------------------------------------------
2023-03-14 11:40:36,556 INFO:

2023-03-14 11:40:36,556 INFO: Running attach action
2023-03-14 11:40:36,556 INFO: Attaching universe...
2023-03-14 11:40:36,557 DEBUG: Url: http://localhost:9000/api/v1/session_info
2023-03-14 11:40:36,603 DEBUG: Success Status 200
2023-03-14 11:40:36,603 DEBUG: Response: {'apiToken': '900799d7-0013-4a7b-a079-e3123471976f4', 'customerUUID': 'f33e3c9b-75ab-4c30-80ad-cba85646ea39', 'userUUID': 'a9190fe6-1067-409f-95cf-dbd96893c9c9'}
2023-03-14 11:40:36,603 DEBUG: Url: http://localhost:9000/api/v1/customers/f33e3c9b-75ab-4c30-80ad-cba85646ea39/universes/7182b4ca-984b-4a51-9cc7-67b69526fd46/import
2023-03-14 11:40:36,603 DEBUG: Request body: <__main__.MultiPartForm object at 0x7f994bfb6c10>
2023-03-14 11:40:37,025 DEBUG: Error Status 400
2023-03-14 11:40:37,025 DEBUG: Error Reason Bad Request
2023-03-14 11:40:37,025 DEBUG: Error Response {"success":false,"httpMethod":"POST","requestUri":"/api/v1/customers/f33e3c9b-75ab-4c30-80ad-cba85646ea39/universes/7182b4ca-984b-4a51-9cc7-67b69526fd46/import","error":"Attach/Detach feature is not enabled"}
Traceback (most recent call last):
  File "./yb_attach_detach.py", line 381, in <module>
    yb_attach_detach.run()
  File "./yb_attach_detach.py", line 222, in run
    self.action_map[action]()
  File "./yb_attach_detach.py", line 201, in run_attach
    open_url(req)
  File "./yb_attach_detach.py", line 295, in open_url
    raise err
  File "./yb_attach_detach.py", line 288, in open_url
    resp = urllib_request.urlopen(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request```

*Testing locking*
1. Perform a detach. Go to universe UI on the source platform, verify that the current universe is spinning and we are unable to make any universe actions.
2. Perform an attach. Go to the universe UI on the target platform, verify that the universe is in ready state.
Also, purposely throw error on detach and make sure that the universe gets unlocked

In addition, updated UTs.

Reviewers: sanketh, nsingh

Reviewed By: nsingh

Subscribers: sb-yb, jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D23567