hotfix: A C99 compliant declaration was used
A C99 compliant declaration was used by mistake -

In function ‘transform_cypher_optional_match_clause’:
error: ‘for’ loop initial declarations are only allowed in C99 mode

for (int i = list_length(pstate->p_joinexprs) + 1; i < j->rtindex; i++)

This corrects that issue.