[#11689] YSQL: Unsupported system columns are not always rejected
Summary:
YSQL does not support some system columns. For example:

```
yugabyte=# create table foo(id int);
create table foo(id int);
CREATE TABLE
yugabyte=# select ctid from foo;
select ctid from foo;
ERROR:  System column with id -1 is not supported yet
yugabyte=# explain select ctid from foo;
explain select ctid from foo;
ERROR:  System column with id -1 is not supported yet
yugabyte=# explain analyze select ctid from foo;
explain analyze select ctid from foo;
ERROR:  System column with id -1 is not supported yet
```

The system column ctid has internal attribute number -1. The above errors indicate that ctid is not
supported by YSQL.

However, in returning clause we do not reject ctid:

```
yugabyte=# insert into foo values (1) returning ctid;
insert into foo values (1) returning ctid;
      ctid
----------------
 (4294967295,0)
(1 row)

```

What's printed (4294967295,0) is not a valid ctid. It is in fact a special value reserved for
invalid block number:

```
#define InvalidBlockNumber      ((BlockNumber) 0xFFFFFFFF)
```

Same is true for certain select queries. For example:

```
yugabyte=# create table foo(id int, primary key(id));
create table foo(id int, primary key(id));
CREATE TABLE
yugabyte=# insert into foo values (1);
insert into foo values (1);
INSERT 0 1
yugabyte=# select ctid from foo where id = 1;
select ctid from foo where id = 1;
      ctid
----------------
 (4294967295,0)
(1 row)

```

To be consistent, we should also reject ctid in all contexts instead of sometimes returning
4294967295 which only represents a invalid block number and can cause confusion. In addition to
ctid, this also applies to several other unsupported system columns: cmin, cmax, xmin, xmax. For
example:

```
yugabyte=# insert into foo values (2) returning cmin, cmax, xmin, xmax;
insert into foo values (2) returning cmin, cmax, xmin, xmax;
 cmin | cmax | xmin |    xmax
------+------+------+------------
 2249 | 2249 |  112 | 4294967295
(1 row)

INSERT 0 1
yugabyte=# select cmin, cmax, xmin, xmax from foo where id = 2;
select cmin, cmax, xmin, xmax from foo where id = 2;
 cmin  | cmax  | xmin |    xmax
-------+-------+------+------------
 16386 | 16386 |  112 | 4294967295
(1 row)
```
Note that what's returned in the returning clause appears to be some type/table id or max/invalid
transaction number.

I added new function YbCheckUnsupportedSystemColumns to reject unsupported system columns.

Test Plan:
(1) ./yb_build.sh debug --java-test 'org.yb.pgsql.TestPgRegressContribPostgresFdw#schedule'
(2) ./yb_build.sh asan && ./yb_build.sh asan --java-test 'org.yb.pgsql.TestPgRegressContribPostgresFdw#schedule'
verify in org.yb.pgsql.TestPgRegressContribPostgresFdw-output.txt that no longer saw error:

```
src/backend/utils/adt/tid.c:112:16: runtime error: left shift of 65535 by 16 places cannot be
represented in type 'int'
```

Reviewers: dfelsing, fizaa

Reviewed By: fizaa

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D15871