[#6274] Shorten system query cache update interval for word count test
Summary:
TestCassandraSparkWordCount.testDefaultRun fails with:
```
java.io.IOException: Couldn't find ybdemo_keyspace.lines or any similarly named keyspace and table pairs
```

This was due to the default system query cache update interval (4s) being relatively long which misses certain tables.

This revision shortens the system query cache update interval which allows table creation to be detected.

Test Plan: Run TestCassandraSparkWordCount 12 times in release build which pass.

Reviewers: bogdan

Reviewed By: bogdan

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D9838