[PLAT-19201] make SetupYNP/YNPProvisioning reboot nodes before retries
Summary: `SetupYNP` and `YNPProvisioning` need to be able to hard reboot nodes in case the SSH server dies. They should override the default retry limit and carry the data to retrieve the provider which `HardRebootServer` requires later.

Test Plan:
1. Modify `ProvisionInstancesMethod#callback` to throw a recoverable error and try to create a universe:

```
com.yugabyte.yw.common.RecoverableException: Dual NIC setup failed. Code: 3. Output: ybops.common.exceptions.YBOpsRecoverableError: Custom exit code exception: test
    at com.yugabyte.yw.common.ShellResponse.processErrors(ShellResponse.java:53)
    at com.yugabyte.yw.commissioner.tasks.subtasks.YNPProvisioning.run(YNPProvisioning.java:251)
    at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:1052)
    at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1566)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
2025-12-11T20:14:53.215Z  [debug] 50151ae5-3ca3-4325-90a3-2b973e806cfe TaskExecutor.java:1208 [TaskPool-CreateUniverse(13ec05ab-c998-4938-95f8-245c094c8448)-0] com.yugabyte.yw.commissioner.TaskExecutor Task creator callstack:
com.yugabyte.yw.commissioner.TaskExecutor$SubTaskGroup.addSubTask(TaskExecutor.java:688)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.lambda$createYNPProvisioningTask$47(UniverseDefinitionTaskBase.java:2433)
java.base/java.lang.Iterable.forEach(Iterable.java:75)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.createYNPProvisioningTask(UniverseDefinitionTaskBase.java:2405)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.lambda$createCreateNodeTasks$51(UniverseDefinitionTaskBase.java:2552)
com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.applyOnNodesWithStatus(UniverseTaskBase.java:7320)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.createCreateNodeTasks(UniverseDefinitionTaskBase.java:2533)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.createProvisionNodeTasks(UniverseDefinitionTaskBase.java:2726)
com.yugabyte.yw.commissioner.tasks.CreateUniverse.run(CreateUniverse.java:242)
com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:1052)
com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1273)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2025-12-11T20:14:53.238Z  [debug] 50151ae5-3ca3-4325-90a3-2b973e806cfe TaskExecutor.java:1071 [TaskPool-CreateUniverse(13ec05ab-c998-4938-95f8-245c094c8448)-0] com.yugabyte.yw.commissioner.TaskExecutor Completed task YNPProvisioning(13ec05ab-c998-4938-95f8-245c094c8448)(13ec05ab-c998-4938-95f8-245c094c8448, yb-admin-amindrov-failure-test-n1) in 9800ms
2025-12-11T20:14:53.241Z  [debug] 50151ae5-3ca3-4325-90a3-2b973e806cfe TransactionUtil.java:113 [TaskPool-CreateUniverse(13ec05ab-c998-4938-95f8-245c094c8448)-0] com.yugabyte.yw.models.helpers.TransactionUtil Trying(1)...
2025-12-11T20:14:53.243Z  [info] 50151ae5-3ca3-4325-90a3-2b973e806cfe DefaultTaskExecutionListener.java:34 [TaskPool-CreateUniverse(13ec05ab-c998-4938-95f8-245c094c8448)-0] com.yugabyte.yw.commissioner.DefaultTaskExecutionListener Task taskType: YNPProvisioning, taskState: Failure is completed
2025-12-11T20:14:53.254Z  [warn] 50151ae5-3ca3-4325-90a3-2b973e806cfe TaskExecutor.java:1581 [TaskPool-CreateUniverse(13ec05ab-c998-4938-95f8-245c094c8448)-0] com.yugabyte.yw.commissioner.TaskExecutor Task YNPProvisioning(13ec05ab-c998-4938-95f8-245c094c8448)(13ec05ab-c998-4938-95f8-245c094c8448, yb-admin-amindrov-failure-test-n1) with params {"platformVersion":"2.29.0.0-PRE_RELEASE","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","deviceInfo":{"volumeSize":100,"numVolumes":1,"storageClass":"standard","storageType":"Persistent"},"universeUUID":"13ec05ab-c998-4938-95f8-245c094c8448","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"internalYsqlServerRpcPort":6433,"nodeExporterPort":9300,"otelCollectorMetricsPort":8889},"extraDependencies":{"installNodeExporter":true},"runOnlyPrechecks":false,"clusters":[],"currentClusterType":"PRIMARY","rootAndClientRootCASame":true,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"updateSucceeded":true,"universePaused":false,"autoRollbackPerformed":false,"softwareUpgradeState":"Ready","fipsEnabled":false,"isSoftwareRollbackAllowed":false,"nextClusterIndex":1,"allowInsecure":true,"setTxnTableWaitCountFlag":false,"itestS3PackagePath":"","remotePackagePath":"","nodesResizeAvailable":false,"useNewHelmNamingStyle":false,"mastersInDefaultRegion":true,"isKubernetesOperatorControlled":false,"overridePrebuiltAmiDBVersion":false,"sequenceNumber":-1,"importedState":"NONE","capability":"EDITS_ALLOWED","updateOptions":[],"otelCollectorEnabled":false,"skipMatchWithUserIntent":false,"installNodeAgent":false,"nodeAgentMissing":false,"universeDetached":false,"azUuid":"487b4b6a-c039-4039-bed0-ec3f4608613d","nodeName":"yb-admin-amindrov-failure-test-n1","useSystemd":false,"isMaster":false,"isTserver":false,"properties":{},"sshUser":"centos","customerUuid":"f33e3c9b-75ab-4c30-80ad-cba85646ea39","nodeAgentInstallDir":"/opt/yugabyte","isYbPrebuiltImage":false,"xclusterInfo":{"sourceXClusterConfigs":[],"targetXClusterConfigs":[]},"sourceXClusterConfigs":[],"targetXClusterConfigs":[]} attempt 0 has failed
2025-12-11T20:14:53.259Z  [warn] 50151ae5-3ca3-4325-90a3-2b973e806cfe NodeTaskBase.java:75 [TaskPool-CreateUniverse(13ec05ab-c998-4938-95f8-245c094c8448)-0] com.yugabyte.yw.commissioner.tasks.subtasks.NodeTaskBase Encountered a recoverable error, hard rebooting node yb-admin-amindrov-failure-test-n1
2025-12-11T20:14:53.260Z  [info] 50151ae5-3ca3-4325-90a3-2b973e806cfe HardRebootServer.java:20 [TaskPool-CreateUniverse(13ec05ab-c998-4938-95f8-245c094c8448)-0] com.yugabyte.yw.commissioner.tasks.subtasks.HardRebootServer Hard rebooting instance yb-admin-amindrov-failure-test-n1
```

2. Set a breakpoint in `SetupYNP` before the call to `ShellResponse#processErrors`, set its `code` to 3 to trigger a recoverable exception:

```
2025-12-11T20:41:01.271Z  [error] 76ea1c60-ecad-4332-9204-e9c2340b9c56 TaskExecutor.java:1200 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.commissioner.TaskExecutor Failed to execute task type SetupYNP UUID 0cde2b03-006b-4291-bd6c-cd1930bb0464 details {"platformVersion":"2.29.0.0-PRE_RELEASE","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"27418d50-32e9-458c-9604-9bd0b385d4ab","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"internalYsqlServerRpcPort":6433,"nodeExporterPort":9300,"otelCollectorMetricsPort":8889},"extraDependencies":{"installNodeExporter":true},"runOnlyPrechecks":false,"clusters":[],"currentClusterType":"PRIMARY","rootAndClientRootCASame":true,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"updateSucceeded":true,"universePaused":false,"autoRollbackPerformed":false,"softwareUpgradeState":"Ready","fipsEnabled":false,"isSoftwareRollbackAllowed":false,"nextClusterIndex":1,"allowInsecure":true,"setTxnTableWaitCountFlag":false,"itestS3PackagePath":"","remotePackagePath":"","nodesResizeAvailable":false,"useNewHelmNamingStyle":false,"mastersInDefaultRegion":true,"isKubernetesOperatorControlled":false,"overridePrebuiltAmiDBVersion":false,"sequenceNumber":-1,"importedState":"NONE","capability":"EDITS_ALLOWED","updateOptions":[],"otelCollectorEnabled":false,"skipMatchWithUserIntent":false,"installNodeAgent":false,"nodeAgentMissing":false,"universeDetached":false,"azUuid":"487b4b6a-c039-4039-bed0-ec3f4608613d","nodeName":"yb-admin-amindrov-failure-test-n1","useSystemd":false,"isMaster":false,"isTserver":false,"properties":{},"nodeAgentInstallDir":"/opt/yugabyte","sshUser":"centos","customerUuid":"f33e3c9b-75ab-4c30-80ad-cba85646ea39","sudoAccess":true,"xclusterInfo":{"targetXClusterConfigs":[],"sourceXClusterConfigs":[]},"targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
com.yugabyte.yw.common.RecoverableException: Extracting node-agent failed. Code: 3. Output: Command output:
    at com.yugabyte.yw.common.ShellResponse.processErrors(ShellResponse.java:53)
    at com.yugabyte.yw.commissioner.tasks.subtasks.SetupYNP.run(SetupYNP.java:163)
    at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:1052)
    at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1566)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
2025-12-11T20:41:01.272Z  [debug] 76ea1c60-ecad-4332-9204-e9c2340b9c56 TaskExecutor.java:1208 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.commissioner.TaskExecutor Task creator callstack:
com.yugabyte.yw.commissioner.TaskExecutor$SubTaskGroup.addSubTask(TaskExecutor.java:688)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.lambda$createSetupYNPTask$45(UniverseDefinitionTaskBase.java:2380)
java.base/java.lang.Iterable.forEach(Iterable.java:75)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.createSetupYNPTask(UniverseDefinitionTaskBase.java:2356)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.lambda$createCreateNodeTasks$51(UniverseDefinitionTaskBase.java:2541)
com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.applyOnNodesWithStatus(UniverseTaskBase.java:7320)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.createCreateNodeTasks(UniverseDefinitionTaskBase.java:2533)
com.yugabyte.yw.commissioner.tasks.UniverseDefinitionTaskBase.createProvisionNodeTasks(UniverseDefinitionTaskBase.java:2726)
com.yugabyte.yw.commissioner.tasks.CreateUniverse.run(CreateUniverse.java:242)
com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:1052)
com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1273)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2025-12-11T20:41:01.293Z  [debug] 76ea1c60-ecad-4332-9204-e9c2340b9c56 TaskExecutor.java:1071 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.commissioner.TaskExecutor Completed task SetupYNP(27418d50-32e9-458c-9604-9bd0b385d4ab)(27418d50-32e9-458c-9604-9bd0b385d4ab, yb-admin-amindrov-failure-test-n1) in 176199ms
2025-12-11T20:41:01.300Z  [debug] 76ea1c60-ecad-4332-9204-e9c2340b9c56 TransactionUtil.java:113 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.models.helpers.TransactionUtil Trying(1)...
2025-12-11T20:41:01.303Z  [info] 76ea1c60-ecad-4332-9204-e9c2340b9c56 DefaultTaskExecutionListener.java:34 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.commissioner.DefaultTaskExecutionListener Task taskType: SetupYNP, taskState: Failure is completed
2025-12-11T20:41:01.314Z  [warn] 76ea1c60-ecad-4332-9204-e9c2340b9c56 TaskExecutor.java:1581 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.commissioner.TaskExecutor Task SetupYNP(27418d50-32e9-458c-9604-9bd0b385d4ab)(27418d50-32e9-458c-9604-9bd0b385d4ab, yb-admin-amindrov-failure-test-n1) with params {"platformVersion":"2.29.0.0-PRE_RELEASE","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"27418d50-32e9-458c-9604-9bd0b385d4ab","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"internalYsqlServerRpcPort":6433,"nodeExporterPort":9300,"otelCollectorMetricsPort":8889},"extraDependencies":{"installNodeExporter":true},"runOnlyPrechecks":false,"clusters":[],"currentClusterType":"PRIMARY","rootAndClientRootCASame":true,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"updateSucceeded":true,"universePaused":false,"autoRollbackPerformed":false,"softwareUpgradeState":"Ready","fipsEnabled":false,"isSoftwareRollbackAllowed":false,"nextClusterIndex":1,"allowInsecure":true,"setTxnTableWaitCountFlag":false,"itestS3PackagePath":"","remotePackagePath":"","nodesResizeAvailable":false,"useNewHelmNamingStyle":false,"mastersInDefaultRegion":true,"isKubernetesOperatorControlled":false,"overridePrebuiltAmiDBVersion":false,"sequenceNumber":-1,"importedState":"NONE","capability":"EDITS_ALLOWED","updateOptions":[],"otelCollectorEnabled":false,"skipMatchWithUserIntent":false,"installNodeAgent":false,"nodeAgentMissing":false,"universeDetached":false,"azUuid":"487b4b6a-c039-4039-bed0-ec3f4608613d","nodeName":"yb-admin-amindrov-failure-test-n1","useSystemd":false,"isMaster":false,"isTserver":false,"properties":{},"nodeAgentInstallDir":"/opt/yugabyte","sshUser":"centos","customerUuid":"f33e3c9b-75ab-4c30-80ad-cba85646ea39","sudoAccess":true,"xclusterInfo":{"targetXClusterConfigs":[],"sourceXClusterConfigs":[]},"targetXClusterConfigs":[],"sourceXClusterConfigs":[]} attempt 0 has failed
2025-12-11T20:41:01.325Z  [warn] 76ea1c60-ecad-4332-9204-e9c2340b9c56 NodeTaskBase.java:75 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.commissioner.tasks.subtasks.NodeTaskBase Encountered a recoverable error, hard rebooting node yb-admin-amindrov-failure-test-n1
2025-12-11T20:41:01.326Z  [info] 76ea1c60-ecad-4332-9204-e9c2340b9c56 HardRebootServer.java:20 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.commissioner.tasks.subtasks.HardRebootServer Hard rebooting instance yb-admin-amindrov-failure-test-n1
2025-12-11T20:41:01.350Z  [info] 76ea1c60-ecad-4332-9204-e9c2340b9c56 NodeManager.java:377 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.common.NodeManager node.sshUserOverride centos, sshuser used null
2025-12-11T20:41:01.350Z  [info] 76ea1c60-ecad-4332-9204-e9c2340b9c56 NodeManager.java:378 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.common.NodeManager node.sshPortOverride 22, sshPort used 22
2025-12-11T20:41:01.351Z  [info] 76ea1c60-ecad-4332-9204-e9c2340b9c56 NodeManager.java:476 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.common.NodeManager Effective SSH user: centos
2025-12-11T20:41:01.399Z  [info] 76ea1c60-ecad-4332-9204-e9c2340b9c56 ShellProcessHandler.java:181 [TaskPool-CreateUniverse(27418d50-32e9-458c-9604-9bd0b385d4ab)-0] com.yugabyte.yw.common.ShellProcessHandler Starting proc (abbrev cmd) - bin/ybcloud.sh gcp --region us-west2 instance hard_reboot yb-admin-amindrov-failure-test-n1
```

Reviewers: nsingh, anijhawan

Reviewed By: nsingh

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D48979