[BACKPORT 2025.2][#30880] YSQL: fix PG backend crash during shutdown
Summary:
When running concurrent create index stress test, it often fails with the stacktrace:

```
(lldb) bt all
error: libyb_pggate.so GetDIE for DIE 0x32 is outside of its CU 0x3e7b16
* thread #1, name = 'postgres', stop reason = signal SIGSEGV
  * frame #0: 0x00007f497d9e110d libyb_pggate.so`::YBCIsLegacyModeForCatalogOps() [inlined] std::__1::__optional_storage_base<yb::pggate::PgSysTablePrefetcher, false>::has_value[abi:ne210101](this=0x0000000000000130) const at optional:361:82
    frame #1: 0x00007f497d9e110d libyb_pggate.so`::YBCIsLegacyModeForCatalogOps() [inlined] std::__1::optional<yb::pggate::PgSysTablePrefetcher>::operator bool[abi:ne210101](this= Has Value=true ) const at optional:825:84
    frame #2: 0x00007f497d9e110d libyb_pggate.so`::YBCIsLegacyModeForCatalogOps() [inlined] yb::pggate::PgApiImpl::IsSysTablePrefetchingStarted(this=0x0000000000000000) const at pggate.cc:2434:28
    frame #3: 0x00007f497d9e110d libyb_pggate.so`::YBCIsLegacyModeForCatalogOps() [inlined] YBCIsSysTablePrefetchingStarted at ybc_pggate.cc:2445:17
    frame #4: 0x00007f497d9e1106 libyb_pggate.so`::YBCIsLegacyModeForCatalogOps() at ybc_pggate.cc:2054:8
    frame #5: 0x00007f497d9c64ec libyb_pggate.so`yb::pggate::PgTxnManager::SerialNo::IncTxn(this=0x0000105d3fee8800, preserve_read_time_history=<unavailable>, catalog_read_time_serial_no=13) at pg_txn_manager.cc:193:10
    frame #6: 0x00007f497d9c879a libyb_pggate.so`yb::pggate::PgTxnManager::ResetTxnAndSession() [inlined] yb::pggate::PgTxnManager::IncTxnSerialNo(this=0x0000105d3fee87e0) at pg_txn_manager.cc:847:14
    frame #7: 0x00007f497d9c8773 libyb_pggate.so`yb::pggate::PgTxnManager::ResetTxnAndSession(this=0x0000105d3fee87e0) at pg_txn_manager.cc:619:3
    frame #8: 0x00007f497d9c7b48 libyb_pggate.so`yb::pggate::PgTxnManager::FinishPlainTransaction(this=0x0000105d3fee87e0, commit=<unavailable>, ddl_commit_info=<unavailable>) at pg_txn_manager.cc:611:3
    frame #9: 0x00007f497d9c6b15 libyb_pggate.so`yb::pggate::PgTxnManager::~PgTxnManager() [inlined] yb::pggate::PgTxnManager::AbortPlainTransaction(this=0x0000105d3fee87e0) at pg_txn_manager.cc:553:10
    frame #10: 0x00007f497d9c6b02 libyb_pggate.so`yb::pggate::PgTxnManager::~PgTxnManager(this=0x0000105d3fee87e0) at pg_txn_manager.cc:264:3
    frame #11: 0x00007f497d97e31a libyb_pggate.so`yb::RefCountedThreadSafe<yb::pggate::PgTxnManager, yb::DefaultRefCountedThreadSafeTraits<yb::pggate::PgTxnManager>>::Release() const [inlined] yb::RefCountedThreadSafe<yb::pggate::PgTxnManager, yb::DefaultRefCountedThreadSafeTraits<yb::pggate::PgTxnManager>>::DeleteInternal(x=0x0000105d3fee87e0) at ref_counted.h:226:44
    frame #12: 0x00007f497d97e312 libyb_pggate.so`yb::RefCountedThreadSafe<yb::pggate::PgTxnManager, yb::DefaultRefCountedThreadSafeTraits<yb::pggate::PgTxnManager>>::Release() const [inlined] yb::DefaultRefCountedThreadSafeTraits<yb::pggate::PgTxnManager>::Destruct(x=0x0000105d3fee87e0) at ref_counted.h:188:5
    frame #13: 0x00007f497d97e312 libyb_pggate.so`yb::RefCountedThreadSafe<yb::pggate::PgTxnManager, yb::DefaultRefCountedThreadSafeTraits<yb::pggate::PgTxnManager>>::Release(this=0x0000105d3fee87e0) const at ref_counted.h:217:7
    frame #14: 0x00007f497d97f723 libyb_pggate.so`yb::pggate::PgApiImpl::~PgApiImpl() [inlined] scoped_refptr<yb::pggate::PgTxnManager>::~scoped_refptr(this=0x0000105d3fca6ea8) at ref_counted.h:348:13
    frame #15: 0x00007f497d97f712 libyb_pggate.so`yb::pggate::PgApiImpl::~PgApiImpl(this=0x0000105d3fca6d80) at pggate.cc:810:1
    frame #16: 0x00007f497d9d8d56 libyb_pggate.so`::YBCDestroyPgGate() [inlined] std::__1::default_delete<yb::pggate::PgApiImpl>::operator(this=<unavailable>, __ptr=0x0000105d3fca6d80)[abi:ne210101](yb::pggate::PgApiImpl*) const at unique_ptr.h:77:5
    frame #17: 0x00007f497d9d8d4e libyb_pggate.so`::YBCDestroyPgGate() [inlined] std::__1::unique_ptr<yb::pggate::PgApiImpl, std::__1::default_delete<yb::pggate::PgApiImpl>>::reset[abi:ne210101](this=<unavailable>, __p=0x0000000000000000) at unique_ptr.h:290:7
    frame #18: 0x00007f497d9d8d49 libyb_pggate.so`::YBCDestroyPgGate() [inlined] std::__1::unique_ptr<yb::pggate::PgApiImpl, std::__1::default_delete<yb::pggate::PgApiImpl>>::~unique_ptr[abi:ne210101](this=<unavailable>) at unique_ptr.h:259:71
    frame #19: 0x00007f497d9d8d49 libyb_pggate.so`::YBCDestroyPgGate() at ybc_pggate.cc:529:3
    frame #20: 0x0000559cb6843f4b postgres`YBOnPostgresBackendShutdown at pg_yb_utils.c:1280:2
    frame #21: 0x0000559cb6852748 postgres`ProcKill(code=<unavailable>, arg=<unavailable>) at proc.c:916:3
    frame #22: 0x0000559cb6852664 postgres`shmem_exit(code=<unavailable>) at ipc.c:280:3
    frame #23: 0x0000559cb685254d postgres`proc_exit_prepare(code=<unavailable>) at ipc.c:202:2
    frame #24: 0x0000559cb57d13b5 postgres`proc_exit(code=<unavailable>) at ipc.c:115:2
    frame #25: 0x0000559cb6857c93 postgres`PostgresMain(dbname=<unavailable>, username=<unavailable>) at postgres.c:0
    frame #26: 0x0000559cb68025ec postgres`BackendRun(port=<unavailable>) at postmaster.c:5064:2
    frame #27: 0x0000559cb6851f13 postgres`ServerLoop [inlined] BackendStartup(port=<unavailable>) at postmaster.c:4765:3
    frame #28: 0x0000559cb6851eda postgres`ServerLoop at postmaster.c:1915:7
    frame #29: 0x0000559cb574faf3 postgres`PostmasterMain(argc=25, argv=0x0000105d3fe0a340) at postmaster.c:1569:11
    frame #30: 0x0000559cb5692c60 postgres`PostgresServerProcessMain(argc=25, argv=0x0000105d3fe0a340) at main.c:213:3
    frame #31: 0x0000559cb53a0d02 postgres`main + 34
    frame #32: 0x00007f497d42a610 libc.so.6`__libc_start_call_main + 128
    frame #33: 0x00007f497d42a6c0 libc.so.6`__libc_start_main@@GLIBC_2.34 + 128
    frame #34: 0x0000559cb53a0c4e postgres`_start + 46

```

This is a null pointer reference and the sequence is

1. YBCDestroyPgGate() is called during shutdown
```
void YBCDestroyPgGate() {
  LOG_IF(FATAL, !is_main_thread())
      << __PRETTY_FUNCTION__ << " should only be invoked from the main thread";

  if (pgapi_shutdown_done.exchange(true)) {
    LOG(DFATAL) << __PRETTY_FUNCTION__ << " should only be called once";
    return;
  }
  {
    std::unique_ptr<pggate::PgApiImpl> local_pgapi(pgapi);
    pgapi = nullptr; // YBCPgIsYugaByteEnabled() must return false from now on.
  }
  VLOG(1) << __PRETTY_FUNCTION__ << " finished";
}
```
Note that pgapi is set to nullptr before the object `local_pgapi` is destroyed.

2. YBCIsLegacyModeForCatalogOps
```
bool YBCIsLegacyModeForCatalogOps() {
  //
  // If object locking is enabled:
  //
  // (1) Catalog writes will use the CatalogSnapshot's read time serial number instead of the
  //     TransactionSnapshot's read time serial number (which is the legacy pre-object locking
  //     behavior). This is required to allow concurrent DDLs by not causing write-write conflicts
  //     based on overlapping [transaction read time, commit time] windows. The serialization of
  //     catalog modifications via DDLs is now handled by object locks. Catalog writes were using
  //     the kTransactional session type pre-object locking and that stays the same.
  //
  // (2) Catalog reads will always use the kTransactional session type. This is done so that they
  //     can also use the CatalogSnapshot's read time serial number to read the latest data (and)
  //     see the catalog data modified by the current active transaction (this is required because
  //     transactional DDL is enabled if object locking is enabled).
  //
  //     In the pre-object locking mode, catalog reads for DML transactions go via the kCatalog
  //     session type which has a single catalog_read_time_ (see pg_session.h). Catalog reads
  //     executed as part of a DDL transaction (or) after a DDL in a DDL-DML transaction block
  //     (i.e., with transactional DDL enabled) go via the kTransactional session type and would use
  //     the TransactionSnapshot's read time serial number.
  //
  return !YBCIsObjectLockingEnabled() || !yb_enable_concurrent_ddl || YBCIsInitDbModeEnvVarSet()
    || YBCIsSysTablePrefetchingStarted();
}
```
3. YBCIsSysTablePrefetchingStarted
```
bool YBCIsSysTablePrefetchingStarted() {
  return pgapi->IsSysTablePrefetchingStarted();
}
```

Since pgapi is nullptr, `pgapi->IsSysTablePrefetchingStarted()` failed.

Fixed by checking pgapi.

Original commit: ef8adfee0ea706d0c879bca27c8255edf0459dd1 / D51657

Test Plan: Verify the fix using concurrent create index test suite saw no more such crash

Reviewers: pjain, #db-approvers

Reviewed By: pjain, #db-approvers

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D51728