[BACKPORT 2025.1][#28348] YSQL: Fix bug in delete inval messages for dropped database
Summary:
To reproduce the bug:

Create a RF-1 cluster using 2.25.1.0-b85 initdb snapshot (which did not have the table
pg_catalog.pg_yb_invalidation_messages):

```
./bin/yb-ctl create --rf 1 --master_flags initial_sys_catalog_snapshot_path=$HOME/tmp/yugabyte-2.25.1.0/share/initial_sys_catalog_snapshot
```

Run the following ysqlsh session:

```
yugabyte=# create database db1;
CREATE DATABASE
yugabyte=# drop database db1;
ERROR:  relation "pg_catalog.pg_yb_invalidation_messages" does not exist
LINE 1: DELETE FROM pg_catalog.pg_yb_invalidation_messages WHERE db_...
                    ^
QUERY:  DELETE FROM pg_catalog.pg_yb_invalidation_messages WHERE db_oid = 16384
```

This is a recent regression bug introduced by 0dd2f62eb8aa51be520c69f6dfae8276b26d14cc.

I made a change to only delete the invalidation messages associated with db_oid for a dropped
database when the table `pg_catalog.pg_yb_invalidation_messages` exists.
Jira: DB-18033

Original commit: 5f51edbd3833fe10e8688f73c16bd0ab11671bbf / D46534

Test Plan:
Manual test
create a RF-1 cluster using 2.25.1.0 initdb snapshot

```
./bin/yb-ctl create --rf 1 --master_flags initial_sys_catalog_snapshot_path=/net/dev-server-myang/share/tmp/yugabyte-2.25.1.0/share/initial_sys_catalog_snapshot

```

Run the above ysqlsh session, no more error:
```
yugabyte=# create database db1;
CREATE DATABASE
yugabyte=# drop database db1;
DROP DATABASE
yugabyte=#
```

Reviewers: kfranz, sanketh

Reviewed By: kfranz

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D46556