[PLAT-3701][Platform] Task Improvement - Make redis table creation idempotent
Summary:
Redis table creation is via API directly. There is no way to create only if it does not exist.
Creating a redis table internally makes two RPC calls - create NS and create the table in the NS.
As there is no way to get the NS, it attempts to create the NS again and checks the error message.

Test Plan:
Manually ran by inducing failure right after creating the redis table so that the task could be retried.

2022-04-13 20:50:22.591 [info] CreateTable.java:177 [TaskPool-CreateUniverse(70a3a0c3-4d16-4f0b-8ae9-7500b91af339)-0] Running CreateTable(redis): universe = 70a3a0c3-4d16-4f0b-8ae9-7500b91af339, masterAddress = 10.9.201.147:7100
2022-04-13 20:50:23.307 [info] AsyncYBClient.java:2063 [New I/O worker #199] Discovered tablet YB Master for table YB Master with partition ["", "")
2022-04-13 20:50:23.516 [info] YBClient.java:163 [TaskPool-CreateUniverse(70a3a0c3-4d16-4f0b-8ae9-7500b91af339)-0] Redis namespace system_redis already exists.
2022-04-13 20:50:23.820 [info] CreateTable.java:196 [TaskPool-CreateUniverse(70a3a0c3-4d16-4f0b-8ae9-7500b91af339)-0] Created table 'redis' of type REDIS_TABLE_TYPE.

Prior to the fix, the error was
org.yb.client.MasterErrorException: Server[YB Master - 10.9.202.114:7100] ALREADY_PRESENT[code 6]: Keyspace 'system_redis' already exists

Also verified for the case where namespace is created but the table is not created.

Made a minor cleanup in UniverseTaskBase to keep the task classes in one place.

Reviewers: sanketh, amalyshev

Reviewed By: amalyshev

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D16549