Revert "Remove Raw Json for Tables Controller"
Summary:
This reverts commit e5a049d8fe0e20165d1a2b711aea952783bf2b9e.

Latest itest run failed with the error

```
2021-07-01 09:34:49,283 requester.py:52 DEBUG testsimpleops-k8s-rf3 GET successful, response: [{"tableUUID":"000030ad-0000-3000-8000-000000004000","keySpace":"postgres","tableType":"PGSQL_TABLE_TYPE","tableName":"postgresqlkeyvalue","relationType":"USER_TABLE_RELATION","sizeBytes":8294220.0,"isIndexTable":false},{"tableUUID":"cad34414-dc31-4122-be18-6a244a48d982","keySpace":"ybdemo_keyspace","tableType":"YQL_TABLE_TYPE","tableName":"cassandrakeyvalue","relationType":"USER_TABLE_RELATION","sizeBytes":1.1703687E7,"isIndexTable":false}]
2021-07-01 09:34:49,284 yw_proxy.py:516 ERROR testsimpleops-k8s-rf3 Did not find REDIS_TABLE_TYPE system_redis.redis Table
2021-07-01 09:34:49,284 test_base.py:155 ERROR testsimpleops-k8s-rf3 ITEST FAILED testsimpleops-k8s-rf3 : RuntimeError('Table REDIS_TABLE_TYPE system_redis.redis not found.')
```

Test Plan: Create a universe with yedis enabled, verify that the table listing returns redis table.

Reviewers: wesley, daniel

Reviewed By: daniel

Subscribers: jenkins-bot

Differential Revision: https://phabricator.dev.yugabyte.com/D12148