[BACKPORT 2025.2][#28810] YSQL,ASH: Take time range as input in yb_active_session_history() SQL function
Summary:
Original commit: 910e4279a6a57afcc3749e7e9539106c359b5177 / D47717
The most common query pattern for ASH is on the sample_time column,
mostly for the last 'X' minutes. But this filter is not pushed down to the
underlying C function, so we end up scanning the entire circular buffer
before discarding the rows that don't pass the filter.

Here is an example explain plan where we don't end up returning any rows
(because the sample_time filter was given a time in the future) but still the
execution time is 382 ms.
```
yugabyte=# explain (analyze) select * from yb_active_session_history where sample_time >= '2025-10-29T04:15:28.762800Z';
                                                             QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------
 Function Scan on yb_active_session_history  (cost=0.00..1250.00 rows=33333 width=280) (actual time=375.689..375.690 rows=0 loops=1)
   Filter: (sample_time >= '2025-10-29 04:15:28.7628+00'::timestamp with time zone)
   Rows Removed by Filter: 556926
 Planning Time: 0.054 ms
 Execution Time: 382.964 ms
 Peak Memory Usage: 4229 kB
(6 rows)
```

This diff updates the existing function `yb_active_session_history()` to
`yb_active_session_history(start_time TIMESTAMPTZ DEFAULT NULL, end_time TIMESTAMPTZ DEFAULT NULL)`

Here is what the parameters mean:
- `start_time`: Out of all the rows returned, the lowest `sample_time` should not be less than start_time. If this is NULL, rows will be returned from the earliest available time in the circular buffer
- `end_time`: Out of all the rows returned, the highest `sample_time` should not be more than or equal to end_time. If this is NULL, rows will be returned till the most recent available time in the circular buffer

This function returns the rows between `start_time` and `end_time` in increasing
order of sample_time. Since the circular buffer stores the entries in the
increasing order of sample_time, we can binary search to find the indexes
between which we should scan the circular buffer. This results in only a
portion of the circular buffer being scanned, and as a result, it speeds up
ASH queries with filters on sample_time.

Here are some of the possible configurations of this function:
- `yb_active_session_history()`: Returns all the rows in ascending order of `sample_time`
- `yb_active_session_history(X)`: Returns all the rows where `sample_time >= X` in ascending order of `sample_time`
- `yb_active_session_history(end_time => Y)`: Returns all the rows where `sample_time < Y` in ascending order of `sample_time`
- `yb_active_session_history(X, Y)`: Returns all the rows where `X <= sample_time < Y` in ascending order of `sample_time`

If the user gives `start_time > end_time` in the arguments, an error is returned.

In the following example, we can see that, with the old view, 320484 rows
were scanned from the buffer, and then discarded, with the execution time
being 589 ms. But with the new SQL function with the same sample_time filters,
we don't scan the buffer (because the sample_time filter is in the future), and
the execution time is lower than 1 ms.
```
yugabyte=# explain analyze select * from yb_active_session_history where sample_time >= '2025-11-16T20:07:06.762800Z' AND sample_time <= '2025-11-17T20:07:06.762800Z';
                                                                               QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Function Scan on yb_active_session_history  (cost=0.00..1500.00 rows=500 width=280) (actual time=581.779..581.779 rows=0 loops=1)
   Filter: ((sample_time >= '2025-11-17 01:37:06.7628+05:30'::timestamp with time zone) AND (sample_time <= '2025-11-18 01:37:06.7628+05:30'::timestamp with time zone))
   Rows Removed by Filter: 320484
 Planning Time: 0.117 ms
 Execution Time: 589.378 ms
 Peak Memory Usage: 4223 kB
(6 rows)

yugabyte=# explain analyze select * from yb_active_session_history('2025-11-16T20:07:06.762800Z', '2025-11-17T20:07:06.762800Z');
                                                                QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------
 Function Scan on yb_active_session_history  (cost=0.00..1000.00 rows=100000 width=280) (actual time=0.035..0.035 rows=0 loops=1)
 Planning Time: 0.043 ms
 Execution Time: 0.073 ms
 Peak Memory Usage: 44 kB
(4 rows)
```

Some more changes --
- Introduced a new function `YbGetNumberOfFunctionInputParameters` to decide whether to expect arguments or not in the SQL function.

Test Plan:
./yb_build.sh --cxx-test pg_ash-test --gtest_filter YbAshV2Test.TestStartTimeGreaterThanEndTime
./yb_build.sh --cxx-test pg_ash-test --gtest_filter YbAshV2Test.TestRowsAreInAscendingOrderOfSampleTime
./yb_build.sh --cxx-test pg_ash-test --gtest_filter YbAshV2Test.TestStartTimeIsInclusive
./yb_build.sh --cxx-test pg_ash-test --gtest_filter YbAshV2Test.TestEndTimeIsExclusive
./yb_build.sh --cxx-test pg_ash-test --gtest_filter YbAshV2TestWithCircularBufferSize.TestYbAshFunctionAndViewReturnSameSamples/0
./yb_build.sh --cxx-test pg_ash-test --gtest_filter YbAshV2TestWithCircularBufferSize.TestYbAshFunctionAndViewReturnSameSamples/1

./yb_build.sh --java-test TestYsqlUpgrade

Manually tested that difference in versions of schema and code are handled properly. Steps --
- Checkout the previous HEAD and run `./yb_build.sh reinitdb`
- Checkout this commit and run `./yb_build.sh`
- Start a cluster, connect with ysqlsh and run the following queries
```
yugabyte=# select * from yb_active_session_history;
           sample_time           |           root_request_id            | rpc_request_id | wait_event_component | wait_event_class |  wait_event  |          top_level_node_id           | query_id |  pid  | client_node_ip  | wait_event_aux | sample_weight | wait_event_type | ysql_dbid | wait_event_code | pss_mem_bytes | ysql_userid
---------------------------------+--------------------------------------+----------------+----------------------+------------------+--------------+--------------------------------------+----------+-------+-----------------+----------------+---------------+-----------------+-----------+-----------------+---------------+-------------
 2025-12-10 17:55:10.1961+05:30  | 00000000-0000-0000-0000-000000000000 |             45 | TServer              | Common           | OnCpu_Active | b70c8258-3d1f-41bd-a532-97a11255605b |        5 | 13744 | 127.0.0.1:53815 |                |             1 | Cpu             |     13529 |      4143972352 |             0 |           0
(1 row)

yugabyte=# select * from yb_active_session_history(current_timestamp);
ERROR:  function yb_active_session_history(timestamp with time zone) does not exist
LINE 1: select * from yb_active_session_history(current_timestamp);
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
- Run `./yb-admin upgrade_ysql`. This will apply the migration files and the schema will be updated
- From the same connection, run the following queries
```
yugabyte=# select * from yb_active_session_history;
           sample_time            |           root_request_id            | rpc_request_id | wait_event_component | wait_event_class |  wait_event  |          top_level_node_id           |      query_id       |  pid  | client_node_ip  | wait_event_aux | sample_weight | wait_event_type | ysql_dbid | wait_event_code | pss_mem_bytes | ysql_userid
----------------------------------+--------------------------------------+----------------+----------------------+------------------+--------------+--------------------------------------+---------------------+-------+-----------------+----------------+---------------+-----------------+-----------+-----------------+---------------+-------------
 2025-12-10 17:55:10.1961+05:30   | 00000000-0000-0000-0000-000000000000 |             45 | TServer              | Common           | OnCpu_Active | b70c8258-3d1f-41bd-a532-97a11255605b |                   5 | 13744 | 127.0.0.1:53815 |                |             1 | Cpu             |     13529 |      4143972352 |             0 |           0
(1 row)

yugabyte=# select * from yb_active_session_history(current_timestamp);
 sample_time | root_request_id | rpc_request_id | wait_event_component | wait_event_class | wait_event | top_level_node_id | query_id | pid | client_node_ip | wait_event_aux | sample_weight | wait_event_type | ysql_dbid | wait_event_code | pss_mem_bytes | ysql_userid
-------------+-----------------+----------------+----------------------+------------------+------------+-------------------+----------+-----+----------------+----------------+---------------+-----------------+-----------+-----------------+---------------+-------------
(0 rows)
```

Reviewers: jason, ishan.chhangani

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D51143