[PLAT-16688][YBA CLI]Add support for enabling connection pooling during universe creation
Summary:
Add a provision to introduce preview flags similar to preview commands

Addition to create universe flags:
```
      --enable-connection-pooling                        This is a preview flag (may change in future). [Optional] Enable Connection Pooling for the universe. (default false)
      --internal-ysql-server-rpc-port int                This is a preview flag (may change in future). [Optional] Internal YSQL Server RPC Port used when connection pooling is enabled. (default 6433)
```

```
 yba universe edit
Error: required flag(s) "name" not set
Usage:
  yba universe edit [flags]
  yba universe edit [command]

Preview Commands (may change in future)
  ysql        Edit YSQL settings for a YugabyteDB Anywhere Universe

Flags:
  -f, --force              [Optional] Bypass the prompt for non-interactive usage.
  -n, --name string        [Required] The name of the universe to be edited.
  -s, --skip-validations   [Optional] Skip validations before running the CLI command.
  -h, --help               help for edit

Global Flags:
  -a, --apiToken string    YugabyteDB Anywhere api token.
      --config string      Config file, defaults to $HOME/.yba-cli.yaml
      --debug              Use debug mode, same as --logLevel debug.
      --disable-color      Disable colors in output. (default false)
  -H, --host string        YugabyteDB Anywhere Host (default "http://localhost:9000")
  -l, --logLevel string    Select the desired log level format. Allowed values: debug, info, warn, error, fatal. (default "info")
  -o, --output string      Select the desired output format. Allowed values: table, json, pretty. (default "table")
      --timeout duration   Wait command timeout, example: 5m, 1h. (default 168h0m0s)
      --wait               Wait until the task is completed, otherwise it will exit immediately. (default true)
```

```
yba universe edit ysql
Edit YSQL settings for a YugabyteDB Anywhere Universe

Usage:
  yba universe edit ysql [flags]

Aliases:
  ysql, ysql-configure, configure-ysql

Examples:
yba universe edit ysql --name <universe-name>

Flags:
      --ysql string                         [Optional] YSQL endpoint. Allowed values: enable, disable.
      --ysql-auth string                    [Optional] YSQL authentication. Allowed values: enable, disable.
      --ysql-password string                [Optional] YSQL authentication password. Use single quotes ('') to provide values with special characters. Required when YSQL authentication is enabled
      --connection-pooling string           [Optional] Connection Pooling settings. Allowed values: enable, disable.
      --ysql-server-http-port int           [Optional] YSQL Server HTTP Port. (default 13000)
      --ysql-server-rpc-port int            [Optional] YSQL Server RPC Port. (default 5433)
      --internal-ysql-server-rpc-port int   [Optional] Internal YSQL Server RPC Port used when connection pooling is enabled. (default 6433)
  -h, --help                                help for ysql

Global Flags:
  -a, --apiToken string    YugabyteDB Anywhere api token.
      --config string      Config file, defaults to $HOME/.yba-cli.yaml
      --debug              Use debug mode, same as --logLevel debug.
      --disable-color      Disable colors in output. (default false)
  -f, --force              [Optional] Bypass the prompt for non-interactive usage.
  -H, --host string        YugabyteDB Anywhere Host (default "http://localhost:9000")
  -l, --logLevel string    Select the desired log level format. Allowed values: debug, info, warn, error, fatal. (default "info")
  -n, --name string        [Required] The name of the universe to be edited.
  -o, --output string      Select the desired output format. Allowed values: table, json, pretty. (default "table")
  -s, --skip-validations   [Optional] Skip validations before running the CLI command.
      --timeout duration   Wait command timeout, example: 5m, 1h. (default 168h0m0s)
      --wait               Wait until the task is completed, otherwise it will exit immediately. (default true)
```

Test Plan:
`yba universe create -n dkumar-cli --provider-code gcp --provider-name dkumar-cli --yb-db-version 2.25.0.0-b144 --num-nodes 1 --replication-factor 1 --user-tags yb_owner=dkumar,yb_task=dev,yb_dept=eng  --enable-connection-pooling`

`yba universe edit ysql --name dkumar-cli --ysql enable --ysql-auth enable --ysql-password 'Password#123' --connection-pooling enable

` yba universe edit ysql --name dkumar-cli --ysql disable`

Reviewers: skurapati, vbansal, sneelakantan

Reviewed By: skurapati, sneelakantan

Subscribers: mzafar, yash.priyam, yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D41835