[#10308] YSQL: Prevent setting tablespaces for temp tables
Summary:
Temporary tables are not backed by DocDB storage. Therefore assigning
tablespaces to temporary tables in Yugabyte clusters is meaningless.
Currently, trying to assign a tablespace to a temporary table throws the following error:

```
yugabyte=# CREATE TEMPORARY TABLE test (key int) TABLESPACE testtablespace;
ERROR:  could not create directory "pg_tblspc/16384/PG_11_201809051/12463": No such file or directory
```

This patch modifies this behavior to the following:
```
yugabyte=# CREATE TEMPORARY TABLE test (key int) TABLESPACE testtablespace;
ERROR:  cannot set tablespaces for temporary tables
```

Test Plan: ybd --scb --sj --java-test org.yb.pgsql.TestPgRegressTablespaces

Reviewers: amartsinchyk

Reviewed By: amartsinchyk

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D13425