[BACKPORT 2.17.0] [PLAT-6464] [Openshift] Support bundle creation failed with group id '1000720000' is too big
Summary:
Creating a support bundle on openshift throws the following error:
```
java.lang.IllegalArgumentException: group id '1000720000' is too big ( > 2097151 ).
Use STAR or POSIX extensions to overcome this limit
```

Added tarArchive setBigNumberMode to fix the POSIX issue.

Original commit: 650e05e679d03458d0ef33eb373ea241bbd314f7 / D21562

Test Plan:
Ran UTs
Ran itests.

@bgandhi helped do manual testing for this on master (2.17.1). What he did was:
```
Run the latest itest image of yugaware on an OpenShift cluster.
And change the container entrypoint to sleep instead of running yugaware jar.
And we will copy the jar to this running container and start the yugaware process.
That way we will be able to run the code without building a new container image.
```
After this, we manually created a universe on the openshift portal containing the new jar files, and created a support bundle. It got created successfully.

Reviewers: sanketh, bgandhi, sneelakantan

Reviewed By: sneelakantan

Subscribers: yugaware, jenkins-bot, bgandhi

Differential Revision: https://phabricator.dev.yugabyte.com/D21607