[#30491] YSQL: add debug log for pgstat catalog version update
Summary:
We still see index creation timeout error in concurrent create index test:
```
om.yugabyte.util.PSQLException: ERROR: timed out waiting for postgres backends to catch up
  Detail: 1 backends on database 16385 are still behind catalog version 966.
  Hint: Run the following query on all tservers to find the lagging backends: SELECT * FROM pg_stat_activity WHERE backend_type != "walsender" AND backend_type != "yb-conn-mgr walsender" AND backend_type != "yb auto analyze backend" AND backend_type != "yb index backfill" AND backend_type != "yb matview refresh" AND catalog_version < 966 AND datid = 16385;
  Where: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.; Thread 4 (test_kfin_tech_matview_21.idx_t4_20_98884): com.yugabyte.util.PSQLException: ERROR: timed out waiting for postgres backends to catch up
```

To help debugging, I made a change to log pgstat catalog version each time when it is set via
function `yb_pgstat_set_catalog_version`. In this way we should be able to find out each PG
backend's current pgstat catalog version (which is displayed in the system view pg_stat_activity as
catalog_version column). We should be able to find out which PG backend's last set pgstat catalog
version is still < 966.

I also added MyDatabaseId into the various relevant logs.

Test Plan:
Manual test, create RF-1 cluster, run a simple command via ysqlsh:
```
./bin/yb-ctl create --rf 1 --tserver_flags='log_ysql_catalog_versions=true'
./bin/ysqlsh
ysqlsh (15.12-YB-2.29.0.0-b0)
Type "help" for help.

yugabyte=# select 1;
 ?column?
----------
        1
(1 row)

yugabyte=# create table foo(id int);
CREATE TABLE
yugabyte=# create index on foo(id);
CREATE INDEX
```
Look at the PG log for the new logs:
```
2026-03-09 18:35:32.018 UTC [483599] LOG:  set db 0 local catalog version: 1
2026-03-09 18:35:32.018 UTC [483599] LOG:  set db 0 pgstat catalog version: 1
2026-03-09 18:35:38.350 UTC [483629] LOG:  set db 0 local catalog version: 1
2026-03-09 18:35:38.350 UTC [483629] LOG:  set db 0 pgstat catalog version: 1
2026-03-09 18:35:38.358 UTC [483629] LOG:  set db 13537 local catalog version: 1
2026-03-09 18:35:38.358 UTC [483629] LOG:  set db 13537 pgstat catalog version: 1
2026-03-09 18:35:38.385 UTC [483640] LOG:  set db 0 local catalog version: 1
2026-03-09 18:35:38.385 UTC [483640] LOG:  set db 0 pgstat catalog version: 1
2026-03-09 18:35:38.387 UTC [483640] LOG:  set db 13537 local catalog version: 1
2026-03-09 18:35:38.387 UTC [483640] LOG:  set db 13537 pgstat catalog version: 1
2026-03-09 18:35:38.528 UTC [483640] LOG:  set db 13537 local catalog version: 1
2026-03-09 18:35:38.528 UTC [483640] LOG:  set db 13537 pgstat catalog version: 1
2026-03-09 18:35:38.537 UTC [483640] LOG:  set db 13537 pgstat catalog version: 1
2026-03-09 18:35:44.282 UTC [483629] LOG:  set db 13537 pgstat catalog version: 1
2026-03-09 18:35:49.161 UTC [483629] LOG:  set db 13537 pgstat catalog version: 1
2026-03-09 18:35:49.542 UTC [483629] LOG:  set db 13537 new catalog version: 2
2026-03-09 18:35:49.600 UTC [483629] LOG:  set db 13537 local catalog version: 2
2026-03-09 18:35:49.600 UTC [483629] LOG:  set db 13537 pgstat catalog version: 2
2026-03-09 18:35:54.216 UTC [483629] LOG:  set db 13537 pgstat catalog version: 2
2026-03-09 18:35:54.433 UTC [483629] LOG:  set db 13537 new catalog version: 3
2026-03-09 18:35:54.459 UTC [483629] LOG:  set db 13537 local catalog version: 3
2026-03-09 18:35:54.459 UTC [483629] LOG:  set db 13537 pgstat catalog version: 3
2026-03-09 18:35:54.489 UTC [483679] LOG:  set db 0 local catalog version: 1
2026-03-09 18:35:54.489 UTC [483679] LOG:  set db 0 pgstat catalog version: 1
2026-03-09 18:35:54.657 UTC [483679] LOG:  set db 1 local catalog version: 1
2026-03-09 18:35:54.657 UTC [483679] LOG:  set db 1 pgstat catalog version: 1
2026-03-09 18:35:54.666 UTC [483679] LOG:  set db 1 pgstat catalog version: 1
2026-03-09 18:35:54.827 UTC [483679] LOG:  set db 1 pgstat catalog version: 1
2026-03-09 18:35:54.846 UTC [483629] LOG:  set db 13537 new catalog version: 4
2026-03-09 18:35:54.851 UTC [483629] LOG:  set db 13537 local catalog version: 4
2026-03-09 18:35:54.851 UTC [483629] LOG:  set db 13537 pgstat catalog version: 4
2026-03-09 18:35:54.881 UTC [483693] LOG:  set db 0 local catalog version: 1
2026-03-09 18:35:54.881 UTC [483693] LOG:  set db 0 pgstat catalog version: 1
2026-03-09 18:35:54.893 UTC [483693] LOG:  set db 1 pgstat catalog version: 1
2026-03-09 18:35:55.146 UTC [483693] LOG:  set db 1 pgstat catalog version: 1
2026-03-09 18:35:55.193 UTC [483704] LOG:  set db 0 local catalog version: 1
2026-03-09 18:35:55.193 UTC [483704] LOG:  set db 0 pgstat catalog version: 1
2026-03-09 18:35:55.194 UTC [483704] LOG:  set db 13537 local catalog version: 4
2026-03-09 18:35:55.194 UTC [483704] LOG:  set db 13537 pgstat catalog version: 4
2026-03-09 18:35:55.207 UTC [483704] LOG:  set db 13537 pgstat catalog version: 4
2026-03-09 18:35:55.208 UTC [483704] LOG:  set db 13537 pgstat catalog version: 4
2026-03-09 18:35:55.250 UTC [483704] LOG:  set db 13537 pgstat catalog version: 4
2026-03-09 18:35:55.299 UTC [483629] LOG:  set db 13537 new catalog version: 5
2026-03-09 18:35:55.301 UTC [483629] LOG:  set db 13537 local catalog version: 5
2026-03-09 18:35:55.301 UTC [483629] LOG:  set db 13537 pgstat catalog version: 5
```
Note those db 0 logs happen at the beginning of the connection when MyDatabaseId wasn't
even set yet.

Reviewers: sanketh, kfranz

Reviewed By: kfranz

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D51078