[BACKPORT 2.18][PLAT-7281] All ws clients to start using YBA's custom CA trust-store
Summary:
When a custom CA certificate is added, updated, or deleted in YBA's
trust-store, this change updates all the trust-store listeners about the change
in the custom CA certificates. Today, there is one type of listener - all siloed
ws clients.

It adds `[{"path":<truststore path>, "type":<truststore type>, "password": <>}, ...]`
of the YBA's trust-store to ws SSL configuration so that these CA trust certificates
can also be used along with the default certificates Java runtime would use. It is
important to note that if we configure play.ws.ssl to say that there is a custom store
path/data then we must state all the default Java SSL paths to it as well. Hence, this
change also figures out all the default Java truststore configurations using system
properties and adds it to Play's SSL config as well.

All of these configurations are added only if the trust-store paths exists and there is
at least one custom CA certificate in it.

This change also includes changes related to wsClient from D26317 or 5548a8c18644
Original diff: D26035 or 0b5f2f92d128

Test Plan:
- Generic

1. Add no custom CA certs, ws SSL config is not updated.
2. Add/update/delete a custom CA, ws SSL config gets updated if there is any ws client active.
3. Remove the last custom CA, ensure ws SSL config is not updated as ca bundles are empty.

- HA

Created a replicated YBA with a custom CA certificate. During HA setup,
uploaded an incorrect cert for peer in HA. This because during HA setup
with HTTPs peer YBAs we force users to provide a root cert.
With this config, if the custom CA cert was not added using trust-store
APIs, it errored out as follows when active instance tried to sync YBA
backup to standby instance-
```
com.yugabyte.yw.common.ApiHelper Unexpected exception while parsing response
java.util.concurrent.ExecutionException: java.net.ConnectException:
  No trust manager was able to validate this certificate chain: # of exceptions = 1
...
Caused by: com.typesafe.sslconfig.ssl.CompositeCertificateException:
...
```
After adding the custom CA cert to trust-store, active instance was able
to send backups to the standby instance. Deleting the same CA certificate
from custom trust-store caused the next backup sync to fail.

Also, sent backups to an endpoint configured with well-known CA. It went
past the SSL connection and then failed, meaning the handshake was working.
Without adding the default Java paths into SSL config it would fail.

- Webhook/alerts.
Tested HTTPs Moogsoft endpoint with well-known CA.

Reviewers: amalyshev, sb-yb, nbhatia, cwang

Reviewed By: sb-yb, cwang

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D26463