[BACKPORT 2.19.2][#18928] YSQL: Fixed multiple bugs for YSQL Connection Manager
Summary:
Original commit: 5e923a03d67b17739f2b5dd9db4e642672485982 / D28269
The following errors needed to be fixed:

- `Error at shmat for shared memory segment with id '3997710'. Invalid argument`
- Broken connections:

```
ERROR:  odyssey: ccf74520740e9: remote server read/write error saea3be703d62: Broken pipe
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded
```
as well as the difference in the number of server connections in stats from 13000/rpcz and 13000/connections apis.

- Duplicate db stats in the response of 13000/connections API call:

  - This is faced when a route (pool) is closed due to no client connection.
  - This is due to a wrong index assignment policy for yb_stats for the route, leading to a new index allocation for a db whenever a new route for the same db is created (the previous route was destroyed due to no client connection)
Jira: DB-7779

Test Plan:
Jenkins: urgent
Ensure that sysbench create and run works fine for a high number of threads (10000). Check that during the sysbench run,  13000/connections API shows an appropriate value of the number of logical connections.

Reviewers: nkumar

Reviewed By: nkumar

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D28281