[#26734] YSQL: DDL Savepoints part 1 - Track sub_transaction_id in DDLs
Summary:
Currently, YSQL does not support executing Data Definition Language (DDL) statements within a transaction block that also uses SAVEPOINTs. Attempting to do so results in the following error:

```
yugabyte=*# savepoint foo;
SAVEPOINT
yugabyte=*# create table foo();
ERROR:  interleaving SAVEPOINT & DDL in transaction block not supported by YugaByte yet
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/26734. React with thumbs up to raise its priority.
```

This limitation breaks compatibility with standard PostgreSQL.
- Many applications and ORM frameworks rely on savepoints to manage complex transaction logic, such as implementing conditional execution paths or handling partial rollbacks. Forcing users to remove SAVEPOINTs from their DDL transactions creates significant friction for migrating applications to YugabyteDB.
- The READ COMMITTED isolation level, a common default, internally uses sub-transactions for each statement to provide statement-level atomicity.
- Functions use sub-transactions to implement BEGIN...EXCEPTION blocks for error handling. This means that any stored procedure that includes a DDL statement inside an exception block would be unusable, hindering the migration of procedural code.

Supporting savepoints for DDLs requires more work than for DMLs due to how YB provides atomicity to DDLs.
- DMLs operate directly on table data within the distributed DocDB storage layer. Rolling back a DML is handled natively by the transaction system, which simply discards the provisional records written by the txn / subtxn.
- DDLs modify the database's schema which is outside the confines of YB's transactional system. YB uses a special two-phase process for atomicity. The schema change is first applied, and a ysql_ddl_txn_verifier_state is written to the system catalog. If the transaction later aborts, the yb-master uses this state to perform an explicit reverse operation to roll back DocDB schema.

Following this process, a ROLLBACK TO SAVEPOINT involving a DDL must trigger an explicit rollback of the DocDB schema via yb-master. To do this, save `ysql_ddl_txn_verifier_state` for each subtxn. To rollback a set of savepoints, perform the revert operation for each `ysql_ddl_txn_verifier_state` corresponding to the rolled back subtxns and remove the entries from the `ysql_ddl_txn_verifier_state`.

Done in this revision:
- Each DDL that makes changes to DocDB schema now also stores the sub_transaction_id in the `ysql_ddl_txn_verifier_state`
- A `ysql_ddl_txn_verifier_state` entry per savepoint is stored in sys-catalog
- Transaction commit and rollback logic has been updated to handle multiple ysql_ddl_txn_verifier_state entries
- Changes are covered by the test flag `ysql_yb_ddl_savepoint_enabled`

Example:
```
begin;
create table test (a int, d int);
savepoint a;
alter table test add column b text;
savepoint b;
alter table test add column c text;
alter table test add column e text;
savepoint c;
alter table test drop column d;
```
For the above transaction, the `ysql_ddl_txn_verifier_state` of the table `test` will have the following entries:
```
ysql_ddl_txn_verifier_state {
  contains_create_table_op: true
  sub_transaction_id: 1
}
ysql_ddl_txn_verifier_state {
  contains_alter_table_op: true
  previous_schema: ...
  previous_table_name: "test"
  sub_transaction_id: 2
}
ysql_ddl_txn_verifier_state {
  contains_alter_table_op: true
  previous_schema: ...
  previous_table_name: "test"
  sub_transaction_id: 3
}
ysql_ddl_txn_verifier_state {
  contains_alter_table_op: true
  previous_schema: ...
  previous_table_name: "test"
  sub_transaction_id: 4
}
```

At the current state, this revision doesn't offer any new user facing functionality. It just ensures that the overall transaction commit and abort works even if there were savepoints in the block.

Left for follow-ups:
- Rollback to a savepoint which contains a DDL will not rollback the DocDB schema changes. This support will be added in a follow-up. Not an issue since the feature is disabled via test flag

**Upgrade/Rollback safety:**
This is a new feature guarded under a test flag
Jira: DB-16109

Test Plan:
```
./yb_build.sh --cxx-test pgwrapper_pg_ddl_transaction-test --gtest_filter bool/PgDdlSavepointMiniClusterTest.TestTransactionStateMultipleSubTransactions/0
./yb_build.sh --cxx-test pgwrapper_pg_ddl_transaction-test --gtest_filter bool/PgDdlSavepointMiniClusterTest.TestTransactionStateMultipleSubTransactions/1
./yb_build.sh --cxx-test pgwrapper_pg_ddl_transaction-test --gtest_filter bool/PgDdlSavepointMiniClusterTest.TestTransactionStateRollForwards/0
./yb_build.sh --cxx-test pgwrapper_pg_ddl_transaction-test --gtest_filter bool/PgDdlSavepointMiniClusterTest.TestTransactionStateRollForwards/1
```

Reviewers: hsunder, mlillibridge, pjain, myang, patnaik.balivada, fizaa

Reviewed By: myang

Subscribers: svc_phabricator, jhe, yql

Differential Revision: https://phorge.dev.yugabyte.com/D45506