[BACKPORT 2.12][#11715] YSQL: Fix bug in statement_timeout rollback
Summary:
The test org.yb.pgsql.TestPgRegressPlpgsql.testPgRegressPlpgsql fails intermittently with an
error such as:

```
ERROR:  Timed out: InsertSequenceTuple RPC (request call id 4099) to 127.69.38.127:10214 timed out
after 4.000s
```

After debugging, I found that this is because the test has set a shorter statement_timeout earlier:

```
create function trap_timeout() returns void as $$
begin
  declare x int;
  begin
    -- we assume this will take longer than 2 seconds:
    select count(*) into x from tenk1 a, tenk1 b, tenk1 c;
  exception
    when others then
      raise notice 'caught others?';
    when query_canceled then
      raise notice 'nyeah nyeah, can''t stop me';
  end;
  -- Abort transaction to abandon the statement_timeout setting.  Otherwise,
  -- the next top-level statement would be vulnerable to the timeout.
  raise exception 'end of function';
end$$ language plpgsql;

begin;
set statement_timeout to 2000;
select trap_timeout();
rollback;
```

Here within the `begin;` block, `statement_timeout` is set to 2000ms. Then because the `begin;` block
is rolled back, Postgres will also rollback `statement_timeout` to the old value 0 (which means no timeout
in Postgres). When we set `statement_timeout` to 2000ms, or set `statement_timeout` back to 0 on rollback,
`YBCSetTimeout` is called to propagate the new value to the current pggate via

```
  pgapi->SetTimeout(timeout_ms);
```

There is a bug in `YBCSetTimeout`: when the input timeout_ms is 0, it does not do anything and
simply returned. This leaves the old 2000ms in pgapi, which affects future top-level statement
timeout. Internally, YB adds an additional 2 seconds to 2000ms as the outbound RPC timeout.  That
gives 4000ms. Most of the time, top-level statements can execute successfully within 4000ms. But
occasionally there will be a statement whose execution exceeds 4000ms, causing the timeout error as shown above.

I fixed the bug by taking care of 0 for timeout_ms. Because 0 means no timeout, the default RPC
timeout is used in `pgapi->SetTimeout(timeout_ms);`.

Original commit: 615bb758d8046d840f88a75612a507d4ede808a0 / D17986

Test Plan:
Jenkins: rebase: 2.12
./yb_build.sh debug --java-test 'org.yb.pgsql.TestPgRegressPlpgsql#testPgRegressPlpgsql'

Reviewers: mihnea, zyu

Reviewed By: zyu

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D18016