[#20340] YSQL: Mitigate MISMATCHED_SCHEMA error in cross DB concurrent DDLs
Summary:
While performing Cross-DB Concurrent DDLs with per-database catalog version turned on,
some DDLs failed with the below error,

DDL Query:
```
CREATE TABLE tempTable1 AS SELECT * FROM tb_0 limit 1000000
```

Error :
```
ERROR: The catalog snapshot used for this transaction has been invalidated:
MISMATCHED_SCHEMA Where: Catalog Version Mismatch: A DDL occurred while
processing this query. Try again.
```

Context:

* We are concurrently executing Cross-DB DDLs Sample app with multiple threads.
  Notably, we ensure there is no simultaneous execution of DDL and DML operations
  within the same database.
* The table doesn't contains any data.
* No Global DDLs are being executed.

After debugging, I found that this is caused by the contention in the buffer
that stores shared cache invalidation messages. When a backend A needs to store
a list of invalidation messages, if the buffer is full, it needs to discard some
messages from the buffer. Each backend maintains `nextMsgNum` pointer indicating
the next message it needs to read. If one of the discarded messages has not been
read/consumed by a backend B, then backend B needs to have its `resetState` set
to true, which will trigger backend B to invoke `InvalidateSystemCaches` which in
turn calls `YbResetCatalogCacheVersion` in YSQL. That will reset
`yb_catalog_cache_version` of backend B to 0, leading to the above error when
backend B makes a RPC call to tserver.

To mitigate the issue, I made a change that utilize the fact that backend B only
needs to apply a message that was sent by itself:

```
    /* In YB mode all messages originated by other processes are silently ignored */
    if (IsYugaByteEnabled() && msg->yb_header.sender_pid != getpid())
        return;
```

So we do not need to set `resetState` of backend B to true if the discarded
messages were not sent by backend B. We can simply mark backend B as if it
had already read those discarded messages.

Test Plan:
Deploy a package with this diff and run the SqlCrossDBLoadWithDDL test and
confirm that the above error disappeared (this bug could not be reproduced
using a local cluster on my dev vm).

Reviewers: jason, tverona

Reviewed By: jason

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D31584