[YSQL] #995: Raise error on unsupported WHERE condition with secondary index
Summary:
Currently, WHERE condition using the "IN", "IS NULL", "IS NOT NULL", etc with a secondary index is
not supported yet. In this revision, the underlying search option will be checked and error will be
raised when such options are used.

Test Plan:
yb_create_index.sql

```
postgres=# create table t (a int);
CREATE TABLE
postgres=# create index on t (a);
CREATE INDEX
postgres=# insert into t values (1);
INSERT 0 1
postgres=# insert into t values (2);
INSERT 0 1
postgres=# select * from t where a in (1, 2);
ERROR:  WHERE condition option 32 not supported yet
DETAIL:  The WHERE condition option is not supported yet.
```

Reviewers: mihnea

Reviewed By: mihnea

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D6339