[#16009] YSQL: Fix the system catalog versioning behaviour on CREATE TABLE with FK reference command
Summary:
Today CREATE TABLE with Foreign key (ie. the reference table) does not increment the system catalog version. The catalog version must be incremented so that the active Postgres connections refresh the Postgres cache and become  aware of the new foreign key relationship. This will allow incoming DML operations like insert or delete to adhere to the new constraint.

The reason why catalog version is not incremented on this command is because when the statement runs, internally we have a nested subcommand (in this case AlterTable) which gets invoked to set the foreign key constraints.  Although the AlterTable subcommand determines the catalog version must be incremented, the result does not get persisted up to the top-level CreateStmt DDL. When we reach the top-level CreateStmt DDL, the catalog version is set to stay the same thus the version does not get incremented as it's supposed to.

With this change, we persist the two flags `is_catalog_version_increment` and `is_breaking_catalog_change` inside the `DdlTransactionState` such that when the process utility is a top-level command or is atomic SPI command we increment the version and/or set it as breaking change. Only specific subcommand will trigger the flags to update such as with CREATE TABLE with FOREIGN KEY reference command. For example, we use the new field in the `DdlTransactionState` called `original_node_tag` to record the initial command as `CreateStmt`. Later when we're inside the subcommand `AlterStmt` and foreign key constraint gets calculated, we ensure to increment the catalog version.

Test Plan:
Updated the test file which tracks system catalog version on DDLs.

Verified the behaviour on YSQL shell:

// connection 1:
create table t1 (col int unique);
insert into t1 values(1);
insert into t1 values(2);

// connection 2:
create table t2 (col int references t1(col));
insert into t2 values(2);

// connection 1:
delete from t1 where col = 2; -- prior to this change the delete went through
ERROR:  update or delete on table "t1" violates foreign key constraint "t2_col_fkey" on table "t2"
DETAIL:  Key (col)=(2) is still referenced from table "t2".

Reviewers: mihnea, myang, tverona

Reviewed By: myang, tverona

Subscribers: tverona, yql

Maniphest Tasks: T1

Differential Revision: https://phabricator.dev.yugabyte.com/D23619