[#4993] [YSQL] enabled split options in the abscence of a primary key by using default ybrowid as PK
Summary:
Currently split options do not work in the absence of a primary key. However, we can split rows into different tablets by hash partitioning the ybrowid column. Hence, this diff enables us to utilize ybrowid for splitting data into different tablets.
In this context, we first remove the error that is thrown in the front end side that disables creating a table with no PK and with split options. Furthermore, for such tables, we split only if they are not colocated tables (or tables with a tablegroup), as well as system tables.

Test Plan:
1.
```
CREATE TABLE tbl13 (
  a      text,
  b      date,
  c      time
) SPLIT INTO 9 TABLETS;

```
Previously this would't succeed, however now we have succeeded this. After executing this statement, you can go to http://127.0.0.1:7000/, click on **see all tables**, click the table name and check that there are 4 leaders in that table.
2. Added tests where primary keys that are range partitioned cannot contain split options. For example,

```
CREATE TABLE tbl13 (
  a      text,
  b      date,
  c      time
) SPLIT INTO 9 TABLETS;
```
tis table command will throw an error

> ERROR:  HASH columns must be present to split by number of tablets

3. Finally colocated tables with no-PK should not be allowed to use split options. For example,

```
CREATE TABLE split_table ( a integer, b text ) SPLIT INTO 4 TABLETS;
```
should error out providing

> ERROR:  HASH columns must be present to split by number of tablets

 as the output.

Reviewers: neha, oleg, mihnea, alex

Reviewed By: alex

Subscribers: bogdan, zyu, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D9151