[#13120, #12663] YSQL: Disallow ALTER TABLE which cause table rewrite
Summary:
ALTER TABLE which causes table rewrite is not supported for now

```
CREATE TABLE t(k int);
INSERT INTO t VALUES(1), (2), (3);
ALTER TABLE t ADD COLUMN s2 TIMESTAMP DEFAULT clock_timestamp();
ERROR:  Operation not allowed in YugaByte mode heap_insert
```

This diff is disabled such `ALTER TABLE` operations by returning meaningful error

```
ERROR:  Rewriting of YB table is not yet implemented
HINT:  See https://github.com/YugaByte/yugabyte-db/issues/13278. Click '+' on the description to raise its priority
```

Test Plan:
Jenkins

New test case was introduced

```
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressTable'
```

Reviewers: alex, jason

Reviewed By: jason

Subscribers: zyu, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D18321