[BACKPORT 2.12] [#9547] YSQL: alter table of parent geo-partitioned table affects select on child
Summary:
Failing example:
```
-- Add column to parent partitioned table.
yugabyte@yugabyte=# alter table transactions add column foo varchar(30);
ALTER TABLE

-- Column is added to child partition in PG metadata.
yugabyte@yugabyte=# \d transactions_eu;
                        Table "public.transactions_eu"
    Column     |            Type             | Collation | Nullable | Default
---------------+-----------------------------+-----------+----------+---------
 user_id       | integer                     |           | not null |
 geo_partition | character varying           |           | not null |
 foo           | character varying(30)       |           |          |
Partition of: transactions FOR VALUES IN ('EU', 'EMEA')

-- Select data from child
localhost:5433 yugabyte@yugabyte=# select * from transactions_eu;
ERROR:  Invalid argument: Invalid column number 8
```

The above issue is happening because ALTER on parent partitioned table
recursively reflects the ALTER operation on the child partitions by
the PG layer. However, this does not happen on the DocDB side.
This leads to mismatch in the YSQL and DocDB metadata for the child
partition tables following an ALTER, resulting in failure of future
DQL and DML operations.

Original Diff: https://phabricator.dev.yugabyte.com/D14685
Original Commit: ff176a5b2208646572c7220a58ac60700d5837e8

Test Plan:
Jenkins: rebase: 2.12
ybd --scb --sj --java-test org.yb.pgsql.TestPgRegressPartitions

Reviewers: myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D15820