docdb: stop passing an int to subprocess.check_output in yb_backup.py
Summary:
A recent [[ https://phabricator.dev.yugabyte.com/D15686 | change ]] to yb_backup.py added calls to yb-admin to disable tablet splitting. If `local_yb_admin_binary` is set as a flag, then the command line passed to `subprocess.check_output` is a list including an integer. The reason why the unit tests all pass is the unit tests do not set `local_yb_admin_binary`. In this case, logic inside of `run_ssh_cmd` quotes the constructed command line as a single string, and the list passed to `subprocess.check_output` instead looks like `['bash', '-c', 'yb-admin disable_tablet_splitting 3000']`, which runs successfully.

There are two calls that look like this:

```
DISABLE_SPLITTING_MS = 30000
...
self.run_yb_admin(["disable_tablet_splitting", DISABLE_SPLITTING_MS])
```

When running this script, I get the following errors:
```
2022-05-26 11:05:08,666 ERROR: Failed to run command [[ /Users/zdrudi/code/yugabyte-db/build/latest/bin/yb-admin --master_addresses 127.0.0.1:7100 disable_tablet_splitting 30000 ]]: expected str, bytes or os.PathLike object, not int
```

subprocess.check_output seems to require string arguments:
```
% python
>>> import subprocess
>>> subprocess.check_output(["head", "-n", "1", "master.zsh"])
'#!/bin/zsh\n'
>>> subprocess.check_output(["head", "-n", 1, "master.zsh"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

Test Plan: run yb_backup.py, no exceptions caused by this call anymore.

Reviewers: skedia, asrivastava

Reviewed By: asrivastava

Subscribers: jenkins-bot, ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D17230