[#24012] YSQL: Replace deprecated function shared_ptr::unique to fix macos compiler error
Summary:
An unknown change started causing compilation errors on macos. Fix these compiler errors.

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
../../src/yb/tablet/tablet_vector_indexes.cc:109:15: error: no member named 'unique' in 'std::shared_ptr<std::vector<std::shared_ptr<yb::docdb::VectorIndex>>>'
  109 |   if (indexes.unique()) {
      |       ~~~~~~~ ^
1 error generated.

Input files:
  src/yb/tablet/CMakeFiles/tablet.dir/tablet_vector_indexes.cc.o
  /Users/gaurav/code/clean/yugabyte-db/src/yb/tablet/tablet_vector_indexes.cc
Output file (from -o): src/yb/tablet/CMakeFiles/tablet.dir/tablet_vector_indexes.cc.o
\-------------------------------------------------------------------------------
```
Jira: DB-12899

Test Plan: Jenkins

Reviewers: sergei, hsunder, mihnea

Reviewed By: sergei

Subscribers: ybase, yql

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D41815