[BACKPORT 2024.1][#26058,#25957] YSQL: Reduce catalog reads in distinct pushdown
Summary:
Original commit: 160ccb23949ab9391341814693f4a34321fdb5d1 / D41935
### Issue

Lets take a simple schema

```
CREATE TABLE example(t1 TEXT, u2 UUID, t3 TEXT);
CREATE INDEX ex_idx ON example(t1 ASC, u2 ASC, t3 ASC);
```

The following query causes catalog lookups on pg_amop even after the first run.

```
select distinct (t1, u2, t3) from example where u2 = '00000000-0000-0000-0000-000000000000'::uuid AND t1 = 'foo';
```

Output:

```
set yb_debug_log_catcache_events=1;
set client_min_messages=LOG;
explain (analyze, dist) select distinct (t1, u2, t3) from example where u2 = '00000000-0000-0000-0000-000000000000'::uuid AND t1 = 'foo';
LOG:  Catalog cache miss on cache with id 3:
Target rel: pg_amop (oid : 2602), index oid 2654
Search keys: 98, s, 9932
LOG:  Catalog cache miss on cache with id 3:
Target rel: pg_amop (oid : 2602), index oid 2654
Search keys: 2972, s, 9922
                                                                 QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------
 Unique  (cost=15.32..15.73 rows=82 width=32) (actual time=0.852..0.852 rows=0 loops=1)
   ->  Sort  (cost=15.32..15.52 rows=82 width=32) (actual time=0.851..0.851 rows=0 loops=1)
         Sort Key: (ROW(t1, u2, t3))
         Sort Method: quicksort  Memory: 25kB
         ->  Distinct Index Only Scan using ex_idx on example  (cost=0.00..12.71 rows=82 width=32) (actual time=0.833..0.833 rows=0 loops=1)
               Index Cond: ((t1 = 'foo'::text) AND (u2 = '00000000-0000-0000-0000-000000000000'::uuid))
               Distinct Keys: t1, u2, t3
               Heap Fetches: 0
               Storage Index Read Requests: 1
               Storage Index Read Execution Time: 0.675 ms
 Planning Time: 4.704 ms
 Execution Time: 1.096 ms
 Storage Read Requests: 1
 Storage Read Execution Time: 0.675 ms
 Storage Rows Scanned: 0
 Storage Write Requests: 0
 Catalog Read Requests: 2
 Catalog Read Execution Time: 3.312 ms
 Catalog Write Requests: 0
 Storage Flush Requests: 0
 Storage Execution Time: 3.987 ms
 Peak Memory Usage: 92 kB
(22 rows)
```

This is undesirable because the pg backend needs to fetch data from yb-master each time the query is run. This becomes increasingly problematic when the query has more index columns and index clauses. This increased communication between postgres backends and yb-master leads to high latency.

### Root Cause

#### Source of catalog requests

Following stack trace indicates where the catalog requests come from

```
stack     @     0x55a0f4355a31  SearchCatCacheMiss
            @     0x55a0f435494d  SearchCatCacheInternal
            @     0x55a0f4357bec  get_op_opfamily_strategy
            @     0x55a0f40bf376  yb_calculate_distinct_prefixlen
            @     0x55a0f40d704b  build_index_paths
            @     0x55a0f40d458a  get_index_paths
            @     0x55a0f40d3f6c  create_index_paths
            @     0x55a0f40c3e78  set_plain_rel_pathlist
            @     0x55a0f40c3c31  set_rel_pathlist
            @     0x55a0f40bfb60  make_one_rel
            @     0x55a0f40f1104  query_planner
            @     0x55a0f40f3b44  grouping_planner
            @     0x55a0f40f2818  subquery_planner
            @     0x55a0f40f12f5  standard_planner
            @     0x7ff0d2d959f8  pgss_planner
            @     0x7ff0d2c0f671  pg_hint_plan_planner
            @     0x55a0f41f5446  pg_plan_queries
            @     0x55a0f435ea3e  BuildCachedPlan
            @     0x55a0f435e05f  GetCachedPlan
```

When computing the length of the distinct prefix, any trailing constants are removed from the prefix. These trailing constants must come from index clauses because distinct pushdown only supports index conditions at the time of this revision. The planner tries finding an index clause of the form `indexkey = constant` for each index column. This requires a call to `get_op_opfamily_strategy` to verify that the index clause operator corresponds to the same data type as the index column.

#### Why do catalog requests persist after the first query?

The call get_op_opfamily_strategy returns InvalidStrategy when there is a mismatch between the data type of index clause operator and the data type of the index column. This result is not cached by YB at the time of this revision because negative caching is disabled.

#### Why are there a lot of catalog requests?

The catalog requests here are proportional to number of index clauses * number of index columns each time a distinct index scan is considered for planning. This is a quadratic-like explosion in catalog requests.

This happens because,

1. for calculating distinct prefix length, we identify all constant columns of the index. i.e. columns of form col = 5. Iteration length is number of index cols.
2. To identify such columns, for each column, we iterate over all index clauses and determine if the operator is in the same class as the index col's datatype. Iteration length is number of clauses and is done for each index col.

### Proposal

Planner can avoid a lot of cache lookups if it first checks that the indexkey matches the lhs of the index clause before the lookup. Since the indexkey typically matches the lhs of the index clause only when the data types match, the planner does not run into the negative caching problem.

### Impact

The catalog  requests persist when

1. there is more than one data type in the index considered for distinct index scan.
2. there is atleast one index clause.

The catalog requests blow up when there are a lot of index clauses and index columns.
Jira: DB-15384, DB-15280

Test Plan:
Jenkins

Added a simple test query with uuid and text datatypes and an index clause for each data type. This query must have zero catalog requests after the first run.

Without this fix, the test fails with the below error

```
java.lang.AssertionError: Json conflicts:
"Catalog Read Requests": '2' is not == '0'
```

Backport-through: 2.20

Reviewers: smishra, sanketh, tnayak

Reviewed By: sanketh

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D42123