Remove nanoid
Summary:
nanoid v4 is an ESM only package so we run into issues when our code is transpiled.
This causes errors in `npm test`
```
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { randomFillSync } from 'crypto'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
For now we'll remove the nanoid dependency and use build-in functions to generate a random alphanumeric string.

Test Plan:
Pass `npm test`
```
Test Suites: 1 skipped, 16 passed, 16 of 17 total
Tests:       6 skipped, 94 passed, 100 total
Snapshots:   0 total
Time:        39.622s
Ran all test suites related to changed files.
```
Verify that existing usages of nanoid's random id generation still work fine with the new random string generator:
Region deletion-
{F35520}
Random GCE Network name generation (feature disabled by default- enabled for testing only):
{F35521}

Reviewers: rmadhavan

Reviewed By: rmadhavan

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D23668