[BACKPORT 2025.2.3][#27863] YSQL: Revert Fix create index inconsistency using ysql lease
Summary:
This reverts commit dfe6292fdcd27f47992f55ccbad71a5924467cf1.

Reverting the commit since it caused regression when --enable_ysql_operation_lease=false.

Original commit: dfe6292fdcd27f47992f55ccbad71a5924467cf1 / D51688

Test Plan:
Jenkins: urgent, rebase: 2025.2.3

(1) Do manual test
Before the fix (using stock 2025.2.3 build):
```
tmp$ ./yugabyte-2025.2.3.0/bin/yb-ctl create --rf 1 --tserver_flags
'enable_ysql_operation_lease=false' --master_flags
'enable_ysql_operation_lease=false'
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 1 | Replication Factor: 1
|
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte
|
| YSQL Shell          : yugabyte-2025.2.3.0/bin/ysqlsh
|
| YCQL Shell          : yugabyte-2025.2.3.0/bin/ycqlsh
|
| YEDIS Shell         : yugabyte-2025.2.3.0/bin/redis-cli
|
| Web UI              : http://127.0.0.1:7000/
|
| Cluster Data        : /net/dev-server-myang/share/yugabyte-data
|
----------------------------------------------------------------------------------------------------

For more info, please use: yb-ctl status
tmp$ ./yugabyte-2025.2.3.0/bin/ysqlsh
ysqlsh (15.12-YB-2025.2.3.0-b0)
Type "help" for help.

yugabyte=# create table foo(id int);
CREATE TABLE
yugabyte=# create index on foo(id);
ERROR:  timed out waiting for postgres backends to catch up
DETAIL:  Failed to determine how many backends on database 13537 are
still behind catalog version 2.
yugabyte=#
```

After the fix (run the test in the code fix build):

```
yb2$ ./bin/yb-ctl create --rf 1 --tserver_flags
'enable_ysql_operation_lease=false' --master_flags
'enable_ysql_operation_lease=false'
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 1 | Replication Factor: 1
|
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte
|
| YSQL Shell          : bin/ysqlsh
|
| YCQL Shell          : bin/ycqlsh
|
| YEDIS Shell         : bin/redis-cli
|
| Web UI              : http://127.0.0.1:7000/
|
| Cluster Data        : /net/dev-server-myang/share/yugabyte-data
|
----------------------------------------------------------------------------------------------------

For more info, please use: yb-ctl status
yb2$ ./bin/ysqlsh
ysqlsh (15.12-YB-2025.2.3.1-b0)
Type "help" for help.

yugabyte=# create table foo(id int);
CREATE TABLE
yugabyte=# create index on foo(id);
CREATE INDEX
yugabyte=#
```
(2) ./yb_build.sh release --cxx-test pg_concurrent_ddls-test

Reviewers: xCluster, hsunder, sanketh, jason, #db-approvers

Reviewed By: jason, #db-approvers

Subscribers: mihnea, svc_phabricator, yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D53998