[PLAT-5380] Set gFlag to use hostname for onprem TLS enabled universes using DNS
Summary:
TLS enabled universes that use DNS addresses and has `--server_broadcast_addresses` and
`--rpc_bind_addresses` set to DNS names would fail during SQL inserts:
```
ybops.common.exceptions.YBOpsRecoverableError: Custom exit code exception: Remote shell command
'b'bash -c /home/yugabyte/tserver/bin/ysqlsh -h $(dirname "$(ls -t /tmp/.yb.*/.s.PGSQL.* | head -1)") -p 5433 -U yugabyte -d system_platform -c "SELECT jsonb_agg(x) FROM (SELECT version()) as x"''
failed with return code 'Custom exit code exception: Runtime error:
Command <..cmd..> returned error code 2: ysqlsh: FATAL:  Network error: Handshake failed: Network error (yb/rpc/secure_stream.cc:1106):
Endpoint does not match, address: 10.150.3.125, hostname: 10.150.3.125' and error '1'
```
We could see this error while creating on-prem universes. The above error meant postgres was
attempting to connect to a TServer using IP address instead of DNS.
DB team had created a new gFlag `use_node_hostname_for_local_tserver` to fix this issue. This change
adds this gFlag to DB nodes when the deployment type is on-prem.

Test Plan:
1. Ensure create universe with DNS+TLS succeeds with this change. Before
   this we would fail in wait for TServer
2. Ensure gFlags are set appropriately.

Reviewers: sanketh, amalyshev, yshchetinin

Reviewed By: yshchetinin

Subscribers: jenkins-bot, yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D23023