[BACKPORT 2024.1][#25711] YSQL: Fix DESCRIBE command for indexes with a space in the name
Summary:
Original commit: D41688 / 79be8975b36d29d7e9935e6c778fec1d6eeba1e3
Code merging (NOT a clean backport).

Before the fix `\d` command can output a error for any index with a space in the index name.
Example:
```
CREATE TABLE
CREATE INDEX
ERROR:  invalid name syntax
LINE 2: FROM yb_table_properties('public.foo tbl_pkey'::regclass) pr...
                                 ^
ERROR:  invalid name syntax
```
After the fix the command works correctly:
```
              Table "public.foo tbl"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 i      | integer |           | not null |
 j      | integer |           |          |
Indexes:
    "foo tbl_pkey" PRIMARY KEY, lsm (i HASH)
    "foo idx" lsm (j HASH)
```

The main change: use `yb_table_properties(<index-oid>)` instead of
`yb_table_properties('<index-schema>.<index-name>'::regclass)`.

Test Plan: ./yb_build.sh --java-test  org.yb.pgsql.TestPgRegressIndex#schedule

Reviewers: mihnea, hsunder

Reviewed By: hsunder

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D42064