[BACKPORT 2025.2][#28955] YSQL: Fix CREATE INDEX when savepoint for DDL is enabled
Summary:
When DDL for savepoint support is enabled via `TEST_ysql_yb_enable_ddl_savepoint_support`, the CREATE INDEX command when executed
outside of a transaction block leads to a yb-master crash loop.

```
CREATE TABLE employees ( id INT PRIMARY KEY, employee_code VARCHAR(20) UNIQUE, department VARCHAR(50) );
CREATE INDEX idx_department ON employees(department);
qq=# CREATE INDEX idx_department ON employees(department);
ERROR:  Invalid table definition: Error creating index qq.idx_department on the master: Given invalid sub_transaction_id: 0 vs 1
```

This error indicates that yb-master received an invalid sub_transaction_id in the CreateTable RPC. The bug happens because we always pass the active sub-transaction-id from the local tserver to yb-master in case of CreateTable. CREATE INDEX command in this case is executed as a separate DDL transaction. For more information on when CREATE INDEX starts a separate DDL transaction, refer to D43199 / 8eb1e718f864.

Savepoint is only supported for transactional ddl and not in the case of separate DDL transaction. As a result, the sub_transaction_id ends up being invalid and hence the failure. This revision fixes the bug by not passing the sub_transaction_id to yb-master if it is invalid. This only affects statements which run as separate
ddl transactions even if txn ddl is enabled. CREATE INDEX is the only such statement.
Jira: DB-18692

Original commit: 0f63df89849f3aa3833c6881ddcc67e949006c93 / D47510

Test Plan:
Manually tested the scenario as well and added to the regress test.

./yb_build.sh --java-test 'org.yb.pgsql.TestDdlSavepoints'

Reviewers: myang, patnaik.balivada, pjain

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D47541