[#5408] [YSQL] Provide separate header file for built-in float types
Summary:
Postgres commit https://github.com/postgres/postgres/commit/6bf0bc842bd75877e31727eb559c6a69e237f831

Background: this change is needed for the json path backport.

When I was building with json path backport, I got the following error:
```
In file included from src/postgres/src/backend/utils/adt/jsonpath_exec.c:71:\n
src/postgres/src/include/utils/float.h:73:1: error: static declaration of \'get_float4_infinity\' follows non-static declaration\nget_float4_infinity(void)\n
^\n
src/postgres/src/include/utils/builtins.h:57:14: note: previous declaration is here\nextern float get_float4_infinity(void);
```
The get_float4_infinity is no longer mentioned in src/include/utils/builtins.h of postgres.

Original commit message:

    Some data types under adt/ have separate header files, but most simple
    ones do not, and their public functions are defined in builtins.h.  As
    the patches improving geometric types will require making additional
    functions public, this seems like a good opportunity to create a header
    for floats types.

    Commit 1acf757255 made _cmp functions public to solve NaN issues locally
    for GiST indexes.  This patch reworks it in favour of a more widely
    applicable API.  The API uses inline functions, as they are easier to
    use compared to macros, and avoid double-evaluation hazards.

Test Plan:
  Build Postgres with the change and run unit test. Make sure test passes.

Reviewers: mihnea, dmitry, alex

Reviewed By: alex

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D9172