[#20915] DocDB: Assert callback and validator are in same compilation units
Summary:
Flag validators must be defined in the same translation unit (source file) that the flag itself is defined in. This is because the initialization order of global variables across different translation units is undefined. The validator requires the pointer to the flag, so must be initialized only after the flag is defined.

This change creates a typedef of a bool with the flag definition and static_asserts the existence of the type in `DEFINE_validator` and `REGISTER_CALLBACK`.

Removed
```
DEFINE_validator(vmodule, &yb::ValidateVmodule);
REGISTER_CALLBACK(vmodule, "UpdateVmodule", &yb::UpdateVmodule);
```

and replaced it with a direct call to `flags_callback_internal::RegisterGlobalFlagUpdateCallback` from `ParseCommandLineFlags`

Fixes #20915
Jira: DB-9897

Test Plan:
Add the below line to `ysql_conn_mgr_wrapper.cc` and ensure build fails
`DEFINE_validator(enable_ysql_conn_mgr, &ValidateEnableYsqlConnMgr);`

Error:

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
../../src/yb/yql/ysql_conn_mgr_wrapper/ysql_conn_mgr_wrapper.cc:97:1: error: use of undeclared identifier 'enable_ysql_conn_mgr_DefinedInFile'
DEFINE_validator(enable_ysql_conn_mgr, &ValidateEnableYsqlConnMgr);
^
../../src/yb/util/flags.h:49:12: note: expanded from macro 'DEFINE_validator'
    sizeof(_DEFINE_FLAG_IN_FILE(name)), "validator must be DEFINED in the same file as the flag"); \
           ^

```

Reviewers: mkumar

Reviewed By: mkumar

Subscribers: bogdan, yql, ybase

Differential Revision: https://phorge.dev.yugabyte.com/D27884