[BACKPORT 2.6][#9547] YSQL: alter table of parent geo-partitioned table affects select on child
Summary:
Failing example:
```
-- Add column to parent partitioned table.
yugabyte@yugabyte=# alter table transactions add column foo varchar(30);
ALTER TABLE

-- Column is added to child partition in PG metadata.
yugabyte@yugabyte=# \d transactions_eu;
                        Table "public.transactions_eu"
    Column     |            Type             | Collation | Nullable | Default
---------------+-----------------------------+-----------+----------+---------
 user_id       | integer                     |           | not null |
 geo_partition | character varying           |           | not null |
 foo           | character varying(30)       |           |          |
Partition of: transactions FOR VALUES IN ('EU', 'EMEA')

-- Select data from child
localhost:5433 yugabyte@yugabyte=# select * from transactions_eu;
ERROR:  Invalid argument: Invalid column number 8
```

The above issue is happening because ALTER on parent partitioned table
recursively reflects the ALTER operation on the child partitions by
the PG layer. However, this does not happen on the DocDB side.
This leads to mismatch in the YSQL and DocDB metadata for the child
partition tables following an ALTER, resulting in failure of future
DQL and DML operations.

Original Diff: https://phabricator.dev.yugabyte.com/D14685
Original Commit: ff176a5b2208646572c7220a58ac60700d5837e8

Conflict resolution:
Since the number of tests has become too high to fit into an acceptable
timeout, the tests were split into multiple tests before the original
commit was pushed into master. However commit
ccabdf72f6feead6eb8061a475bf40c9a2b8e0be that introduces this
split cannot be back ported to 2.6 as it requires other commits before it.

Adding the tests introduced by this commit further increases the possibility
of the test failing due to timeout. Hence in this commit, introduce a new
file TestYbPgPartitions and only run the tests introduced by YB into its
schedule. This simple split does not require any previous commits and will
also not run into timeout issues.
Starting 2.8 release onwards, the split tests are present, so there will not be
any divergence from 2.8 onwards.

Test Plan:
Jenkins: rebase: 2.6
ybd --scb --sj --java-test org.yb.pgsql.TestPgRegressPartitions
ybd --scb --sj --java-test org.yb.pgsql.TestYbPgPartitions

Reviewers: myang

Reviewed By: myang

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D15823