[PLAT-9257] Fix Azure orphaned resource deletion
Summary:
Fix Azure orphaned resource deletion. Right now, bad argument is being passed for listing disks
which leads to the orphaned resource cleanup function exiting without deleting any of the orphaned
resources. This diff removes that bad argument.

Error due to bad argument:
```
2023-06-14T05:40:10.494Z  [debug] 39d04631-e7e1-4979-8af1-592c631d2eb4 ShellProcessHandler.java:276 [TaskPool-DestroyUniverse(423c4494-ce78-4eaa-bb56-49f88f63596f)-1] com.yugabyte.yw.common.ShellProcessHandler TypeError: request() got an unexpected keyword argument 'filter'
```

This diff also fixes deletion of orphaned public IPs. The current code was not breaking out of for-loop after deletion of orphaned NICs, fixed that.

Test Plan: Tested manually.

Reviewers: cdavid, muthu, rtsisyk

Reviewed By: cdavid, muthu

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D26179