[#15183] docdb: fix gcc builds
Summary:
Previous [[ https://github.com/yugabyte/yugabyte-db/commit/98645ac6caac29b0fba4db2a3b5b0cb7c6726a2e | diff ]] broke builds on gcc:

```
[2023-02-22T00:04:54.633Z] /-------------------------------------------------------------------------------
[2023-02-22T00:04:54.633Z] | COMPILATION FAILED
[2023-02-22T00:04:54.633Z] |-------------------------------------------------------------------------------
[2023-02-22T00:04:54.634Z] ent/src/yb/master/restore_sys_catalog_state_test.cc: In member function 'virtual void yb::master::RestoreSysCatalogStateTest_Filter_Test::TestBody()':
[2023-02-22T00:04:54.634Z] ent/src/yb/master/restore_sys_catalog_state_test.cc:58:3: error: missing initializer for member 'yb::master::SnapshotScheduleRestoration::parent_to_child_tables' [-Werror=missing-field-initializers]
[2023-02-22T00:04:54.634Z]    58 |   };
[2023-02-22T00:04:54.634Z]       |   ^
[2023-02-22T00:04:54.634Z] cc1plus: all warnings being treated as errors
[2023-02-22T00:04:54.634Z]
[2023-02-22T00:04:54.634Z] Input files:
[2023-02-22T00:04:54.634Z]   src/yb/master/CMakeFiles/restore_sys_catalog_state_test.dir/__/__/__/ent/src/yb/master/restore_sys_catalog_state_test.cc.o
[2023-02-22T00:04:54.634Z]   ent/src/yb/master/restore_sys_catalog_state_test.cc
[2023-02-22T00:04:54.634Z] Output file (from -o): src/yb/master/CMakeFiles/restore_sys_catalog_state_test.dir/__/__/__/ent/src/yb/master/restore_sys_catalog_state_test.cc.o
```

Test Plan: n/a

Reviewers: arybochkin, hsunder, asrivastava

Reviewed By: arybochkin, hsunder, asrivastava

Subscribers: ybase, slingam, bogdan

Differential Revision: https://phabricator.dev.yugabyte.com/D23099