[BACKPORT 2.14][#12587] YSQL: Add yb_make_next_ddl_statement_nonbreaking
Summary:
When running the following set of commands on a cluster

```
CREATE DATABASE db1;
\c db1;
REVOKE ALL ON schema public FROM public;
REVOKE connect ON DATABASE db1 FROM public;
```

It causes the catalog snapshot on other transactions to be invalidated.

```
PostgresqlRollbackException: [40001] Query error: The catalog snapshot used for this transaction has
been invalidated
```

This is because a revoke command is considered as "breaking catalog change". It causes the
`last_breaking_version` in the `pg_yb_catalog_version` table to increase, which has the effect of
aborting all running transactions. Currently there is only a cluster-wide "breaking catalog version"
in the table `pg_yb_catalog_version`, it aborts all running transactions with a snapshot that has a
lower catalog version. Even if we can make `pg_yb_catalog_version` to have different catalog version
numbers for different databases, it may not help in this case. The reason is that a revoke command
may become very involved and may well include semantics that is cross databases. For example, a
superuser may have a current session connected to yugabyte, but it may issue a revoke that affects
another database db1. As a result of the execution of this revoke statement, a shared catalog table
is updated, which for correctness must impact all ongoing transactions that may be relevant and
abort them.

In the above example, `public` represents all users. So in theory it does impact all users. Because
a user may be connected to any database at the time, to ensure strict correctness we should abort
all running transactions because we don't know whether a running transaction involves a user that
is relevant to `schema public` of this database or not. But given the fact that the database `db1`
is freshly created, the user will have the knowledge that all running transactions cannot be
relevant and don't need to be aborted. It will not be easy for YSQL to auto-detect that usage pattern
with the current "breaking catalog change" framework.

This diff adds a session variable yb_make_next_ddl_statement_nonbreaking that superuser or
yb_db_admin role member can use to simply make the next ddl statement non-breaking.
To prevent unintended side effect, it is automatically reset to false after the next ddl statement
completes. In this case if the superuser or yb_db_admin role member is fully aware that the revoke
command is only related to a newly created database, then the work around can be like:

```
CREATE DATABASE db1;
\c db1;
set yb_make_next_ddl_statement_nonbreaking = true;
REVOKE ALL ON schema public FROM public;
set yb_make_next_ddl_statement_nonbreaking = true;
REVOKE connect ON DATABASE db1 FROM public;
```

By default yb_make_next_ddl_statement_nonbreaking defaults to false and will not change the existing
behavior. Note that each ddl that the user wants to make `non-breaking` requires its own
use of yb_make_next_ddl_statement_nonbreaking as shown in the above example.

Original commit: 47fcdf834b0c12644c8c5e405363a96f1d47a519 / D18260

Test Plan:
Jenkins: rebase: 2.14
./yb_build.sh --cxx-test pgwrapper_pg_libpq-test --gtest_filter PgLibPqTest.NonBreakingDDLMode

Reviewers: tverona, mihnea, jason

Reviewed By: jason

Subscribers: yql, zyu, smishra

Differential Revision: https://phabricator.dev.yugabyte.com/D18326